-- GENERATED by `wfj generate` from data/item/item-0229.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("item", {
  [229008] = { "クロークに永続的なエンチャントを施し、Fire Resistanceを$N1上昇させる方法を習得します。", 0xa0f595b6, "u" },
  [229009] = { "クロークに永続的なエンチャントを施し、Nature Resistanceを$N1上昇させる方法を習得します。", 0x1165b881, "u" },
  [229415] = { "サバイバル用の野営地の土台を築きます。この野営地にさらに物資を運び込むと、避難所を建てられます。", 0xac130273, "u" },
  [229894] = { "Cenarion Circleとの評判を永続的に高めます。", 0x8f12afce, "u" },
  [229897] = { "Dark Rune $N1個とFirebloom $N2個と組み合わせて、Signet of Beckoning: Fireを作ります。", 0xae0da25f, "u" },
  [229965] = { "最後の残響のオーブはfelのエネルギーで煮えたぎっています。あなたが自分を終わらせようとしていることを知っているかのように、お返しとばかりにあなたへ軽蔑に満ちた憎しみを放っています。", 0x6565e013, "u" },
})
