-- GENERATED by `wfj generate` from data/item/item-0257.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("item", {
  [257029] = { "綴じられていない羊皮紙の本が何冊か入った古い鞄。", 0xcec2da85, "u" },
  [257126] = { "命の輝きを放っていますが、温もりはありません。", 0x5af3da13, "u" },
  [257348] = { "創造性のひらめきそのものが込められています。", 0x8c5b2473, "u" },
  [257517] = { "倒れたKhanを蘇らせます。", 0x941c111c, "u" },
  [257685] = { "centaurが通貨として使うトーテムがぎっしり詰まっています。対立する氏族のいずれかに届ければ、きっと彼らの好意を得られるでしょう。", 0x60cf6f0d, "u" },
  [257808] = { "Everlookへ配達する手紙と小包です。", 0x16592308, "u" },
  [257809] = { "Mount Hyjalへ配達する手紙と小包です。", 0xa8d1552c, "u" },
})
