-- GENERATED by `wfj generate` from data/item/item-0256.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("item", {
  [256057] = { "別の世界から来た、非常に珍しい水晶。その数多くの用途はまだ見つかり始めたばかりです。", 0x3a97c899, "u" },
  [256058] = { "Draenethyst CrystalでUthek's Staffを強化します。", 0x40bee7fb, "u" },
  [256061] = { "Accursed Skullにかけられた死霊術の呪いを解こうと試みます。", 0x9b828052, "u" },
})
