-- GENERATED by `wfj generate` from data/item/item-0246.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("item", {
  [246213] = { "Stranglethorn Valeから届いた材木の積み荷。Arathi Highlandsであなたの陣営の役に立つだろう。", 0x2b313da5, "u" },
  [246683] = { "宝を掘り出します。", 0x954d90f3, "u" },
  [246778] = { "Vek'zolを召喚します。", 0x98732f71, "u" },
  [246885] = { "この人形がとても大切にされていたことがわかります。", 0xc2c629ba, "u" },
  [246888] = { "淡い青の光沢を帯びた、拳ほどの大きさの水晶の塊。", 0xf7d28755, "u" },
  [246948] = { "$D1の間、近接攻撃力が$N1上昇し、体が大きくなります。", 0x1f3c4cc7, "u" },
})
