-- GENERATED by `wfj generate` from data/item/item-0180.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("item", {
  [180089] = { "Right Clickでパンダの子を呼び出し、また帰します。", 0x3bbaa8c6, "u" },
})
