-- GENERATED by `wfj generate` from data/item/item-0074.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("item", {
  [74610] = { "このペットの呼び出し方を習得します。", 0x42caee1b, "u" },
  [74611] = { "このペットの呼び出し方を習得します。", 0x42caee1b, "u" },
})
