-- GENERATED by `wfj generate` from data/item/item-0230.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("item", {
  [230008] = { "忍者の暗殺者の姿になります。", 0xdd706146, "u" },
  [230903] = { "Depleted Essence of Fireに魔力を込めます。\nこの奇妙な巻物から炎の魔力が放たれています。", 0x470f0a6e, "u" },
  [230909] = { "Depleted Essence of Fireに魔力を込めます。", 0x2a35ab25, "u" },
  [230946] = { "Comprehension Charmで巻物を解読します。どんな魔法が込められているのか、誰にもわからない。", 0xce6c2da9, "u" },
  [230947] = { "Depleted Essence of Frostに魔力を込めます。\nこの奇妙な巻物から冷気の魔力が放たれています。", 0xa3207054, "u" },
  [230949] = { "Depleted Essence of Frostに魔力を込めます。", 0xe983ec96, "u" },
})
