-- GENERATED by `wfj generate` from data/item/item-0233.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("item", {
  [233197] = { "マニュアルを使ってArgent Squireを呼び出し、Silithidとの戦闘訓練を行います。Squireのいる場で倒したSilithidは、Argent Dawnとの評判を上昇させます。", 0xec5a51f0, "u" },
  [233198] = { "近くのパーティーまたはレイドのメンバーを鼓舞し、呪文のクリティカル率を$N1%、近接および遠隔攻撃のクリティカル率を$N2%、攻撃力を$N3上昇させます。持続時間は$D1です。同様のワールド効果とは重複せず、Chronoboonsの影響を受けません。", 0xe487cf6e, "u" },
  [233200] = { "songflowerを召喚し、パーティーまたはレイドの全メンバーの近接、遠隔、呪文のクリティカル率を$N1%、能力値を$N2、$D1の間上昇させます。同様のワールド効果とは重複しません。Chronoboonsの影響を受けません。", 0xe9db065f, "u" },
  [233209] = { "Firewaterの大釜を$D1の間召喚します。パーティーまたはレイドの全メンバーが使用でき、$D2の間、近接攻撃力が$N2上昇し、体が大きくなります。", 0x0fcd9860, "u" },
  [233217] = { "この香を吸い込むと影の中に溶け込み、Hive'Ashi、Hive'Regal、Hive'Zoraの内部で忍び歩けるようになりますが、移動速度が$N1%低下します。持続時間は$D1です。", 0x2b7ea238, "u" },
  [233250] = { "枝を使ってAncient of Warを呼び出し、Silithidとの戦いを手伝わせます。", 0x65c2a94b, "u" },
})
