-- GENERATED by `wfj generate` from data/item/item-0122.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("item", {
  [122270] = { "オークションハウスでゴールドと引き換えに売ることができます。落札者はこれを$N1日分のゲーム時間と交換できます。", 0x7f426164, "u" },
  [122284] = { "使用：World of Warcraftアカウントにゲーム時間を$N1日追加します。", 0x9e2060a4, "u" },
})
