-- GENERATED by `wfj generate` from data/item/item-0202.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("item", {
  [202251] = { "おやつの袋を開けて対象のポケットにこっそり忍ばせ、この対象に対するBeastsのダメージを$N1増加させます。", 0xe2383ce6, "u" },
  [202256] = { "Quick Drawのアビリティを得ます：\r\n\n$I1\r\n遠隔武器を抜いて敵に素早く射撃し、通常の遠隔武器ダメージを与え、$D1の間、対象の移動速度を$N1%低下させます。コンボポイントを$N3獲得します。\r\n\nQuick Drawは、Sinister Strikeによって発動する、またはSinister Strikeを強化するすべてのタレントと効果の恩恵を受けます。", 0xb4295320, "u" },
  [202316] = { "武器に毒を塗ります。毒は$N1分間持続します。\n攻撃のたびに$N2%の確率で敵を毒に冒し、$D1の間、移動速度を$N3%低下させます。", 0x6bb4a1f1, "u" },
  [202641] = { "この本は泥にまみれているが、ページにはルーンが刻まれ、何かの隠語で短いメモが書かれている。", 0x1b2cf59d, "u" },
})
