-- GENERATED by `wfj generate` from data/item/item-0266.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("item", {
  [266156] = { "取り扱い注意。", 0x50bc26a8, "u" },
  [266158] = { "Rockhide Boarを$D1の間、手なずけて仲間にし始めます。何らかの理由で獣の注意がそれると、手なずけは失敗します。", 0x2f79cf82, "u" },
  [266161] = { "苗木を植えます。", 0x312e4f4d, "u" },
  [266252] = { "壊れた留め金のせいで、ロケットは閉じたまま開きません。", 0xc2508cfb, "u" },
  [266253] = { "Gray Forest Wolfを$D1の間、手なずけて仲間にし始めます。何らかの理由で獣の注意がそれると、手なずけは失敗します。", 0xbc523dae, "u" },
  [266254] = { "Young Forest Bearを$D1の間、手なずけて仲間にし始めます。何らかの理由で獣の注意がそれると、手なずけは失敗します。", 0xf0dcdeeb, "u" },
  [266427] = { "Twilight's Hammerのカルト信者から見つかった、Farholdeの公式の封印が押された記録です。", 0x82620460, "u" },
  [266433] = { "荷造り途中の持ち物がはみ出している木箱やかごです。これを集めた者は、急いで立ち去ったようです。", 0xa0a6f92e, "u" },
})
