-- GENERATED by `wfj generate` from data/item/item-0046.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("item", {
  [46102] = { "【使用】この騎乗生物の呼び出し方を習得する。", 0x720161a4, "u" },
  [46362] = { "Venomhide Hatchlingを召喚します。Un'Goro Crater、Tanaris、Silithusでのみ使用できます。", 0xe64abc24, "u" },
})
