-- GENERATED by `wfj generate` from data/item/item-0237.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("item", {
  [237023] = { "非常用の隠れ場所を設置します。その近くに立っている間、ほとんどの敵はあなたに気づきにくくなります。注意深い敵はそう簡単にはだまされないかもしれません。\n\n戦闘中は使用できません。", 0x0cd5325a, "u" },
  [237037] = { "FinestのためのFine Dining。", 0x486a79c9, "u" },
  [237196] = { "Sulphur Ventに設置します。\n樽には採取用の道具が入っていないようです。", 0x1a542d68, "u" },
  [237230] = { "Suspicious Collection Equipmentの横に置きます。\n木箱から木炭の匂いがします。", 0x5b652237, "u" },
  [237504] = { "補給士官に届ければ、たっぷりと報酬がもらえます。", 0xc49cf70c, "u" },
})
