-- GENERATED by `wfj generate` from data/item/item-0223.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("item", {
  [223077] = { "走る速度と泳ぐ速度がわずかに上昇します。同様の効果とは重複しません。", 0x51f5d912, "u" },
  [223147] = { "新しいEngravingのアビリティを習得します。", 0xbc8956a2, "u" },
  [223163] = { "Scroll of Spatial Mendingの作り方を習得します。", 0x1057dec3, "u" },
  [223168] = { "対象のLeyline Confluxとの同調を試みます。", 0x85dfe0f2, "u" },
  [223171] = { "対象のLeyline Confluxとの同調を試みます。", 0x85dfe0f2, "u" },
  [223288] = { "新しいEngravingのアビリティを習得します。", 0xbc8956a2, "u" },
  [223912] = { "ImbiberからCurse、Disease、Poisonをそれぞれ一つずつ取り除こうと試みます。", 0x28825c19, "u" },
  [223913] = { "healthを$N1回復します。", 0x4d16029e, "u" },
  [223914] = { "healthを$N1回復します。", 0x4d16029e, "u" },
})
