-- GENERATED by `wfj generate` from data/item/item-0285.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("item", {
  [285104] = { "Dalaranの明かりを灯します。\n輝き続けろ！", 0x10e406f3, "u" },
  [285275] = { "投擲攻撃が着弾時に爆発し、近くの敵に$N1のFireダメージを与えます。", 0x975e2d49, "u" },
  [285276] = { "投擲攻撃が着弾時に爆発し、近くの敵に$N1のFireダメージを与えます。", 0x002674fb, "u" },
  [285277] = { "投擲攻撃が着弾時に爆発し、近くの敵に$N1のFireダメージを与えます。", 0xd46b2a07, "u" },
  [285278] = { "投擲攻撃が着弾時に爆発し、近くの敵に$N1のFireダメージを与えます。", 0xfe9a4f93, "u" },
  [285279] = { "鍛冶に使えない？ なら敵に投げつければいいのです。", 0xf5c6c49f, "u" },
  [285280] = { "対象に脳震盪を起こさせ、$D1の間、移動速度を$N1%低下させます。\nBlacksmith Hammerとしても使えます。", 0x26f908ae, "u" },
  [285281] = { "$D1の間、対象をスタンさせます。\nBlacksmith Hammerとしても使えます。", 0x41b8bafa, "u" },
  [285285] = { "Satchel of Copper Bombsの製作方法を習得します。", 0x9d3012a6, "u" },
  [285286] = { "Satchel of Bronze Bombsの製作方法を習得します。", 0xf2d7a0c3, "u" },
  [285287] = { "Satchel of Iron Bombsの製作方法を習得します。", 0xd5b06080, "u" },
  [285288] = { "Satchel of Dark Iron Bombsの製作方法を習得します。", 0x9de01c9c, "u" },
  [285289] = { "Cracked Blacksmith Hammerの製作方法を習得します。", 0x44fadea0, "u" },
  [285290] = { "Mithril Blacksmith Hammerの製作方法を習得します。", 0x1490aa3a, "u" },
  [285291] = { "Arcanite Blacksmith Hammerの製作方法を習得します。", 0x0af4dac9, "u" },
  [285332] = { "対象を突き刺し、$N1のPhysicalダメージを与えます。", 0x970d45f0, "u" },
  [285351] = { "生産性を容赦なく強いられたせいで、縫い目がほつれている。", 0xbb402501, "u" },
  [285359] = { "$D1かけてmanaを$N1回復します。飲んでいる間は座っている必要があります。\n聞かないほうがいい。", 0x9fbff5ff, "u" },
  [285362] = { "魔法のかかったワイングラスは決してこぼれない。", 0x814e39b4, "u" },
})
