-- GENERATED by `wfj generate` from data/item/item-0172.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("item", {
  [172070] = { "あなたのクラスとレベルに合ったアイテムが入っています。空きインベントリスロットが$N1個必要です。", 0x7639c693, "u" },
})
