-- GENERATED by `wfj generate` from data/item/item-0287.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("item", {
  [287416] = { "チーズケーキを食べると幸せになります。", 0x81d403b4, "u" },
  [287505] = { "Kyleに昼食を出します！\nKyleはこのジューシーなごちそうにかぶりつけたら大喜びでしょう！", 0x5e17d5fa, "u" },
})
