-- GENERATED by `wfj generate` from data/item/item-0033.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("item", {
  [33154] = { "【使用】このペットの呼び出し方を\n習得する。", 0x42caee1b, "u" },
})
