-- GENERATED by `wfj generate` from data/item/item-0034.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("item", {
  [34085] = { "冬の衣装セット\n3セット：冬の衣装一式", 0x329bc3f0, "u" },
  [34086] = { "冬の衣装セット\n3セット：冬の衣装一式", 0x931b3fc4, "u" },
  [34087] = { "冬の衣装セット\n3セット：冬の衣装一式", 0x8f3396e2, "u" },
  [34261] = { "Green Winter Clothesの縫い方を習得します。", 0x014987cd, "u" },
  [34262] = { "Winter Bootsの製作方法を習得します。", 0xbd6e27f9, "u" },
  [34319] = { "Red Winter Clothesの縫い方を習得します。", 0x010c4007, "u" },
})
