-- GENERATED by `wfj generate` from data/item/item-0259.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("item", {
  [259226] = { "ただの鉄鉱石ですが、霊界に縛られています。", 0x3d923c21, "u" },
  [259229] = { "インベントリに入れている間、Ghostly Iron Depositsが見えるようになります。普通の採掘用ツルハシとしても使えます！", 0x25086c80, "u" },
  [259461] = { "ああ、なんてこと……", 0x4ef9947b, "u" },
  [259846] = { "装備している釣り竿にルアーを取り付け、$N2分間Fishingを$N1上昇させます。", 0x7748ea7e, "u" },
  [259890] = { "$D1の間、水上を歩けるようになります。", 0x42a8b6d3, "u" },
  [259990] = { "これはトロールの牙の指輪でした。かつては大切にされていたのは明らかですが、それはずっと昔のことです。", 0xf3966152, "u" },
})
