-- GENERATED by `wfj generate` from data/item/item-0212.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("item", {
  [212160] = { "時の織物を変化させ、ドラゴン退治、Dire Maul、Zul'Gurub、Felwoodによる有益なワールド効果を一時停止します。", 0x51f8d523, "u" },
  [212225] = { "次にSoul Shardを消費する呪文を、Soul Shardなしで詠唱できます。", 0x4defdf27, "u" },
  [212230] = { "Soul Vesselの作り方を習得します。", 0x835f9100, "u" },
  [212548] = { "新しいEngravingのアビリティを習得します。", 0xbc8956a2, "u" },
  [212549] = { "新しいEngravingのアビリティを習得します。", 0xbc8956a2, "u" },
  [212551] = { "新しいEngravingのアビリティを習得します。", 0xbc8956a2, "u" },
  [212552] = { "新しいEngravingのアビリティを習得します。", 0xbc8956a2, "u" },
  [212559] = { "新しいEngravingのアビリティを習得します。", 0xbc8956a2, "u" },
  [212560] = { "新しいEngravingのアビリティを習得します。", 0xbc8956a2, "u" },
  [212561] = { "新しいEngravingのアビリティを習得します。", 0xbc8956a2, "u" },
  [212562] = { "新しいEngravingのアビリティを習得します。", 0xbc8956a2, "u" },
  [212568] = { "頭部スロットのアイテムに永続的なエンチャントを施し、CatまたはBearの形態に変身したときにenergyを$N1、またはrageを$N2得られるようにします。", 0x8b0dbf5f, "u" },
  [212580] = { "5秒ごとにmanaを$N1回復します。", 0x9ac76902, "u" },
  [212584] = { "5秒ごとにmanaを$N1回復します。", 0x9ac76902, "u" },
})
