-- GENERATED by `wfj generate` from data/item/item-0216.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("item", {
  [216483] = { "Witherbarkの巣の中にあるゴングを打ち鳴らします。", 0x7ebcfac1, "u" },
  [216491] = { "Stranglethorn Valeから届いた材木の積み荷。Arathi Highlandsであなたの陣営の役に立つだろう。", 0x2b313da5, "u" },
  [216606] = { "新しいEngravingのアビリティを習得します。", 0xbc8956a2, "u" },
  [216619] = { "ひとつかみ食べて、道中の遅れを取り戻そう！\nおなじみのレーズンとピーナッツ……それにもっといろいろ！", 0xe24843b2, "u" },
  [216635] = { "適切な動力源と組み合わせて、Charged Voidcoreを作ります。\nWirdalが必要としているvoidcoreの特徴に一致するようだが、完全に力を失っている。再充電する方法があるはずだ……", 0x1c5b2e49, "u" },
  [216636] = { "この物体は周囲の光と温もりをすべて吸い込んでいるようだ。触れるととても冷たい。", 0x4e92cc55, "u" },
  [216637] = { "どこかの誰かには役に立つのかもしれないが、あなたにはただのがらくたにしか見えない。", 0x11462515, "u" },
  [216645] = { "この小さく浮かぶエネルギーの粒には、闇のエネルギーが満ちている。これでどんな驚くべき魔法を動かせるのか、誰にもわからない。", 0xce943a0d, "u" },
  [216748] = { "Portal of Summoningを習得します。", 0xcfb15750, "u" },
  [216879] = { "Comprehension Charmで巻物を解読します。どんな魔法が込められているのか、誰にもわからない。", 0xce6c2da9, "u" },
})
