-- GENERATED by `wfj generate` from data/item/item-0245.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("item", {
  [245983] = { "長い年月で使い込まれ滑らかになったこのこぶ材の表面には、熊の足跡が彫り込まれています。助けを必要としている別の同志にこれを託したいという強い思いを感じます。", 0x50bcf04d, "u" },
})
