-- GENERATED by `wfj generate` from data/item/item-0224.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("item", {
  [224806] = { "Fel ScarまたはRiftを、Legionの領域の奥深くにある世界とつなげます。予測できない危険な効果が生じるかもしれません。", 0x2c3e94e3, "u" },
  [224893] = { "Fel ScarまたはRiftを、Legionの領域の奥深くにある世界とつなげます。予測できない危険な効果が生じるかもしれません。", 0x2c3e94e3, "u" },
  [224912] = { "Legion Portal Tunerに過剰な力を込めます。", 0x8db069f9, "u" },
})
