-- GENERATED by `wfj generate` from data/item/item-0024.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("item", {
  [24071] = { "どうやら内部専用のもののようだ。", 0xe7cdb736, "u" },
  [24101] = { "Ferocious Bite（Rank 5）を習得します。", 0x35438e09, "u" },
  [24102] = { "Eviscerate（Rank 9）を習得します。", 0xe102a9e7, "u" },
  [24281] = { "彫刻は完成しなかったようだ……", 0x522d0fb6, "u" },
  [24283] = { "銃身に「Lasitor」という名が刻まれている。", 0x66d0de76, "u" },
  [24358] = { "呪文と効果によるダメージと回復量が最大$N1上昇します。", 0x76cbff0e, "u" },
})
