-- GENERATED by `wfj generate` from data/item/item-0184.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("item", {
  [184937] = { "時の織物を変化させ、ドラゴン退治、Dire Maul、Zul'Gurub、Felwoodによる有益なワールド効果を一時停止します。", 0x51f8d523, "u" },
  [184938] = { "一時停止していたワールド効果を元に戻します。", 0x89976410, "u" },
})
