-- GENERATED by `wfj generate` from data/item/item-0240.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("item", {
  [240845] = { "試作品の磁石を一時的に露出させて強化し、散らばった金属の物体を引き寄せようと試みます。", 0x2133869e, "u" },
  [240846] = { "ある人のガラクタは別の人の宝物です。本人が好むと好まざるとにかかわらず！", 0x4843a396, "u" },
  [240945] = { "$D1かけてhealthを$N1回復します。食事中は座っている必要があります。\nパイは同じ大きさの三切れに切り分けられていたのに、なぜかあなたは一番小さな一切れを手にしていました。", 0xfd1ba045, "u" },
})
