-- GENERATED by `wfj generate` from data/item/item-0214.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("item", {
  [214435] = { "Cougar Cageを開けます", 0x301667bd, "u" },
})
