-- GENERATED by `wfj generate` from data/item/item-0222.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("item", {
  [222962] = { "新しいEngravingのアビリティを習得します。", 0x83c8b2f0, "u" },
})
