-- GENERATED by `wfj generate` from data/item/item-0243.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("item", {
  [243065] = { "野生の魔力を込めます。", 0x90fdaadc, "u" },
  [243203] = { "淡い青の光沢を帯びた、拳ほどの大きさの水晶の塊。", 0xf7d28755, "u" },
  [243299] = { "一か所で全部使ってしまわないように。", 0x9777e5ed, "u" },
})
