-- GENERATED by `wfj generate` from data/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.meta = {
  schema = 1,
  english = { db2 = "1.60.1.70009", pfquest = "7786596", vmangos = "13b49dc", wago = "1.15.9.69722", wdb = "1.15.9.69722+1.60.1.70009" },
  counts = { quest = 4536, item = 9047, spell = 8284, objective = 358, area = 215, gossip = 10641, book = 1130, ui = 13392, reading = 42430, gloss = 132254 },
  fields = { quest = { "title", "objectives", "description", "progress", "completion" }, item = { "description" }, spell = { "description", "aura" }, objective = { "text" }, area = { "text" } },
}
