-- UI/MenusUnit.lua: the keys the unit right-click menus may show (data; UI/Menus reads it).
-- One key set for every level-1 `which` (SELF, TARGET, PLAYER, ENEMY_PLAYER, PARTY, PET, FOCUS, FRIEND): each entry's
-- text is a UnitPopup button's GetText (blizzard_unitpopupshared/unitpopupsharedbuttonmixins.lua; mainline/
-- unitpopupbuttons.lua; camelot overrides blizzard_unitpopup/camelot/unitpopupmenus.lua:2–43); the title is the
-- unit's name (unitpopupshared.lua:110–116). In a group the self and party menus add the loot, role and group entries:
-- the loot method's title is the chosen method's name, the threshold's the quality's (_G["ITEM_QUALITY"..n.."_DESC"],
-- unitpopupbuttons.lua:609–616, 773–774), a role radio is INLINE_<ROLE>_ICON .. " " .. <ROLE> (the `icon` label form,
-- unitpopupsharedbuttonmixins.lua:3549–3589), the loot opt-out is "Pass on Loot: %s" around Yes / No (:3339).
local _, WFJ = ...
WFJ.MenusUnit = {
  KEYS = { "RAID_TARGET_ICON", "RAID_TARGET_1", "RAID_TARGET_2", "RAID_TARGET_3", "RAID_TARGET_4",
    "RAID_TARGET_5", "RAID_TARGET_6", "RAID_TARGET_7", "RAID_TARGET_8", "RAID_TARGET_NONE", "SET_FOCUS",
    "CLEAR_FOCUS", "SELF_HIGHLIGHT_UNIT_FRAME", "SELF_HIGHLIGHT_CIRCLE", "SELF_HIGHLIGHT_ICON", "PVP_FLAG", "ENABLE",
    "DISABLE", "UNIT_FRAME_DROPDOWN_SUBSECTION_TITLE_LOOT", "UNIT_FRAME_DROPDOWN_SUBSECTION_TITLE_INSTANCE",
    "UNIT_FRAME_DROPDOWN_SUBSECTION_TITLE_OTHER", "UNIT_FRAME_DROPDOWN_SUBSECTION_TITLE_INTERACT", "RESET_INSTANCES",
    "VOICE_CHAT", "OTHER", "HUD_EDIT_MODE_MENU", "SEND_BATTLETAG_REQUEST", "ADD_WOW_FRIEND", "ADD_CHARACTER_FRIEND",
    "ADD_FRIEND", "PARTY_INVITE", "SUGGEST_INVITE", "REQUEST_INVITE", "INSPECT", "COMPARE_ACHIEVEMENTS", "FOLLOW",
    "DUEL", "DUEL_TO_DEATH", "REPORT_IN_WORLD_PLAYER", "COPY_CHARACTER_NAME", "PVP_REPORT_AFK", "WHISPER", "TRADE",
    "IGNORE", "MOVE_TO_WHISPER_WINDOW", "TARGET", "SET_NOTE", "COMMUNITY_MESSAGE_DROP_DOWN_DELETE", "IGNORE_REMOVE",
    "REMOVE_FRIEND", "REPORT_CHAT", "PET_RENAME", "PET_DISMISS", "RELEASE_PET_BUTTON_LABEL",
    "BINDING_NAME_INTERACTTARGET", "PARTY_LEAVE", "PARTY_UNINVITE", "PARTY_PROMOTE", "VOTE_TO_KICK",
    "REPORT_GROUP_MEMBER", "CONVERT_TO_RAID", "CONVERT_TO_PARTY",
    -- the group entries of the self and party menus
    "LOOT_METHOD", "LOOT_FREE_FOR_ALL", "LOOT_ROUND_ROBIN", "MASTER_LOOTER", "LOOT_GROUP_LOOT",
    "LOOT_NEED_BEFORE_GREED", "ITEM_QUALITY0_DESC", "ITEM_QUALITY1_DESC", "ITEM_QUALITY2_DESC", "ITEM_QUALITY3_DESC",
    "ITEM_QUALITY4_DESC", "ITEM_QUALITY5_DESC", "ITEM_QUALITY6_DESC", "OPT_OUT_LOOT_TITLE", "SET_ROLE", "NO_ROLE",
    "TANK", "HEALER", "DAMAGER", "INSTANCE_PARTY_LEAVE",
    -- the self menu's instance abandon vote (UnitPopupPartyInstanceAbandonButtonMixin, camelot
    -- unitpopupmenus.lua:21) and the pet menu's abandon (the same English as RELEASE_PET_BUTTON_LABEL)
    "VOTE_TO_ABANDON", "PET_ABANDON" },
  -- the loot entries' hovers (GetTooltipText → the element's own tooltip)
  TOOLTIPS = { "NEWBIE_TOOLTIP_UNIT_FREE_FOR_ALL", "NEWBIE_TOOLTIP_UNIT_ROUND_ROBIN",
    "NEWBIE_TOOLTIP_UNIT_MASTER_LOOTER", "NEWBIE_TOOLTIP_UNIT_GROUP_LOOT", "NEWBIE_TOOLTIP_UNIT_NEED_BEFORE_GREED",
    "NEWBIE_TOOLTIP_UNIT_OPT_OUT_LOOT",
    -- the abandon vote's cooldown hover ("… in %s", a `time` argument)
    "VOTE_TO_ABANDON_ON_COOLDOWN",
    -- the whisper entry's hover on an age-restricted account: its title (the entry's English again) and
    -- the red warning line (UnitPopupWhisperButtonMixin:TooltipWarning, unitpopupsharedbuttonmixins.lua:469–475;
    -- DisplayUnitPopupTooltip :2–23)
    "WHISPER", "AGE_RESTRICTED_CHAT_MINOR_TOOLTIP", "AGE_RESTRICTED_CHAT_UNVERIFIED_TOOLTIP" },
  -- the same hover in the other `which`s that list the whisper entry
  WHISPER_TIPS = { "WHISPER", "AGE_RESTRICTED_CHAT_MINOR_TOOLTIP", "AGE_RESTRICTED_CHAT_UNVERIFIED_TOOLTIP" },
  -- the `which`s outside level 1, each with its own list: its effective entries (shared ←
  -- mainline/unitpopupmenus.lua ← camelot/unitpopupmenus.lua overrides) mapped through each button mixin's GetText
  -- (unitpopupsharedbuttonmixins.lua; mainline/unitpopupbuttons.lua). The title is the unit's, the friend's or the
  -- club's name (contextData.name, communitieslist.lua:790–805): UI/Menus registers every one with `titleIsName`.
  -- RAID's main tank / assist and focus entries sit beside protected actions: text-only writes, like every entry.
  WHICH = {
    BN_FRIEND = { "MOVE_TO_WHISPER_WINDOW", "TARGET", "SOCIAL_UI_BATTLE_NET_TITLE_FRIEND_EDIT_NAME_BUTTON_LABEL",
      "SET_NOTE", "SOCIAL_UI_BATTLE_NET_FRIEND_TAGS_LABEL", "VIEW_FRIENDS_OF_FRIENDS",
      "UNIT_FRAME_DROPDOWN_SUBSECTION_TITLE_INTERACT", "PARTY_INVITE", "SUGGEST_INVITE", "REQUEST_INVITE", "WHISPER",
      "UNIT_FRAME_DROPDOWN_SUBSECTION_TITLE_OTHER", "ADD_FAVORITE_STATUS", "REMOVE_FAVORITE_STATUS", "REMOVE_FRIEND",
      "REPORT_IN_WORLD_PLAYER", "REPORT_CHAT" },
    BN_FRIEND_OFFLINE = { "SOCIAL_UI_BATTLE_NET_TITLE_FRIEND_EDIT_NAME_BUTTON_LABEL", "SET_NOTE",
      "SOCIAL_UI_BATTLE_NET_FRIEND_TAGS_LABEL", "VIEW_FRIENDS_OF_FRIENDS",
      "UNIT_FRAME_DROPDOWN_SUBSECTION_TITLE_INTERACT",
      "WHISPER", "UNIT_FRAME_DROPDOWN_SUBSECTION_TITLE_OTHER", "ADD_FAVORITE_STATUS", "REMOVE_FAVORITE_STATUS",
      "REMOVE_FRIEND", "REPORT_IN_WORLD_PLAYER" },
    RAID_PLAYER = { "RAID_TARGET_ICON", "RAID_TARGET_1", "RAID_TARGET_2", "RAID_TARGET_3", "RAID_TARGET_4",
      "RAID_TARGET_5", "RAID_TARGET_6", "RAID_TARGET_7", "RAID_TARGET_8", "RAID_TARGET_NONE", "SET_FOCUS", "ADD_FRIEND",
      "SEND_BATTLETAG_REQUEST", "ADD_CHARACTER_FRIEND", "ADD_WOW_FRIEND",
      "UNIT_FRAME_DROPDOWN_SUBSECTION_TITLE_INTERACT",
      "SET_RAID_LEADER", "SET_RAID_ASSISTANT", "DEMOTE", "WHISPER", "INSPECT", "COMPARE_ACHIEVEMENTS", "TRADE",
      "FOLLOW", "DUEL", "UNIT_FRAME_DROPDOWN_SUBSECTION_TITLE_OTHER", "VOICE_CHAT", "SET_ROLE", "TANK", "HEALER",
      "DAMAGER", "NO_ROLE", "HUD_EDIT_MODE_MENU", "REPORT_GROUP_MEMBER", "REPORT_IN_WORLD_PLAYER",
      "COPY_CHARACTER_NAME", "PVP_REPORT_AFK", "VOTE_TO_KICK", "REMOVE" },
    RAID = { "SET_FOCUS", "UNIT_FRAME_DROPDOWN_SUBSECTION_TITLE_INTERACT", "SET_RAID_LEADER", "SET_RAID_ASSISTANT",
      "SET_MAIN_TANK", "SET_MAIN_ASSIST", "DEMOTE", "UNIT_FRAME_DROPDOWN_SUBSECTION_TITLE_OTHER", "VOICE_CHAT",
      "HUD_EDIT_MODE_MENU", "REPORT_GROUP_MEMBER", "COPY_CHARACTER_NAME", "PVP_REPORT_AFK", "VOTE_TO_KICK", "REMOVE" },
    COMMUNITIES_WOW_MEMBER = { "TARGET", "ADD_FRIEND", "SEND_BATTLETAG_REQUEST", "ADD_CHARACTER_FRIEND",
      "ADD_WOW_FRIEND", "UNIT_FRAME_DROPDOWN_SUBSECTION_TITLE_INTERACT", "PARTY_INVITE", "SUGGEST_INVITE",
      "REQUEST_INVITE", "WHISPER", "IGNORE_REMOVE", "IGNORE", "COMMUNITIES_LIST_DROP_DOWN_LEAVE_CHARACTER_COMMUNITY",
      "COMMUNITIES_LIST_DROP_DOWN_LEAVE_COMMUNITY", "COMMUNITY_MEMBER_LIST_DROP_DOWN_REMOVE",
      "COMMUNITY_MEMBER_LIST_DROP_DOWN_SET_NOTE", "COMMUNITY_MEMBER_LIST_DROP_DOWN_ROLES",
      "UNIT_FRAME_DROPDOWN_SUBSECTION_TITLE_OTHER", "REPORT_CLUB_MEMBER", "COPY_CHARACTER_NAME" },
    COMMUNITIES_GUILD_MEMBER = { "TARGET", "ADD_FRIEND", "SEND_BATTLETAG_REQUEST", "ADD_CHARACTER_FRIEND",
      "ADD_WOW_FRIEND", "UNIT_FRAME_DROPDOWN_SUBSECTION_TITLE_INTERACT", "PARTY_INVITE", "SUGGEST_INVITE",
      "REQUEST_INVITE", "WHISPER", "IGNORE_REMOVE", "IGNORE", "GUILD_PROMOTE",
      "UNIT_FRAME_DROPDOWN_SUBSECTION_TITLE_OTHER", "GUILD_LEAVE", "REPORT_CLUB_MEMBER", "COPY_CHARACTER_NAME" },
    COMMUNITIES_MEMBER = { "COMMUNITY_MEMBER_LIST_DROP_DOWN_BATTLETAG_FRIEND",
      "UNIT_FRAME_DROPDOWN_SUBSECTION_TITLE_INTERACT", "COMMUNITIES_LIST_DROP_DOWN_LEAVE_CHARACTER_COMMUNITY",
      "COMMUNITIES_LIST_DROP_DOWN_LEAVE_COMMUNITY", "COMMUNITY_MEMBER_LIST_DROP_DOWN_REMOVE",
      "COMMUNITY_MEMBER_LIST_DROP_DOWN_SET_NOTE", "COMMUNITY_MEMBER_LIST_DROP_DOWN_ROLES",
      "UNIT_FRAME_DROPDOWN_SUBSECTION_TITLE_OTHER", "REPORT_CLUB_MEMBER" },
    COMMUNITIES_COMMUNITY = { "COMMUNITIES_LIST_DROP_DOWN_CLEAR_UNREAD_NOTIFICATIONS",
      "COMMUNITIES_LIST_DROP_DOWN_INVITE", "COMMUNITIES_LIST_DROP_DOWN_COMMUNITIES_SETTINGS",
      "COMMUNITIES_LIST_DROP_DOWN_COMMUNITIES_NOTIFICATION_SETTINGS", "COMMUNITIES_LIST_DROP_DOWN_UNFAVORITE",
      "COMMUNITIES_LIST_DROP_DOWN_FAVORITE", "COMMUNITIES_LIST_DROP_DOWN_LEAVE_CHARACTER_COMMUNITY",
      "COMMUNITIES_LIST_DROP_DOWN_LEAVE_COMMUNITY" },
    GUILDS_GUILD = { "COMMUNITIES_LIST_DROP_DOWN_CLEAR_UNREAD_NOTIFICATIONS", "COMMUNITIES_LIST_DROP_DOWN_INVITE",
      "GUILD_CONTROL_BUTTON_TEXT", "GUILD_RECRUITMENT", "COMMUNITIES_LIST_DROP_DOWN_COMMUNITIES_NOTIFICATION_SETTINGS",
      "GUILD_LEAVE" },
    CHAT_ROSTER = { "UNIT_FRAME_DROPDOWN_SUBSECTION_TITLE_INTERACT", "TARGET", "WHISPER", "CHAT_OWNER",
      "MAKE_MODERATOR", "REMOVE_MODERATOR", "UNIT_FRAME_DROPDOWN_SUBSECTION_TITLE_OTHER", "REPORT_CHAT",
      "COPY_CHARACTER_NAME", "VOICE_CHAT_SETTINGS" },
    RECENT_ALLY = { "SEND_BATTLETAG_REQUEST", "ADD_WOW_FRIEND", "TARGET", "RECENT_ALLIES_MENU_BUTTON_LABEL_SET_NOTE",
      "UNIT_FRAME_DROPDOWN_SUBSECTION_TITLE_INTERACT", "WHISPER", "PARTY_INVITE",
      "UNIT_FRAME_DROPDOWN_SUBSECTION_TITLE_OTHER", "RECENT_ALLIES_MENU_BUTTON_LABEL_UNPIN",
      "RECENT_ALLIES_MENU_BUTTON_LABEL_PIN", "IGNORE_REMOVE", "IGNORE", "REPORT_IN_WORLD_PLAYER",
      "COPY_CHARACTER_NAME" },
    RECENT_ALLY_OFFLINE = { "RECENT_ALLIES_MENU_BUTTON_LABEL_SET_NOTE", "UNIT_FRAME_DROPDOWN_SUBSECTION_TITLE_OTHER",
      "RECENT_ALLIES_MENU_BUTTON_LABEL_UNPIN", "RECENT_ALLIES_MENU_BUTTON_LABEL_PIN", "IGNORE_REMOVE", "IGNORE",
      "COPY_CHARACTER_NAME" },
    DISCORD_USER_SELF = { "DISCORD_CHAT_MESSAGE_CLICK_DELETE" },
  },
}

-- The Menus.TAGS entries these lists make (UI/Menus adds them at load): the level-1 `which`s share KEYS / TOOLTIPS;
-- every other `which` has its own WHICH list. A unit menu's title is the unit's name (titleIsName).
-- → { tag → spec }
function WFJ.MenusUnit.tags()
  local unit, out = WFJ.MenusUnit, {}
  for _, which in ipairs({ "SELF", "TARGET", "PLAYER", "ENEMY_PLAYER", "PARTY", "PET", "FOCUS", "FRIEND" }) do
    out["MENU_UNIT_" .. which] = { source = "unitpopupshared.lua:110", keys = unit.KEYS, tooltips = unit.TOOLTIPS,
      titleIsName = true }
  end
  for which, keys in pairs(unit.WHICH or {}) do
    local tips
    for _, key in ipairs(keys) do if key == "WHISPER" then tips = unit.WHISPER_TIPS end end
    out["MENU_UNIT_" .. which] = { source = "unitpopupshared.lua:110", keys = keys, tooltips = tips,
      titleIsName = true }
  end
  return out
end
