-- GENERATED by `wfj generate` from data/area/area-0095.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("area", {
  [95771] = { "Fargodeep Mineの中を偵察する", 0x773ecf4f, "." },
})
