-- GENERATED by `wfj generate` from data/area/area-0008.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("area", {
  [8114] = { "4つの拠点を支配する。", 0x21fa850c, "." },
  [8115] = { "5つの拠点を奪う。", 0x9c16bafa, "." },
  [8121] = { "4つの拠点を保持する。", 0xeeca7718, "." },
  [8122] = { "5つの拠点を保持する。", 0x8bd78f9e, "." },
  [8286] = { "Brood of Nozdormuを見つける。", 0x91deb4db, "." },
  [8373] = { "Southshoreに投げ込まれた悪臭爆弾を片付ける！", 0x8a9ddea9, "." },
  [8447] = { "伝説の目覚め。", 0x18583789, "." },
  [8868] = { "Elune's Blessingを受ける。", 0x13d90ad0, "." },
})
