-- GENERATED by `wfj generate` from data/area/area-0009.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("area", {
  [9051] = { "Devilsaurをとげで刺した", 0x7fe9e667, "." },
  [9260] = { "サークルを調べる", 0xb112bd4c, "." },
  [9261] = { "サークルを調べる", 0xb112bd4c, "." },
  [9262] = { "サークルを調べる", 0xb112bd4c, "." },
  [9263] = { "サークルを調べる", 0xb112bd4c, "." },
  [9264] = { "サークルを調べる", 0xb112bd4c, "." },
  [9265] = { "サークルを調べる", 0xb112bd4c, "." },
})
