-- GENERATED by `wfj generate` from data/area/area-0005.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("area", {
  [5088] = { "Sacred Fire of Lifeに火を灯す", 0xf76a4ccd, "." },
  [5096] = { "指揮テントを破壊し、野営地にScourgeの旗を立てる", 0x9534edcb, "." },
  [5126] = { "Loraxの話を聞く", 0x9a024340, "." },
  [5156] = { "Shatter Scar Valeのクレーターを探索する", 0x40e5732e, "." },
  [5203] = { "Arko'narinを守りながらShadow Holdから連れ出す", 0x6eb4909b, "." },
  [5321] = { "Kerlonian Evershadeを南への道沿いに、彼の鞄のところまで護衛する", 0x2bdac56b, "." },
  [5713] = { "Aynashaを守る", 0x2ddb1674, "." },
  [5727] = { "あなたがBurning Bladeの一員であることへのNeeru Firebladeの反応を探る", 0x6ac17624, "." },
  [5742] = { "Tirionの話", 0xf3a55d4f, "." },
  [5821] = { "Gizelton CaravanをKolkar Centaur Villageの先まで護衛する", 0x6fd66f94, "." },
  [5929] = { "Great Bear Spiritを探し出し、熊の本質について教わる。", 0x0f52dfe3, "." },
  [5930] = { "Great Bear Spiritを探し出し、熊の本質について教わる。", 0x0f52dfe3, "." },
  [5943] = { "Gizelton CaravanをMannoroc Covenの先まで護衛する", 0xddbc7059, "." },
  [5944] = { "贖罪？", 0xb030885b, "." },
})
