-- GENERATED by `wfj generate` from data/area/area-0096.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("area", {
  [96204] = { "Lumina Windsingerを安全な場所まで護衛する", 0x8a6fa6d1, "." },
})
