-- GENERATED by `wfj generate` from data/area/area-0098.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("area", {
  [98430] = { "Perith StormhoofをPalemane Rockから護衛して連れ出す", 0xbf836749, "." },
  [98435] = { "Wildmane Wellを浄化する", 0xc38bb5cf, "." },
})
