-- GENERATED by `wfj generate` from data/area/area-0097.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("area", {
  [97288] = { "Abominable HeadをUndercityの誰かに届ける。", 0x45912d90, "." },
  [97894] = { "船でAuberdineへ行き、Gorbold Steelhandを見つける。", 0x5d3337ff, "." },
})
