-- GENERATED by `wfj generate` from data/area/area-0003.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("area", {
  [3141] = { "Loramusの話", 0xd2c49d2b, "." },
  [3321] = { "Trentonの仕事ぶりを見る", 0x5573ba32, "." },
  [3366] = { "Nightmare Shardについて誰かに話す", 0x2bbd7527, "." },
  [3367] = { "Doriusの護衛", 0xd5676c06, "." },
  [3377] = { "Zamaelの話", 0xb8596e2c, "." },
  [3382] = { "Captain Vanessa Beltisをnagaの襲撃から守る", 0x0df82ba5, "." },
  [3441] = { "Velarokの話", 0x3dd78ec7, "." },
  [3453] = { "松明の作成", 0x41d32399, "." },
  [3505] = { "Magus Rimtoriのキャンプを見つける", 0x70cd791a, "." },
  [3525] = { "Belnistraszが偶像を停止させる儀式を行う間、彼を守る", 0x5eda2c2d, "." },
  [3625] = { "武器の作成", 0x56b20d80, "." },
  [3702] = { "Thaurissanの物語", 0xd621b174, "." },
  [3982] = { "猛攻を生き延びる", 0xdc0f36bf, "." },
})
