-- GENERATED by `wfj generate` from data/area/area-0093.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("area", {
  [93125] = { "Rokrenを護衛してOutcast Hideawayから脱出させる", 0x249272b7, "." },
  [93585] = { "Father TuttleをThe Harborageまで護衛する", 0xbc6fc9f5, "." },
})
