-- GENERATED by `wfj generate` from data/area/area-0007.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("area", {
  [7046] = { "Scepter of Celebrasを作る", 0x1713f5ed, "." },
  [7141] = { "Drek'tharを倒す。", 0x2d57c617, "." },
  [7142] = { "Vanndar Stormpikeを倒す。", 0xa26a7187, "." },
  [7481] = { "Master Telmius Dreamseekerを見つけた", 0x8a708df4, "." },
  [7482] = { "Master Telmius Dreamseekerを見つけた", 0x8a708df4, "." },
  [7622] = { "光と影の均衡", 0xf2986d90, "." },
  [7843] = { "Wildhammerへの伝言を届けた", 0xf9a345ff, "." },
  [7961] = { "Polymorphed Chickenに電撃を浴びせる", 0x31c9fbbd, "." },
})
