-- GENERATED by `wfj generate` from data/area/area-0087.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("area", {
  [87491] = { "炎のエレメンタルを護衛してDun Modrから脱出させる", 0x3a2075d8, "." },
})
