-- GENERATED by `wfj generate` from data/area/area-0094.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("area", {
  [94013] = { "Vuldren Alphaを手なずける", 0xf68000a2, "." },
  [94436] = { "Tyr's WatchにいるDeathguard Billmuthと話す。", 0x0b39a5af, "." },
  [94438] = { "Symbol of Lifeを持って行き、Venomweb ValeでDeathguard Falganを蘇生させる。", 0x1b676ced, "." },
  [94568] = { "会話を見守る", 0xc57efd0a, "." },
  [94792] = { "Rockhide Boarを手なずける", 0xace1ef75, "." },
  [94863] = { "Gray Forest Wolfを手なずける", 0xd616abc6, "." },
  [94864] = { "Young Forest Bearを手なずける", 0x1940044d, "." },
  [94978] = { "Windsong Crawlerを手なずける", 0xbed558cc, "." },
  [94979] = { "Ornery Galestriderを手なずける", 0x71cb4c75, "." },
})
