-- GENERATED by `wfj generate` from data/area/area-0092.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("area", {
  [92401] = { "Ruins of LordaeronでのEdward Heartweaverの失踪を調べる。", 0x5b830c47, "." },
  [92464] = { "荒れ狂う風についてさらに調べる。", 0x55c782d9, "." },
  [92529] = { "Falaath Villageの入り口にいるMissionary Jasaanと話す", 0xa342318a, "." },
})
