"""data/ lines → Lua text (pure; no disk). One function per artifact (architecture/data-model.md, ADR-008)."""

from __future__ import annotations

import re
from collections.abc import Iterable
from typing import Any

from wfj.core.normalize import NORM_VERSION
from wfj.emit import schema

_SPACES = re.compile(r"\s+")  # a whitespace run, compared as one space between pages' Japanese

HEADER = "-- GENERATED by `wfj generate` from {src}. Do not edit: `wfj validate` regenerates and diffs it."


def lua_string(s: str) -> str:
    """Lua 5.1 double-quoted literal: backslash, quote, newline, CR, tab escaped; other C0/DEL as \\ddd."""
    out: list[str] = []
    for ch in s:
        o = ord(ch)
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\r":
            out.append("\\r")
        elif ch == "\t":
            out.append("\\t")
        elif o < 0x20 or o == 0x7F:
            out.append(f"\\{o:03d}")
        else:
            out.append(ch)
    return '"' + "".join(out) + '"'


def h1_literal(hash16: str) -> str:
    """First 32 bits of a 16-hex `english.hash` as a Lua hex literal."""
    return f"0x{int(hash16[:8], 16):08x}"


def shipped(line: dict[str, Any]) -> bool:
    return line.get("status") in schema.STATUS_CHAR and bool(str(line.get("ja") or "").strip())


def rows(
    type_: str,
    lines: Iterable[dict[str, Any]],
    female: dict[tuple[int, str], tuple[str, str]] | None = None,
    masked: dict[tuple[int, str], tuple[str, str, str | None]] | None = None,
    branches: dict[tuple[int, str], list[tuple[str, str]]] | None = None,
) -> dict[int, list[str]]:
    """{id: [slot literals…]} for a numeric-id type; ids with no shipped field are absent.
    `female` (quest only): (id, field) → (English hash, female-variant key). A row with any field
    whose `english.hash` is that hash gets h1f×5 after the status string (`nil` for the other fields);
    every other row is unchanged.
    `masked` (quest only): (id, field) → (English hash, masked key, masked female key). A field
    whose Japanese is filled from live values (`$N<k>` / `$D<k>`) ships the masked keys as its h1 / h1f
    (its English holds a count only the live line shows, so only a masked comparison can tell a rewording
    from a count) when its `english.hash` is that English. A stale one ships its sticky hash, which no
    masked live line can equal, so it stays marked (ADR-003).
    `branches` (ADR-043; item / spell): (id, field) → [(variant Japanese, shape)…] for a line whose
    Japanese keeps `$?` conditionals. That slot ships as a table, `{ "<variant 1>", …, shape = { … } }`,
    which the addon's `Align.checkVariants` chooses from."""
    slots = schema.SLOTS[type_]
    fields = slots["fields"]
    by_id: dict[int, dict[str, dict[str, Any]]] = {}
    for ln in lines:
        if shipped(ln) and ln["field"] in fields:
            got = by_id.setdefault(int(ln["id"]), {})
            if ln["field"] in got:  # a duplicate is reported, never resolved last-wins
                raise ValueError(f"duplicate {type_} line {ln['id']}/{ln['field']}")
            got[ln["field"]] = ln
    out: dict[int, list[str]] = {}
    for id_ in sorted(by_id):
        got = by_id[id_]
        for f, ln in got.items():
            if not ln.get("english") or not ln["english"].get("hash"):
                raise ValueError(
                    f"{type_} {id_}/{f}: shipped without english {{hash, src}}; run `make check`"
                )
        text = [
            (variants_literal(branches[(id_, f)]) if branches and (id_, f) in branches
             else lua_string(got[f]["ja"])) if f in got else "nil"
            for f in fields
        ]
        # ADR-019: a quest field checked against another field's English (`english.of`) ships no h1, because
        # the addon's live check and the collector's known check compare h1 with this field's live English
        own = {f for f in got if not (type_ == "quest" and got[f]["english"].get("of"))}
        live = {
            f for f in own
            if masked and _FILLED.search(got[f]["ja"]) and (id_, f) in masked
            and masked[(id_, f)][0] == got[f]["english"]["hash"]
        }
        hashes = [
            h1_literal(masked[(id_, f)][1] if f in live else got[f]["english"]["hash"]) if f in own else "nil"
            for f in fields
        ]
        status = "".join(schema.STATUS_CHAR[got[f]["status"]] if f in got else schema.MISSING for f in fields)
        out[id_] = text + hashes + [lua_string(status)]
        if female and "female" in slots:
            fem = [
                None if f not in own
                else masked[(id_, f)][2] if f in live
                else _female_of(female, id_, f, got[f])
                for f in fields
            ]
            if any(fem):
                out[id_] += [h1_literal(k) if k else "nil" for k in fem]
    return out


_FILLED = re.compile(r"\$[ND]\d")


def variants_literal(variants: list[tuple[str, str]]) -> str:
    """A branch line's slot: its variants' Japanese, then their shapes (`<values>/<durations>`)."""
    texts = ", ".join(lua_string(ja) for ja, _ in variants)
    shapes = ", ".join(lua_string(shape) for _, shape in variants)
    return f"{{ {texts}, shape = {{ {shapes} }} }}"


def _female_of(
    female: dict[tuple[int, str], tuple[str, str]], id_: int, field: str, line: dict[str, Any]
) -> str | None:
    hit = female.get((id_, field))
    return hit[1] if hit and hit[0] == line["english"]["hash"] else None


def keyed_rows(type_: str, lines: Iterable[dict[str, Any]]) -> dict[str, list[str]]:
    """{key: [text, status]} for a keyed type (schema.KEYED_TYPES). gossip is keyed
    by its id (the English hash); a book page by `english.hash`, the English its Japanese was
    checked against, since the addon finds a page by its live English. A key match means the client shows
    exactly that English, so a book row's status is always "." (a stale page's changed English is another
    key).
    Pages sharing one English share one row when their Japanese is equal (whitespace runs compared as one
    space, as `wfj import` compares texts: pages whose English differs only in layout; the lowest
    page id's text is written); different Japanese under one key raises, naming the ids (never
    resolved silently). One stated exception: a `stale` book line under a key a current (trusted) page also
    has gives way: the current page was checked against that English, the stale one only against its own
    former text.
    """
    book = type_ == "book"
    out: dict[str, list[str]] = {}
    ids: dict[str, list[Any]] = {}
    texts: dict[str, str] = {}
    shipped_lines = [ln for ln in lines if shipped(ln)]
    current = {
        str((ln.get("english") or {}).get("hash")) for ln in shipped_lines if book and ln["status"] != "stale"
    }
    for ln in sorted(shipped_lines, key=lambda ln: ln["id"]):
        if book:
            if not ln.get("english") or not ln["english"].get("hash"):
                raise ValueError(f"book {ln['id']}: shipped without english {{hash, src}}; run `make check`")
            key = str(ln["english"]["hash"])
            if ln["status"] == "stale" and key in current:
                continue
        else:
            key = str(ln["id"])
        row = [lua_string(ln["ja"]), lua_string("." if book else schema.STATUS_CHAR[ln["status"]])]
        if key in out:
            if not book:
                raise ValueError(f"duplicate {type_} line {key}")
            if _SPACES.sub(" ", texts[key]).strip() != _SPACES.sub(" ", ln["ja"]).strip():
                raise ValueError(
                    f"book pages {', '.join(map(str, ids[key]))} and {ln['id']} share the English {key} "
                    "with different Japanese; one English, one Japanese"
                )
            ids[key].append(ln["id"])
            continue
        out[key] = row
        ids[key] = [ln["id"]]
        texts[key] = ln["ja"]
    return out


def gender_aliases(
    k_rows: dict[str, list[str]], female: dict[str, str]
) -> tuple[dict[str, list[str]], list[str]]:
    """The alias rows for a keyed type: a row whose key (always the English hash) has a
    female-variant key is repeated under that key, so a female character's live English finds the same
    Japanese. Stated rule for a shared key (reported, never silent): a real row under the female
    key wins and the alias is dropped; aliases with equal rows give one row; aliases with different rows
    give none (that English stays live English).
    → ({female key: row}, sorted dropped female keys)"""
    wanted: dict[str, list[list[str]]] = {}
    for key, row in k_rows.items():
        fkey = female.get(key)
        if fkey and fkey != key:
            wanted.setdefault(fkey, []).append(row)
    aliases: dict[str, list[str]] = {}
    dropped: list[str] = []
    for fkey, cands in wanted.items():
        if fkey in k_rows or any(c != cands[0] for c in cands):
            dropped.append(fkey)
        else:
            aliases[fkey] = cands[0]
    return aliases, sorted(dropped)


def ui_rows(lines: Iterable[dict[str, Any]]) -> dict[str, list[str]]:
    """{key: [text, h1, status]} for shipped UI strings; a shipped line needs its English hash."""
    out: dict[str, list[str]] = {}
    for ln in sorted((ln for ln in lines if shipped(ln)), key=lambda ln: ln["id"]):
        key = str(ln["id"])
        if key in out:
            raise ValueError(f"duplicate ui line {key}")
        if not ln.get("english") or not ln["english"].get("hash"):
            raise ValueError(f"ui {key}: shipped without english {{hash, src}}; run `make check`")
        status = lua_string(schema.STATUS_CHAR[ln["status"]])
        out[key] = [lua_string(ln["ja"]), h1_literal(ln["english"]["hash"]), status]
    return out


def ui_shard(key: str) -> str:
    return key[:1].upper()


def ui_text(c: str, shard_rows: dict[str, list[str]]) -> str:
    src = f"data/ui/ui-{c}.jsonl"
    return _add_text("ui", src, ((lua_string(k), slots) for k, slots in sorted(shard_rows.items())))


def _add_text(type_: str, src: str, entries: Iterable[tuple[str, list[str]]]) -> str:
    lines = [HEADER.format(src=src), "local _, WFJ = ...", f'WFJ.Data.add("{type_}", {{']
    for key, slots in entries:
        lines.append(f"  [{key}] = {{ {', '.join(slots)} }},")
    lines.append("})")
    return "\n".join(lines) + "\n"


def shard_text(type_: str, nnnn: int, shard_rows: dict[int, list[str]]) -> str:
    src = f"data/{type_}/{type_}-{nnnn:04d}.jsonl"
    return _add_text(type_, src, ((str(id_), slots) for id_, slots in sorted(shard_rows.items())))


def keyed_text(type_: str, nn: str, shard_rows: dict[str, list[str]]) -> str:
    """A keyed type's shard. gossip names its JSONL shard; a book shard gathers pages from
    any `data/book/` shard (its key is the English hash, not the page id)."""
    src = f"data/{type_}/{type_}-{nn}.jsonl" if type_ != "book" else "data/book/"
    return _add_text(type_, src, ((lua_string(k), slots) for k, slots in sorted(shard_rows.items())))


def _packed_word(entry: list[str], meanings: dict[tuple[str, str, str], int]) -> str:
    if len(entry) == 5:
        return f"{entry[0]}={entry[1]}={meanings[(entry[2], entry[3], entry[4])]}"
    return f"{entry[0]}={entry[1]}"


def reading_text(
    type_: str,
    shard: int | str,
    records: Iterable[dict[str, Any]],
    meanings: dict[tuple[str, str, str], int] | None = None,
) -> str:
    """One shard of readings for `type_` (ADR-036):
    `WFJ.Data.add("reading", { ["<type>:<id>"] = { <field> = "word=reading word=reading …", … } })`.
    One packed string per field (a string per word and per reading would cost more than the Japanese
    itself, in the file and in the client's memory); words are ASCII-free and readings kana-only, so " " and
    "=" never occur inside them. Rows by id, fields in the type's order, words in reading order. `records`
    are current ones. A word with a meaning packs as "word=reading=n", n its number in `meanings`
    (the generated meaning table, Data/Gloss/)."""
    from wfj.core.model import FIELDS  # the translation type's field order

    by_id: dict[int | str, dict[str, list[list[str]]]] = {}
    for rec in records:
        by_id.setdefault(rec["id"], {})[rec["field"]] = rec["words"]
    src = f"data/reading/{type_}/" + (
        "" if type_ == "book"  # keyed by the English hash, not the page id the shards hold
        else f"{type_}-{shard:04d}.jsonl" if isinstance(shard, int) else f"{type_}-{shard}.jsonl"
    )
    lines = [HEADER.format(src=src), "local _, WFJ = ...", 'WFJ.Data.add("reading", {']
    for id_ in sorted(by_id, key=lambda i: (0, i, "") if isinstance(i, int) else (1, 0, i)):
        fields = by_id[id_]
        parts = []
        for f in FIELDS[type_]:
            if f in fields:
                packed = " ".join(_packed_word(e, meanings or {}) for e in fields[f])
                parts.append(f"{f} = {lua_string(packed)}")
        lines.append(f"  [{lua_string(f'{type_}:{id_}')}] = {{ {', '.join(parts)} }},")
    lines.append("})")
    return "\n".join(lines) + "\n"


def gloss_text(_shard: int, rows: dict[int, tuple[str, str, str]]) -> str:
    """One file of the word popup's meanings (ADR-039):
    `WFJ.Data.add("gloss", { [n] = "dictionary form\treading\tmeaning" })`, numbered as the reading rows
    point at them. Rows by number."""
    from wfj.core import glosses

    lines = [HEADER.format(src="data/reading/ (the words' meanings)"), "local _, WFJ = ...",
             'WFJ.Data.add("gloss", {']
    lines += [f"  [{n}] = {lua_string(glosses.row_text(rows[n]))}," for n in sorted(rows)]
    lines.append("})")
    return "\n".join(lines) + "\n"


def meta_text(schema_version: int, english: dict[str, list[str]], counts: dict[str, int]) -> str:
    """`WFJ.Data.meta`: content-derived facts only (no timestamp, no path).

    `english` is {source: the versions its shipped lines were checked against}, joined with `+` when there is
    more than one. A source normally has exactly one; the quest cache has two, because two clients served
    different subsets of the quests and a union import keeps both (ADR-020). The per-line
    `english.src` is the exact version in every case; this is the summary."""
    eng = ", ".join(f"{k} = {lua_string('+'.join(sorted(v)))}" for k, v in sorted(english.items()))
    cnt = ", ".join(f"{k} = {counts.get(k, 0)}" for k in schema.TOC_ORDER)
    fields = ", ".join(
        f"{t} = {{ {', '.join(lua_string(f) for f in schema.SLOTS[t]['fields'])} }}" for t in schema.TYPES
    )
    return (
        "\n".join(
            [
                HEADER.format(src="data/"),
                "local _, WFJ = ...",
                "WFJ.Data.meta = {",
                f"  schema = {schema_version},",
                f"  english = {{ {eng} }},",
                f"  counts = {{ {cnt} }},",
                f"  fields = {{ {fields} }},",
                "}",
            ]
        )
        + "\n"
    )


def toc_block(relpaths: Iterable[str]) -> list[str]:
    """The TOC lines between the markers (backslash paths, as the client wants them)."""
    return [schema.TOC_BEGIN, *(p.replace("/", "\\") for p in relpaths), schema.TOC_END]


def vectors_text(rows: list[dict], head: str = "return") -> str:
    """`head` receives the table: `return` (the busted twin) or `WFJ.Data.vectors =` (Data/Vectors.lua)."""
    lines = [
        "-- GENERATED by pipeline/wfj/dev/gen_vectors.py from hash_vectors.jsonl. Do not edit.",
        f'{head} {{ norm = "{NORM_VERSION}", cases = {{',
    ]
    for r in rows:
        p = "nil"
        if r["player"]:
            pl = r["player"]
            p = (
                f"{{ name = {lua_string(pl['name'])}, class = {lua_string(pl['class'])}, "
                f"race = {lua_string(pl['race'])} }}"
            )
        lines.append(
            f"  {{ id = {lua_string(r['id'])}, raw = {lua_string(r['raw'])}, player = {p}, "
            f"norm = {lua_string(r['norm'])}, h1 = {r['h1']}, h2 = {r['h2']}, "
            f"key = {lua_string(r['key'])} }},"
        )
    lines.append("} }")
    return "\n".join(lines) + "\n"
