"""The voice addons' own files (ADR-061, ADR-062). Deterministic text.

A pack folder holds its TOC, Register.lua, README.txt and Sound/; the entry folder (the one a player
installs, which names every pack as a required dependency on CurseForge) holds only its TOC and README.txt.

The pack depends on the main addon and hands it one table through the main addon's single global,
`WoWForeverJapanese_RegisterVoice`. Format 2 (ADR-062): each line is { file name, Japanese hash,
seconds, v = { [voice id] = { file name, seconds } } }, the `v` table only for a line several differently
cast creatures say; `creatures` maps each speaker of such a line to its voice id ({ male voice, female
voice } for a creature shown as both). The addon plays a file only when the hash equals the hash of the
Japanese it ships.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Any

from wfj.emit.lua_writer import lua_string

FOLDER = "WoWForeverJapanese_Voice"
FORMAT = 2
VERSION = "0.0.1-mvp"
TITLE = "WoW Forever Japanese Voice (日本語音声)"
# the main addon's 字 medallion, so the voice rows nested under it in the AddOn List carry the same icon
ICON = "Interface\\AddOns\\WoWForeverJapanese\\Media\\icon"


def toc_text(
    interface: str,
    credits: Mapping[str, str] | None,
    title: str = TITLE,
    version: str = VERSION,
    project_id: int = 0,
) -> str:
    """A pack's TOC (with `credits`, it loads Register.lua) or the entry's (`credits` None: no files). The
    dependency on the main addon only orders loading: installing voice never installs the main addon."""
    if credits:
        notes = (
            f"Japanese voice for WoW Forever Japanese. Voices made locally with {credits['engine']}, "
            f"models {credits['models']} ({credits['licence']})."
        )
    else:
        notes = "Japanese voice for WoW Forever Japanese: installs every voice pack. No audio of its own."
    head = [
        f"## Interface: {interface}",
        f"## Title: {title}",
        f"## Notes: {notes}",
        f"## IconTexture: {ICON}",
        "## Dependencies: WoWForeverJapanese",
        "## Author: Zyaga",
        f"## Version: {version}",
    ]
    if project_id:
        head.append(f"## X-Curse-Project-ID: {project_id}")
    return "\n".join([*head, "", *(["Register.lua", ""] if credits else [])])


def _line(key: str, e: Mapping[str, Any]) -> str:
    head = f"{lua_string(e['file'])}, {lua_string(e['hash'])}, {e['seconds']:.1f}"
    if not e.get("variants"):
        return f"    [{lua_string(key)}] = {{ {head} }},"
    v = ", ".join(
        f"[{lua_string(vid)}] = {{ {lua_string(f)}, {s:.1f} }}"
        for vid, (f, s) in sorted(e["variants"].items())
    )
    return f"    [{lua_string(key)}] = {{ {head}, v = {{ {v} }} }},"


def _creature(c: int, v: str | tuple[str, str]) -> str:
    if isinstance(v, tuple):
        return f"    [{c}] = {{ {lua_string(v[0])}, {lua_string(v[1])} }},"
    return f"    [{c}] = {lua_string(v)},"


def _errors(errors: Mapping[str, Any]) -> list[str]:
    if not errors:
        return []
    kinds = [f"      [{e}] = {lua_string(k)}," for e, k in sorted(errors["kinds"].items())]
    voices = []
    for who, files in sorted(errors["voices"].items()):
        voices.append(f"      [{lua_string(who)}] = {{")
        voices += [
            f"        [{lua_string(k)}] = {{ {lua_string(f)}, {s:.1f} }},"
            for k, (f, s) in sorted(files.items())
        ]
        voices.append("      },")
    return ["  errors = {", "    kinds = {", *kinds, "    },", "    voices = {", *voices, "    },", "  },"]


def register_text(
    lines: Mapping[str, Mapping[str, Any]],
    creatures: Mapping[int, Any] | None = None,
    errors: Mapping[str, Any] | None = None,
    folder: str = FOLDER,
) -> str:
    """`lines`: {pack key: {file, hash, seconds, variants: {voice id: (file, seconds)}}}; `creatures`:
    {creature id: voice id or (male, female)}; `errors`: {kinds: {game voice id: kind}, voices:
    {"<race>-<f|m>": {kind: (file, seconds)}}}, the character's own spoken error lines. Written sorted."""
    body = [_line(key, e) for key, e in sorted(lines.items())]
    who = [_creature(c, v) for c, v in sorted((creatures or {}).items())]
    return "\n".join(
        [
            "-- Generated by wfj voice pack. Do not edit.",
            "WoWForeverJapanese_RegisterVoice({",
            f"  format = {FORMAT},",
            f"  folder = {lua_string(folder)},",
            "  lines = {",
            *body,
            "  },",
            "  creatures = {",
            *who,
            "  },",
            *_errors(errors or {}),
            "})",
            "",
        ]
    )


def readme_text(
    credits: Mapping[str, str], count: int, title: str = "WoW Forever Japanese Voice", holds: str = ""
) -> str:
    return "\n".join(
        [
            title,
            "",
            "Japanese voice over for the WoW Forever Japanese addon, which it needs to play anything.",
            *([holds] if holds else []),
            f"It holds {count} lines, spoken from the addon's own Japanese.",
            "",
            "Credits",
            f"- Speech engine: {credits['engine']}",
            f"- Voice models: {credits['models']}",
            f"- Licence of the voice models: {credits['licence']}",
            "",
            "The voices were generated on the maintainer's own computer. No hosted service was used.",
            "",
        ]
    )


def entry_readme_text(title: str, packs: Sequence[tuple[str, str]]) -> str:
    """`packs`: (title, what it holds) of every pack the entry installs."""
    return "\n".join(
        [
            title,
            "",
            "Japanese voice over for the WoW Forever Japanese addon, which it needs to play anything.",
            "This addon holds no audio. Installing it from the CurseForge app installs every voice pack:",
            "",
            *(f"- {t}: {h}" for t, h in packs),
            "",
            "One setting in the addon's options turns the voice off.",
            "Removing these addons leaves the addon working.",
            "",
        ]
    )
