"""The voice pack addon's own files: its TOC, Register.lua and README.txt (ADR-061). Deterministic text.

The pack depends on the main addon and hands it one table through the main addon's single global,
`WoWForeverJapanese_RegisterVoice`. Format 2 (ADR-062): each line is { file name, Japanese hash,
seconds, v = { [voice id] = { file name, seconds } } }, the `v` table only for a line several differently
cast creatures say; `creatures` maps each speaker of such a line to its voice id ({ male voice, female
voice } for a creature shown as both). The addon plays a file only when the hash equals the hash of the
Japanese it ships.
"""

from __future__ import annotations

from collections.abc import Mapping
from typing import Any

from wfj.emit.lua_writer import lua_string

FOLDER = "WoWForeverJapanese_Voice"
FORMAT = 2
VERSION = "0.0.1-mvp"


def toc_text(interface: str, credits: Mapping[str, str]) -> str:
    notes = (
        f"Japanese voice for WoW Forever Japanese. Voices made locally with {credits['engine']}, "
        f"models {credits['models']} ({credits['licence']})."
    )
    return "\n".join(
        [
            f"## Interface: {interface}",
            "## Title: WoW Forever Japanese Voice (日本語音声)",
            f"## Notes: {notes}",
            "## Dependencies: WoWForeverJapanese",
            "## Author: Zyaga",
            f"## Version: {VERSION}",
            "",
            "Register.lua",
            "",
        ]
    )


def _line(key: str, e: Mapping[str, Any]) -> str:
    head = f"{lua_string(e['file'])}, {lua_string(e['hash'])}, {e['seconds']:.1f}"
    if not e.get("variants"):
        return f"    [{lua_string(key)}] = {{ {head} }},"
    v = ", ".join(
        f"[{lua_string(vid)}] = {{ {lua_string(f)}, {s:.1f} }}"
        for vid, (f, s) in sorted(e["variants"].items())
    )
    return f"    [{lua_string(key)}] = {{ {head}, v = {{ {v} }} }},"


def _creature(c: int, v: str | tuple[str, str]) -> str:
    if isinstance(v, tuple):
        return f"    [{c}] = {{ {lua_string(v[0])}, {lua_string(v[1])} }},"
    return f"    [{c}] = {lua_string(v)},"


def register_text(lines: Mapping[str, Mapping[str, Any]], creatures: Mapping[int, Any] | None = None) -> str:
    """`lines`: {pack key: {file, hash, seconds, variants: {voice id: (file, seconds)}}}; `creatures`:
    {creature id: voice id or (male, female)}. Written sorted."""
    body = [_line(key, e) for key, e in sorted(lines.items())]
    who = [_creature(c, v) for c, v in sorted((creatures or {}).items())]
    return "\n".join(
        [
            "-- Generated by wfj voice pack. Do not edit.",
            "WoWForeverJapanese_RegisterVoice({",
            f"  format = {FORMAT},",
            f"  folder = {lua_string(FOLDER)},",
            "  lines = {",
            *body,
            "  },",
            "  creatures = {",
            *who,
            "  },",
            "})",
            "",
        ]
    )


def readme_text(credits: Mapping[str, str], count: int) -> str:
    return "\n".join(
        [
            "WoW Forever Japanese Voice",
            "",
            "Japanese voice over for the WoW Forever Japanese addon, which it needs to play anything.",
            f"It holds {count} lines, spoken from the addon's own Japanese.",
            "",
            "Credits",
            f"- Speech engine: {credits['engine']}",
            f"- Voice models: {credits['models']}",
            f"- Licence of the voice models: {credits['licence']}",
            "",
            "The voices were generated on the maintainer's own computer. No hosted service was used.",
            "",
        ]
    )
