"""The voice pack addon's own files: its TOC, Register.lua and README.txt (ADR-061). Deterministic text.

The pack depends on the main addon and hands it one table through the main addon's single global,
`WoWForeverJapanese_RegisterVoice`. Each entry is { file name, Japanese hash, seconds }; the addon plays a
file only when the hash equals the hash of the Japanese it ships for that key.
"""

from __future__ import annotations

from collections.abc import Mapping

from wfj.emit.lua_writer import lua_string

FOLDER = "WoWForeverJapanese_Voice"
FORMAT = 1
VERSION = "0.0.1-mvp"


def toc_text(interface: str, credits: Mapping[str, str]) -> str:
    notes = (
        f"Japanese voice for WoW Forever Japanese. Voices made locally with {credits['engine']}, "
        f"models {credits['models']} ({credits['licence']})."
    )
    return "\n".join(
        [
            f"## Interface: {interface}",
            "## Title: WoW Forever Japanese Voice (日本語音声)",
            f"## Notes: {notes}",
            "## Dependencies: WoWForeverJapanese",
            "## Author: Zyaga",
            f"## Version: {VERSION}",
            "",
            "Register.lua",
            "",
        ]
    )


def register_text(lines: Mapping[str, tuple[str, str, float]]) -> str:
    """`lines`: {pack key: (file name, Japanese hash, seconds)}, written sorted by key."""
    body = [
        f"    [{lua_string(key)}] = {{ {lua_string(f)}, {lua_string(h)}, {s:.1f} }},"
        for key, (f, h, s) in sorted(lines.items())
    ]
    return "\n".join(
        [
            "-- Generated by wfj voice pack. Do not edit.",
            "WoWForeverJapanese_RegisterVoice({",
            f"  format = {FORMAT},",
            f"  folder = {lua_string(FOLDER)},",
            "  lines = {",
            *body,
            "  },",
            "})",
            "",
        ]
    )


def readme_text(credits: Mapping[str, str], count: int) -> str:
    return "\n".join(
        [
            "WoW Forever Japanese Voice",
            "",
            "Japanese voice over for the WoW Forever Japanese addon, which it needs to play anything.",
            f"It holds {count} lines, spoken from the addon's own Japanese.",
            "",
            "Credits",
            f"- Speech engine: {credits['engine']}",
            f"- Voice models: {credits['models']}",
            f"- Licence of the voice models: {credits['licence']}",
            "",
            "The voices were generated on the maintainer's own computer. No hosted service was used.",
            "",
        ]
    )
