"""Every spell a fresh level-1 character has shows its description in Japanese. The set is
pipeline/level1_spells.txt (`make level1-spells`, from the client's SkillLineAbility / SkillLine tables; see
wfj.dev.level1_spells); the English and the Japanese are data/english/spell and data/spell."""

import json
from pathlib import Path

from wfj.core import align


def _ids(root: Path) -> set[int]:
    lines = (root / "pipeline/level1_spells.txt").read_text(encoding="utf-8").splitlines()
    assert lines[0].startswith("# GENERATED by `python -m wfj.dev.level1_spells"), lines[0]
    return {int(ln) for ln in lines[1:] if ln.strip()}


def _descriptions(folder: Path, key: str) -> dict[int, dict]:
    out: dict[int, dict] = {}
    for path in sorted(folder.glob("*.jsonl")):
        for raw in path.read_text(encoding="utf-8").splitlines():
            row = json.loads(raw)
            if row.get("field") == "description" and row.get(key):
                out[row["id"]] = row
    return out


def test_every_level1_spell_with_english_has_japanese(root):
    ids = _ids(root)
    assert len(ids) > 100  # the artifact is the whole set, not a sample
    english = _descriptions(root / "data/english/spell", "en")
    japanese = _descriptions(root / "data/spell", "ja")
    missing = sorted(i for i in ids if english.get(i, {}).get("en", "").strip() and i not in japanese)
    assert missing == [], f"level-1 spells with English and no Japanese: {missing}"


def test_the_name_list_tail_spells_translate_their_head_and_keep_the_names_live(root):
    english = _descriptions(root / "data/english/spell", "en")
    japanese = _descriptions(root / "data/spell", "ja")
    for spell in (1293657, 1293712):  # Languages, Armor Proficiency
        assert align.split_tail(english[spell]["en"])[1], spell
        row = japanese[spell]
        assert row["ja"].endswith(align.TAIL) and align.tail_problems(english[spell]["en"], row["ja"]) == []
        # a spell line is never trusted offline (ADR-007): it ships `unaligned` and the addon's Align.check gates it
        assert row["status"] == "unaligned" and row["provenance"]["class"] == "machine"
        assert row["provenance"]["source"].startswith("draft-spell-level1-sg")
