"""The player-visible spell scope (`wfj.dev.visible_spells`) and its committed artifact.

The generator reads two installed game clients, which CI does not have, so, as for `ui_inventory.txt`, what
is tested here is the pure part and the **committed artifact's integrity**: its header counts must match its
rows, so a regeneration that half-wrote or mis-scoped it fails the gate rather than silently shrinking the
translation scope."""

from pathlib import Path

import pytest

from wfj.dev import visible_spells as vs
from wfj.io import db2
from wfj.io.jsonl_store import Store

ARTIFACT = Path(__file__).resolve().parents[2] / "pipeline" / "visible_spells.txt"


def test_render_and_read_round_trip(tmp_path):
    sets = {"item": {5, 9}, "skill": {9, 40}, "trait": {40}}
    lines = vs.render("1.60.1.69913", "wow_classic_beta", sets)
    assert lines[0].startswith("# GENERATED by `python -m wfj.dev.visible_spells` from 1.60.1.69913")
    assert "item: 2 · skill: 2 · trait: 1 · union: 3" in lines[4]
    assert lines[5:] == ["item 5", "item,skill 9", "skill,trait 40"]  # ascending, sources in fixed order
    path = tmp_path / "visible_spells.txt"
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    assert vs.read_artifact(path) == {
        5: frozenset({"item"}),
        9: frozenset({"item", "skill"}),
        40: frozenset({"skill", "trait"}),
    }


@pytest.mark.parametrize(
    "line", ["item", "item 5 9", "item x", "nope 5", "item,nope 5", "5"]
)
def test_a_malformed_artifact_line_is_refused(tmp_path, line):
    path = tmp_path / "visible_spells.txt"
    path.write_text(f"# header\n{line}\n", encoding="utf-8")
    with pytest.raises(vs.VisibleError):
        vs.read_artifact(path)


def test_comments_and_blank_lines_are_skipped(tmp_path):
    path = tmp_path / "visible_spells.txt"
    path.write_text("# a\n\n  \nitem 7\n# b\n", encoding="utf-8")
    assert vs.read_artifact(path) == {7: frozenset({"item"})}


def test_an_unverified_layout_is_refused(tmp_path, monkeypatch):
    """The scope must not be derived from a field we have not verified on this build: a layout is trusted only on evidence."""
    m = vs.MAPS[0]

    class FakeArchive:
        def file_data_id(self, path, fallback=None):
            return fallback

        def read_file(self, fdid):
            return b"", []

    header = db2.Header(0, 0, 0, 0, 0xDEADBEEF, 0, 0, 0, 0, 0, 0, 0)
    monkeypatch.setattr(db2, "read_header", lambda buf, name="db2": header)
    with pytest.raises(vs.VisibleError, match=r"layout 0xDEADBEEF is not one its spell column was verified"):
        vs._spell_field(FakeArchive(), m)


def test_every_pinned_map_names_a_field_per_layout():
    for m in vs.MAPS:
        assert m.spell_field and m.evidence and m.file_data_id > 0
        assert all(isinstance(h, int) and isinstance(f, int) and f >= 0 for h, f in m.spell_field.items())
    assert {m.name for m in vs.MAPS} == {"SkillLineAbility", "TraitDefinition"}


def test_the_committed_artifact_is_consistent():
    """The gate on the artifact: the header's per-source counts and union must match the rows below it."""
    text = ARTIFACT.read_text(encoding="utf-8")
    assert "GENERATED by `python -m wfj.dev.visible_spells`" in text
    counts = [ln for ln in text.splitlines() if ln.startswith("# item: ")]
    assert len(counts) == 1
    stated = dict(
        part.strip().split(": ") for part in counts[0].lstrip("# ").split(" · ")
    )
    rows = vs.read_artifact(ARTIFACT)
    assert len(rows) == int(stated["union"])
    for source in vs.SOURCES:
        assert sum(1 for s in rows.values() if source in s) == int(stated[source])
    assert all(i > 0 and s for i, s in rows.items())
    assert sorted(rows) == list(rows)  # ascending, so a diff of a regeneration is readable


def test_the_scope_actually_narrows_the_spell_backlog(root):
    """The point of the scope: the visible set must be a real subset of the spells that have English and no Japanese,
    or scoping a batch by it would be theatre."""
    rows = vs.read_artifact(ARTIFACT)
    store, english = Store(root / "data"), Store(root / "data", english=True)
    have = {ln["id"] for ln in store.load("spell") if ln["field"] == "description"}
    gaps = {ln["id"] for ln in english.load("spell") if ln["field"] == "description"} - have
    visible_gaps = gaps & set(rows)
    assert visible_gaps, "no visible spell is missing Japanese; the artifact or the store is wrong"
    assert len(visible_gaps) < len(gaps) / 2, (
        f"{len(visible_gaps)} of {len(gaps)} description gaps are visible; the scope is meant to cut this "
        "backlog to a fraction, so a ratio this high means the artifact is not filtering"
    )


def test_an_unreadable_join_table_fails_instead_of_emptying_the_item_set(monkeypatch):
    """On Forever ItemEffect has no relationship map, so falling back to it when ItemXItemEffect
    cannot be read produced an empty item set and a scope with no item spells, silently. Only an ABSENT
    optional table falls back; any other failure is a VisibleError."""
    from types import SimpleNamespace

    def fake(archive, name):
        if name == "ItemXItemEffect":
            raise vs.VisibleError("ItemXItemEffect: encrypted section")
        if name == "ItemEffect":
            return SimpleNamespace(rows={1: [0] * 9}, relation={}), {"SpellID": 6}
        return SimpleNamespace(rows={1: ()}, relation={}), {}

    monkeypatch.setattr(vs, "_verified", fake)
    with pytest.raises(vs.VisibleError, match="encrypted"):
        vs.visible(object())
    # absent AND no relationship map: nothing can be joined: refused, never an empty set
    monkeypatch.setattr(vs, "_verified", lambda a, n: None if n == "ItemXItemEffect" else fake(a, n))
    with pytest.raises(vs.VisibleError, match="no item can be joined"):
        vs.visible(object())
