"""The UI inventory reads a Forever client UI extract, whose paths are lowercased, through a casefold index
over the camelot file map (FOREVER_WINDOWS). Forever is the only target, so there is no Classic Era run and no
`--client` switch."""

import io
import os
from contextlib import redirect_stdout
from pathlib import Path

import pytest

from wfj.dev import ui_inventory

GLOBALS = 'BaseTag,TagText_lang\nACCEPT,Accept\nLOG_OUT,Log Out\nCLOSE,Close\nSPELL_STAT1_NAME,Strength\nITEM_SOULBOUND,Soulbound\n'


def _lowercased_tree(tmp_path: Path, windows: dict[str, list[str]], body: str) -> Path:
    """Every mapped file, written the way a client_ui extract names it: the whole path lowercased."""
    addons = tmp_path / "interface" / "addons"
    for files in windows.values():
        for rel in files:
            f = addons / rel.lower()
            f.parent.mkdir(parents=True, exist_ok=True)
            f.write_text(body, encoding="utf-8")
    return addons


def _run(argv: list[str]) -> tuple[int, str]:
    out = io.StringIO()
    with redirect_stdout(out):
        code = ui_inventory.main(argv)
    return code, out.getvalue()


def test_the_forever_map_resolves_on_a_lowercased_extract(tmp_path):
    addons = _lowercased_tree(tmp_path, ui_inventory.FOREVER_WINDOWS, '<Button text="LOG_OUT"/>\nx = ACCEPT\n')
    index = ui_inventory.file_index(addons)
    for files in ui_inventory.FOREVER_WINDOWS.values():
        for rel in files:
            assert ui_inventory.resolve(index, rel).exists(), rel  # Blizzard's casing finds the lowercased file
    strings = {"LOG_OUT": "Log Out", "ACCEPT": "Accept", "ITEM_SOULBOUND": "Soulbound"}
    rows = ui_inventory.inventory(addons, strings, ui_inventory.FOREVER_WINDOWS)
    assert ("gamemenu", "LOG_OUT") in rows and ("questmap", "ACCEPT") in rows
    assert ("tooltip", "ITEM_SOULBOUND") in rows  # the FAMILIES are shared by both clients
    assert {s for s, _ in rows} == set(ui_inventory.FOREVER_WINDOWS)


def test_the_forever_map_keeps_blizzard_casing():
    # a map written in lowercase would pass on the extract and hide a typo; the casing is Blizzard's TOC casing
    assert all(any(c.isupper() for c in rel) for files in ui_inventory.FOREVER_WINDOWS.values() for rel in files)


def test_a_missing_file_is_named(tmp_path):
    addons = _lowercased_tree(tmp_path, {"x": ["Blizzard_MailFrame/MailFrame.lua"]}, "")
    with pytest.raises(FileNotFoundError, match="Blizzard_MailFrame/MailFrame.xml"):
        ui_inventory.window_keys(addons, ["Blizzard_MailFrame/MailFrame.xml"], {})


def test_main_stamps_the_header_and_takes_no_client(tmp_path):
    gs = tmp_path / "GlobalStrings.csv"
    gs.write_text(GLOBALS, encoding="utf-8")
    forever = _lowercased_tree(tmp_path / "f", ui_inventory.FOREVER_WINDOWS, "LOG_OUT\n")
    code, out = _run([str(forever), str(gs)])
    assert code == 0
    assert out.splitlines()[0] == ("# GENERATED by `python -m wfj.dev.ui_inventory` from the Forever (camelot) UI "
                                   "extract + GlobalStrings.")
    assert "gamemenu LOG_OUT" in out.splitlines()
    # there is no `--client` switch; passing it is a usage error, never a silent Era run
    assert _run(["--client", "forever", str(forever), str(gs)])[0] == 2
    assert _run(["--client", "era", str(forever), str(gs)])[0] == 2


def _source(env: str, default: Path) -> Path | None:
    path = Path(os.environ[env]) if env in os.environ else default
    return path if path.exists() else None


def test_forever_output_matches_the_committed_inventory(root):
    # Needs a Forever UI extract + its GlobalStrings: WFJ_FOREVER_UI=<extract>/interface/addons, WFJ_FOREVER_GLOBALSTRINGS
    addons = _source("WFJ_FOREVER_UI", root / "predecessors/forever-ui-1.60.1.70009/interface/addons")
    gs = _source("WFJ_FOREVER_GLOBALSTRINGS", root / "predecessors/clients/forever-1.60.1.70009/GlobalStrings.csv")
    if addons is None or gs is None:
        pytest.skip("no Forever UI extract")
    code, out = _run([str(addons), str(gs)])
    assert code == 0
    assert out == (root / "pipeline/ui_inventory.txt").read_text(encoding="utf-8")


def test_a_casefold_collision_is_refused(tmp_path):
    # two paths that differ only in case would otherwise resolve to whichever rglob returned last.
    # Needs a case-sensitive file system (CI's Linux); skipped where the second write lands on the first file.
    (tmp_path / "x").mkdir()
    (tmp_path / "x" / "Frame.lua").write_text("", encoding="utf-8")
    (tmp_path / "x" / "frame.lua").write_text("", encoding="utf-8")
    if len(list((tmp_path / "x").iterdir())) < 2:
        pytest.skip("case-insensitive file system")
    with pytest.raises(ValueError, match="differ only in case"):
        ui_inventory.file_index(tmp_path)


def test_the_tutorial_family_is_the_live_popup_ids_only():
    # only the ids the mainline TutorialFrame's DISPLAY_DATA lists draw (tutorialframe.lua:119–182, 365–368);
    # the body / title lookup takes race / class variants (:446–455, 481–487).
    strings = {"TUTORIAL17": "Reply.", "TUTORIAL_TITLE17": "Replying to Whispers", "TUTORIAL52": "A pet.",
               "TUTORIAL17_HUMAN": "Reply, human.", "TUTORIAL1": "Welcome.", "TUTORIAL_TITLE50": "Keyring",
               "TUTORIAL170": "Not an id.", "TUTORIAL_HUD_REVAMP_BAG_CHANGES": "Bags.", "TUTORIAL46": ""}
    assert ui_inventory.dynamic_keys("tutorial", strings) == {"TUTORIAL17", "TUTORIAL_TITLE17", "TUTORIAL52",
                                                               "TUTORIAL17_HUMAN"}


def test_the_tutorial_windows_are_mapped():
    # the popup is its own surface; the pointer frame and the reachable Blizzard_Tutorials parts are `help`
    assert ui_inventory.FOREVER_WINDOWS["tutorial"] == ["Blizzard_FrameXML/Mainline/TutorialFrame.lua",
                                                         "Blizzard_FrameXML/Mainline/TutorialFrame.xml"]
    help_files = set(ui_inventory.FOREVER_WINDOWS["help"])
    assert "Blizzard_TutorialManager/Blizzard_TutorialPointerFrame.lua" in help_files
    assert "Blizzard_Tutorials/Blizzard_Tutorials_Classes.lua" in help_files
    assert not any("NewPlayerExperience" in f or "BoostTutorial" in f for f in help_files)
