"""The Forever window list is mechanical. Every Blizzard addon the `camelot` client loads in game
(pipeline/forever_addons.txt, generated by `make forever-addons` from the client's TOCs) has exactly one
disposition with a reason (pipeline/forever_addon_dispositions.txt), the `surface` dispositions and the inventory's
file map (FOREVER_WINDOWS) name each other, and every window `SetTitle(` call site of a surface addon is
dispositioned (pipeline/forever_titles.txt)."""

import os
import re
from pathlib import Path

import pytest

from wfj.dev import client_addons, ui_inventory

ROOT = Path(__file__).resolve().parents[2]
# `no-content`: the window has an entry point on camelot, but the Forever client's own tables carry
# none of the content it opens on (a covenant window with no covenant spell, item or quest).
DISPOSITIONS = ("surface", "library", "no-text", "unreachable", "no-content", "planned", "not-a-window")
# `planned`: the text is not handled yet and is left as the client shows it.
TITLE_KINDS = ("key", "name", "ruled", "dynamic")
_LINE = re.compile(r"^(\S+)\s+(\S+)(?:\s+([^#]*?))?\s+#\s+(\S.*)$")
_EVIDENCE = re.compile(r"[\w/.-]+\.(?:lua|xml|toc):\d+|no reference in the load set")
_TABLES = re.compile(r"ItemSparse|SpellName|QuestV2|Spell\b|GlobalStrings|Forever tables")


def _lines(rel: str) -> list[str]:
    text = (ROOT / rel).read_text(encoding="utf-8")
    return [ln for ln in text.splitlines() if ln.strip() and not ln.startswith("#")]


def _addons() -> dict[str, str]:
    out = {}
    for ln in _lines("pipeline/forever_addons.txt"):
        addon, state, files = ln.split()
        assert state in client_addons.STATES and files.isdigit(), ln
        assert addon not in out, f"{addon} listed twice"
        out[addon] = state
    return out


def _dispositions() -> dict[str, tuple[str, str, str]]:
    out = {}
    for ln in _lines("pipeline/forever_addon_dispositions.txt"):
        m = _LINE.match(ln)
        assert m, f"a disposition needs `<addon> <disposition> [argument] # reason`: {ln!r}"
        addon, kind, arg, reason = m.group(1), m.group(2), (m.group(3) or "").strip(), m.group(4)
        assert kind in DISPOSITIONS, ln
        assert addon not in out, f"{addon} dispositioned twice"
        out[addon] = (kind, arg, reason)
    return out


def test_every_in_game_addon_has_exactly_one_disposition():
    in_game = {a for a, state in _addons().items() if state in ("login", "lod")}
    listed = set(_dispositions())
    assert not in_game - listed, f"no disposition: {sorted(in_game - listed)}"
    assert not listed - in_game, f"not an in-game addon of this build: {sorted(listed - in_game)}"


def test_surface_dispositions_and_the_inventory_map_name_each_other():
    surfaces_named: set[str] = set()
    surface_addons: set[str] = set()
    for addon, (kind, arg, _) in _dispositions().items():
        if kind != "surface":
            continue
        names = [n for n in re.split(r"[,\s]+", arg) if n]
        assert names, f"{addon}: surface names no surface"
        unknown = [n for n in names if n not in ui_inventory.FOREVER_WINDOWS]
        assert not unknown, f"{addon}: {unknown} not in FOREVER_WINDOWS"
        surfaces_named |= set(names)
        surface_addons.add(addon)
    for surface, files in ui_inventory.FOREVER_WINDOWS.items():
        assert surface in surfaces_named, f"no addon is dispositioned `surface {surface}`"
        for rel in files:
            addon = rel.split("/", 1)[0].casefold()
            assert addon in surface_addons, f"{rel} ({surface}) belongs to {addon}, which is not a surface addon"


def test_unreachable_and_no_content_dispositions_carry_their_evidence():
    for addon, (kind, arg, reason) in _dispositions().items():
        if kind == "unreachable":
            assert _EVIDENCE.search(reason), f"{addon}: unreachable without a file:line (or a no-reference) reason"
        elif kind == "no-content":
            assert _EVIDENCE.search(reason), f"{addon}: no-content without its entry point (file:line)"
            assert _TABLES.search(reason), f"{addon}: no-content without the client-table evidence"
        elif kind != "surface":
            assert not arg, f"{addon}: {kind} takes no argument"


def _titles() -> list[tuple[str, str, str, list[str]]]:
    out = []
    for ln in _lines("pipeline/forever_titles.txt"):
        body, _, reason = ln.partition("#")
        parts = body.split()
        assert len(parts) >= 3 and reason.strip(), f"a title needs `<addon> <path>:<line> <kind> […] # reason`: {ln!r}"
        addon, site, kind, rest = parts[0], parts[1], parts[2], parts[3:]
        assert kind in TITLE_KINDS and re.fullmatch(r"\S+\.lua:\d+", site), ln
        out.append((addon, site, kind, rest))
    return out


def test_title_dispositions_are_well_formed():
    keys = {ln.split()[0] for ln in _lines("pipeline/ui_keys.txt")}
    sites = set()
    for _addon, site, kind, rest in _titles():
        assert site not in sites, f"{site} dispositioned twice"
        sites.add(site)
        if kind == "key":
            assert len(rest) == 2, f"{site}: key takes `<KEY> <surface>`"
            key, surface = rest
            assert key in keys, f"{site}: {key} is not in ui_keys.txt"
            assert surface in ui_inventory.FOREVER_WINDOWS, f"{site}: no surface {surface}"
        else:
            assert not rest, f"{site}: {kind} takes no argument"


def test_every_set_title_site_of_a_surface_addon_is_dispositioned():
    default = ROOT / "predecessors/forever-ui-1.60.1.70338/interface/addons"
    addons = Path(os.environ["WFJ_FOREVER_UI"]) if "WFJ_FOREVER_UI" in os.environ else default
    if not addons.is_dir():
        pytest.skip("no Forever UI extract")
    surface_addons = {a for a, (kind, _, _) in _dispositions().items() if kind == "surface"}
    found = {f"{rel}:{n}" for _, rel, n, _ in client_addons.titles(addons, surface_addons)}
    listed = {site for _, site, _, _ in _titles()}
    assert not found - listed, f"SetTitle sites with no disposition: {sorted(found - listed)}"
    assert not listed - found, f"dispositioned sites the client does not have: {sorted(listed - found)}"
