"""Every kind of tooltip line the client tags (Enum.TooltipDataLineType) and every kind of tooltip it builds from
tooltip data (Enum.TooltipDataType) has exactly one recorded decision, from the client's own documentation
(pipeline/tooltip_line_kinds_inventory.txt and pipeline/tooltip_data_types_inventory.txt, generated by
`make tooltip-line-kinds`). A claim is checked, not trusted: a translated line kind names the dictionary keys it
relies on, and each must be a shipped key (and in UI/TooltipUnit's key list when that module writes it); a hooked
tooltip type must be registered by the module named. A kind a new client build adds fails here until decided."""

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
_KIND = re.compile(r"^([A-Za-z]+)\s+#\s+(translated|english): (\S.*)$")
_TYPE = re.compile(r"^([A-Za-z]+)\s+#\s+(hooked|not hooked): (\S.*)$")
_MODULE = re.compile(r"UI/(\w+)")
_KEYS = re.compile(r"keys: ([A-Z0-9_ ]+?)(?:;|$)")


def _inventory(name: str) -> list[str]:
    out = []
    for raw in (ROOT / "pipeline" / name).read_text(encoding="utf-8").splitlines():
        if raw.startswith("#") or not raw.strip():
            continue
        value, kind = raw.split()
        assert value.isdigit(), raw
        out.append(kind)
    return out


def _decisions(name: str, pattern: re.Pattern[str]) -> dict[str, tuple[str, str]]:
    out: dict[str, tuple[str, str]] = {}
    for raw in (ROOT / "pipeline" / name).read_text(encoding="utf-8").splitlines():
        if raw.startswith("#") or not raw.strip():
            continue
        m = pattern.match(raw)
        assert m, f"{name}: not a decision line: {raw!r}"
        assert m.group(1) not in out, f"{m.group(1)} decided twice"
        out[m.group(1)] = (m.group(2), m.group(3))
    return out


def _shipped_ui() -> set[str]:
    keys = {ln.strip() for ln in (ROOT / "pipeline/ui_keys.txt").read_text(encoding="utf-8").splitlines()
            if ln.strip() and not ln.startswith("#")}
    english = set()
    for path in (ROOT / "data/english/ui").glob("*.jsonl"):
        english |= {json.loads(ln)["id"] for ln in path.read_text(encoding="utf-8").splitlines() if ln.strip()}
    japanese = set()
    for path in (ROOT / "data/ui").glob("*.jsonl"):
        for ln in path.read_text(encoding="utf-8").splitlines():
            if ln.strip():
                row = json.loads(ln)
                if row.get("status") in ("trusted", "verified") and row.get("ja"):
                    japanese.add(row["id"])
    return keys & english & japanese


def _unit_keys() -> set[str]:
    text = (ROOT / "addon/WoWForeverJapanese/UI/TooltipUnit.lua").read_text(encoding="utf-8")
    block = text[text.index("TooltipUnit.KEYS = {"):text.index("local function creatureOnly")]
    return set(re.findall(r'"([A-Z][A-Z0-9_]+)"', block))


def test_inventories_list_the_client_enumerations():
    kinds, types = _inventory("tooltip_line_kinds_inventory.txt"), _inventory("tooltip_data_types_inventory.txt")
    assert len(kinds) == len(set(kinds)) and len(types) == len(set(types))
    assert {"QuestTitle", "QuestObjective", "UnitOwner", "UnitThreat", "GemSocket"} <= set(kinds)
    assert {"Item", "Spell", "Unit", "UnitAura", "MinimapMouseover", "Toy", "Currency"} <= set(types)


def test_every_line_kind_has_one_decision():
    kinds, decisions = set(_inventory("tooltip_line_kinds_inventory.txt")), _decisions(
        "tooltip_line_kinds.txt", _KIND)
    assert sorted(kinds - decisions.keys()) == [], "a tooltip line kind with no decision"
    assert sorted(decisions.keys() - kinds) == [], "a decision for a kind the client does not have"


def test_translated_line_kinds_name_real_keys_or_data():
    shipped, unit = _shipped_ui(), _unit_keys()
    for kind, (verdict, why) in _decisions("tooltip_line_kinds.txt", _KIND).items():
        if verdict != "translated":
            continue
        modules = _MODULE.findall(why)
        assert modules, f"{kind}: a translated kind names the module that writes it"
        for module in modules:
            assert (ROOT / f"addon/WoWForeverJapanese/UI/{module}.lua").is_file(), f"{kind}: no UI/{module}.lua"
        keys = _KEYS.search(why)
        assert keys or "data:" in why, f"{kind}: name its `keys:` or say `data:`"
        for key in (keys.group(1).split() if keys else []):
            assert key in shipped, f"{kind}: {key} is not a shipped dictionary key"
            if modules[0] == "TooltipUnit":
                assert key in unit, f"{kind}: {key} is not in TooltipUnit.KEYS, so the unit tooltip never matches it"


def test_every_tooltip_type_has_one_decision_that_matches_the_hooks():
    types, decisions = set(_inventory("tooltip_data_types_inventory.txt")), _decisions(
        "tooltip_data_types.txt", _TYPE)
    assert sorted(types - decisions.keys()) == [], "a tooltip type with no decision"
    assert sorted(decisions.keys() - types) == [], "a decision for a type the client does not have"
    hooked: dict[str, set[str]] = {}
    for module in ("Tooltip", "TooltipUnit"):
        text = (ROOT / f"addon/WoWForeverJapanese/UI/{module}.lua").read_text(encoding="utf-8")
        names = set(re.findall(r"AddTooltipPostCall\(types\.(\w+)", text))
        for listed in re.findall(r'for _, name in ipairs\(\{([^}]*)\}\) do\s+if types\[name\]', text):
            names |= set(re.findall(r'"(\w+)"', listed))
        hooked[module] = names
    for kind, (verdict, why) in decisions.items():
        registered = {m for m, names in hooked.items() if kind in names}
        if verdict == "hooked":
            module = _MODULE.search(why)
            assert module and module.group(1) in registered, f"{kind}: claimed hooked by a module that does not hook it"
        else:
            assert not registered, f"{kind}: claimed not hooked, but {sorted(registered)} hooks it"
