"""Coverage is found from the client's source, not from in-game screenshots. Every UI string the translated surfaces
can show (pipeline/ui_inventory.txt, generated by `make ui-inventory` from a Forever client UI extract + its
GlobalStrings) is either in the dictionary (pipeline/ui_keys.txt) or deliberately excluded with a reason
(pipeline/ui_exclusions.txt); every inventoried surface has an addon module and every module's surface is
inventoried. Forever is the only target, so there is no Classic Era inventory."""

import re
from pathlib import Path

from wfj.dev import ui_inventory
from wfj.io import wago

_EXCL = re.compile(r"^([A-Z][A-Z0-9_]*|ItemSubClass:\d+:\d+)\s+#\s+(\S.*)$")


INVENTORY = "pipeline/ui_inventory.txt"


def _inventory(root: Path) -> dict[str, set[str]]:
    out: dict[str, set[str]] = {}
    for raw in (root / INVENTORY).read_text(encoding="utf-8").splitlines():
        if raw.startswith("#") or not raw.strip():
            continue
        surface, key = raw.split()
        out.setdefault(key, set()).add(surface)
    return out


def _exclusions(root: Path) -> dict[str, str]:
    out: dict[str, str] = {}
    for raw in (root / "pipeline/ui_exclusions.txt").read_text(encoding="utf-8").splitlines():
        if raw.startswith("#") or not raw.strip():
            continue
        m = _EXCL.match(raw)
        assert m, f"exclusion without a reason: {raw!r}"
        assert m.group(1) not in out, f"{m.group(1)} excluded twice"
        out[m.group(1)] = m.group(2)
    return out


def test_every_inventoried_string_is_translated_or_excluded_with_a_reason(root):
    inventory = _inventory(root)
    keys = set(wago.read_keys(root / "pipeline/ui_keys.txt"))
    excluded = _exclusions(root)
    missing = sorted(k for k in inventory if k not in keys and k not in excluded)
    assert missing == [], f"inventoried but neither translated nor excluded: {missing[:20]}"
    assert sorted(keys & set(excluded)) == []


def _loadset(root: Path) -> set[str]:
    lines = (root / "pipeline/ui_loadset.txt").read_text(encoding="utf-8").splitlines()
    assert lines[0].startswith("# GENERATED by `python -m wfj.dev.ui_loadset"), lines[0]
    return {ln.split()[1] for ln in lines[1:] if ln.strip()}


def test_every_string_a_loaded_window_file_names_is_translated_or_excluded(root):
    # the window inventory scans the files each hooked window names; this sweep reads every loaded file of the
    # addons that carry text (pipeline/ui_loadset.txt), so a string outside those files cannot go unnoticed
    keys = set(wago.read_keys(root / "pipeline/ui_keys.txt"))
    undecided = sorted(_loadset(root) - keys - set(_exclusions(root)))
    assert undecided == [], f"{len(undecided)} named by a loaded file, neither translated nor excluded: {undecided[:20]}"


def test_the_inventory_covers_every_hooked_surface(root):
    surfaces = {s for ss in _inventory(root).values() for s in ss}
    assert surfaces == set(ui_inventory.FOREVER_WINDOWS)
    header = (root / INVENTORY).read_text(encoding="utf-8").splitlines()[0]
    assert header.startswith("# GENERATED by `python -m wfj.dev.ui_inventory"), header
    assert not (root / "pipeline/ui_inventory_forever.txt").exists()
    assert not (root / "pipeline/ui_classic_only.txt").exists()


def test_every_exclusion_names_a_key_the_forever_ui_can_reach(root):
    # no exclusion is left over from a Classic Era inventory. Each one either is inventoried or is a
    # Forever system the inventory's window scan does not see (gamepad prompts, screen narration, a shared English).
    inventory = set(_inventory(root)) | _loadset(root)
    stray = {k: r for k, r in _exclusions(root).items() if k not in inventory}
    assert all(("gamepad" in r or "narration" in r or "one English" in r) for r in stray.values()), stray


# Modules that declare a Compat namespace but are not a translated surface.
NOT_SURFACES = {"scan", "readings"}  # the word-reading box rides the quest / gossip surfaces, no window
_SURFACE_CONST = re.compile(r'^local (?:SURFACE|DECLARE) = "([a-z.]+)"', re.M)


def _module_surfaces(root: Path) -> dict[str, str]:
    out: dict[str, str] = {}
    for path in sorted((root / "addon/WoWForeverJapanese/UI").glob("*.lua")):
        for name in _SURFACE_CONST.findall(path.read_text(encoding="utf-8")):
            base = name.split(".")[0]
            if base not in NOT_SURFACES:
                out.setdefault(base, path.name)
    return out


def test_every_inventoried_surface_has_a_module_and_every_module_is_inventoried(root):
    # a surface with no hook, or a hook with no inventory, fails. Forever surfaces only (no Classic Era `questlog` /
    # `honor` modules).
    assert set(_module_surfaces(root)) == set(ui_inventory.FOREVER_WINDOWS)


def test_first_ui_pass_keys_are_resolved(root):
    # keys the first UI pass left open are resolved: a key now, or a reason of its own
    keys = set(wago.read_keys(root / "pipeline/ui_keys.txt"))
    assert "HONOR" in keys
    excluded = _exclusions(root)
    assert "no Forever UI file writes it" in excluded["ITEM_MOD_STAMINA_SHORT"]
    assert "repair mode" in excluded["REPAIR_COST"]


def test_the_hooked_windows_label_keys_are_inventoried(root):
    # a window key the dictionary carries must come from that window's source, so the inventory is not stale
    inventory = _inventory(root)
    for key in ("ACCEPT", "QUEST_OBJECTIVES", "ABANDON_QUEST", "RETURN_TO_GAME", "CURRENTLY_EQUIPPED", "CHANCE_TO_CRIT"):
        assert key in inventory, key
    # one label per surface, from that surface's own source (the Forever load set)
    samples = {
        "character": "CHARACTER", "reputation": "AT_WAR", "spellbook": "SHOW_ALL_SPELL_RANKS", "trainer": "TRAIN",
        "gossip": "GOODBYE", "bags": "EQUIP_CONTAINER", "mail": "SENDMAIL", "raid": "CONVERT_TO_RAID",
    }
    for surface, key in samples.items():
        assert surface in inventory.get(key, set()), (surface, key)


def test_the_forever_inventory_carries_the_retargeted_surfaces_labels(root):
    # one label per re-targeted Forever surface, from that surface's camelot / mainline source
    inventory = _inventory(root)
    samples = {
        "questmap": "ABANDON_QUEST_ABBREV", "pvprank": "PVP_RANK_NUMBER", "communities": "COMMUNITIES_ROSTER_COLUMN_TITLE_RANK",
        "skills": "SKILL_DETAIL_SELECT_PROMPT", "talents": "TALENT_FRAME_APPLY_BUTTON_TEXT", "gamemenu": "LOG_OUT",
        "friends": "WHO_LIST_SEARCH_INSTRUCTIONS", "help": "PROFESSIONS_BUTTON", "mail": "SENDMAIL",
        "spellbook": "SPELLBOOK", "merchant": "MERCHANT_PAGE_NUMBER",
    }
    keys = set(wago.read_keys(root / "pipeline/ui_keys.txt"))
    for surface, key in samples.items():
        assert surface in inventory.get(key, set()), (surface, key)
        assert key in keys, key
    # the Classic Era-only surfaces are not in the file map
    assert not {"questlog", "honor"} & set(ui_inventory.FOREVER_WINDOWS)
    assert {"questmap", "pvprank", "communities"} <= set(ui_inventory.FOREVER_WINDOWS)
    assert not hasattr(ui_inventory, "WINDOWS") and not hasattr(ui_inventory, "CLIENTS")


def test_the_forever_triage_keeps_names_english_and_curation(root):
    # the rank-0 title is a name, and names stay in English. "Back" takes its own word: BACK owns its Japanese
    # (Core/UIStrings.lua OWN), so it is listed while INVTYPE_CLOAK keeps 背中
    excluded = _exclusions(root)
    assert "name" in excluded["PVP_RANK_0_NAME"]
    assert "BACK" not in excluded
    assert "BACK" in set(wago.read_keys(root / "pipeline/ui_keys.txt"))
    # `|T…|t` is markup the Japanese keeps verbatim, so the texture-carrying QUEST_LOG_NO_QUESTS is listed
    assert "QUEST_LOG_NO_QUESTS" not in excluded
    assert "QUEST_LOG_NO_QUESTS" in set(wago.read_keys(root / "pipeline/ui_keys.txt"))


def test_no_exclusion_blames_an_unhooked_widget(root):
    # "shown only by a widget the <surface> surface does not hook" is a placeholder reason: the widget is hooked or
    # found untranslatable, so none may stay
    assert not [k for k, reason in _exclusions(root).items() if "does not hook" in reason]

