"""Every kind of tooltip line the client tags (Enum.TooltipDataLineType, pipeline/tooltip_line_kinds_inventory.txt,
generated by `make tooltip-line-kinds` from the Forever UI extract) has exactly one recorded decision in
pipeline/tooltip_line_kinds.txt: translated by which module, or left as the client wrote it and why. A kind a new
client build adds fails here until someone decides on it."""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
_DECISION = re.compile(r"^([A-Za-z]+)\s+#\s+(translated|english): (\S.*)$")
_MODULE = re.compile(r"UI/(\w+)")


def _inventory() -> list[str]:
    out = []
    for raw in (ROOT / "pipeline/tooltip_line_kinds_inventory.txt").read_text(encoding="utf-8").splitlines():
        if raw.startswith("#") or not raw.strip():
            continue
        value, name = raw.split()
        assert value.isdigit(), raw
        out.append(name)
    return out


def _decisions() -> dict[str, tuple[str, str]]:
    out: dict[str, tuple[str, str]] = {}
    for raw in (ROOT / "pipeline/tooltip_line_kinds.txt").read_text(encoding="utf-8").splitlines():
        if raw.startswith("#") or not raw.strip():
            continue
        m = _DECISION.match(raw)
        assert m, f"a decision must read `<Kind>  # translated|english: <why>`: {raw!r}"
        assert m.group(1) not in out, f"{m.group(1)} decided twice"
        out[m.group(1)] = (m.group(2), m.group(3))
    return out


def test_inventory_lists_the_client_kinds():
    kinds = _inventory()
    assert len(kinds) == len(set(kinds))
    assert {"QuestTitle", "QuestObjective", "UnitOwner", "SpellDescription", "GemSocket"} <= set(kinds)


def test_every_kind_has_one_decision():
    kinds, decisions = set(_inventory()), _decisions()
    assert sorted(kinds - decisions.keys()) == [], "a tooltip line kind with no decision"
    assert sorted(decisions.keys() - kinds) == [], "a decision for a kind the client does not have"


def test_translated_decisions_name_a_module_that_exists():
    for kind, (verdict, why) in _decisions().items():
        if verdict != "translated":
            continue
        modules = _MODULE.findall(why)
        assert modules, f"{kind}: a translated kind names the module that writes it"
        for module in modules:
            assert (ROOT / f"addon/WoWForeverJapanese/UI/{module}.lua").is_file(), f"{kind}: no UI/{module}.lua"
