-- GENERATED by `wfj generate` from data/reading/ui/ui-K.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("reading", {
  ["ui:KEYBINDINGFRAME_MOUSEWHEEL_ERROR"] = { text = "押下=おうか=78545 解放=かいほう=116965 状態=じょうたい=97218 持つ=もつ=79820 アクション=アクション=30850 マウスホイール=マウスホイール=34077 割り当てられません=わりあてられません=49930" },
  ["ui:KEYRING"] = { text = "キーリング=キーリング=31681" },
  ["ui:KEY_BINDING_TOOLTIP"] = { text = "右クリック=みぎクリック=54965 割り当て=わりあて=49914 解除=かいじょ=117134" },
  ["ui:KEY_BOUND"] = { text = "キー=キー=31673 割り当てました=わりあてました=49924" },
  ["ui:KEY_MOUSEWHEELDOWN"] = { text = "マウスホイール=マウスホイール=34076 下=した=36372" },
  ["ui:KEY_MOUSEWHEELUP"] = { text = "マウスホイール=マウスホイール=34076 上=うえ=36026" },
  ["ui:KILLING_BLOW_TOOLTIP"] = { text = "あなた=あなた=493 自身=じしん=110760 とどめを刺した=とどめをさした=19770 敵=てき=83936 プレイヤー=プレイヤー=33852" },
  ["ui:KILLING_BLOW_TOOLTIP_TITLE"] = { text = "とどめ=とどめ=19761 回数=かいすう=58117" },
  ["ui:KILLS"] = { text = "キル=キル=31669" },
  ["ui:KILLS_COMBATLOG_TOOLTIP"] = { text = "パーティ=パーティ=33503 メンバー=メンバー=34252 何か=なにか=41739 キルした=キルした=31670 とき=とき=19100 メッセージ=メッセージ=34239 表示します=ひょうじします=113343" },
})
