-- GENERATED by `wfj generate` from data/reading/ui/ui-J.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("reading", {
  ["ui:JOIN_QUEUE"] = { text = "参加=さんか=53685 リクエスト=リクエスト=35004" },
  ["ui:JOIN_THE_ALLIANCE"] = { text = "加わる=くわわる=51353" },
  ["ui:JOIN_THE_HORDE"] = { text = "加わる=くわわる=51353" },
  ["ui:JOURNEYMAN"] = { text = "一人前=いちにんまえ=35517" },
  ["ui:JOURNEYS_MAX_RENOWN_LABEL"] = { text = "最大=さいだい=87751 名声=めいせい=56699" },
  ["ui:JOURNEY_UNLOCKED_TOAST"] = { text = "ジャーニー=ジャーニー=32880 解放=かいほう=119247" },
})
