-- GENERATED by `wfj generate` from data/reading/ui/ui-J.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("reading", {
  ["ui:JOIN_QUEUE"] = { text = "参加=さんか=54185 リクエスト=リクエスト=35345" },
  ["ui:JOIN_THE_ALLIANCE"] = { text = "加わる=くわわる=51836" },
  ["ui:JOIN_THE_HORDE"] = { text = "加わる=くわわる=51836" },
  ["ui:JOURNEYMAN"] = { text = "一人前=いちにんまえ=35861" },
  ["ui:JOURNEYS_MAX_RENOWN_LABEL"] = { text = "最大=さいだい=88531 名声=めいせい=57220" },
  ["ui:JOURNEY_UNLOCKED_TOAST"] = { text = "ジャーニー=ジャーニー=33215 解放=かいほう=120301" },
})
