-- GENERATED by `wfj generate` from data/reading/ui/ui-K.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("reading", {
  ["ui:KEYBINDINGFRAME_MOUSEWHEEL_ERROR"] = { text = "押下=おうか=77885 解放=かいほう=115969 状態=じょうたい=96390 持つ=もつ=79154 アクション=アクション=30701 マウスホイール=マウスホイール=33813 割り当てられません=わりあてられません=49482" },
  ["ui:KEYRING"] = { text = "キーリング=キーリング=31495" },
  ["ui:KEY_BINDING_TOOLTIP"] = { text = "右クリック=みぎクリック=54473 割り当て=わりあて=49466 解除=かいじょ=116128" },
  ["ui:KEY_BOUND"] = { text = "キー=キー=31487 割り当てました=わりあてました=49476" },
  ["ui:KILLING_BLOW_TOOLTIP"] = { text = "あなた=あなた=493 自身=じしん=109803 とどめを刺した=とどめをさした=19667 敵=てき=83237 プレイヤー=プレイヤー=33602" },
  ["ui:KILLING_BLOW_TOOLTIP_TITLE"] = { text = "とどめ=とどめ=19660 回数=かいすう=57602" },
  ["ui:KILLS"] = { text = "キル=キル=31483" },
  ["ui:KILLS_COMBATLOG_TOOLTIP"] = { text = "パーティ=パーティ=33268 メンバー=メンバー=33982 何か=なにか=41371 キルした=キルした=31484 とき=とき=19002 メッセージ=メッセージ=33969 表示します=ひょうじします=112371" },
})
