-- GENERATED by `wfj generate` from data/reading/ui/ui-J.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("reading", {
  ["ui:JOIN_QUEUE"] = { text = "参加=さんか=52237 リクエスト=リクエスト=34116" },
  ["ui:JOURNEYMAN"] = { text = "一人前=いちにんまえ=34606" },
  ["ui:JOURNEY_UNLOCKED_TOAST"] = { text = "ジャーニー=ジャーニー=32073 解放=かいほう=115967" },
})
