-- GENERATED by `wfj generate` from data/reading/ui/ui-Y.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("reading", {
  ["ui:YELL"] = { text = "叫び=さけび=54237" },
  ["ui:YELLOW_GEM"] = { text = "黄=き=133521" },
  ["ui:YELL_MESSAGE"] = { text = "叫び=さけび=54237" },
  ["ui:YES"] = { text = "はい=はい=23666" },
  ["ui:YOUR_CLASS_MAY_NOT_PERFORM_ROLE"] = { text = "あなた=あなた=501 クラス=クラス=31574 この=この=8534 ロール=ロール=34397 担当できません=たんとうできません=77919" },
  ["ui:YOUR_ROLE"] = { text = "あなた=あなた=501 ロール=ロール=34397" },
  ["ui:YOU_COLLECTED_LABEL"] = { text = "収集=しゅうしゅう=52573" },
  ["ui:YOU_EARNED_LABEL"] = { text = "獲得=かくとく=96816" },
  ["ui:YOU_LOOT_MONEY"] = { text = "拾いました=ひろいました=78153" },
  ["ui:YOU_LOOT_MONEY_GUILD"] = { text = "拾いました=ひろいました=78153 ギルドバンク=ギルドバンク=31525 預け入れ=あずけいれ=131169" },
  ["ui:YOU_LOOT_MONEY_MOD"] = { text = "拾いました=ひろいました=78153" },
  ["ui:YOU_RECEIVED"] = { text = "入手=にゅうしゅ=46074" },
  ["ui:YOU_RECEIVED_LABEL"] = { text = "入手しました=にゅうしゅしました=46095" },
  ["ui:YOU_WON_LABEL"] = { text = "獲得=かくとく=96827" },
})
