-- GENERATED by `wfj generate` from data/reading/ui/ui-K.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("reading", {
  ["ui:KEYBINDINGFRAME_MOUSEWHEEL_ERROR"] = { text = "押下=おうか=80778 解放=かいほう=120303 状態=じょうたい=100010 持つ=もつ=82093 アクション=アクション=31766 マウスホイール=マウスホイール=35027 割り当てられません=わりあてられません=51314" },
  ["ui:KEYRING"] = { text = "キーリング=キーリング=32605" },
  ["ui:KEY_BINDING_TOOLTIP"] = { text = "右クリック=みぎクリック=56496 割り当て=わりあて=51298 解除=かいじょ=120473" },
  ["ui:KEY_BOUND"] = { text = "キー=キー=32597 割り当てました=わりあてました=51308" },
  ["ui:KEY_MOUSEWHEELDOWN"] = { text = "マウスホイール=マウスホイール=35026 下=した=37363" },
  ["ui:KEY_MOUSEWHEELUP"] = { text = "マウスホイール=マウスホイール=35026 上=うえ=37010" },
  ["ui:KILLING_BLOW_TOOLTIP"] = { text = "あなた=あなた=506 自身=じしん=113909 とどめを刺した=とどめをさした=20358 敵=てき=86309 プレイヤー=プレイヤー=34800" },
  ["ui:KILLING_BLOW_TOOLTIP_TITLE"] = { text = "とどめ=とどめ=20348 回数=かいすう=59731" },
  ["ui:KILLS"] = { text = "キル=キル=32593" },
  ["ui:KILLS_COMBATLOG_TOOLTIP"] = { text = "パーティ=パーティ=34448 メンバー=メンバー=35205 何か=なにか=42879 キルした=キルした=32594 とき=とき=19667 メッセージ=メッセージ=35192 表示します=ひょうじします=116567" },
})
