-- GENERATED by `wfj generate` from data/reading/ui/ui-Z.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("reading", {
  ["ui:ZONE"] = { text = "ゾーン=ゾーン=33297" },
  ["ui:ZONE_COLON"] = { text = "ゾーン=ゾーン=33297" },
  ["ui:ZOOM_IN"] = { text = "ズームイン=ズームイン=33242" },
  ["ui:ZOOM_OUT"] = { text = "ズームアウト=ズームアウト=33239" },
})
