-- GENERATED by `wfj generate` from data/reading/ui/ui-Z.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("reading", {
  ["ui:ZONE"] = { text = "ゾーン=ゾーン=33443" },
  ["ui:ZONE_COLON"] = { text = "ゾーン=ゾーン=33443" },
  ["ui:ZOOM_IN"] = { text = "ズームイン=ズームイン=33388" },
  ["ui:ZOOM_OUT"] = { text = "ズームアウト=ズームアウト=33385" },
})
