-- GENERATED by `wfj generate` from data/reading/ui/ui-Y.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("reading", {
  ["ui:YELL"] = { text = "叫び=さけび=53809" },
  ["ui:YELLOW_GEM"] = { text = "黄=き=132431" },
  ["ui:YELL_MESSAGE"] = { text = "叫び=さけび=53809" },
  ["ui:YES"] = { text = "はい=はい=23506" },
  ["ui:YOUR_CLASS_MAY_NOT_PERFORM_ROLE"] = { text = "あなた=あなた=497 クラス=クラス=31359 この=この=8472 ロール=ロール=34151 担当できません=たんとうできません=77299" },
  ["ui:YOUR_ROLE"] = { text = "あなた=あなた=497 ロール=ロール=34151" },
  ["ui:YOU_COLLECTED_LABEL"] = { text = "収集=しゅうしゅう=52162" },
  ["ui:YOU_EARNED_LABEL"] = { text = "獲得=かくとく=96048" },
  ["ui:YOU_LOOT_MONEY"] = { text = "拾いました=ひろいました=77531" },
  ["ui:YOU_LOOT_MONEY_GUILD"] = { text = "拾いました=ひろいました=77531 ギルドバンク=ギルドバンク=31310 預け入れ=あずけいれ=130091" },
  ["ui:YOU_LOOT_MONEY_MOD"] = { text = "拾いました=ひろいました=77531" },
  ["ui:YOU_RECEIVED"] = { text = "入手=にゅうしゅ=45715" },
  ["ui:YOU_RECEIVED_LABEL"] = { text = "入手しました=にゅうしゅしました=45736" },
  ["ui:YOU_WON_LABEL"] = { text = "獲得=かくとく=96058" },
})
