-- GENERATED by `wfj generate` from data/reading/ui/ui-Y.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("reading", {
  ["ui:YELL"] = { text = "叫び=さけび=54233" },
  ["ui:YELLOW_GEM"] = { text = "黄=き=133513" },
  ["ui:YELL_MESSAGE"] = { text = "叫び=さけび=54233" },
  ["ui:YES"] = { text = "はい=はい=23665" },
  ["ui:YOUR_CLASS_MAY_NOT_PERFORM_ROLE"] = { text = "あなた=あなた=501 クラス=クラス=31573 この=この=8533 ロール=ロール=34396 担当できません=たんとうできません=77912" },
  ["ui:YOUR_ROLE"] = { text = "あなた=あなた=501 ロール=ロール=34396" },
  ["ui:YOU_COLLECTED_LABEL"] = { text = "収集=しゅうしゅう=52570" },
  ["ui:YOU_EARNED_LABEL"] = { text = "獲得=かくとく=96809" },
  ["ui:YOU_LOOT_MONEY"] = { text = "拾いました=ひろいました=78146" },
  ["ui:YOU_LOOT_MONEY_GUILD"] = { text = "拾いました=ひろいました=78146 ギルドバンク=ギルドバンク=31524 預け入れ=あずけいれ=131161" },
  ["ui:YOU_LOOT_MONEY_MOD"] = { text = "拾いました=ひろいました=78146" },
  ["ui:YOU_RECEIVED"] = { text = "入手=にゅうしゅ=46071" },
  ["ui:YOU_RECEIVED_LABEL"] = { text = "入手しました=にゅうしゅしました=46092" },
  ["ui:YOU_WON_LABEL"] = { text = "獲得=かくとく=96820" },
})
