-- GENERATED by `wfj generate` from data/reading/ui/ui-X.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("reading", {
  ["ui:XPBAR_LABEL"] = { text = "経験値=けいけんち=108748 バー=バー=34004" },
  ["ui:XP_STATUS_BAR_TEXT"] = { text = "経験値=けいけんち=108748" },
  ["ui:XP_TEXT_BANKED_XP_HEADER"] = { text = "貯めた=ためた=124103 経験値=けいけんち=108748" },
})
