-- GENERATED by `wfj generate` from data/quest/quest-0088.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("quest", {
  [88756] = { "派手な一発を取り戻す", "Dark Iron Dwarfの野営地からStolen Explosivesを$N1個取り戻す。", "Dark Ironsはここから東のDireforge Hillにいくつか野営地を構えとる。奴らはわしらの建設現場からexplosivesをごっそり盗んで、自分らのテントに運び込んだんだ。\n\nDark Ironsが火薬樽ひとつでどんな悪さをしでかすか、わざわざ言うまでもねえだろう！\n\nDark Ironsが危険なのは分かっとるが、あの樽は取り返さにゃならん。ほかの樽とは、赤い印がついとるから見分けがつく。Dark Ironsにくれてやるわけにはいかん！", nil, nil, 0xc57287cb, 0x0a061175, 0xf19bd9f0, nil, nil, "...mm" },
  [88757] = { "失われし者たちの装身具", "Essene's Necklace、Essene's Spellbook、Essene's Waterskinを持ち帰る。", "Dark Ironsから逃げている間に、装備をたくさん落としてしまった！\n\nどうやらなくしたのは……緑の革のwaterskinと、spellbookと、necklaceと……とにかく、どれも必要なものなんだ！\n\n私が荷物を詰め直して息を整えている間に見つけてくれたら、すごく助かる。", nil, nil, 0xb1b07501, 0x8dd0b2c0, 0xd5dd92b9, nil, nil, "...mm" },
  [88758] = { "失われし者たちの想い", "EsseneのメモをCorma Villardのもとへ持ち帰る。", "あとは荷物を詰め直すだけで、ここから出られる！\n\n最後にもうひとつ頼みを聞いてくれるなら、ほら、このメモをCormaに届けてくれ。私が生きていて、今そっちへ向かっていると伝わるはずだ！", nil, nil, 0x4c47fdf9, 0x12fd10da, 0x3d2951ce, nil, nil, "...mm" },
})
