-- GENERATED by `wfj generate` from data/quest/quest-0087.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("quest", {
  [87288] = { "柔らかなSaberの毛皮", "Soft Nightsaber Peltを$N1枚、Aldriaのところへ持って行ってください。", "こんにちは、旅の方！ 私たちの村を楽しんでいただけているといいのですが。私はDolanaarが好きなんです。小さくて素朴で、みんな親切ですから。\n\n私は地元の商人で、旅に役立ちそうな道具や小物をいろいろ仕入れています。実は、取引に興味がおありなら、nightsaber peltsが少し必要なんです。この雄大な生き物たちは美しいのですが、このあたりのものはかなり気が荒いので、身を守るために戦っても気に病むことはありませんよ。", nil, nil, 0x8e68b306, 0x5828382e, 0x9dca9c14, nil, nil, "...mm" },
  [87760] = { "聖なる潜り手", "Stormscale Beastmistressを見つけて倒し、彼女のRod of Deep Dominionを持ち帰ってください。", "Darnassusから返事が届いた、{name}！\n\n動物のサンプルから、nagaがこの海の生き物たちを支配し、嫌がる乗騎や荷役の獣として使っていたことが分かった。あまりに強情なもの、年老いたもの、ひどく傷ついたものは、娯楽のために追い払っていたのだ。なんと非道な！\n\nこれを止めるのは我々の神聖な務めだ！\n\nnagaはRuins of Mathystraに兵を置いていて、沖からthreshersを捕らえているに違いない。奴らの獣使いを見つけて倒し、その支配の道具を持ち帰ってくれ！", nil, nil, 0xbe769717, 0x6347b42a, 0xeef193cf, nil, nil, "...mm" },
})
