-- GENERATED by `wfj generate` from data/quest/quest-0076.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("quest", {
  [76156] = { "Earthmotherと共なる狩り", "Thunder Bluffの南東にあるVenture Companyの鉱山に忍び込み、発破用品の荷車からSeaforium Mining Chargeを5個集めて、Thunder BluffにいるBoarton Shadetotemのところへ持ち帰ってください。", "お前には隠された密やかな技の才能を感じるぞ、{class}。この仮面を使って近くのVenture Companyの鉱山に潜入し、奴らの物資を盗んでこい。説得力のある変装には見えないかもしれないが、腕の立つローグなら、人を惹きつける笑顔と巧みな陽動だけで、どんな見張りもすり抜けられる。お前にもその力があると私は信じている。", nil, nil, 0xec81cab9, 0xde9c38a6, 0x5a3e40a5, nil, nil, "...mm" },
  [76160] = { "Earthmotherと共なる狩り", "Thunder Bluffの北でWindfury Coneを8個集めてMortar and Pestleで使い、できたものを持ってThunder BluffにいるBoarton Shadetotemのところへ戻ってください。", "もしかしたら、お前の才能は変装ではなく毒にあるのかもしれん。北にいるHarpiesは、強い毒性を持つ樹脂を出す木に巣を作っている。巣の周りに落ちているconesを集めて、それを砕いて軟膏にしろ。刃に塗れば、この軟膏は敵の傷を肉に焼きつけ、その血を塩に変えるだろう。", nil, nil, 0xec81cab9, 0x9fd15768, 0x073c4ce2, nil, nil, "...mm" },
  [76240] = { "Earthmotherと共なる狩り", "Raw Brilliant Smallfishを買うか釣るかして手に入れ、Thunder BluffにいるBoarton Shadetotemの目の前でKnife Setを使ってそれをさばいてください。", "成功につながるかもしれない考えが、最後に一つある。お前にはまだ隠された才能があると感じるが、もっと遠回しなやり方でそれを引き出してみよう。\n\nRaw Brilliant Smallfishを手に入れて、ここへ持ってこい。この短剣を使って、それをさばいて切り身にするのだ。深く考えるな――自然にできることをやればいい。", nil, nil, 0xec81cab9, 0xb349e16f, 0xad230608, nil, nil, "...mm" },
})
