-- GENERATED by `wfj generate` from data/quest/quest-0082.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("quest", {
  [82208] = { "図書館のさらなる友", nil, nil, nil, nil, 0xf10ee12c, nil, nil, nil, nil, ".mmmm" },
  [82656] = { "Wild Leather Vest", "Turtle Scale Breastplatesを$N1個、Turtle Scale Glovesを$N2個、WildvineをCamp MojacheのJangdor Swiftstriderのところへ持って行って下さい。", "Wild Leatherのベストは、Wild Leather防具一式の要だ。ベストの骨組みとその中に織り込まれたwildvineが、胴体を最大限に守りつつ、強力な魔力が衣服全体に行き渡る品を生み出すのだ。\n\nこの型紙には、Turtle Scale breastplatesを2つ、Turtle Scale glovesを2組、それにwildvineを一つ用意してもらう。簡単な修行ではないが、お前なら確かにやり遂げられる腕がある。", nil, nil, 0x762367c6, 0xc0931d0e, 0x0f2311f8, nil, nil, "...mm" },
  [82657] = { "Wild Leather Vest", "Turtle Scale Breastplatesを$N1個、Turtle Scale Glovesを$N2個、WildvineをFeathermoon StrongholdのPratt McGrubbenのところへ持って行って下さい。", "Wild Leatherのベストは、Wild Leather防具一式の要だ。ベストの骨組みがwildvineと溶け合い、胴体を最大限に守りつつ、強力な魔力が衣服全体に行き渡る品が出来上がるんだ。\n\nこの型紙には、Turtle Scale breastplatesを2つ、Turtle Scale glovesを2組、それにwildvineを一つ用意してもらう。大変な注文だけど、君ならほとんど苦労せずに揃えられるはずだ。", nil, nil, 0x762367c6, 0x1e64e910, 0xcfbb37a9, nil, nil, "...mm" },
})
