-- GENERATED by `wfj generate` from data/quest/quest-0084.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("quest", {
  [84338] = { "拘束力のある契約", "Sulfuronの設計図を受け取りたいなら、Thorium Brotherhood ContractをLokhtos Darkbargainerに渡して下さい。", "署名者は、Thorium Brotherhood（TB Ltd.）へ納品するSulfuronのインゴットが本物であり、その模造品ではないことをここに宣言する。また署名者は、Sulfurasの製作、鍛造、発見、創造、販売、あるいは摂取を試みた結果として本人に生じるいかなる損害も、TB Ltd.の責任または過失ではないことを了承する。\n\nこの契約書に署名することにより、あなたはここに記載されたすべての条項に同意したものとする。\n\n_________________\n\n署名", nil, nil, 0xb3e013a8, 0xb4f357b1, 0x9f3945b5, nil, nil, "...mm", nil, nil, 0xc22a16e9, nil, nil },
  [84395] = { "Undead Potatoes", nil, nil, nil, nil, 0xe94bc437, nil, nil, nil, nil, ".mmmm" },
  [84396] = { "Magma or Lava?", nil, nil, nil, nil, 0xddd086e3, nil, nil, nil, nil, ".mmmm" },
  [84397] = { "Northern Kalimdor - A Comprehensive Guide", nil, nil, nil, nil, 0x1b1a6b97, nil, nil, nil, nil, ".mmmm" },
  [84398] = { "A Study of the Light", nil, nil, nil, nil, 0xddb1ac83, nil, nil, nil, nil, ".mmmm" },
  [84399] = { "ドカーン！", nil, nil, nil, nil, 0x41be4c43, nil, nil, nil, nil, ".mmmm" },
  [84400] = { "The Knight and the Lady", nil, nil, nil, nil, 0xec2c7ac8, nil, nil, nil, nil, ".mmmm" },
  [84401] = { "Scourge: Undead Menace or Misunderstood?", nil, nil, nil, nil, 0xd1d7a21a, nil, nil, nil, nil, ".mmmm" },
  [84402] = { "Necromancy 101", nil, nil, nil, nil, 0xaebf1ec4, nil, nil, nil, nil, ".mmmm" },
  [84495] = { "Fiery Plate Gauntlets", "Enchanted Thorium Barsを$N1個、Essence of Fireを$N2個、Star Rubiesを$N3個、Malyfous Darkhammerのところへ持って行って下さい。Unfired Plate Gauntletsも渡す必要がある。", "Thaurissanの髭にかけて！\n\nどこでそれを見つけたんだ？\n\nそれより、それを手放す気はあるか？ もちろん、そんな気高い心遣いには礼をするぞ。\n\nこうしよう、{name}。そのunfired gauntletsを譲ってくれたら、お前さん自身の一式を作る方法を教えてやる。正確なレシピを絞り込めるように、材料を集めてきてくれるだけでいい。\n\n取引成立か？？\n\n必要なもののリストはこれだ。お前さんがgauntletsを提供してくれるんだから、エンチャントされていないthoriumはわしが自腹で用意しよう。", nil, nil, 0x4cbb6a5e, 0x5de76819, 0xccc5a0a0, nil, nil, "...mm" },
})
