-- GENERATED by `wfj generate` from data/quest/quest-0080.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("quest", {
  [80001] = { "再び灯す", nil, nil, nil, nil, 0xef1f92bd, nil, nil, nil, nil, ".mmmm" },
  [80241] = { "鍛冶の起源", "Golden Scale Bracersを六つ、StormwindのHank the Hammerのところへ持って行って下さい。", "わしがお前さんくらいの年の頃、Galvanという名のドワーフがわしを弟子にして、鎧鍛冶の道を教えてくれた。Booty Bayへ発つ前に、鍛冶の技を高める意欲と決意のある者は皆鍛えてやると約束させられたんだ――だからわしはここにいる――あれから何年も経った今もな。\n\nさて、お前さんも少し学ぶ時だ。golden scale bracersを6つ作ってくれ。そうすれば鍛冶がどこから来たのかがわかるだろう、{name}。", nil, nil, 0x5dd39489, 0x350387d3, 0x870eb53b, nil, nil, "...mm" },
})
