-- GENERATED by `wfj generate` from data/ui/ui-J.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("ui", {
  ["JOIN_QUEUE"] = { "参加をリクエスト", 0xd6f22d98, "." },
  ["JOURNEYMAN"] = { "一人前", 0xb8b3b7cb, "." },
  ["JOURNEY_UNLOCKED_TOAST"] = { "ジャーニー解放", 0xa63faa78, "." },
})
