-- GENERATED by `wfj generate` from data/ui/ui-K.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("ui", {
  ["KEYBINDINGFRAME_MOUSEWHEEL_ERROR"] = { "押下と解放の状態を持つアクションにはマウスホイールを割り当てられません", 0x9445c57c, "." },
  ["KEYRING"] = { "キーリング", 0x86e9ad33, "." },
  ["KEY_BINDING_NAME_AND_KEY"] = { "%s（%s）", 0x515ea73e, "." },
  ["KEY_BINDING_TOOLTIP"] = { "<右クリックで割り当て解除>", 0xddf7d0f8, "." },
  ["KEY_BOUND"] = { "キーを割り当てました", 0x6d8aee77, "." },
  ["KEY_UNBOUND_ERROR"] = { "|cffff0000アクション「%s」の割り当てが解除されました！|r", 0x34112563, "." },
  ["KILLING_BLOW_TOOLTIP"] = { "あなた自身がとどめを刺した敵プレイヤー", 0xde750b8c, "." },
  ["KILLING_BLOW_TOOLTIP_TITLE"] = { "とどめ回数", 0xfcbc1456, "." },
  ["KILLS"] = { "キル", 0x32b2bdea, "." },
  ["KILLS_COMBATLOG_TOOLTIP"] = { "パーティのメンバーが何かをキルしたときにメッセージを表示します。", 0x36e44560, "." },
})
