-- GENERATED by `wfj generate` from data/ui/ui-X.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("ui", {
  ["XPBAR_LABEL"] = { "経験値バー", 0xf61e2626, "." },
  ["XP_STATUS_BAR_TEXT"] = { "経験値: %d/%d", 0xfaf4f2d7, "." },
  ["XP_TEXT_BANKED_XP_HEADER"] = { "貯めた経験値", 0x0514d90a, "." },
})
