-- GENERATED by `wfj generate` from data/ui/ui-Y.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("ui", {
  ["YELL"] = { "叫び", 0x0c07a520, "." },
  ["YELLOW_GEM"] = { "黄", 0x6c7c7722, "." },
  ["YELL_MESSAGE"] = { "叫び", 0x0c07a520, "." },
  ["YES"] = { "はい", 0x00178243, "." },
  ["YOUR_CLASS_MAY_NOT_PERFORM_ROLE"] = { "あなたのクラスはこのロールを担当できません。", 0x22cc9461, "." },
  ["YOUR_ROLE"] = { "あなたのロール", 0x6c3c037f, "." },
  ["YOU_COLLECTED_LABEL"] = { "収集", 0xc050fff6, "." },
  ["YOU_EARNED_LABEL"] = { "獲得", 0xe34c8f22, "." },
  ["YOU_LOOT_MONEY"] = { "%sを拾いました", 0x64b51f40, "." },
  ["YOU_LOOT_MONEY_GUILD"] = { "%sを拾いました(%sをギルドバンクに預け入れ)", 0x7a7c23cc, "." },
  ["YOU_LOOT_MONEY_MOD"] = { "%sを拾いました(+%s)", 0x7a002794, "." },
  ["YOU_RECEIVED"] = { "入手:", 0xf602dd1d, "." },
  ["YOU_RECEIVED_LABEL"] = { "入手しました", 0x7eb928fd, "." },
  ["YOU_WON_LABEL"] = { "獲得！", 0x10e5029d, "." },
})
