-- GENERATED by `wfj generate` from data/ui/ui-Z.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("ui", {
  ["ZONE"] = { "ゾーン", 0x0c2c9214, "." },
  ["ZONE_COLON"] = { "ゾーン:", 0x3acec094, "." },
  ["ZOOM_IN"] = { "ズームイン", 0x4045483a, "." },
  ["ZOOM_OUT"] = { "ズームアウト", 0xe3758c8d, "." },
})
