-- GENERATED by `wfj generate` from data/objective/objective-0471.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("objective", {
  [471121] = { "Kul Tiransがここにいる理由を探る", 0x399b6957, "." },
  [471636] = { "自ら進んで血を捧げる", 0x9fb50498, "." },
  [471637] = { "Tortured Soulを解放する", 0x9cef74cc, "." },
  [471712] = { "Ardin Grassmanに何が起きたのかを調べる", 0x83a0a47e, "." },
  [471841] = { "キャンプファイアのそばに座る", 0xd2953d47, "." },
  [471923] = { "Tailoringのスキルを20まで上げる", 0xf38e72c6, "." },
  [471934] = { "Boosted Restバフを得る", 0x801ef2f5, "." },
})
