-- GENERATED by `wfj generate` from data/objective/objective-0447.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("objective", {
  [447296] = { "謎を解く", 0x96bbc2f4, "." },
})
