-- GENERATED by `wfj generate` from data/objective/objective-0381.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("objective", {
  [381035] = { "Egg of Onyxiaを破壊する", 0x27e32b20, "." },
  [381080] = { "Scythe of Eluneの手がかりを見つける", 0xecdc12ef, "." },
  [381116] = { "Theldren's Teamを倒す", 0x4d98205c, "." },
  [381131] = { "Lay of Ameth'Aranを読む", 0xd33b39d7, "." },
  [381132] = { "Fall of Ameth'Aranを読む", 0xd36da949, "." },
  [381142] = { "Night RunでHighborneの魂を解放する", 0xaffa4610, "." },
  [381143] = { "SatyrnaarでHighborneの魂を解放する", 0x5813f300, "." },
  [381177] = { "Drullを救出する", 0x6d39f825, "." },
  [381178] = { "Tog'tharを救出する", 0x64af34f4, "." },
  [381321] = { "Ysidaを解放する", 0x19481639, "." },
  [381589] = { "Metzen the Reindeerを見つけて救出する", 0xa60c43d1, "." },
  [381845] = { "Silithystを持ち帰る", 0x99f2356d, "." },
  [381874] = { "Rabid Thistle Bearを捕獲する", 0xb4020a0e, "." },
  [381915] = { "Ju-Ju Heapsを破壊する", 0x69be99a1, "." },
  [381953] = { "Silithystを届ける", 0x9a3d2bb8, "." },
  [381965] = { "Scourgeの建造物を破壊する", 0x06b00cea, "." },
  [381999] = { "Gor'tesh Headを突き立てる", 0x08d39302, "." },
})
