-- GENERATED by `wfj generate` from data/objective/objective-0472.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("objective", {
  [472272] = { "キャンプファイアの近くで/sitエモートを使う", 0x07a12f4c, "." },
  [472273] = { "Boosted Restバフを得る", 0x801ef2f5, "." },
  [472284] = { "Tailoringのスキルを20まで上げる", 0xf38e72c6, "." },
})
