-- GENERATED by `wfj generate` from data/objective/objective-0448.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("objective", {
  [448737] = { "Kroll Mountainshadeを救出する", 0x9d992f05, "." },
  [448738] = { "Alara Grovemenderを救出する", 0xc76a625c, "." },
  [448739] = { "Elenora Marshwalkerを救出する", 0xaa7c2ff7, "." },
  [448818] = { "Alyssian Windcallerを救出する", 0x5f4a9489, "." },
  [448819] = { "Doran Dreamboughを救出する", 0x6ff25c78, "." },
  [448820] = { "Maseara Autumnmoonを救出する", 0xb8867f97, "." },
  [448889] = { "Elianar Shadowdrinkerを救出する", 0x4657d838, "." },
  [448890] = { "Serlina Starbrightを救出する", 0x22753c1c, "." },
  [448891] = { "Veanna Cloudsleeperを救出する", 0xf9365ed3, "." },
  [448933] = { "Mellias Earthtenderを救出する", 0x45b4cd72, "." },
  [448934] = { "Nerene Brooksingerを救出する", 0xedb151a2, "." },
  [448935] = { "Jamniss Treemenderを救出する", 0x045712e6, "." },
})
