-- GENERATED by `wfj generate` from data/objective/objective-0463.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("objective", {
  [463417] = { "Koboldの足跡をたどる", 0xcbcd606d, "." },
})
