-- GENERATED by `wfj generate` from data/objective/objective-0445.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("objective", {
  [445980] = { "Illari Duskfeatherを見つけた", 0xc7174335, "." },
})
