-- GENERATED by `wfj generate` from data/objective/objective-0462.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("objective", {
  [462326] = { "Frightened Paladinに手を貸す", 0xdf429b53, "." },
  [462329] = { "BrillのShari Stilwellに報告する", 0x410c0a4a, "." },
  [462436] = { "Hilda the Breakerと話す", 0x53e4d0d0, "." },
  [462437] = { "Jorin Crogeと話す", 0xde4674cb, "." },
  [462438] = { "Ander Sollidenと話す", 0x4c336f05, "." },
  [462439] = { "Danitha Morrと話す", 0xe7530beb, "." },
})
