-- GENERATED by `wfj generate` from data/objective/objective-0474.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("objective", {
  [474392] = { "水晶から学べることを学ぶ", 0x5e46ff49, "." },
  [474454] = { "Aamelia Windfieldと話す", 0x6a994c17, "." },
  [474501] = { "起爆装置を使う", 0x125a5bb1, "." },
})
