-- GENERATED by `wfj generate` from data/objective/objective-0480.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("objective", {
  [480147] = { "Kyleに餌をあげた", 0x73cce68d, "." },
  [480284] = { "Neeru Firebladeの反応を確かめる", 0xd3fe7bc4, "." },
})
