-- GENERATED by `wfj generate` from data/objective/objective-0479.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("objective", {
  [479017] = { "Randal Emersonから指示を受ける", 0x1d0e4aad, "." },
  [479018] = { "High Tinker Mekkatorqueと話す", 0x3ba9399f, "." },
  [479019] = { "King Magni Bronzebeardと話す", 0x960d6338, "." },
  [479020] = { "Tyrande Whisperwindと話す", 0xbc1c9bb6, "." },
  [479025] = { "Vol'jinと話す", 0x3d2e07a1, "." },
  [479026] = { "Cairne Bloodhoofと話す", 0x607021a5, "." },
  [479027] = { "Lady Sylvanas Windrunnerと話す", 0x19e7ef9c, "." },
  [479385] = { "プレイヤーとの決闘に勝つか、Novice Warriorsを倒す", 0x9a5b34f1, "." },
  [479408] = { "Deathguardsを鼓舞する", 0xfc11df5d, "." },
})
