-- GENERATED by `wfj generate` from data/objective/objective-0469.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("objective", {
  [469647] = { "Lumina Windsingerと話す", 0xce24a8cc, "." },
  [469963] = { "Trevanからメモを受け取る", 0x51dd770a, "." },
  [469964] = { "Ottが刃を作るのを見届ける", 0xa107c44d, "." },
})
