-- GENERATED by `wfj generate` from data/objective/objective-0466.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("objective", {
  [466031] = { "RoadでValenniaを見つける", 0x2bb977b1, "." },
  [466100] = { "Lorthunaと対決する", 0x90290d9d, "." },
  [466251] = { "Strange Hermitについてもっと調べる", 0xe0e5c185, "." },
  [466278] = { "Wind Hollowを解放する", 0x41ea73e1, "." },
  [466633] = { "Rathiril Sunlanceと話す", 0xd567c2e0, "." },
  [466639] = { "Shen'dar Highlandsの人里離れた家を見つける", 0x9bd70556, "." },
})
