-- GENERATED by `wfj generate` from data/objective/objective-0464.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("objective", {
  [464773] = { "Roiling Windsを破壊する", 0xc7468ec2, "." },
  [464975] = { "カルト信者たちの計画を探る", 0xdfa1f88a, "." },
  [464991] = { "Illaya Amberwindと話す", 0xcb5d90b0, "." },
})
