-- GENERATED by `wfj generate` from data/objective/objective-0468.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("objective", {
  [468000] = { "Enchanted Skyhopperを駆除する", 0x6b377b51, "." },
  [468023] = { "宿屋の主人と話す", 0xb77d53d4, "." },
  [468024] = { "宿屋の主人と話す", 0xb77d53d4, "." },
  [468449] = { "Talaanis Shadowsongと話す", 0x86fdd1d2, "." },
  [468519] = { "High Order Apprenticeを倒す", 0x4a0b9854, "." },
  [468521] = { "Windshaper Novice Seerを倒す", 0xa29a5781, "." },
  [468541] = { "Anchor Pylonを見る", 0xc9fec2d6, "." },
  [468803] = { "Jorel Windsingerを見つける", 0x5c123983, "." },
  [468886] = { "Injured Druidsを癒す", 0x5a91fc67, "." },
})
