-- GENERATED by `wfj generate` from data/objective/objective-0466.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("objective", {
  [466020] = { "Gelkis Captiveを救出した", 0xb080756b, "." },
  [466024] = { "Haggard Bonesを眠りにつかせた", 0x6df832b1, "." },
  [466031] = { "RoadでValenniaを見つける", 0x2bb977b1, "." },
  [466100] = { "Lorthunaと対決する", 0x90290d9d, "." },
  [466176] = { "Magram Frontを調査する", 0xd107abe8, "." },
  [466177] = { "Outcast Hideawayを調査する", 0x610e1d03, "." },
  [466251] = { "Strange Hermitについてもっと調べる", 0xe0e5c185, "." },
  [466278] = { "Wind Hollowを解放する", 0x41ea73e1, "." },
  [466302] = { "Khan Jehnを蘇らせた", 0x131df9ab, "." },
  [466600] = { "Mularaと話す", 0x8678b9fb, "." },
  [466633] = { "Rathiril Sunlanceと話す", 0xd567c2e0, "." },
  [466639] = { "Shen'dar Highlandsの人里離れた家を見つける", 0x9bd70556, "." },
})
