-- GENERATED by `wfj generate` from data/objective/objective-0475.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("objective", {
  [475500] = { "Gatehouse Shipmentを届ける", 0x4cf01516, "." },
  [475632] = { "Brazier of Eternal Flameに火を灯す", 0xe6989535, "." },
  [475684] = { "Olariaanと儀式を完了する", 0x4dd71a4f, "." },
  [475750] = { "Hissing Serumを投与する", 0x4256b4ff, "." },
})
