-- GENERATED by `wfj generate` from data/objective/objective-0465.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("objective", {
  [465190] = { "Thendal Grove Ley Lineの近くでRead Ley Lineの能力を使う", 0x8a8ff262, "." },
  [465191] = { "Rathiril Sunlanceの話を聞く", 0x1fa1ad74, "." },
  [465192] = { "Illayaの話を聞く", 0x7a6c4738, "." },
  [465193] = { "Elemental Convergenceの近くでSkysightを使う", 0xbea37cc8, "." },
  [465282] = { "Al'Aketh Turncoatを見つける", 0xc1352e97, "." },
  [465403] = { "Alvarion Windfieldの話を聞く", 0xc892d279, "." },
  [465404] = { "Aamelia Windfieldを見つける", 0xd8af91b6, "." },
  [465421] = { "Aameliaについて行き、最後の戦いに挑む", 0xff716600, "." },
  [465667] = { "Elemental Currentsのデータを集める", 0x94cdad6f, "." },
  [465686] = { "Fillion Flamebreezeを見つける", 0xfae43c43, "." },
  [465687] = { "敵を避けながらFillion Flamebreezeを安全な場所まで運ぶ", 0x082264eb, "." },
  [465741] = { "爆薬を仕掛ける", 0xb2080a68, "." },
  [465787] = { "Haggard Bonesを召喚するか倒す", 0x44ff5f83, "." },
  [465809] = { "Windshapersを仲間に引き入れる", 0x6e1607b1, "." },
  [465810] = { "High Orderを仲間に引き入れる", 0x9692fa9e, "." },
  [465840] = { "Valennia Stormfistと話す", 0xacafaca0, "." },
  [465935] = { "Hyusaa Quickbreezeに報告する", 0x32498a3f, "." },
  [465999] = { "Accursed Skullを浄化する", 0xdd5f2c13, "." },
})
