-- GENERATED by `wfj generate` from data/objective/objective-0461.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("objective", {
  [461780] = { "Injured Deathguardを癒す", 0x7b83ef0a, "." },
})
