-- GENERATED by `wfj generate` from data/objective/objective-0477.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("objective", {
  [477011] = { "Veenixを見つける", 0x36a09fcd, "." },
  [477266] = { "Enchantingのスキルを20まで上げる", 0x67d7fcad, "." },
  [477267] = { "Engineeringのスキルを20まで上げる", 0xe75484ed, "." },
  [477268] = { "Enchantingのスキルを20まで上げる", 0x67d7fcad, "." },
  [477270] = { "Engineeringのスキルを20まで上げる", 0xe75484ed, "." },
  [477368] = { "Mountaineer Corneliusを見つける", 0x4c37d9bb, "." },
  [477504] = { "Tarantula Eggを破壊する", 0xecffe759, "." },
  [477518] = { "Webbed Forsakenを解放する", 0x280e18e3, "." },
  [477632] = { "Doctor Martin Felbenと話す", 0x35c836fd, "." },
})
