-- GENERATED by `wfj generate` from data/objective/objective-0478.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("objective", {
  [478338] = { "Elaadrinの話を聞く", 0xf531ca63, "." },
  [478339] = { "Ayessaの話を聞く", 0x8190c0ad, "." },
  [478910] = { "Darkspear Islandsで勝利する", 0x730d9ec8, "." },
  [478911] = { "Darkspear Islandsで勝利する", 0x730d9ec8, "." },
  [478912] = { "Darkspear Islandsで勝利する", 0x730d9ec8, "." },
  [478913] = { "Darkspear Islandsで勝利する", 0x730d9ec8, "." },
  [478914] = { "Darkspear Islandsで勝利する", 0x730d9ec8, "." },
  [478915] = { "Darkspear Islandsで勝利する", 0x730d9ec8, "." },
})
