"""The client-table text rows no key ships (pipeline/family_rows.txt).

A text family ships only the keys `pipeline/ui_keys.txt` lists, one key per distinct English (ADR-042,
ADR-052), so a row a new build adds stays English until someone lists it. The served-text inventory sees
columns, not rows, and cannot catch that. This file names every row of every family whose English no listed
key of that family covers, each with the reason it is left out. `make family-rows` rewrites it from the pinned
Forever tables: a row it already names keeps its reason while its English is the same, and any other row gets
`?`. tests/python/test_family_rows.py fails on a `?`, so a new row is either listed in ui_keys.txt or given a
reason.

Usage: python -m wfj.dev.family_rows <client folder> <ui_keys.txt> <family_rows.txt>   (prints the new file)
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

from wfj.core.hashing import key as hash_key
from wfj.core.normalize import normalize_v1
from wfj.io import wago

UNREVIEWED = "?"
_LINE = re.compile(r"^(\S+)\s+(\S+)\s+([0-9a-f]{16})\s*(?:#.*)?$")
_BUILD = re.compile(r"^# build: (\S+)")

HEADER = """\
# Client-table text rows no key in ui_keys.txt ships, each with the reason it is left out. GENERATED by
# `make family-rows` (pipeline/wfj/dev/family_rows.py); edit only the reason column. One row per distinct
# English per family (the lowest id). A new row comes in as `?`: list it in ui_keys.txt (then rerun) or give
# it a reason. Reasons: curated (left out when the family was curated: names, zones, dungeons, classes,
# professions, ranks, developer and test rows; ADR-042, ADR-052), developer (a developer or tracking row the
# client never shows), name (a name; names stay English), gossip (an NPC's own line, shipped by the gossip
# surface), not-shown (a row no window shows, with the evidence after the hash).
"""


def english_hash(text: str) -> str:
    return hash_key(normalize_v1(text))


def uncovered(folder: Path, keys: list[str]) -> dict[str, str]:
    """{"<family>:<id>": English} for each distinct English of each family that no listed key of that family
    covers (the lowest id stands for the others)."""
    table = wago.read_families(folder)
    families = {*wago.TEXT_FAMILIES, "ItemSubClassName"}
    listed = set(wago.expand_keys([k for k in keys if k.split(":", 1)[0] in families], table))
    covered: dict[str, set[str]] = {}
    for k in listed:
        if k in table:
            covered.setdefault(k.split(":", 1)[0], set()).add(table[k])
    out: dict[str, str] = {}
    seen: set[tuple[str, str]] = set()

    def order(k: str) -> tuple[str, tuple[int, ...]]:
        family, _, rest = k.partition(":")
        return family, tuple(int(x) for x in rest.split(":"))

    for k in sorted(table, key=order):
        family = k.split(":", 1)[0]
        text = table[k]
        if text in covered.get(family, set()) or (family, text) in seen:
            continue
        seen.add((family, text))
        out[k] = text
    return out


def read(path: Path) -> tuple[str | None, dict[str, tuple[str, str, str]]]:
    """(build, {key: (reason, english hash, the rest of the line)}) from an existing file."""
    build: str | None = None
    rows: dict[str, tuple[str, str, str]] = {}
    if not path.is_file():
        return build, rows
    for raw in path.read_text(encoding="utf-8").splitlines():
        m = _BUILD.match(raw)
        if m:
            build = m.group(1)
            continue
        if not raw.strip() or raw.startswith("#"):
            continue
        m = _LINE.match(raw)
        if not m:
            raise ValueError(f"{path.name}: unreadable line: {raw}")
        comment = raw.split("#", 1)[1].strip() if "#" in raw else ""
        rows[m.group(1)] = (m.group(2), m.group(3), comment)
    return build, rows


def render(build: str, rows: dict[str, str], old: dict[str, tuple[str, str, str]]) -> str:
    lines = [HEADER.rstrip("\n"), f"# build: {build}"]
    # a row is named by the lowest id holding its English, which a build can change, so a reason
    # follows the English
    by_english = {(key.split(":", 1)[0], h): (reason, comment) for key, (reason, h, comment) in old.items()}
    for k, text in rows.items():
        h = english_hash(text)
        reason, comment = UNREVIEWED, ""
        if k in old and old[k][1] == h:
            reason, comment = old[k][0], old[k][2]
        elif (k.split(":", 1)[0], h) in by_english:
            reason, comment = by_english[(k.split(":", 1)[0], h)]
        shown = " ".join(text.split())
        comment = comment or (shown[:90] + ("..." if len(shown) > 90 else ""))
        lines.append(f"{k}  {reason}  {h}  # {comment}")
    return "\n".join(lines) + "\n"


def main(argv: list[str]) -> int:
    if len(argv) != 3:
        print(__doc__, file=sys.stderr)
        return 2
    folder, keys_path, rows_path = (Path(a) for a in argv)
    source = folder / "tables-source.txt"
    stamp = source.read_text(encoding="utf-8") if source.is_file() else ""
    m = re.search(r"^\S+ \S+@(\S+)$", stamp, re.MULTILINE)
    build = m.group(1) if m else folder.name
    _, old = read(rows_path)
    sys.stdout.write(render(build, uncovered(folder, wago.read_keys(keys_path)), old))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
