"""Generate vectors/align_vectors.{jsonl,lua}: the shared contract between core/align.py and Core/Align.lua.

Each row: {id, op, text, scope?, allowlist, expected}. `op` ∈ names · checkNames · numbers · numberWords.
`expected` is the Python result (numbers: sorted multiset as a list). Both suites iterate every row.
Usage: python -m wfj.dev.gen_align_vectors [out_dir]
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

from wfj.core import align
from wfj.emit.lua_writer import lua_string

AL = ["health", "mana", "horde", "stamina"]

CASES: list[tuple[str, str, str, str | None]] = [
    # id, op, text, scope
    ("names-01", "names", "Silverwind RefugeにいるSenani Thunderheartは、Sharptalon's Clawを見た。", None),
    ("names-02", "names", "Healthを回復。Manaも。Hordeの兵士。", None),
    ("names-03", "names", "Mk2 の ab cd と Kul'Tiras", None),
    ("names-04", "names", "{name}と{class}は Northshire Abbeyへ", None),
    ("names-05", "names", "Sharptalon’s Claw と Deathstalker Quinn", None),
    ("names-06", "names", "Splintertree Post, Ashenvale", None),
    ("names-07", "names", "Twilight's Hammer と twilight's hammer", None),
    ("names-08", "names", "ワインWineとワイン", None),
    ("names-09", "names", "Thunder Bluffの Cairne Bloodhoof", None),
    ("names-10", "names", "Restores 61 health over 18 sec. Must remain seated while eating.", None),
    (
        "check-01",
        "checkNames",
        "Silverwind RefugeにいるSenani Thunderheart",
        "Bring Sharptalon's Claw to Senani Thunderheart at Splintertree Post, Ashenvale.",
    ),
    ("check-02", "checkNames", "Post Splintertreeへ", "Bring it to Splintertree Post, Ashenvale."),
    ("check-03", "checkNames", "Chef Grualと話して下さい", "Speak with Chef Grual in Goldshire."),
    ("check-04", "checkNames", "Chef Grualと話して下さい", "Speak with Grual in Goldshire."),
    ("check-05", "checkNames", "Healthを回復", "Restores 61 health over 18 sec."),
    ("check-06", "checkNames", "Kul'Tirasの船", "The ships of Kul Tiras"),
    ("check-07", "checkNames", "Hakkarの祭壇", "the altar of Hakkari"),
    ("check-08", "checkNames", "Durnholde Keepへ", "Go to Durnholde."),
    ("numbers-01", "numbers", "Kobold Verminを１０匹殺し、Mk2を3つ", None),
    ("numbers-02", "numbers", "18秒間でhealthを61回復。回復中は座っている必要があります。", None),
    ("numbers-03", "numbers", "1,200ダメージと18.5秒", None),
    ("numbers-04", "numbers", "N1とN2は数ではない。５０ゴールド。", None),
    ("numbers-05", "numbers", "2abc 3 4x 55 66", None),
    ("numbers-06", "numbers", "Use: Restores 61 health over 18 sec. 3 3 3", None),
    ("numbers-07", "numbers", "Mk12を使え、abc12と34xyz、over 18sec.", None),
    ("numbers-08", "numbers", "Deals 12abc damage and 120 more", None),
    ("words-01", "numberWords", "twenty-five silver and two hundred gold, a dozen eggs", None),
    ("words-02", "numberWords", "Kill six Kobold Vermin and one Kobold Worker", None),
    ("words-03", "numberWords", "one thousand years; Single target; NINE lives", None),
    ("words-04", "numberWords", "Restores 61 health over 18 sec.", None),
    ("words-05", "numberWords", "thirteen-fourteen fifty two", None),
    ("words-06", "numberWords", "one2 and 3three and ten thousand and twenty five", None),
    ("words-07", "numberWords", "Hundred one-time a single", None),
]


def build() -> list[dict]:
    al = set(AL)
    rows = []
    for id_, op, text, scope in CASES:
        if op == "names":
            expected: object = align.latin_names(text, al)
        elif op == "checkNames":
            expected = align.check_names(text, scope or "", al)[1]
        elif op == "numbers":
            expected = sorted(align.numbers(text).elements(), key=lambda s: (len(s), s))
        elif op == "numberWords":
            expected = align.english_number_words(text)
        else:
            raise ValueError(op)
        row = {"id": id_, "op": op, "text": text, "scope": scope, "allowlist": AL, "expected": expected}
        rows.append(row)
    return rows


def to_lua(rows: list[dict]) -> str:
    lines = [
        "-- GENERATED by pipeline/wfj/dev/gen_align_vectors.py from align_vectors.jsonl. Do not edit.",
        "return { cases = {",
    ]
    al = ", ".join(lua_string(a) for a in AL)
    for r in rows:
        scope = lua_string(r["scope"]) if r["scope"] is not None else "nil"
        exp = ", ".join(lua_string(e) for e in r["expected"])
        lines.append(
            f"  {{ id = {lua_string(r['id'])}, op = {lua_string(r['op'])}, text = {lua_string(r['text'])}, "
            f"scope = {scope}, allowlist = {{ {al} }}, expected = {{ {exp} }} }},"
        )
    lines.append("} }")
    return "\n".join(lines) + "\n"


def write(out_dir: Path) -> None:
    rows = build()
    out_dir.mkdir(parents=True, exist_ok=True)
    with (out_dir / "align_vectors.jsonl").open("w", encoding="utf-8") as f:
        for r in rows:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")
    (out_dir / "align_vectors.lua").write_text(to_lua(rows), encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    args = argv if argv is not None else sys.argv[1:]
    out = Path(args[0]) if args else Path(__file__).resolve().parents[3] / "vectors"
    write(out)
    print(f"wrote {out / 'align_vectors.jsonl'} + .lua ({len(CASES)} cases)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
