"""The spells a fresh level-1 character already has, so a gap there is measured, not guessed.

    python -m wfj.dev.level1_spells --wow "<World of Warcraft>" --product wow_classic_beta > level1_spells.txt

A spell is in the set when a `SkillLineAbility` row learns it automatically (`AcquireMethod` 1 = on learning
the skill line, 2 = on gaining a level that the line allows) at skill rank ≤ 1, on a skill line that is not a
profession (`SkillLine.CategoryID` 11) or a secondary skill (9), every race and class together. The artifact
is committed, like `visible_spells.txt`, so the gate (`tests/python/test_level1_spells.py`) needs no game
install.

Read-only use of the local archive (ADR-021). Nothing is imported from these tables.

Column maps, pinned with their evidence (the method of `visible_spells`):
- `SkillLineAbility` layout `0x224F7EA0` (Forever, 18 fields): 3 SkillLine, 4 Spell (cross-build 6,035 /
  6,047, `visible_spells.MAPS`), 5 MinSkillLineRank (1 on 7,807 of 7,824 rows), 8 AcquireMethod (values 0–3).
- `SkillLine` layout `0x6763217C`: 6 CategoryID (values 6–12; checked on known lines: 98 / 109 languages → 10,
  414 / 415 armor → 8, 164 / 171 professions → 11, 129 / 185 / 356 secondary skills → 9, 6 / 26 class lines →
  7).
At 1.60.1.69913 the set is 171 spells. The research's scratch count was 221 with a filter it did not record;
every variant tried (with or without the secondary skills, with or without the rank bound) leaves the same two
spells (Languages and Armor Proficiency) with English and no Japanese.
"""

from __future__ import annotations

import argparse
import sys
from collections.abc import Sequence
from pathlib import Path

from wfj.io import casc, db2

SKILL_LINE_ABILITY = ("SkillLineAbility", 1266278, 0x224F7EA0)
SKILL_LINE = ("SkillLine", 1240935, 0x6763217C)
F_SKILL_LINE, F_SPELL, F_MIN_RANK, F_ACQUIRE = 3, 4, 5, 8
F_CATEGORY = 6
AUTO_LEARNED = (1, 2)
NOT_A_CLASS_SKILL = (9, 11)  # secondary skills, professions


class Level1Error(ValueError):
    """A table could not be read, or its layout is not the one its columns were verified on."""


def _table(archive: casc.LocalArchive, spec: tuple[str, int, int]) -> db2.Db2Table:
    name, fdid, layout = spec
    try:
        buf, gaps = archive.read_file(archive.file_data_id(f"DBFilesClient\\{name}.db2", fdid))
        got = db2.read_header(buf, name).layout_hash
        if got != layout:
            raise Level1Error(
                f"{name}: layout 0x{got:08X}, verified on 0x{layout:08X}; re-verify the columns"
            )
        return db2.read(buf, string_fields=frozenset(), encrypted=gaps, name=name)
    except (casc.CascError, db2.Db2Error) as e:
        raise Level1Error(f"{name}: {e}") from e


def level1(archive: casc.LocalArchive) -> set[int]:
    category = {i: r[F_CATEGORY] for i, r in _table(archive, SKILL_LINE).rows.items()}
    return {
        r[F_SPELL]
        for r in _table(archive, SKILL_LINE_ABILITY).rows.values()
        if r[F_SPELL] and r[F_ACQUIRE] in AUTO_LEARNED and r[F_MIN_RANK] <= 1
        and category.get(r[F_SKILL_LINE]) not in NOT_A_CLASS_SKILL
    }


def main(argv: Sequence[str] | None = None) -> int:
    p = argparse.ArgumentParser(prog="wfj.dev.level1_spells", description=__doc__.split("\n", 1)[0])
    p.add_argument("--wow", required=True, type=Path, help="the folder holding .build.info")
    p.add_argument("--product", required=True, help="the client, e.g. wow_classic_beta")
    a = p.parse_args(argv)
    try:
        archive = casc.LocalArchive(a.wow, a.product)
        ids = sorted(level1(archive))
    except (casc.CascError, Level1Error) as e:
        print(f"level1_spells: {e}", file=sys.stderr)
        return 1
    print(f"# GENERATED by `python -m wfj.dev.level1_spells --product {a.product}` at "
          f"{archive.info.version}: {len(ids)} spells a fresh level-1 character has (see the "
          "module docstring).")
    print("\n".join(str(i) for i in ids))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
