"""Tooltip line kinds: every kind of line the client tags a tooltip line with (Enum.TooltipDataLineType), read
from the client's own API documentation, so a kind no surface has decided on is found mechanically.

    python -m wfj.dev.tooltip_line_kinds <Interface/AddOns> > pipeline/tooltip_line_kinds_inventory.txt

`make tooltip-line-kinds` reads the Forever UI extract. The output is `<value> <Name>` per line, in value order.
`tests/python/test_tooltip_line_kinds.py` asserts every inventoried kind has exactly one decision in
pipeline/tooltip_line_kinds.txt. Re-run when the client build changes; commit the result.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

DOC = "blizzard_apidocumentationgenerated/tooltipinfoshareddocumentation.lua"
_ENUM = re.compile(r'Name = "TooltipDataLineType",.*?Fields =\s*\{(.*?)\n\t\t\t\},', re.S)
_FIELD = re.compile(r'\{ Name = "(\w+)", Type = "TooltipDataLineType", EnumValue = (\d+) \}')


def kinds(addons: Path) -> list[tuple[int, str]]:
    """The (value, name) pairs of Enum.TooltipDataLineType in the client's documentation, in value order."""
    path = next((p for p in addons.rglob("*.lua") if str(p).lower().endswith(DOC)), None)
    if path is None:
        raise SystemExit(f"tooltip_line_kinds: no {DOC} under {addons}")
    block = _ENUM.search(path.read_text(encoding="utf-8"))
    if block is None:
        raise SystemExit(f"tooltip_line_kinds: no TooltipDataLineType enumeration in {path}")
    return sorted((int(v), n) for n, v in _FIELD.findall(block.group(1)))


def main(argv: list[str]) -> int:
    if len(argv) != 1:
        print(__doc__, file=sys.stderr)
        return 2
    print("# GENERATED by `python -m wfj.dev.tooltip_line_kinds` from the Forever (camelot) UI extract.")
    for value, name in kinds(Path(argv[0])):
        print(f"{value} {name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
