"""Tooltip line kinds: every kind of line the client tags a tooltip line with (Enum.TooltipDataLineType), read
from the client's own API documentation, so a kind no surface has decided on is found mechanically.

    python -m wfj.dev.tooltip_line_kinds <Interface/AddOns> > pipeline/tooltip_line_kinds_inventory.txt
    python -m wfj.dev.tooltip_line_kinds --types <Interface/AddOns> \
        > pipeline/tooltip_data_types_inventory.txt

`make tooltip-line-kinds` reads the Forever UI extract. The output is `<value> <Name>` per line, in value
order.
`tests/python/test_tooltip_line_kinds.py` asserts every inventoried kind has exactly one decision in
pipeline/tooltip_line_kinds.txt, and with `--types` the same for the tooltip types (Enum.TooltipDataType) in
pipeline/tooltip_data_types.txt. Re-run when the client build changes; commit the result.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

DOC = "blizzard_apidocumentationgenerated/tooltipinfoshareddocumentation.lua"


def _patterns(enum: str) -> tuple[re.Pattern[str], re.Pattern[str]]:
    block = re.compile(rf'Name = "{enum}",.*?Fields =\s*\{{(.*?)\n\t\t\t\}},', re.S)
    field = re.compile(rf'\{{ Name = "(\w+)", Type = "{enum}", EnumValue = (\d+) \}}')
    return block, field


def kinds(addons: Path, enum: str = "TooltipDataLineType") -> list[tuple[int, str]]:
    """The (value, name) pairs of an enumeration in the client's tooltip documentation, in value order."""
    path = next((p for p in addons.rglob("*.lua") if str(p).lower().endswith(DOC)), None)
    if path is None:
        raise SystemExit(f"tooltip_line_kinds: no {DOC} under {addons}")
    pattern, field = _patterns(enum)
    block = pattern.search(path.read_text(encoding="utf-8"))
    if block is None:
        raise SystemExit(f"tooltip_line_kinds: no {enum} enumeration in {path}")
    return sorted((int(v), n) for n, v in field.findall(block.group(1)))


def main(argv: list[str]) -> int:
    types = argv[:1] == ["--types"]
    args = argv[1:] if types else argv
    if len(args) != 1:
        print(__doc__, file=sys.stderr)
        return 2
    flag = " --types" if types else ""
    print(f"# GENERATED by `python -m wfj.dev.tooltip_line_kinds{flag}` from the Forever (camelot) UI"
          " extract.")
    for value, name in kinds(Path(args[0]), "TooltipDataType" if types else "TooltipDataLineType"):
        print(f"{value} {name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
