"""Every GlobalStrings name the Forever client's loaded addon files mention, for the addons the addon
translates, so no string can sit in a loaded window file without a decision.

    python -m wfj.dev.ui_loadset <Interface/AddOns> <GlobalStrings.csv> > pipeline/ui_loadset.txt

The window inventory (pipeline/ui_inventory.txt) scans the files each hooked window names. This sweep reads
every file of every addon camelot loads in game (`wfj.dev.client_addons.sweep`) whose disposition in
pipeline/forever_addon_dispositions.txt is `surface`, `planned` or `library`, collects each name the
inventory's pattern finds there that GlobalStrings defines, and leaves out the names the window inventory
already has. An addon marked `unreachable`, `no-content`, `not-a-window` or `no-text` is covered by that
reason as a whole. The output is `<addon> <KEY>` per line, sorted. tests/python/test_ui_coverage.py asserts
every key is in pipeline/ui_keys.txt or pipeline/ui_exclusions.txt with a reason. `make ui-inventory` writes
it with the inventory.
"""

from __future__ import annotations

import sys
from pathlib import Path

from wfj.dev import client_addons, ui_inventory
from wfj.io import wago

DISPOSITIONS = Path(__file__).resolve().parents[2] / "forever_addon_dispositions.txt"
SWEPT = ("surface", "planned", "library")


def swept_addons(path: Path = DISPOSITIONS) -> set[str]:
    """The addons whose files carry text the addon may show."""
    out = set()
    for line in path.read_text(encoding="utf-8").splitlines():
        parts = line.split("#", 1)[0].split()
        if len(parts) >= 2 and parts[1] in SWEPT:
            out.add(parts[0])
    return out


def loadset(addons: Path, strings: dict[str, str], known: set[str], swept: set[str]) -> list[tuple[str, str]]:
    index = ui_inventory.file_index(addons)
    rows: set[tuple[str, str]] = set()
    for addon, _, files in client_addons.sweep(addons, index):
        if addon not in swept:
            continue
        for rel in files:
            text = index[rel].read_text(encoding="utf-8-sig", errors="ignore")
            if rel.endswith(".lua"):
                text = ui_inventory._strip_comments(text)
            for m in ui_inventory._NAMES.finditer(text):
                key = next(g for g in m.groups() if g)
                if key in strings and key not in known:
                    rows.add((addon, key))
    return sorted(rows)


def main(argv: list[str]) -> int:
    if len(argv) != 2 or argv[0].startswith("-"):
        print(__doc__, file=sys.stderr)
        return 2
    strings = wago.read_global_strings(Path(argv[1]))
    known = set(ui_inventory.read_inventory())
    print(f"# GENERATED by `python -m wfj.dev.ui_loadset` from {ui_inventory.SOURCE} + GlobalStrings.")
    for addon, key in loadset(Path(argv[0]), strings, known, swept_addons()):
        print(f"{addon} {key}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
