"""The Forever (camelot) client's windows as the UI inventory reads them: the files each translated
surface loads, and the string names Blizzard builds at run time. Data for `wfj.dev.ui_inventory`; a new window
or a new client build changes this file, not the scanner.
"""

from __future__ import annotations

# The Forever (camelot) load set per surface, resolved from the Forever TOCs ([Family] = Mainline,
# [Game] = Camelot; a line loads when its AllowLoadGameType names camelot or mainline and its
# ExcludeLoadGameType names neither). Forever has no QuestLogFrame, HonorFrame or classic guild frame: the
# quest log is the mainline quest map (`questmap`), honor is the camelot PvP rank frame (`pvprank`), the
# guild is Blizzard_Communities (`communities`).
_U = "Blizzard_UIPanels_Game/"
_PS = "Blizzard_PlayerSpells/"
FOREVER_WINDOWS: dict[str, list[str]] = {
    "questframe": [
        _U + "Mainline/QuestFrame.lua",
        _U + "Mainline/QuestFrame.xml",
        _U + "Camelot/QuestFrameTemplates.lua",
        _U + "Mainline/QuestFrameTemplates.xml",
        _U + "Mainline/QuestInfo.lua",
        _U + "Mainline/QuestInfo.xml",
    ],
    # the quest map's details and list, the popup detail frame (both in QuestMapFrame.xml), the shared
    # QuestInfo FontStrings, and the objective tracker's quest module
    "questmap": [
        _U + "Mainline/QuestMapFrame.lua",
        _U + "Mainline/QuestMapFrame.xml",
        _U + "Camelot/QuestMapFrameOverrides.lua",
        _U + "Camelot/QuestMapFrameUtils.lua",
        _U + "Mainline/QuestInfo.lua",
        _U + "Mainline/QuestInfo.xml",
        "Blizzard_ObjectiveTracker/Blizzard_ObjectiveTracker.lua",
        "Blizzard_ObjectiveTracker/Blizzard_ObjectiveTracker.xml",
        "Blizzard_ObjectiveTracker/Blizzard_QuestObjectiveTracker.lua",
        "Blizzard_ObjectiveTracker/Blizzard_QuestObjectiveTracker.xml",
        "Blizzard_ObjectiveTracker/Camelot/Blizzard_QuestObjectiveTrackerOverride.lua",
        "Blizzard_FrameXMLUtil/Camelot/QuestUtilsOverrides.lua",
    ],
    "gamemenu": [
        "Blizzard_GameMenu/Shared/GameMenuFrame.lua",
        "Blizzard_GameMenu/Shared/GameMenuFrame.xml",
        "Blizzard_SharedXML/Shared/Frame/MainMenuFrameTemplates.lua",
        "Blizzard_SharedXML/Mainline/Frame/MainMenuFrameTemplates.xml",
    ],
    "tooltip": ["Blizzard_GameTooltip/Mainline/GameTooltip.lua"],
    "character": [
        _U + "Camelot/CharacterFrame.lua",
        _U + "Camelot/CharacterFrame.xml",
        _U + "Camelot/PaperDollFrame.lua",
        _U + "Camelot/PaperDollFrame.xml",
        _U + "Shared/PaperDollFrameStats.lua",
        _U + "Vanilla/PaperDollFrameStats.lua",
        _U + "Cata/PaperDollFrameStats.lua",
        _U + "Camelot/PaperDollFrameStats.lua",
        # the constants the camelot panes read their labels from (Blizzard_UIPanels_Game.toc:42, 50, 51)
        _U + "Camelot/PaperDollFrameConstants.lua",
        _U + "Mainline/PaperDollFrameConstants.lua",
        _U + "Camelot/CharacterFrameConstants.lua",
    ],
    "reputation": [_U + "Camelot/ReputationFrame.lua", _U + "Camelot/ReputationFrame.xml"],
    "skills": [_U + "Camelot/SkillsFrame.lua", _U + "Camelot/SkillsFrame.xml"],
    "pvprank": [_U + "Camelot/PVPRankFrame.lua", _U + "Camelot/PVPRankFrame.xml"],
    "spellbook": [
        _PS + "Blizzard_PlayerSpellsFrame.lua",
        _PS + "Camelot/Blizzard_PlayerSpellsFrame.lua",
        _PS + "Camelot/Blizzard_PlayerSpellsFrame.xml",
        _PS + "SpellBook/Blizzard_SpellBookFrame.lua",
        _PS + "SpellBook/Blizzard_SpellBookFrame.xml",
        _PS + "Camelot/SpellBook/Blizzard_SpellBookFrame.lua",
        _PS + "SpellBook/Blizzard_SpellBookCategory.lua",
        _PS + "SpellBook/Blizzard_SpellBookSearch.lua",
        _PS + "SpellBook/Blizzard_SpellBookItem.lua",
        _PS + "SpellBook/Blizzard_SpellBookItem.xml",
        _PS + "SpellBook/Blizzard_SpellBookTemplates.xml",
        _PS + "Camelot/SpellBook/Blizzard_SpellBookTemplates.xml",
        "Blizzard_PagedContent/Blizzard_PagingControls.lua",  # the spellbook's page text
        "Blizzard_PagedContent/Blizzard_PagingControls.xml",
    ],
    "talents": [
        _PS + "ClassTalents/Blizzard_ClassTalentsFrame.lua",
        _PS + "Camelot/ClassTalents/Blizzard_ClassTalentsFrame.lua",
        _PS + "Camelot/ClassTalents/Blizzard_ClassTalentsFrame.xml",
        _PS + "ClassTalents/Blizzard_ClassTalentUtil.lua",
        _PS + "Camelot/ClassTalents/Blizzard_ClassTalentUtil.lua",
        "Blizzard_SharedTalentUI/Camelot/Blizzard_SharedTalentOverrides.lua",
        # the talent button tooltip (TALENT_BUTTON_TOOLTIP_* lines)
        "Blizzard_SharedTalentUI/Blizzard_TalentDisplay.lua",
        "Blizzard_SharedTalentUI/Blizzard_TalentButtonSpend.lua",
        "Blizzard_SharedTalentUI/Blizzard_TalentButtonSelect.lua",
    ],
    "trainer": [
        "Blizzard_TrainerUI/Mainline/Blizzard_TrainerUI.lua",
        "Blizzard_TrainerUI/Mainline/Blizzard_TrainerUI.xml",
        "Blizzard_TrainerUI/Mainline/Blizzard_TrainerUI_Camelot.lua",
    ],
    "gossip": [
        _U + "Shared/GossipFrameShared.lua",
        _U + "Shared/GossipFrameShared.xml",
        _U + "Mainline/GossipFrame.lua",
        _U + "Mainline/GossipFrame.xml",
    ],
    "merchant": [_U + "Mainline/MerchantFrame.lua", _U + "Mainline/MerchantFrame.xml"],
    "bank": [
        _U + "Camelot/BankFrame.lua",
        _U + "Camelot/BankFrame.xml",
        _U + "Mainline/BankFrameTemplates.lua",
        _U + "Mainline/BankFrameTemplates.xml",
    ],
    "bags": [
        _U + "Mainline/ContainerFrame.lua",
        _U + "Camelot/ContainerFrame.lua",
        _U + "Mainline/ContainerFrame.xml",
        "Blizzard_MainMenuBarBagButtons/Shared/MainMenuBarBagButtons.lua",
        "Blizzard_MainMenuBarBagButtons/Camelot/MainMenuBarBagButtons.lua",
        "Blizzard_MainMenuBarBagButtons/Camelot/MainMenuBarBagButtons.xml",
        "Blizzard_MainMenuBarBagButtons/Shared/BagsBar.lua",
    ],
    "mail": ["Blizzard_MailFrame/MailFrame.lua", "Blizzard_MailFrame/MailFrame.xml"],
    # friends and ignore (camelot FriendsFrame), and the who list (load-on-demand vanilla-style finder)
    "friends": [
        "Blizzard_FriendsFrame/Camelot/FriendsFrame.lua",
        "Blizzard_FriendsFrame/Camelot/FriendsFrame.xml",
        "Blizzard_FriendsFrame/Mainline/FriendsListTemplates.lua",
        "Blizzard_FriendsFrame/Mainline/FriendsListTemplates.xml",
        "Blizzard_GroupFinder_VanillaStyle/Mainline/WhoList.lua",
        "Blizzard_GroupFinder_VanillaStyle/Mainline/WhoList.xml",
    ],
    # the whole window (Blizzard_Communities.toc, camelot load set): the guild view (roster,
    # member list and detail, guild info and news) and ClubFinder, the communities list,
    # chat frame, streams, settings, ticket manager, invitations, tabs, calendar, errors, hyperlinks, avatar
    # picker, language, guild name change, guild rewards / perks and preferred-play settings.
    # Blizzard_CommunitiesSecure runs in the secure environment (UseSecureEnvironment) and is out of reach.
    "communities": [
        "Blizzard_Communities/GuildRoster.lua",
        "Blizzard_Communities/GuildRoster.xml",
        "Blizzard_Communities/CommunitiesMemberList.lua",
        "Blizzard_Communities/CommunitiesMemberList.xml",
        "Blizzard_Communities/GuildInfo.lua",
        "Blizzard_Communities/GuildInfo.xml",
        "Blizzard_Communities/Mainline/GuildInfo.lua",
        "Blizzard_Communities/GuildNews.lua",
        "Blizzard_Communities/GuildNews.xml",
        "Blizzard_Communities/CommunitiesList.lua",
        "Blizzard_Communities/CommunitiesList.xml",
        "Blizzard_Communities/CommunitiesChatFrame.lua",
        "Blizzard_Communities/CommunitiesChatFrame.xml",
        "Blizzard_Communities/CommunitiesInvitationFrame.lua",
        "Blizzard_Communities/CommunitiesInvitationFrame.xml",
        "Blizzard_Communities/CommunitiesGuildFinderFrame.lua",
        "Blizzard_Communities/CommunitiesGuildFinderFrame.xml",
        "Blizzard_Communities/CommunitiesStreams.lua",
        "Blizzard_Communities/CommunitiesStreams.xml",
        "Blizzard_Communities/CommunitiesAvatarPickerDialog.lua",
        "Blizzard_Communities/CommunitiesAvatarPickerDialog.xml",
        "Blizzard_Communities/CommunitiesAddDialogInsecure.lua",
        "Blizzard_Communities/CommunitiesAddDialogInsecure.xml",
        "Blizzard_Communities/CommunitiesTabs.lua",
        "Blizzard_Communities/CommunitiesTabs.xml",
        "Blizzard_Communities/CommunitiesLanguage.lua",
        "Blizzard_Communities/CommunitiesLanguage.xml",
        "Blizzard_Communities/ClubFinderApplicantList.lua",
        "Blizzard_Communities/ClubFinderApplicantList.xml",
        "Blizzard_Communities/ClubFinder.lua",
        "Blizzard_Communities/ClubFinder.xml",
        "Blizzard_Communities/CommunitiesSettings.lua",
        "Blizzard_Communities/CommunitiesSettings.xml",
        "Blizzard_Communities/CommunitiesTicketManagerDialog.lua",
        "Blizzard_Communities/CommunitiesTicketManagerDialog.xml",
        "Blizzard_Communities/CommunitiesErrors.lua",
        "Blizzard_Communities/CommunitiesHyperlink.lua",
        "Blizzard_Communities/CommunitiesCalendar.lua",
        "Blizzard_Communities/CommunitiesCalendar.xml",
        "Blizzard_Communities/GuildRewards.lua",
        "Blizzard_Communities/GuildRewards.xml",
        "Blizzard_Communities/GuildPerks.lua",
        "Blizzard_Communities/GuildPerks.xml",
        "Blizzard_Communities/Mainline/CommunitiesFrame_Bootstrap.lua",
        "Blizzard_Communities/GuildPreferredPlaySettings.lua",
        "Blizzard_Communities/GuildPreferredPlaySettings.xml",
        "Blizzard_Communities/GuildNameChange.xml",
        "Blizzard_Communities/CommunitiesFrame.lua",
        "Blizzard_Communities/CommunitiesFrame.xml",
        "Blizzard_Communities/Camelot/CommunitiesFrameOverrides.lua",
        "Blizzard_Communities/Localization.lua",
        # the shared ClubFinder helpers (the card's "All Specs", the looking-for spec lines)
        "Blizzard_FrameXMLUtil/CommunitiesUtil.lua",
    ],
    "raid": [
        "Blizzard_RaidFrame/Mainline/RaidFrame.lua",
        "Blizzard_RaidFrame/Mainline/RaidFrame.xml",
        "Blizzard_RaidUI/Mainline/Blizzard_RaidUI.lua",
        "Blizzard_RaidUI/Mainline/Blizzard_RaidUI.xml",
    ],
    "help": [
        "Blizzard_MicroMenu/Mainline/MainMenuBarMicroButtons.lua",
        "Blizzard_MicroMenu/Mainline/MainMenuBarMicroButtons.xml",
        "Blizzard_MicroMenu/Camelot/MainMenuBarMicroButtonsOverrides.lua",
        "Blizzard_MicroMenu/Camelot/MicroMenuContainerOverrides.lua",
        "Blizzard_MicroMenu/Camelot/MainMenuBarMicroMenu.xml",
        "Blizzard_PerformanceBar/PerformanceBar.lua",
        "Blizzard_StatusTrackingBar/Shared/ExpBar.lua",
        "Blizzard_StatusTrackingBar/Mainline/ExpBarOverrides.lua",
        "Blizzard_StatusTrackingBar/Camelot/PetExpBar.lua",
        "Blizzard_ActionBar/Shared/PetActionBar.lua",
        "Blizzard_ActionBar/Shared/PossessActionBar.lua",
    ],
}

# Every other window the Forever client loads (ADR-030). One entry per surface module; each file is
# in its addon's camelot load set (`python -m wfj.dev.client_addons --files`), and
# pipeline/forever_addon_dispositions.txt names every surface here (tests/python/test_forever_windows.py).
# An entry for a surface listed above (`help`) adds files to it.
_OTHER_WINDOWS: dict[str, list[str]] = {
    "achievement": [
        "Blizzard_AchievementUI/Mainline/Blizzard_AchievementUI.lua",
        "Blizzard_AchievementUI/Mainline/Blizzard_AchievementUI.xml",
    ],
    "addonlist": [
        "Blizzard_AddonList/AddonList.lua",
        "Blizzard_AddonList/AddonList.xml",
    ],
    "alerts": [
        "Blizzard_FrameXML/Mainline/AlertFrames.lua",
        "Blizzard_FrameXML/Mainline/AlertFrames.xml",
        "Blizzard_FrameXML/Mainline/AlertFrameSystems.lua",
        "Blizzard_FrameXML/Mainline/AlertFrameSystems.xml",
        "Blizzard_FrameXML/Camelot/AlertFrameSystemsOverride.lua",
    ],
    "auctionhouse": [
        "Blizzard_AuctionHouseUI/Shared/Blizzard_AuctionHouseUtil.lua",
        "Blizzard_AuctionHouseUI/Mainline/Blizzard_AuctionHouseUtil.lua",
        "Blizzard_AuctionHouseUI/Shared/Blizzard_AuctionData.lua",
        "Blizzard_AuctionHouseUI/Camelot/Blizzard_AuctionData.lua",
        "Blizzard_AuctionHouseUI/Shared/Blizzard_AuctionHouseSharedTemplates.lua",
        "Blizzard_AuctionHouseUI/Mainline/Blizzard_AuctionHouseSharedTemplates.lua",
        "Blizzard_AuctionHouseUI/Shared/Blizzard_AuctionHouseSharedTemplates.xml",
        "Blizzard_AuctionHouseUI/Mainline/Blizzard_AuctionHouseSharedTemplates.xml",
        "Blizzard_AuctionHouseUI/Shared/Blizzard_AuctionHouseTableBuilder.lua",
        "Blizzard_AuctionHouseUI/Shared/Blizzard_AuctionHouseTableBuilder.xml",
        "Blizzard_AuctionHouseUI/Shared/Blizzard_AuctionHouseTab.lua",
        "Blizzard_AuctionHouseUI/Mainline/Blizzard_AuctionHouseTab.xml",
        "Blizzard_AuctionHouseUI/Shared/Blizzard_AuctionHouseItemList.lua",
        "Blizzard_AuctionHouseUI/Mainline/Blizzard_AuctionHouseItemList.xml",
        "Blizzard_AuctionHouseUI/Shared/Blizzard_AuctionHouseCategoriesList.lua",
        "Blizzard_AuctionHouseUI/Mainline/Blizzard_AuctionHouseCategoriesList.lua",
        "Blizzard_AuctionHouseUI/Mainline/Blizzard_AuctionHouseCategoriesList.xml",
        "Blizzard_AuctionHouseUI/Shared/Blizzard_AuctionHouseSearchBar.lua",
        "Blizzard_AuctionHouseUI/Shared/Blizzard_AuctionHouseSearchBar.xml",
        "Blizzard_AuctionHouseUI/Shared/Blizzard_AuctionHouseBrowseResultsFrame.lua",
        "Blizzard_AuctionHouseUI/Shared/Blizzard_AuctionHouseBrowseResultsFrame.xml",
        "Blizzard_AuctionHouseUI/Shared/Blizzard_AuctionHouseCommoditiesList.lua",
        "Blizzard_AuctionHouseUI/Shared/Blizzard_AuctionHouseCommoditiesList.xml",
        "Blizzard_AuctionHouseUI/Shared/Blizzard_AuctionHouseItemBuyFrame.lua",
        "Blizzard_AuctionHouseUI/Shared/Blizzard_AuctionHouseItemBuyFrame.xml",
        "Blizzard_AuctionHouseUI/Shared/Blizzard_AuctionHouseSellFrame.lua",
        "Blizzard_AuctionHouseUI/Shared/Blizzard_AuctionHouseSellFrame.xml",
        "Blizzard_AuctionHouseUI/Shared/Blizzard_AuctionHouseCommoditiesSellFrame.lua",
        "Blizzard_AuctionHouseUI/Shared/Blizzard_AuctionHouseCommoditiesSellFrame.xml",
        "Blizzard_AuctionHouseUI/Shared/Blizzard_AuctionHouseCommoditiesBuyFrame.lua",
        "Blizzard_AuctionHouseUI/Shared/Blizzard_AuctionHouseCommoditiesBuyFrame.xml",
        "Blizzard_AuctionHouseUI/Shared/Blizzard_AuctionHouseItemSellFrame.lua",
        "Blizzard_AuctionHouseUI/Shared/Blizzard_AuctionHouseItemSellFrame.xml",
        "Blizzard_AuctionHouseUI/Shared/Blizzard_AuctionHouseAuctionsFrame.lua",
        "Blizzard_AuctionHouseUI/Mainline/Blizzard_AuctionHouseAuctionsFrame.xml",
        "Blizzard_AuctionHouseUI/Shared/Blizzard_AuctionHouseWoWTokenFrame.lua",
        "Blizzard_AuctionHouseUI/Shared/Blizzard_AuctionHouseWoWTokenFrame.xml",
        "Blizzard_AuctionHouseUI/Shared/Blizzard_AuctionHouseBuyDialog.lua",
        "Blizzard_AuctionHouseUI/Shared/Blizzard_AuctionHouseBuyDialog.xml",
        "Blizzard_AuctionHouseUI/Shared/Blizzard_AuctionHouseMultisell.lua",
        "Blizzard_AuctionHouseUI/Mainline/Blizzard_AuctionHouseMultisell.xml",
        "Blizzard_AuctionHouseUI/Shared/Blizzard_AuctionHouseFrame.lua",
        "Blizzard_AuctionHouseUI/Shared/Blizzard_AuctionHouseFrame.xml",
    ],
    "barbershop": [
        "Blizzard_BarbershopUI/Mainline/Blizzard_BarberShopUI.lua",
        "Blizzard_BarbershopUI/Mainline/Blizzard_BarberShopUI.xml",
        # the camera buttons' tooltip lines (CustomizationNoHeaderTooltip, watched by UI/BarberShop)
        "Blizzard_CustomizationUI/Blizzard_CustomizationUI.xml",
        # the option / choice frames' own words ("-Select-", "%d: %s", "Source: %s")
        "Blizzard_CustomizationUI/Blizzard_CustomizationOptionTemplates.lua",
    ],
    "battlefieldmap": [
        "Blizzard_BattlefieldMap/Mainline/Blizzard_BattlefieldMap.lua",
        "Blizzard_BattlefieldMap/Mainline/Blizzard_BattlefieldMap.xml",
    ],
    "blackmarket": [
        "Blizzard_BlackMarketUI/Blizzard_BlackMarketUI.lua",
        "Blizzard_BlackMarketUI/Blizzard_BlackMarketUI.xml",
    ],
    "bnettoast": [
        "Blizzard_BNet/Mainline/BNet.lua",
        "Blizzard_BNet/BNet.xml",
        "Blizzard_SocialToast/SocialToast.lua",
        "Blizzard_SocialToast/SocialToast.xml",
    ],
    "bossbanner": [
        "Blizzard_FrameXML/BossBannerToast.lua",
        "Blizzard_FrameXML/BossBannerToast.xml",
    ],
    "calendar": [
        "Blizzard_Calendar/Mainline/Blizzard_Calendar.lua",
        "Blizzard_Calendar/Mainline/Blizzard_Calendar.xml",
        "Blizzard_Calendar/Mainline/Blizzard_CalendarTemplates.xml",
    ],
    "castingbar": [
        "Blizzard_UIPanels_Game/Shared/CastingBarFrame.lua",
        "Blizzard_UIPanels_Game/Shared/CastingBarFrameTemplates.lua",
        "Blizzard_UIPanels_Game/Shared/CastingBarFrameTemplates.xml",
        "Blizzard_UIPanels_Game/Mainline/CastingBarFrame.xml",
    ],
    "channels": [
        "Blizzard_Channels/Mainline/ChannelFrame.lua",
        "Blizzard_Channels/Mainline/ChannelFrame.xml",
        "Blizzard_Channels/Mainline/ChannelRoster.lua",
        "Blizzard_Channels/Mainline/ChannelRoster.xml",
        "Blizzard_Channels/Mainline/RosterButton.lua",
        "Blizzard_Channels/Mainline/RosterButton.xml",
        "Blizzard_Channels/Mainline/VoiceChatPrompt.lua",
        "Blizzard_Channels/Mainline/VoiceChatPrompt.xml",
        "Blizzard_VoiceToggleButton/VoiceToggleButton.lua",
        "Blizzard_VoiceToggleButton/VoiceToggleButton.xml",
        "Blizzard_ChatFrame/Mainline/VoiceChatHeadsetButton.lua",
        "Blizzard_ChatFrame/Mainline/VoiceChatHeadsetButton.xml",
        "Blizzard_ChatFrame/Shared/VoiceChatTranscriptionButton.lua",
        "Blizzard_ChatFrame/Shared/VoiceChatTranscriptionButton.xml",
    ],
    "chatconfig": [
        "Blizzard_ChatFrame/Mainline/ChatConfigFrame.lua",
        "Blizzard_ChatFrame/Mainline/ChatConfigFrame.xml",
    ],
    "chattabs": [
        "Blizzard_ChatFrameBase/Mainline/FloatingChatFrame.xml",
        "Blizzard_ChatFrameBase/Mainline/ChannelFrameButtonMixin.lua",
    ],
    "chromietime": [
        "Blizzard_ChromieTimeUI/Blizzard_ChromieTimeUI.lua",
        "Blizzard_ChromieTimeUI/Blizzard_ChromieTimeUI.xml",
    ],
    "cinematic": [
        "Blizzard_FrameXML/MovieFrame.lua",
        "Blizzard_FrameXML/MovieFrame.xml",
        "Blizzard_FrameXML/Shared/CinematicFrame.lua",
        "Blizzard_FrameXML/Shared/CinematicFrame.xml",
    ],
    "clickbinding": [
        "Blizzard_ClickBindingUI/Blizzard_ClickBindingUI.lua",
        "Blizzard_ClickBindingUI/Blizzard_ClickBindingUI.xml",
    ],
    "coinpickup": [
        "Blizzard_FrameXML/Mainline/CoinPickupFrame.lua",
        "Blizzard_FrameXML/Mainline/CoinPickupFrame.xml",
    ],
    "collections": [
        "Blizzard_Collections/Shared/Blizzard_Collections.lua",
        "Blizzard_Collections/Shared/Blizzard_Collections.xml",
        "Blizzard_Collections/Camelot/Blizzard_CollectionsTabs.xml",
        "Blizzard_Collections/Camelot/Blizzard_CollectionsOverrides.lua",
        "Blizzard_Collections/Shared/Blizzard_CollectionTemplates.lua",
        "Blizzard_Collections/Shared/Blizzard_CollectionTemplates.xml",
        "Blizzard_Collections/Mainline/Blizzard_CollectionTemplates.xml",
        "Blizzard_Collections/Mainline/Blizzard_ToyBox.lua",
        "Blizzard_Collections/Mainline/Blizzard_ToyBox.xml",
        "Blizzard_Collections/Camelot/Blizzard_ToyBoxProgressTracker.xml",
        "Blizzard_Collections/Mainline/Blizzard_HeirloomCollection.lua",
        "Blizzard_Collections/Mainline/Blizzard_HeirloomCollection.xml",
    ],
    "colorpicker": [
        "Blizzard_ColorPickerFrame/Shared/ColorPickerFrame.lua",
        "Blizzard_ColorPickerFrame/Mainline/ColorPickerFrame.lua",
        "Blizzard_ColorPickerFrame/Mainline/ColorPickerFrame.xml",
    ],
    "combatfeedback": [
        "Blizzard_FrameXML/Mainline/CombatFeedback.lua",
    ],
    "combatlog": [
        "Blizzard_CombatLog/Mainline/Blizzard_CombatLog.lua",
        "Blizzard_CombatLog/Mainline/Blizzard_CombatLog.xml",
    ],
    "combattext": [
        "Blizzard_CombatText/Shared/CombatText.lua",
        "Blizzard_CombatText/Shared/CombatTextConstants.lua",
        "Blizzard_CombatText/Shared/CombatTextUtil.lua",
    ],
    "cooldownviewer": [
        "Blizzard_CooldownViewer/CooldownViewerSettings.lua",
        "Blizzard_CooldownViewer/CooldownViewerSettings.xml",
        "Blizzard_CooldownViewer/CooldownViewerSettingsAlerts.lua",
        "Blizzard_CooldownViewer/CooldownViewerSettingsAlerts.xml",
        "Blizzard_CooldownViewer/CooldownViewerEditAlertBase.lua",
        "Blizzard_CooldownViewer/CooldownViewerEditAlertBase.xml",
        "Blizzard_CooldownViewer/CooldownViewerAlert.lua",
        "Blizzard_CooldownViewer/GroupBuffFilter.lua",
        "Blizzard_CooldownViewer/GroupBuffFilter.xml",
        "Blizzard_CooldownViewer/CooldownViewerItemData.lua",
        "Blizzard_CooldownViewer/CooldownViewer.xml",
        "Blizzard_VisualAlerts/VisualAlertTemplates.lua",
    ],
    "crafting": [
        "Blizzard_Professions/Blizzard_ProfessionsCrafting.lua",
        "Blizzard_Professions/Camelot/Blizzard_ProfessionsCrafting.lua",
        "Blizzard_Professions/Blizzard_ProfessionsCrafting.xml",
        "Blizzard_Professions/Blizzard_ProfessionsFrame.lua",
        "Blizzard_Professions/Blizzard_ProfessionsFrameBase.xml",
        "Blizzard_Professions/Blizzard_ProfessionsCraftingOutputLog.lua",
        "Blizzard_Professions/Camelot/Blizzard_ProfessionsCraftingOutputLog.lua",
        "Blizzard_Professions/Blizzard_ProfessionsCraftingOutputLog.xml",
        "Blizzard_Professions/Blizzard_ProfessionsGuildMemberList.lua",
        "Blizzard_Professions/Blizzard_ProfessionsGuildMemberList.xml",
        "Blizzard_Professions/Blizzard_ProfessionsRecipeLevel.lua",
        "Blizzard_Professions/Blizzard_ProfessionsRecipeLevel.xml",
        "Blizzard_Professions/Blizzard_ProfessionsInspectRecipe.lua",
        "Blizzard_Professions/Blizzard_ProfessionsInspectRecipe.xml",
        "Blizzard_ProfessionsTemplates/Blizzard_Professions.lua",
        "Blizzard_ProfessionsTemplates/Camelot/Blizzard_Professions.lua",
        "Blizzard_ProfessionsTemplates/Blizzard_ProfessionsRecipeLoader.lua",
        "Blizzard_ProfessionsTemplates/Blizzard_ProfessionsTransaction.lua",
        "Blizzard_ProfessionsTemplates/Blizzard_ProfessionsTemplates.lua",
        "Blizzard_ProfessionsTemplates/Blizzard_ProfessionsTemplates.xml",
        "Blizzard_ProfessionsTemplates/Blizzard_ProfessionsRecipeList.lua",
        "Blizzard_ProfessionsTemplates/Blizzard_ProfessionsRecipeList.xml",
        "Blizzard_ProfessionsTemplates/Blizzard_ProfessionsRecipeCrafterDetails.xml",
        "Blizzard_ProfessionsTemplates/Blizzard_ProfessionsRecipeCrafterDetails.lua",
        "Blizzard_ProfessionsTemplates/Blizzard_ProfessionsRecipeSlotBase.lua",
        "Blizzard_ProfessionsTemplates/Blizzard_ProfessionsRecipeReagentSlotBase.xml",
        "Blizzard_ProfessionsTemplates/Blizzard_ProfessionsRecipeReagentSlotBase.lua",
        "Blizzard_ProfessionsTemplates/Blizzard_ProfessionsRecipeReagentSlot.xml",
        "Blizzard_ProfessionsTemplates/Blizzard_ProfessionsRecipeReagentSlot.lua",
        "Blizzard_ProfessionsTemplates/Blizzard_ProfessionsRecipeSalvageSlot.xml",
        "Blizzard_ProfessionsTemplates/Blizzard_ProfessionsRecipeSalvageSlot.lua",
        "Blizzard_ProfessionsTemplates/Blizzard_ProfessionsRecipeEnchantSlot.xml",
        "Blizzard_ProfessionsTemplates/Blizzard_ProfessionsRecipeEnchantSlot.lua",
        "Blizzard_ProfessionsTemplates/Blizzard_ProfessionsRecipeRecraftSlot.xml",
        "Blizzard_ProfessionsTemplates/Blizzard_ProfessionsRecipeRecraftSlot.lua",
        "Blizzard_ProfessionsTemplates/Blizzard_ProfessionsRecipeFlyout.xml",
        "Blizzard_ProfessionsTemplates/Blizzard_ProfessionsRecipeFlyout.lua",
        "Blizzard_ProfessionsTemplates/Blizzard_ProfessionsRecipeFlyoutInstance.lua",
        "Blizzard_ProfessionsTemplates/Blizzard_ProfessionsQualityDialog.xml",
        "Blizzard_ProfessionsTemplates/Blizzard_ProfessionsQualityDialog.lua",
        "Blizzard_ProfessionsTemplates/Blizzard_ProfessionsRecipeSchematicForm.lua",
        "Blizzard_ProfessionsTemplates/Camelot/Blizzard_ProfessionsRecipeSchematicFormOverride.lua",
        "Blizzard_ProfessionsTemplates/Camelot/Blizzard_ProfessionsRecipeSchematicForm.xml",
        "Blizzard_ProfessionsTemplates/Blizzard_ProfessionsRecipeSchematicForm.xml",
        "Blizzard_ProfessionsTemplates/Blizzard_ProfessionsRankBar.xml",
        "Blizzard_ProfessionsTemplates/Blizzard_ProfessionsRankBar.lua",
    ],
    "currency": [
        "Blizzard_TokenUI/Camelot/Blizzard_TokenUI.lua",
        "Blizzard_TokenUI/Camelot/Blizzard_TokenUI.xml",
    ],
    "widgets": [  # the UI widgets' lines (the WidgetText family; Blizzard_UIWidgets' own strings)
        "Blizzard_UIWidgets/Blizzard_WidgetsUtil.lua",
        "Blizzard_UIWidgets/Blizzard_UIWidgetManager.lua",
        "Blizzard_UIWidgets/Blizzard_UIWidgetManager.xml",
        "Blizzard_UIWidgets/Blizzard_UIWidgetAnimationTemplates.lua",
        "Blizzard_UIWidgets/Blizzard_UIWidgetAnimationTemplates.xml",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateBase.lua",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateBase.xml",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateIconAndText.lua",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateIconAndText.xml",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateIconTextAndBackground.lua",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateIconTextAndBackground.xml",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateCaptureBar.lua",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateCaptureBar.xml",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateStatusBar.lua",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateStatusBar.xml",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateDoubleStatusBar.lua",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateDoubleStatusBar.xml",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateDoubleIconAndText.lua",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateDoubleIconAndText.xml",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateStackedResourceTracker.lua",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateStackedResourceTracker.xml",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateIconTextAndCurrencies.lua",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateIconTextAndCurrencies.xml",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateTextWithState.lua",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateTextWithState.xml",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateHorizontalCurrencies.lua",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateHorizontalCurrencies.xml",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateBulletTextList.lua",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateBulletTextList.xml",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateScenarioHeaderCurrenciesAndBackground.lua",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateScenarioHeaderCurrenciesAndBackground.xml",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateTextureAndText.lua",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateTextureAndText.xml",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateSpellDisplay.xml",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateSpellDisplay.lua",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateDoubleStateIconRow.xml",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateDoubleStateIconRow.lua",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateTextureAndTextRow.xml",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateTextureAndTextRow.lua",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateZoneControl.xml",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateZoneControl.lua",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateCaptureZone.xml",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateCaptureZone.lua",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateTextureWithAnimation.xml",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateTextureWithAnimation.lua",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateDiscreteProgressSteps.xml",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateDiscreteProgressSteps.lua",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateScenarioHeaderTimer.lua",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateScenarioHeaderTimer.xml",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateTextColumnRow.lua",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateTextColumnRow.xml",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateSpacer.lua",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateSpacer.xml",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateUnitPowerBar.lua",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateUnitPowerBar.xml",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateFillUpFrames.lua",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateFillUpFrames.xml",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateTextWithSubtext.lua",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateTextWithSubtext.xml",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateItemDisplay.lua",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateItemDisplay.xml",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateTugOfWar.lua",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateTugOfWar.xml",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateMapPinAnimation.lua",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateMapPinAnimation.xml",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateScenarioHeaderDelves.lua",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateScenarioHeaderDelves.xml",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateButtonHeader.lua",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateButtonHeader.xml",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTemplatePreyHuntProgress.lua",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTemplatePreyHuntProgress.xml",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTopCenterFrame.lua",
        "Blizzard_UIWidgets/Blizzard_UIWidgetTopCenterFrame.xml",
        "Blizzard_UIWidgets/Blizzard_UIWidgetBelowMinimapFrame.lua",
        "Blizzard_UIWidgets/Blizzard_UIWidgetBelowMinimapFrame.xml",
        "Blizzard_UIWidgets/Blizzard_UIWidgetPowerBarFrame.lua",
        "Blizzard_UIWidgets/Blizzard_UIWidgetPowerBarFrame.xml",
        "Blizzard_UIWidgets/Blizzard_UIWidgetCenterScreenFrame.lua",
        "Blizzard_UIWidgets/Blizzard_UIWidgetCenterScreenFrame.xml",
    ],
    "statistics": [  # the Statistics tab (client-table text only)
        "Blizzard_Statistics/Camelot/StatisticsFrame.lua",
        "Blizzard_Statistics/Camelot/StatisticsFrame.xml",
    ],
    "currencytransfer": [
        "Blizzard_TokenUI/Blizzard_CurrencyTransfer.lua",
        "Blizzard_TokenUI/Blizzard_CurrencyTransfer.xml",
    ],
    "customerorders": [
        "Blizzard_ProfessionsCustomerOrders/Blizzard_ProfessionsCustomerOrders_Bootstrap.lua",
        "Blizzard_ProfessionsCustomerOrders/Blizzard_ProfessionsCustomerOrdersForm.xml",
        "Blizzard_ProfessionsCustomerOrders/Blizzard_ProfessionsCustomerOrdersForm.lua",
        "Blizzard_ProfessionsCustomerOrders/Blizzard_ProfessionsCustomerOrdersRecipeCategoryList.xml",
        "Blizzard_ProfessionsCustomerOrders/Blizzard_ProfessionsCustomerOrdersRecipeCategoryList.lua",
        "Blizzard_ProfessionsCustomerOrders/Blizzard_ProfessionsCustomerOrdersRecipeList.xml",
        "Blizzard_ProfessionsCustomerOrders/Blizzard_ProfessionsCustomerOrdersRecipeList.lua",
        "Blizzard_ProfessionsCustomerOrders/Blizzard_ProfessionsCustomerOrdersBrowseOrders.xml",
        "Blizzard_ProfessionsCustomerOrders/Blizzard_ProfessionsCustomerOrdersBrowseOrders.lua",
        "Blizzard_ProfessionsCustomerOrders/Blizzard_ProfessionsCustomerOrdersMyOrders.xml",
        "Blizzard_ProfessionsCustomerOrders/Blizzard_ProfessionsCustomerOrdersMyOrders.lua",
        "Blizzard_ProfessionsCustomerOrders/Blizzard_ProfessionsCustomerOrders.xml",
        "Blizzard_ProfessionsCustomerOrders/Blizzard_ProfessionsCustomerOrders.lua",
        "Blizzard_ProfessionsCustomerOrders/Registration.lua",
    ],
    "damagemeter": [
        "Blizzard_DamageMeter/DamageMeter.lua",
        "Blizzard_DamageMeter/DamageMeterEntry.lua",
        "Blizzard_DamageMeter/DamageMeterSessionWindow.lua",
        "Blizzard_DamageMeter/DamageMeterSessionWindow.xml",
        "Blizzard_DamageMeter/DamageMeterSourceWindow.lua",
        "Blizzard_DamageMeter/DamageMeterSourceWindow.xml",
    ],
    "deathrecap": [
        "Blizzard_DeathRecap/Mainline/Blizzard_DeathRecap.lua",
        "Blizzard_DeathRecap/Mainline/Blizzard_DeathRecap.xml",
    ],
    "dressup": [
        "Blizzard_UIPanels_Game/Mainline/DressUpFrames.lua",
        "Blizzard_UIPanels_Game/Mainline/DressUpFrames.xml",
        "Blizzard_UIPanels_Game/Camelot/DressUpFramesOverrides.lua",
        # the custom-set dropdown the dressing room inherits (WardrobeCustomSetDropdownTemplate)
        "Blizzard_FrameXML/WardrobeCustomSets.lua",
        "Blizzard_FrameXML/WardrobeCustomSets.xml",
    ],
    "editmode": [
        "Blizzard_EditMode/Shared/EditModeLayoutManagerUtil.lua",
        "Blizzard_EditMode/Shared/EditModePresetLayoutSystemUtils.lua",
        "Blizzard_EditMode/Camelot/EditModePresetLayoutConstants.lua",
        "Blizzard_EditMode/Mainline/EditModePresetLayouts.lua",
        "Blizzard_EditMode/Shared/EditModePresetLayoutsManager.lua",
        "Blizzard_EditMode/Shared/EditModeSettingDisplayInfo.lua",
        "Blizzard_EditMode/Camelot/EditModeUtil.lua",
        "Blizzard_EditMode/Shared/EditModeUtil.lua",
        "Blizzard_EditMode/Shared/EditModeTemplates.lua",
        "Blizzard_EditMode/Shared/EditModeTemplates.xml",
        "Blizzard_EditMode/Shared/EditModeSystemTemplates.lua",
        "Blizzard_EditMode/Shared/EditModeSystemTemplates.xml",
        "Blizzard_EditMode/Shared/EditModeDialogs.lua",
        "Blizzard_EditMode/Shared/EditModeDialogs.xml",
        "Blizzard_EditMode/Shared/EditModeManager.lua",
        "Blizzard_EditMode/Shared/EditModeManagerOverrides.lua",
        "Blizzard_EditMode/Mainline/EditModeManagerOverrides.lua",
        "Blizzard_EditMode/Camelot/EditModeManagerOverrides.lua",
        "Blizzard_EditMode/Shared/EditModeManager.xml",
    ],
    "equipmentflyout": [
        "Blizzard_FrameXML/Camelot/EquipmentFlyout.lua",
        "Blizzard_FrameXML/Camelot/EquipmentFlyout.xml",
    ],
    "eventtrace": [
        "Blizzard_EventTrace/Blizzard_EventTrace.lua",
        "Blizzard_EventTrace/Blizzard_EventTrace.xml",
    ],
    "flightmap": [
        "Blizzard_FlightMap/Blizzard_FlightMap.lua",
        "Blizzard_FlightMap/Blizzard_FlightMap.xml",
        "Blizzard_FlightMap/FM_FlightPathDataProvider.lua",
        "Blizzard_FlightMap/FM_ZoneSummaryDataProvider.lua",
        "Blizzard_SharedMapDataProviders/ClickToZoomDataProvider.lua",
    ],
    # the gamepad-mode HUD (UI/Gamepad): the prompt / legend templates, the persistent
    # controller legend, the radial main menu, the skip button and group targeting's prompt; the window
    # footers' labels are set in each window's own gamepad setup (bags, merchant, quest frame, …), which
    # those surfaces already scan
    "gamepad": [
        "Blizzard_GamepadSharedUtility/InputPrompts/InputPrompts.lua",
        "Blizzard_GamepadSharedUtility/InputPrompts/InputPrompts.xml",
        "Blizzard_GamepadSharedUtility/InputPrompts/InputLegendPromptGroup.lua",
        "Blizzard_GamepadSharedUtility/PromptedBindings/PromptedBinding.lua",
        "Blizzard_GamepadSharedUtility/PromptedBindings/PromptedBindingFooter.lua",
        "Blizzard_GamepadSharedUtility/FrameControlsManager.lua",
        "Blizzard_GamepadSharedUtility/FrameReformUtility.lua",
        "Blizzard_Gamepad/UI/PersistentInputLegend/GamepadPersistentInputLegend.lua",
        "Blizzard_Gamepad/UI/PersistentInputLegend/GamepadPersistentInputLegend.xml",
        "Blizzard_Gamepad/UI/Radials/GamepadRadial.lua",
        "Blizzard_Gamepad/UI/Radials/GamepadRadial.xml",
        "Blizzard_Gamepad/UI/ConsoleHUD/ConsoleTemplates.lua",
        "Blizzard_Gamepad/UI/CinematicMovie.lua",
        "Blizzard_GamepadTargeting/GroupTargeting.lua",
    ],
    "gamepadedit": [
        "Blizzard_GamepadActionBars/ActionBarEditFrame.lua",
        "Blizzard_GamepadActionBars/ActionBarEditFrame.xml",
        "Blizzard_GamepadActionBars/ActionBindingUtil.lua",
        "Blizzard_GamepadActionBars/ActionBarTemplates.xml",
        "Blizzard_GamepadActionBars/MainActionBarFrame.lua",
        "Blizzard_GamepadActionBars/TargetActionBars/Shared.lua",
    ],
    "ghostframe": [
        "Blizzard_FrameXML/GhostFrame.lua",
        "Blizzard_FrameXML/GhostFrame.xml",
    ],
    "groupfinder": [
        "Blizzard_GroupFinder_VanillaStyle/Blizzard_LFGVanilla_ParentFrame.lua",
        "Blizzard_GroupFinder_VanillaStyle/Mainline/Blizzard_LFGVanilla_ParentFrame.xml",
        "Blizzard_GroupFinder_VanillaStyle/Blizzard_LFGVanilla_Listing.lua",
        "Blizzard_GroupFinder_VanillaStyle/Mainline/Blizzard_LFGVanilla_Listing.xml",
        "Blizzard_GroupFinder_VanillaStyle/Blizzard_LFGVanilla_Browse.lua",
        "Blizzard_GroupFinder_VanillaStyle/Mainline/Blizzard_LFGVanilla_Browse.xml",
        "Blizzard_GroupFinder_VanillaStyle/Blizzard_LFGVanilla_VoiceChat.lua",
    ],
    "grouploot": [
        "Blizzard_UIPanels_Game/Mainline/GroupLootFrame.lua",
        "Blizzard_UIPanels_Game/Mainline/GroupLootFrame.xml",
    ],
    "guildbank": [
        "Blizzard_GuildBankUI/Mainline/Blizzard_GuildBankUI.lua",
        "Blizzard_GuildBankUI/Mainline/Blizzard_GuildBankUI.xml",
    ],
    "guildcontrol": [
        "Blizzard_GuildControlUI/Blizzard_GuildControlUI.lua",
        "Blizzard_GuildControlUI/Blizzard_GuildControlUI.xml",
    ],
    "guildinvite": [
        "Blizzard_FrameXML/GuildInviteFrame.lua",
        "Blizzard_FrameXML/GuildInviteFrame.xml",
    ],
    "guildregistrar": [
        "Blizzard_UIPanels_Game/Mainline/GuildRegistrarFrame.lua",
        "Blizzard_UIPanels_Game/Mainline/GuildRegistrarFrame.xml",
    ],
    "guildrename": [
        "Blizzard_GuildRename/Blizzard_GuildRename.lua",
        "Blizzard_GuildRename/Blizzard_GuildRename.xml",
    ],
    "help": [
        "Blizzard_ActionBar/Shared/VehicleLeaveButton.lua",
        "Blizzard_ActionBar/Shared/MultiCastActionBarFrame.lua",
        "Blizzard_OverrideActionBar/OverrideActionBar.xml",
        "Blizzard_DurabilityFrame/DurabilityFrame.lua",
        "Blizzard_Minimap/Mainline/Minimap.lua",
        "Blizzard_Minimap/Mainline/GameTime.lua",
        "Blizzard_Minimap/Mainline/AddonCompartment.lua",
    ],
    "helpframe": [
        "Blizzard_HelpFrame/HelpFrame.lua",
        "Blizzard_HelpFrame/HelpFrame.xml",
    ],
    "hudlabels": [
        "Blizzard_FramerateFrame/Mainline/FramerateFrame.lua",  # the FPS counter's bound form
        "Blizzard_MirrorTimer/Mainline/MirrorTimer.lua",
        "Blizzard_SwingTimer/Blizzard_SwingTimer.lua",
        "Blizzard_SwingTimer/Blizzard_SwingTimer.xml",
        "Blizzard_StatusTrackingBar/Mainline/HonorBar.lua",
        "Blizzard_ActionStatus/Mainline/ActionStatus.lua",
    ],
    "inspect": [
        "Blizzard_InspectUI/Camelot/Blizzard_InspectUI.lua",
        "Blizzard_InspectUI/Camelot/Blizzard_InspectUI.xml",
        "Blizzard_InspectUI/Mainline/InspectPaperDollFrame.lua",
        "Blizzard_InspectUI/Camelot/InspectPaperDollFrame.xml",
        "Blizzard_InspectUI/Camelot/InspectPVPFrame.lua",
        "Blizzard_InspectUI/Camelot/InspectPVPFrame.xml",
        "Blizzard_InspectUI/Camelot/InspectGuildFrame.lua",
        "Blizzard_InspectUI/Camelot/InspectGuildFrame.xml",
    ],
    "instanceabandon": [
        "Blizzard_FrameXML/Mainline/InstanceAbandon.lua",
        "Blizzard_FrameXML/Mainline/InstanceAbandon.xml",
    ],
    "instancedifficulty": [
        "Blizzard_FrameXML/InstanceDifficulty.lua",
        "Blizzard_FrameXML/InstanceDifficulty.xml",
        "Blizzard_FrameXML/Camelot/InstanceDifficultyOverrides.lua",
    ],
    "iteminteraction": [
        "Blizzard_ItemInteractionUI/Blizzard_ItemInteractionUI.lua",
        "Blizzard_ItemInteractionUI/Blizzard_ItemInteractionUI.xml",
    ],
    "itemsocketing": [
        "Blizzard_ItemSocketingUI/Blizzard_ItemSocketingUI.lua",
        "Blizzard_ItemSocketingUI/Blizzard_ItemSocketingUI.xml",
    ],
    "itemupgrade": [
        "Blizzard_ItemUpgradeUI/Mainline/Blizzard_ItemUpgradeUI.lua",
        "Blizzard_ItemUpgradeUI/Mainline/Blizzard_ItemUpgradeUI.xml",
    ],
    "legacy": [
        "Blizzard_LegacySystem/Blizzard_LegacySystemConstants.lua",
        "Blizzard_LegacySystem/Blizzard_LegacySystemUtil.lua",
        "Blizzard_LegacySystem/Blizzard_LegacyChallengeButton.lua",
        "Blizzard_LegacySystem/Blizzard_LegacySystemTemplates.xml",
        "Blizzard_LegacySystem/Blizzard_LegacyRewardTrack.xml",
        "Blizzard_LegacySystem/Blizzard_LegacyRewardTrack.lua",
        "Blizzard_LegacySystem/Blizzard_LegacyTree.xml",
        "Blizzard_LegacySystem/Blizzard_LegacyTree.lua",
        "Blizzard_LegacySystem/Blizzard_LegacyChallengeDetailPane.xml",
        "Blizzard_LegacySystem/Blizzard_LegacyChallengeDetailPane.lua",
        "Blizzard_LegacySystem/Blizzard_LegacyChallengeCategoryList.xml",
        "Blizzard_LegacySystem/Blizzard_LegacyChallengeCategoryList.lua",
        "Blizzard_LegacySystem/Blizzard_LegacyChallenges.xml",
        "Blizzard_LegacySystem/Blizzard_LegacyChallenges.lua",
        "Blizzard_LegacySystem/Blizzard_LegacySystem.lua",
        "Blizzard_LegacySystem/Blizzard_LegacySystem.xml",
        "Blizzard_LegacySystem/Blizzard_LegacyAchievementOverrides.lua",
    ],
    "loot": [
        "Blizzard_UIPanels_Game/Mainline/LootFrame.lua",
        "Blizzard_UIPanels_Game/Mainline/LootFrame.xml",
        "Blizzard_UIPanels_Game/Mainline/ScrollingFlatPanel.lua",
        "Blizzard_UIPanels_Game/Mainline/ScrollingFlatPanel.xml",
    ],
    "loothistory": [
        "Blizzard_FrameXML/Mainline/LootHistory.lua",
        "Blizzard_FrameXML/Mainline/LootHistory.xml",
        "Blizzard_FrameXML/Camelot/LootHistory.lua",
    ],
    "lossofcontrol": [
        "Blizzard_FrameXML/LossOfControlFrame.lua",
        "Blizzard_FrameXML/LossOfControlFrame.xml",
    ],
    "macro": [
        "Blizzard_MacroUI/Blizzard_MacroUI.lua",
        "Blizzard_MacroUI/Blizzard_MacroUI.xml",
        "Blizzard_MacroUI/Blizzard_MacroIconSelector.lua",
        "Blizzard_MacroUI/Blizzard_MacroIconSelector.xml",
        "Blizzard_MacroUI/Mainline/Blizzard_MacroScrollFrame.xml",
    ],
    "majorfactiontoast": [
        "Blizzard_MajorFactions/Blizzard_MajorFactionRenownToast.lua",
        "Blizzard_MajorFactions/Blizzard_MajorFactionRenownToast.xml",
        "Blizzard_MajorFactions/Blizzard_MajorFactionUnlockToast.lua",
        "Blizzard_MajorFactions/Blizzard_MajorFactionUnlockToast.xml",
    ],
    "maplegend": [
        "Blizzard_UIPanels_Game/Mainline/MapLegendFrame.lua",
        "Blizzard_UIPanels_Game/Mainline/MapLegendFrame.xml",
        "Blizzard_UIPanels_Game/Mainline/MapLegendFrameData.lua",
        "Blizzard_UIPanels_Game/Camelot/MapLegendFrameData.lua",
    ],
    "mappins": [
        "Blizzard_SharedMapDataProviders/SharedMapPoiTemplates.lua",
        "Blizzard_SharedMapDataProviders/FlightPointDataProvider.lua",
        "Blizzard_SharedMapDataProviders/DeathMapDataProvider.lua",
        "Blizzard_SharedMapDataProviders/SelectableGraveyardDataProvider.lua",
        "Blizzard_SharedMapDataProviders/WaypointLocationDataProvider.lua",
        "Blizzard_SharedMapDataProviders/DungeonEntranceDataProvider.lua",
        "Blizzard_SharedMapDataProviders/MapLinkDataProvider.lua",
        "Blizzard_SharedMapDataProviders/QuestOfferDataProvider.lua",
        "Blizzard_SharedMapDataProviders/VignetteDataProvider.lua",
        "Blizzard_SharedMapDataProviders/ContentTrackingDataProvider.lua",
        "Blizzard_SharedMapDataProviders/GroupMembersDataProvider.lua",
        "Blizzard_SharedMapDataProviders/WorldQuestDataProvider.lua",
        "Blizzard_SharedMapDataProviders/AreaLabelDataProvider.lua",
        "Blizzard_SharedMapDataProviders/InvasionDataProvider.lua",
        "Blizzard_SharedMapDataProviders/NeighborhoodMapDataProvider.lua",
        "Blizzard_SharedMapDataProviders/QuestDataProvider.lua",
        "Blizzard_SharedMapDataProviders/QuestBlobDataProvider.lua",
        "Blizzard_SharedMapDataProviders/SuperTrackWaypointDataProvider.lua",
    ],
    "mountjournal": [
        "Blizzard_Collections/Mainline/Blizzard_MountCollection.lua",
        "Blizzard_Collections/Mainline/Blizzard_MountCollection.xml",
    ],
    "obliterumforge": [
        "Blizzard_ObliterumUI/Blizzard_ObliterumUI.lua",
        "Blizzard_ObliterumUI/Blizzard_ObliterumUI.xml",
    ],
    "partypose": [
        "Blizzard_PartyPoseUI/Blizzard_PartyPoseUI.lua",
        "Blizzard_PartyPoseUI/Blizzard_PartyPoseUI.xml",
        "Blizzard_MatchCelebrationPartyPoseUI/Blizzard_MatchCelebrationPartyPoseUI.lua",
        "Blizzard_MatchCelebrationPartyPoseUI/Blizzard_MatchCelebrationPartyPoseUI.xml",
        "Blizzard_IslandsPartyPoseUI/Blizzard_IslandsPartyPoseUI.lua",
        "Blizzard_IslandsPartyPoseUI/Blizzard_IslandsPartyPoseUI.xml",
        "Blizzard_WarfrontsPartyPoseUI/Blizzard_WarfrontsPartyPoseUI.lua",
        "Blizzard_WarfrontsPartyPoseUI/Blizzard_WarfrontsPartyPoseUI.xml",
    ],
    "pethappiness": [
        "Blizzard_FrameXML/PetHappiness.lua",
        "Blizzard_FrameXML/PetHappiness.xml",
    ],
    "petition": [
        "Blizzard_UIPanels_Game/Mainline/PetitionFrame.lua",
        "Blizzard_UIPanels_Game/Mainline/PetitionFrame.xml",
    ],
    "petjournal": [
        "Blizzard_Collections/Shared/Blizzard_PetCollection.lua",
        "Blizzard_Collections/Classic/Blizzard_PetCollection.lua",
        "Blizzard_Collections/Classic/Blizzard_PetCollection.xml",
        "Blizzard_Collections/Camelot/Blizzard_PetCollectionScrollBar.xml",
    ],
    "playerchoice": [
        "Blizzard_PlayerChoice/Blizzard_PlayerChoice.lua",
        "Blizzard_PlayerChoice/Blizzard_PlayerChoice.xml",
        "Blizzard_PlayerChoice/Blizzard_PlayerChoiceToggleButton.lua",
        "Blizzard_PlayerChoice/Blizzard_PlayerChoiceToggleButton.xml",
        "Blizzard_PlayerChoice/Blizzard_PlayerChoiceOptionBase.lua",
        "Blizzard_PlayerChoice/Blizzard_PlayerChoiceOptionBase.xml",
        "Blizzard_PlayerChoice/Blizzard_PlayerChoiceNormalOptionTemplate.lua",
        "Blizzard_PlayerChoice/Blizzard_PlayerChoiceNormalOptionTemplate.xml",
        "Blizzard_PlayerChoice/Blizzard_PlayerChoicePowerChoiceTemplate.lua",
        "Blizzard_PlayerChoice/Blizzard_PlayerChoicePowerChoiceTemplate.xml",
        "Blizzard_PlayerChoice/Blizzard_PlayerChoiceTorghastOptionTemplate.lua",
        "Blizzard_PlayerChoice/Blizzard_PlayerChoiceTorghastOptionTemplate.xml",
        "Blizzard_PlayerChoice/Blizzard_PlayerChoiceCovenantChoiceOptionTemplate.lua",
        "Blizzard_PlayerChoice/Blizzard_PlayerChoiceCovenantChoiceOptionTemplate.xml",
        "Blizzard_PlayerChoice/Blizzard_PlayerChoiceCypherOptionTemplate.lua",
        "Blizzard_PlayerChoice/Blizzard_PlayerChoiceCypherOptionTemplate.xml",
        "Blizzard_PlayerChoice/Blizzard_PlayerChoiceGenericPowerChoiceOptionTemplate.lua",
        "Blizzard_PlayerChoice/Blizzard_PlayerChoiceGenericPowerChoiceOptionTemplate.xml",
        "Blizzard_PlayerChoice/Blizzard_PlayerChoiceTimer.lua",
        "Blizzard_PlayerChoice/Blizzard_PlayerChoiceTimer.xml",
    ],
    "professions": [
        "Blizzard_ProfessionsBook/Blizzard_ProfessionsBook_Bootstrap.lua",
        "Blizzard_ProfessionsBook/Blizzard_ProfessionsBook.lua",
        "Blizzard_ProfessionsBook/Camelot/Blizzard_ProfessionsBook.lua",
        "Blizzard_ProfessionsBook/Blizzard_ProfessionsBookTemplates.xml",
        "Blizzard_ProfessionsBook/Camelot/Blizzard_ProfessionsBookTemplates.xml",
        "Blizzard_Professions/Blizzard_Professions_Bootstrap.lua",
        "Blizzard_Professions/Camelot/Blizzard_ProfessionsFrame.lua",
        "Blizzard_Professions/Camelot/Blizzard_ProfessionsFrame.xml",
    ],
    "pvpmatch": [
        "Blizzard_PVPMatch/PVPMatchResults.lua",
        "Blizzard_PVPMatch/PVPMatchResults.xml",
        "Blizzard_PVPMatch/PVPMatchScoreboard.lua",
        "Blizzard_PVPMatch/PVPMatchScoreboard.xml",
        "Blizzard_PVPMatch/PVPMatchTable.lua",
        "Blizzard_PVPMatch/PVPMatchUtil.lua",
    ],
    "questtimer": [
        "Blizzard_QuestTimer/Mainline/Blizzard_QuestTimerOverrides.lua",
        "Blizzard_QuestTimer/QuestTimerButtonTemplate.xml",
        "Blizzard_QuestTimer/Blizzard_QuestTimer.lua",
        "Blizzard_QuestTimer/Mainline/Blizzard_QuestTimer.xml",
    ],
    "queuestatus": [
        "Blizzard_QueueStatusFrame/Mainline/QueueStatusFrame.lua",
        "Blizzard_QueueStatusFrame/Mainline/QueueStatusFrame.xml",
    ],
    "quickjoin": [
        "Blizzard_QuickJoin/QuickJoin.lua",
        "Blizzard_QuickJoin/QuickJoin.xml",
        "Blizzard_QuickJoin/QuickJoinToast.lua",
        "Blizzard_QuickJoin/QuickJoinToast.xml",
        "Blizzard_UIPanels_Game/Shared/SocialQueue.lua",
        "Blizzard_UIPanels_Game/Mainline/RoleSelectionTemplate.lua",
        "Blizzard_UIPanels_Game/Mainline/RoleSelectionTemplate.xml",
    ],
    "quickkeybind": [
        "Blizzard_QuickKeybind/QuickKeybind.xml",
        "Blizzard_QuickKeybind/QuickKeybind.lua",
    ],
    "raidmanager": [
        "Blizzard_CompactRaidFrames/Mainline/Blizzard_CompactRaidFrameManager.lua",
        "Blizzard_CompactRaidFrames/Mainline/Blizzard_CompactRaidFrameManager.xml",
        "Blizzard_CompactRaidFrames/Blizzard_CompactRaidFrameContainer.lua",
        "Blizzard_CompactRaidFrames/Blizzard_CompactRaidFrameContainer.xml",
    ],
    "readycheck": [
        "Blizzard_FrameXML/Mainline/ReadyCheck.lua",
        "Blizzard_FrameXML/Mainline/ReadyCheck.xml",
    ],
    "recentallies": [
        "Blizzard_RecentAllies/Blizzard_RecentAlliesTemplates.lua",
        "Blizzard_RecentAllies/Blizzard_RecentAlliesTemplates.xml",
    ],
    "recruitafriend": [
        "Blizzard_RecruitAFriend/RecruitAFriendFrame.lua",
        "Blizzard_RecruitAFriend/RecruitAFriendFrame.xml",
    ],
    "reportframe": [
        "Blizzard_ReportFrame/ReportFrame.lua",
        "Blizzard_ReportFrame/ReportFrame.xml",
        "Blizzard_ReportFrameShared/ReportFrameShared.lua",
        "Blizzard_ReportFrameShared/ReportFrameShared.xml",
    ],
    "scrappingmachine": [
        "Blizzard_ScrappingMachineUI/Blizzard_ScrappingMachineUI.lua",
        "Blizzard_ScrappingMachineUI/Blizzard_ScrappingMachineUI.xml",
    ],
    "scripterrors": [
        "Blizzard_ScriptErrorsFrame/Blizzard_ScriptErrorsFrame.lua",
        "Blizzard_ScriptErrorsFrame/Blizzard_ScriptErrorsFrame.xml",
    ],
    "settingspanel": [
        "Blizzard_Settings_Shared/NewDefinitionsFramework.lua",
        "Blizzard_Settings_Shared/NewDefinitionsFramework.xml",
        "Blizzard_Settings_Shared/Mainline/NewDefinitions.lua",
        "Blizzard_Settings_Shared/Blizzard_SettingsRegistrar.lua",
        "Blizzard_Settings_Shared/Blizzard_Settings.lua",
        "Blizzard_Settings_Shared/Blizzard_Category.lua",
        "Blizzard_Settings_Shared/Blizzard_CategoryList.lua",
        "Blizzard_Settings_Shared/Blizzard_CategoryList.xml",
        "Blizzard_Settings_Shared/Blizzard_SettingsList.lua",
        "Blizzard_Settings_Shared/Blizzard_SettingsList.xml",
        "Blizzard_Settings_Shared/Blizzard_Setting.lua",
        "Blizzard_Settings_Shared/Blizzard_SettingControls.lua",
        "Blizzard_Settings_Shared/Blizzard_SettingControls.xml",
        "Blizzard_Settings_Shared/Mainline/Blizzard_SettingsPanelTemplates.xml",
        "Blizzard_Settings_Shared/Blizzard_SettingsPanel.lua",
        "Blizzard_Settings_Shared/Blizzard_SettingsPanel.xml",
        "Blizzard_Settings_Shared/Blizzard_Keybindings.lua",
        "Blizzard_Settings_Shared/Blizzard_Keybindings.xml",
        "Blizzard_Settings_Shared/Blizzard_Dialogs.lua",
        "Blizzard_Settings_Shared/Blizzard_SettingsLayouts.lua",
        "Blizzard_Settings_Shared/Blizzard_Registration.lua",
        "Blizzard_Settings_Shared/Blizzard_SettingsInbound.lua",
        "Blizzard_Settings_Shared/Blizzard_Deprecated.lua",
        "Blizzard_Settings_Shared/Mainline/GraphicsOverrides.lua",
        "Blizzard_Settings_Shared/Mainline/AudioOverrides.lua",
        "Blizzard_Settings_Shared/Blizzard_Settings_PreferredPlaySettings.lua",
        "Blizzard_Settings_Shared/Camelot/LanguagesOverrides.lua",
        "Blizzard_SettingsDefinitions_Frame/Mainline/GameplaySettingsGroup.lua",
        "Blizzard_SettingsDefinitions_Frame/Mainline/InterfaceOverrides.lua",
        "Blizzard_SettingsDefinitions_Frame/Mainline/CombatOverrides.lua",
        "Blizzard_SettingsDefinitions_Frame/Mainline/SocialOverrides.lua",
        "Blizzard_SettingsDefinitions_Frame/Mainline/ColorblindOverrides.lua",
        "Blizzard_SettingsDefinitions_Frame/Mainline/KeybindingsOverrides.lua",
        "Blizzard_SettingsDefinitions_Frame/Mainline/AccessibilityOverrides.lua",
        "Blizzard_SettingsDefinitions_Frame/Mainline/NameplatesOverrides.lua",
        "Blizzard_SettingsDefinitions_Frame/Camelot/NameplatesOverrides.lua",
        "Blizzard_SettingsDefinitions_Frame/Camelot/ControlsOverrides.lua",
        "Blizzard_SettingsDefinitions_Frame/Camelot/SocialOverrides.lua",
        "Blizzard_SettingsDefinitions_Frame/Camelot/KeybindingsOverrides.lua",
        "Blizzard_SettingsDefinitions_Frame/Camelot/AccessibilityOverrides.lua",
        "Blizzard_SettingsDefinitions_Frame/Camelot/InterfaceOverrides.lua",
        "Blizzard_SettingsDefinitions_Frame/Controls.xml",
        "Blizzard_SettingsDefinitions_Frame/Controls.lua",
        "Blizzard_SettingsDefinitions_Frame/Interface.lua",
        "Blizzard_SettingsDefinitions_Frame/Interface.xml",
        "Blizzard_SettingsDefinitions_Frame/Combat.lua",
        "Blizzard_SettingsDefinitions_Frame/ActionBars.lua",
        "Blizzard_SettingsDefinitions_Frame/Social.lua",
        "Blizzard_SettingsDefinitions_Frame/PingSystem.xml",
        "Blizzard_SettingsDefinitions_Frame/PingSystem.lua",
        "Blizzard_SettingsDefinitions_Frame/Keybindings.xml",
        "Blizzard_SettingsDefinitions_Frame/Keybindings.lua",
        "Blizzard_SettingsDefinitions_Frame/Accessibility.lua",
        "Blizzard_SettingsDefinitions_Frame/Accessibility.xml",
        "Blizzard_SettingsDefinitions_Frame/Mainline/Colorblind.xml",
        "Blizzard_SettingsDefinitions_Frame/CombatAudioAlertConstants.lua",
        "Blizzard_SettingsDefinitions_Frame/CombatAudioAlertUtil.lua",
        "Blizzard_SettingsDefinitions_Frame/AdvancedOptions.lua",
        "Blizzard_SettingsDefinitions_Frame/Nameplates.lua",
        "Blizzard_SettingsDefinitions_Frame/Nameplates.xml",
        "Blizzard_SettingsDefinitions_Shared/Groups.lua",
        "Blizzard_SettingsDefinitions_Shared/Graphics.xml",
        "Blizzard_SettingsDefinitions_Shared/Graphics.lua",
        "Blizzard_SettingsDefinitions_Shared/Audio.xml",
        "Blizzard_SettingsDefinitions_Shared/Audio.lua",
        "Blizzard_SettingsDefinitions_Shared/Languages.xml",
        "Blizzard_SettingsDefinitions_Shared/Languages.lua",
        "Blizzard_SettingsDefinitions_Shared/Network.lua",
        "Blizzard_SettingsDefinitions_Shared/Gamepad.lua",
        "Blizzard_SettingsDefinitions_Shared/Mac.lua",
        "Blizzard_SettingsDefinitions_Shared/AccessibilitySettingsPreview.lua",
        "Blizzard_SettingsDefinitions_Shared/Mainline/QuestTextPreview.lua",
        "Blizzard_SettingsDefinitions_Shared/Mainline/QuestTextPreview.xml",
        "Blizzard_SettingsDefinitions_Shared/Mainline/TextSizePreview.lua",
        "Blizzard_SettingsDefinitions_Shared/Mainline/TextSizePreview.xml",
        "Blizzard_SettingsDefinitions_Shared/Mainline/Text.lua",
        "Blizzard_SettingsDefinitions_Shared/AudioAssist.lua",
        "Blizzard_SettingsDefinitions_Shared/AudioAssist.xml",
        "Blizzard_SettingsDefinitions_Shared/Subtitles.lua",
        "Blizzard_SettingsDefinitions_Shared/Subtitles.xml",
        "Blizzard_AccessibilityTemplates/Mainline/AccessibilityTemplates.lua",
        "Blizzard_AccessibilityTemplates/AccessibilityIntrinsics.xml",
        "Blizzard_AccessibilityTemplates/QuestTextContrast.lua",
        "Blizzard_AccessibilityTemplates/TextSizeManager.lua",
        "Blizzard_AccessibilityTemplates/TextSizeManagerGame.lua",
        "Blizzard_AccessibilityTemplates/UserScaledElementTemplates.lua",
        "Blizzard_AccessibilityTemplates/UserScaledElementTemplates.xml",
        "Blizzard_AccessibilityTemplates/UserScaledSliderTemplates.xml",
        "Blizzard_Settings/Blizzard_Settings.lua",
    ],
    "settingstutorials": [
        "Blizzard_SettingsDefinitions_Frame/PingSystem.xml",
        "Blizzard_SettingsDefinitions_Frame/PingSystem.lua",
        "Blizzard_SettingsDefinitions_Frame/Nameplates.lua",
        "Blizzard_SettingsDefinitions_Frame/Nameplates.xml",
    ],
    "spellsearch": [
        "Blizzard_SpellSearch/Blizzard_SpellSearchTemplates.lua",
        "Blizzard_SpellSearch/Blizzard_SpellSearchTemplates.xml",
        "Blizzard_SharedTalentUI/Blizzard_ClassTalentSearch.lua",
        "Blizzard_SharedTalentUI/Blizzard_SharedTalentUtil.lua",
    ],
    "splash": [
        "Blizzard_SplashFrame/Mainline/SplashFrame.lua",
        "Blizzard_SplashFrame/Mainline/SplashFrame.xml",
    ],
    "stable": [
        "Blizzard_StableUI/Shared/Blizzard_StableUI_Shared.lua",
        "Blizzard_StableUI/Camelot/Blizzard_StableUI.lua",
        "Blizzard_StableUI/Camelot/Blizzard_StableUI.xml",
    ],
    "stacksplit": [
        "Blizzard_FrameXML/Mainline/StackSplitFrame.lua",
        "Blizzard_FrameXML/Camelot/StackSplitFrame.xml",
    ],
    "statusnotices": [
        "Blizzard_GMChatUI/Blizzard_GMChatUI.lua",
        "Blizzard_GMChatUI/Blizzard_GMChatUI.xml",
        "Blizzard_WowSurveyUI/Blizzard_WowSurveyUI.lua",
        "Blizzard_WowSurveyUI/Blizzard_WowSurveyUI.xml",
        "Blizzard_BehavioralMessaging/Blizzard_BehavioralMessaging.lua",
        "Blizzard_BehavioralMessaging/Blizzard_BehavioralMessaging.xml",
    ],
    "streamingicon": [
        "Blizzard_FrameXML/Mainline/StreamingFrame.lua",
        "Blizzard_FrameXML/Mainline/StreamingFrame.xml",
    ],
    "subscriptioninterstitial": [
        "Blizzard_SubscriptionInterstitialUI/Blizzard_SubscriptionInterstitialUI.lua",
        "Blizzard_SubscriptionInterstitialUI/Blizzard_SubscriptionInterstitialUI.xml",
    ],
    "tabard": [
        "Blizzard_UIPanels_Game/Mainline/TabardFrame.lua",
        "Blizzard_UIPanels_Game/Mainline/TabardFrame.xml",
        "Blizzard_UIPanels_Game/Mainline/TabardModelControlButtonMixin.lua",
    ],
    "taxi": [
        "Blizzard_UIPanels_Game/Shared/TaxiFrame.lua",
        "Blizzard_UIPanels_Game/Shared/TaxiFrame.xml",
    ],
    "texttospeech": [
        "Blizzard_ChatFrame/Shared/TextToSpeechFrame.lua",
        "Blizzard_ChatFrame/Shared/TextToSpeechFrame.xml",
    ],
    "timemanager": [
        "Blizzard_TimeManager/Mainline/Blizzard_TimeManager.lua",
        "Blizzard_TimeManager/Mainline/Blizzard_TimeManager.xml",
        "Blizzard_FrameXMLUtil/GameTimeUtil.lua",
    ],
    "tracker": [
        "Blizzard_ObjectiveTracker/Blizzard_ObjectiveTrackerShared.lua",
        "Blizzard_ObjectiveTracker/Blizzard_ObjectiveTrackerShared.xml",
        "Blizzard_ObjectiveTracker/Blizzard_ObjectiveTrackerBlock.lua",
        "Blizzard_ObjectiveTracker/Blizzard_ObjectiveTrackerModule.lua",
        "Blizzard_ObjectiveTracker/Blizzard_ObjectiveTrackerContainer.lua",
        "Blizzard_ObjectiveTracker/Blizzard_AchievementObjectiveTracker.lua",
        "Blizzard_ObjectiveTracker/Blizzard_MonthlyActivitiesObjectiveTracker.lua",
        "Blizzard_ObjectiveTracker/Blizzard_ProfessionsRecipeTracker.lua",
        "Blizzard_ObjectiveTracker/Blizzard_ScenarioObjectiveTracker.lua",
        "Blizzard_ObjectiveTracker/Blizzard_ScenarioObjectiveTracker.xml",
        "Blizzard_ObjectiveTracker/Blizzard_AutoQuestPopUpTracker.lua",
        "Blizzard_ObjectiveTracker/Blizzard_AutoQuestPopUpTracker.xml",
        "Blizzard_ObjectiveTracker/Blizzard_CampaignQuestObjectiveTracker.lua",
        "Blizzard_ObjectiveTracker/Blizzard_BonusObjectiveTracker.lua",
        "Blizzard_ObjectiveTracker/Blizzard_BonusObjectiveTracker.xml",
        "Blizzard_ObjectiveTracker/Blizzard_AdventureObjectiveTracker.lua",
        "Blizzard_ObjectiveTracker/Blizzard_ObjectiveTrackerUIWidgetContainer.lua",
        "Blizzard_ObjectiveTracker/Blizzard_WorldQuestObjectiveTracker.lua",
        "Blizzard_ObjectiveTracker/Blizzard_InitiativeTasksObjectiveTracker.lua",
    ],
    "trade": [
        "Blizzard_UIPanels_Game/Mainline/TradeFrame.lua",
        "Blizzard_UIPanels_Game/Mainline/TradeFrame.xml",
    ],
    "transmog": [
        "Blizzard_Transmog/Blizzard_Transmog.lua",
        "Blizzard_Transmog/Blizzard_Transmog.xml",
        "Blizzard_Transmog/Blizzard_TransmogTemplates.lua",
        "Blizzard_Transmog/Blizzard_TransmogTemplates.xml",
    ],
    "unitframes": [
        "Blizzard_UnitFrame/Mainline/TargetFrame.xml",
        "Blizzard_UnitFrame/Mainline/TargetFrame.lua",
        "Blizzard_UnitFrame/Mainline/UnitFrame.lua",
        "Blizzard_UnitFrame/Mainline/PartyMemberFrame.lua",
        "Blizzard_UnitFrame/Mainline/PartyFrameTemplates.xml",
        "Blizzard_UnitFrame/Shared/CompactUnitFrame.lua",
        "Blizzard_UnitFrame/Shared/CompactRaidGroup.lua",
        "Blizzard_UnitFrame/Shared/CompactPartyFrame.lua",
        "Blizzard_UnitFrame/Shared/CompactPartyFrame.xml",
    ],
    "wardrobe": [
        "Blizzard_Collections/Shared/Blizzard_Wardrobe_Sets.lua",
        "Blizzard_Collections/Shared/Blizzard_Wardrobe_Sets.xml",
        "Blizzard_Collections/Mainline/Blizzard_Wardrobe.lua",
        "Blizzard_Collections/Camelot/Blizzard_Wardrobe.lua",
        "Blizzard_Collections/Mainline/Blizzard_Wardrobe.xml",
    ],
    "worldmap": [
        "Blizzard_WorldMap/Blizzard_WorldMap.lua",
        "Blizzard_WorldMap/Camelot/Blizzard_WorldMap.lua",
        "Blizzard_WorldMap/Blizzard_WorldMap.xml",
        "Blizzard_WorldMap/Blizzard_WorldMapTemplates.lua",
        "Blizzard_WorldMap/Camelot/Blizzard_WorldMapTemplates.lua",
        "Blizzard_WorldMap/Blizzard_WorldMapTemplates.xml",
        "Blizzard_WorldMap/Camelot/Blizzard_WorldMapTemplates.xml",
        "Blizzard_WorldMap/QuestLogOwnerMixin.lua",
        "Blizzard_WorldMap/WM_WorldQuestDataProvider.lua",
        "Blizzard_WorldMap/WM_EventOverlayDataProvider.lua",
    ],
    "zonetext": [
        "Blizzard_FrameXML/Mainline/ZoneText.lua",
        "Blizzard_FrameXML/Mainline/ZoneText.xml",
    ],
}
for _surface, _files in _OTHER_WINDOWS.items():
    FOREVER_WINDOWS.setdefault(_surface, []).extend(_files)

# The files a fresh level-1 character reaches whose text no surface listed: the chat tab,
# shortcut and channel menus and the edit box header (UI/Menus, UI/ChatTabs), the unit right-click menus
# (UI/Menus), the help-plate tooltip and the level-1 HelpTips (UI/HelpTips), the spellbook's help plate, and
# the event toasts (UI/Alerts). Evidence: the level-1 English gaps research note in docs/research/.
_LEVEL1_WINDOWS: dict[str, list[str]] = {
    "chattabs": [
        "Blizzard_ChatFrameBase/Mainline/FloatingChatFrame.lua",
        "Blizzard_ChatFrameBase/Mainline/ChatFrameMenuButton.lua",
        "Blizzard_ChatFrameBase/Shared/ChatFrameUtil.lua",
        "Blizzard_ChatFrameBase/Shared/ChatFrameEditBox.lua",
        "Blizzard_ChatFrameBase/Mainline/ChatFrameEditBoxOverrides.lua",
        "Blizzard_ChatFrameBase/Mainline/ChatFrameEditBox.xml",
    ],
    "help": [
        "Blizzard_UnitPopup/UnitPopupCustomControls.lua",
        "Blizzard_UnitPopup/Mainline/UnitPopupUtils.lua",
        "Blizzard_UnitPopup/Mainline/UnitPopupButtons.lua",
        "Blizzard_UnitPopup/Shared/UnitPopupButtonsHardcore.lua",
        "Blizzard_UnitPopupShared/UnitPopupSharedButtonMixins.lua",
        "Blizzard_UnitPopupShared/Mainline/UnitPopupSharedButtonMixins.lua",
        "Blizzard_UnitPopupShared/UnitPopupShared.lua",
        "Blizzard_HelpPlate/Blizzard_HelpPlate.lua",
        "Blizzard_HelpPlate/Blizzard_HelpPlate.xml",
        # the level-1 HelpTips of Blizzard_Tutorials (the interact key, super-tracking); the addon's other
        # tutorials: the reachable ones are listed in _TUTORIAL_WINDOWS below
        "Blizzard_Tutorials/Blizzard_Tutorials_Frame_Tutorials.lua",
        "Blizzard_Tutorials/Blizzard_TutorialSuperTrack.lua",
    ],
    "spellbook": [_PS + "SpellBook/Blizzard_SpellBookFrameTutorials.lua"],
    "alerts": ["Blizzard_FrameXML/EventToastManager.lua", "Blizzard_FrameXML/EventToastManager.xml"],
}
for _surface, _files in _LEVEL1_WINDOWS.items():
    FOREVER_WINDOWS.setdefault(_surface, []).extend(_files)

# The tutorials a Forever player can reach: the mainline tutorial popup (UI/Tutorial; loaded on
# camelot by blizzard_framexml.toc:32–33, live ids in DISPLAY_DATA, tutorialframe.lua:119–182) and the
# tutorial manager's pointer arrows with the Blizzard_Tutorials parts that are not retail-only (UI/HelpTips).
# The new player experience, the boost tutorial, Remix, Dracthyr, skyriding and the Trading Post are
# unreachable (pipeline/forever_addon_dispositions.txt).
_TUTORIAL_WINDOWS: dict[str, list[str]] = {
    "tutorial": [
        "Blizzard_FrameXML/Mainline/TutorialFrame.lua",
        "Blizzard_FrameXML/Mainline/TutorialFrame.xml",
    ],
    "help": [
        "Blizzard_TutorialManager/Blizzard_TutorialPointerFrame.lua",
        "Blizzard_Tutorials/Blizzard_Tutorials_Classes.lua",
        "Blizzard_Tutorials/Blizzard_Tutorials_Professions.lua",
        "Blizzard_Tutorials/Blizzard_TutorialReagentBag.lua",
        "Blizzard_Tutorials/BagTutorialUtil.lua",
    ],
}
for _surface, _files in _TUTORIAL_WINDOWS.items():
    FOREVER_WINDOWS.setdefault(_surface, []).extend(_files)

# The UI errors frame (ADR-035). Its lines are sent by the C client (UI_ERROR_MESSAGE /
# UI_INFO_MESSAGE carry the game-message id, blizzard_uierrorsframe/mainline/uierrorsframe.lua:13–24,
# 146–157), so the strings are the `errors` DYNAMIC family below, not a text scan of these files.
FOREVER_WINDOWS["errors"] = [
    "Blizzard_UIErrorsFrame/Mainline/UIErrorsFrame.lua",
    "Blizzard_UIErrorsFrame/Mainline/UIErrorsFrame.xml",
    "Blizzard_UIErrorsFrame/Camelot/UIErrorsFrameOverrides.lua",
]
# Chat system lines (UI/ChatSystem): the errors surface's keys arriving as SYSTEM chat lines,
# added by ChatFrameMixin:MessageEventHandler and by ChatFrameUtil.AddSystemMessage / DisplaySystemMessage*
# (chatframeutil.lua:297–315); the keys are the `chatsystem` DYNAMIC family below.
FOREVER_WINDOWS["chatsystem"] = ["Blizzard_ChatFrameBase/Shared/ChatFrameUtil.lua"]
# NPC speech (UI/Speech): its text is the server's (gossip lines), not GlobalStrings; the files are
# the two writers the module hooks besides the chat frames.
FOREVER_WINDOWS["speech"] = [
    "Blizzard_RaidWarning/RaidWarning.lua",
    "Blizzard_ChatBubble/ChatBubbleTemplates.xml",
]
# The StaticPopup / GameDialog dialogs (UI/Popups, ADR-037). The dialog code; every dialog's own
# strings are read from its StaticPopupDialogs definition anywhere in the load set (popup_keys below).
FOREVER_WINDOWS["popups"] = [
    "Blizzard_StaticPopup_Game/GameDialog.lua",
    "Blizzard_StaticPopup_Game/GameDialog.xml",
    # the StaticPopupSpecial frames UI/Popups walks (they own their text)
    "Blizzard_AddFriend/AddFriendTemplates.lua",
    "Blizzard_AddFriend/AddFriendTemplates.xml",
    "Blizzard_LFGUtil/Mainline/PVPPopup.lua",
    "Blizzard_LFGUtil/Mainline/PVPPopup.xml",
    "Blizzard_LFGUtil/Mainline/PVPHelper.lua",
    "Blizzard_LFGUtil/Mainline/PVPHelper.xml",
    "Blizzard_LFGUtil/Shared/LFGInvitePopup.lua",
    "Blizzard_LFGUtil/Shared/LFGInvitePopup.xml",
    _U + "Mainline/RoleSelectionTemplate.xml",
]


# Names Blizzard builds at run time (`_G["SPELL_STAT"..i.."_NAME"]`), which a text scan cannot see: every
# GlobalStrings key matching one of a surface's patterns is inventoried for it. Among them are the camelot
# character pane's names (camelot/PaperDollFrameStats.lua, camelot/PaperDollFrameConstants.lua) and the
# community calendar's weekdays.
_CLASSES = "DEFAULT|WARRIOR|PALADIN|HUNTER|ROGUE|PRIEST|SHAMAN|MAGE|WARLOCK|DRUID"
DYNAMIC: dict[str, list[str]] = {
    # names built at run time that no scan saw: the report categories (reportframe.lua builds
    # REPORTING_MAJOR_CATEGORY_* / _MINOR_* from the Enum), the role descriptions (lfgrole.lua:71–82,
    # "ROLE_DESCRIPTION_"..role), the weapon-skills header (camelot skillsframe), the icon picker's title
    "reportframe": [r"REPORTING_(MAJOR|MINOR)_CATEGORY_[A-Z0-9_]+"],
    "groupfinder": [r"ROLE_DESCRIPTION_(TANK|HEALER|DAMAGER)"],
    "skills": [r"STAT_CATEGORY_WEAPON_SKILLS"],
    "macro": [r"ICON_SELECTION_TITLE_CURRENT"],
    # the tutorial popup's title / body are _G["TUTORIAL_TITLE"..id] / _G["TUTORIAL"..id] with race /
    # class variants (tutorialframe.lua:446–455, 481–487); only the ids DISPLAY_DATA lists draw (:119–182,
    # :365–368; any other id is flagged and returns), so the family is those 8 ids
    "tutorial": [r"TUTORIAL(_TITLE)?(17|18|22|27|28|37|46|52)(_[A-Z]+)*"],
    # the dialog countdown's unit words (GameDialogDefsUtil.GetDefaultExpirationText passes SECONDS / MINUTES
    # as a dialog argument; UI/Popups puts their Japanese in)
    # the "%s" dialogs' caller lines: the cross-realm party invite (mainline eventimplementation.lua:768)
    # and the talent wipe's _G["CONFIRM_TALENT_WIPE_"..talentType] (gamedialogdefs.lua:96-99)
    "popups": [r"SECONDS|MINUTES", r"INVITATION_XREALM", r"CONFIRM_TALENT_WIPE_\d"],
    # the talent button tooltip's action-bar status and edge-requirements lines (UI/Talents TOOLTIP_KEYS)
    "talents": [r"TALENT_FRAME_SEARCH_TOOLTIP_(NOT_ON_ACTIONBAR|ON_DISABLED_ACTIONBAR|ON_INACTIVE_BONUSBAR)",
                r"GENERIC_TRAIT_FRAME_EDGE_REQUIREMENTS_BUTTON_TOOLTIP"],
    # the loss-of-control words C_LossOfControl hands over as displayText (UI/LossOfControl's DISPLAY list),
    # the subscription window's bullets (_G["…_BULLET"..n], subscriptioninterstitialframe.lua), the
    # text-to-speech check boxes (_G[type.."_TTS_LABEL"], texttospeechframe.lua)
    "lossofcontrol": [r"LOSS_OF_CONTROL_DISPLAY_[A-Z_]+"],
    "subscriptioninterstitial": [r"SUBSCRIPTION_INTERSTITIAL_UPGRADE_BULLET\d+"],
    "texttospeech": [r"[A-Z_]+_TTS_LABEL"],
    "character": [
        r"SPELL_STAT\d_NAME",
        r"RESISTANCE\d_NAME",
        r"RESISTANCE_TYPE\d",
        r"RESISTANCE_(EXCELLENT|VERYGOOD|GOOD|FAIR|POOR|NONE)",
        rf"({_CLASSES})_(STRENGTH|AGILITY|STAMINA|INTELLECT|SPIRIT)_TOOLTIP",
        r"(HEAD|NECK|SHOULDER|BACK|CHEST|SHIRT|TABARD|WRIST|HANDS|WAIST|LEGS|FEET|FINGER\d|TRINKET\d|MAINHAND"
        r"|SECONDARYHAND|RANGED|AMMO|RELIC)SLOT",
        r"STAT_CATEGORY_RESISTANCE",
        r"DAMAGE_SCHOOL[2-7]",
        r"MANA|RAGE|ENERGY|FOCUS|RUNIC_POWER",
        r"STAT_(MANA|RAGE|ENERGY|FOCUS|RUNIC_POWER)_TOOLTIP",
        rf"MELEE_ATTACK_POWER_PET_({_CLASSES})_TOOLTIP",
        rf"({_CLASSES})_MELEE_ATTACK_POWER_TOOLTIP",
        r"DEFAULT_(STRENGTH|AGILITY|STAMINA|INTELLECT|SPIRIT)_TOOLTIP",
        # the hit and crit hovers are `_G["CR_"..class.."_HIT_CAP_TOOLTIP"]` and
        # `_G["STAT_"..class.."_CRIT_BONUS"]` / `…_PET_CRIT_BONUS` (camelot paperdollframestats.lua:449,
        # 539–541)
        rf"CR_({_CLASSES})_HIT_CAP_TOOLTIP",
        rf"STAT_({_CLASSES})_(PET_)?CRIT_BONUS",
    ],
    "reputation": [r"FACTION_STANDING_LABEL\d(_FEMALE)?"],
    "spellbook": [r"PET_TYPE_[A-Z]+"],
    # GetText("GUILD_TOTAL", …) is a quoted name; SEARCH is the who box's SearchBoxTemplate placeholder
    "friends": [r"LASTONLINE_[A-Z]+", r"GUILDCONTROL_OPTION\d+", r"GUILD_TOTAL", r"SEARCH"],
    "help": [r"PET_ACTION_[A-Z]+", r"PET_MODE_[A-Z]+"],
    # the edit box header is `_G["CHAT_"..type.."_SEND"]`
    # (blizzard_chatframebase/shared/chatframeeditbox.lua:693)
    "chattabs": [r"CHAT_[A-Z_]+_SEND"],
    # the unit mouseover lines the client composes (C_TooltipInfo; TooltipDataType.Unit): level,
    # creature type, skinning and corpse lines. The unit's name, guild and the server's lines are never among
    # them.
    "tooltip": [
        r"TOOLTIP_UNIT_LEVEL(_RACE)?(_TYPE)?",
        r"UNIT_(TYPE_)?(PLUS_)?LEVEL_TEMPLATE|UNIT_LEVEL_DEAD_TEMPLATE",
        r"UNIT_SKINNABLE_[A-Z]+",
        r"CORPSE_TOOLTIP",
        # the owner line under a pet, minion or guardian ("Bob's Pet", the UnitOwner line kind)
        r"UNITNAME_TITLE_[A-Z]+|UNITNAME_SUMMON_TITLE\d+",
        # lines the compiled client writes into a unit tooltip and no Lua names: threat, the corpse and
        # skull-level
        # lines, the already-gathered lines, and the item / object / no-progress objective forms
        r"THREAT_TOOLTIP|CORPSE|UNIT_(TYPE_)?LETHAL_LEVEL(_DEAD)?_TEMPLATE|UNIT_ALREADY_SKINNED_[A-Z]+|UNIT_CAPTURABLE",
        r"QUEST_(ITEMS_NEEDED|OBJECTS_FOUND|MONSTERS_KILLED)(_NOPROGRESS)?",
    ],
    # the buff frame's durations are SecondsToTimeAbbrev's `*_ONELETTER_ABBR`
    # (blizzard_sharedxml/timeutil.lua:463–480; blizzard_buffframe/buffframe.lua:427, 1203, 1306); the
    # level-up toast's title and subtitle are client-supplied (toastInfo,
    # blizzard_framexml/eventtoastmanager.lua:491–492) [unverified: which global strings the client uses; the
    # in-game checklist]
    "hudlabels": [r"(DAY|HOUR|MINUTE|SECOND)_ONELETTER_ABBR"],
    "alerts": [r"LEVEL_GAINED", r"LEVEL_UP_YOU_REACHED"],
    # the community calendar tooltip's day is CALENDAR_WEEKDAY_NAMES[weekday]
    # (communitiescalendar.lua:37; the table is WEEKDAY_*, blizzard_framexmlbase/constants.lua:299-307)
    "communities": [r"WEEKDAY_(SUNDAY|MONDAY|TUESDAY|WEDNESDAY|THURSDAY|FRIDAY|SATURDAY)"],
    # every game-message string the errors frame can show: GetGameMessageInfo(id) names the key
    # (blizzard_apidocumentationgenerated/gameerrordocumentation.lua:10–25; voiceutils.lua:82–84 reads _G[it])
    "errors": [
        r"ERR_[A-Z0-9_]+", r"SPELL_FAILED_[A-Z0-9_]+",
        # the strings Blizzard's Lua passes to the frame through a variable (the call-site
        # scan below finds the ones named on the call line): community / club errors
        # (communitieserrors.lua:5–132, gamedialogdefs.lua:1365), guild rename
        # (blizzard_guildrename.lua:22–37, 289), report results
        # (blizzard_game/shared/eventimplementation.lua:1–38), pings (blizzard_pingmanager.lua:10–27 →
        # mainline/eventimplementation.lua:168, [unverified: the C string is one of these]), gamepad radial
        # (gamepadradial.lua:67, 612), crafting orders (blizzard_professionscustomerordersform.lua:472), the
        # profession-tool auto-equip lines (camelot paperdollframe.lua:82–96, 2073;
        # charactermodelframemixin.lua:31), the talent-config throttle (blizzard_sharedtalentframe.lua:1740),
        # the token lines (blizzard_wowtokenuiinsecure.lua:14)
        r"ERROR_CLUB_[A-Z0-9_]+", r"ERROR_COMMUNITIES_[A-Z0-9_]+",
        r"COMMUNITIES_SETTING_CROSS_FACTION_TOOLTIP_ERROR",
        r"GUILD_RENAME_ERROR_[A-Z0-9_]+", r"REPORT_RESULT_[A-Z0-9_]+", r"PING_FAILED_[A-Z0-9_]+",
        r"RADIAL_ERROR_[A-Z0-9_]+", r"CRAFTING_ORDER_FAILED_[A-Z0-9_]+", r"PROFESSIONS_MAX_ORDERS_REACHED",
        r"PROFESSIONS_ORDER_[A-Z_]*FAILED[A-Z_]*", r"(PAPERDOLL|PROFESSIONS)_AUTO_EQUIP_[A-Z]+_ONLY",
        r"(TALENT_FRAME|PROFESSIONS_SPECS)_CONFIG_OPERATION_TOO_FAST", r"TOKEN_TRIAL_RESTRICTIONS",
        r"TOKEN_AUCTIONS_UNAVAILABLE",
        # a removed-from-community line, :format(clubName) (communitieserrors.lua:126–132)
        r"CLUB_REMOVED_REASON_[A-Z0-9_]+",
    ],
    # the prefix the chat frame puts before an NPC's line (CHAT_MONSTER_*_GET,
    # chatframeoverrides.lua:629–633)
    "speech": [r"CHAT_MONSTER_(SAY|YELL|WHISPER|EMOTE|PARTY)_GET", r"CHAT_RAID_BOSS_(EMOTE|WHISPER)_GET"],
    "chatsystem": [
        r"ERR_[A-Z0-9_]+", r"SPELL_FAILED_[A-Z0-9_]+",
        # the prefix before a player's line: "%s says: ", "To %s: " … (_G["CHAT_"..type.."_GET"],
        # chatframeutil.lua:352–355, chatframeoverrides.lua:629–633)
        r"CHAT_(SAY|YELL|EMOTE|WHISPER|WHISPER_INFORM|PARTY|PARTY_LEADER|PARTY_GUIDE|RAID|RAID_LEADER|"
        r"RAID_WARNING|GUILD|OFFICER|INSTANCE_CHAT|INSTANCE_CHAT_LEADER|BN_WHISPER|BN_WHISPER_INFORM|AFK|DND|"
        r"CHANNEL|CHANNEL_JOIN|CHANNEL_LEAVE)_GET",
        # all system chat: the lines the game sends as SYSTEM / LOOT / MONEY /
        # CURRENCY / COMBAT_XP_GAIN / COMBAT_HONOR_GAIN / COMBAT_FACTION_CHANGE / SKILL / TRADESKILLS /
        # OPENING chat, added plain by ChatFrameMixin:MessageEventHandler (chatframeoverrides.lua:397–408) or
        # by the SystemEventHandler (TIME_PLAYED_MSG, PLAYER_LEVEL_CHANGED: chatframeutil.lua:251–263,
        # chatframeutiloverrides.lua:80–86). No Lua names them: the families follow GlobalStrings naming; the
        # one Lua consumer, battlegroundchatfilters.lua:10, matches LOOT_ITEM / CREATED_ITEM against
        # CHAT_MSG_SYSTEM.
        r"LOOT_ITEM(_[A-Z0-9_]+)?", r"LOOT_ROLL_[A-Z0-9_]+", r"CREATED_ITEM(_MULTIPLE)?",
        r"(LOOT_MONEY|YOU_LOOT_MONEY)[A-Z0-9_]*", r"LOOT_(CURRENCY|MONEY)_REFUND",
        r"CURRENCY_GAINED[A-Z0-9_]*",
        r"COMBATLOG_XPGAIN_[A-Z0-9_]+", r"COMBATLOG_(HONOR|DISHONOR|ARENAPOINTS)[A-Z0-9_]*",
        r"FACTION_STANDING_(IN|DE)CREASED[A-Z0-9_]*", r"SKILL_RANK_UP", r"TRADESKILL_LOG_[A-Z0-9_]+",
        r"OPEN_LOCK_[A-Z0-9_]+", r"(MARKED|CLEARED)_(AFK|DND)(_MESSAGE)?", r"TIME_PLAYED_(TOTAL|LEVEL)",
        r"LEVEL_UP(_NO_LINK|_HEALTH|_HEALTH_MANA|_STAT|_SKILL_POINTS)?", r"DURABILITYDAMAGE_DEATH",
        r"INSTANCE_RESET_[A-Z0-9_]+", r"RANDOM_ROLL_RESULT", r"ACHIEVEMENT_BROADCAST(_SELF)?",
    ],
}
