"""Which spells a player can actually be shown, so a translation batch is scoped by evidence.

    python -m wfj.dev.visible_spells --wow "<World of Warcraft>" --product wow_classic_beta \
        [--against-product wow_classic_era] > visible_spells.txt

The re-pull leaves far more spell descriptions with English and no Japanese than a player will ever read:
most spells in `Spell.db2` are internal: procs, scripts, NPC-only, test rows. Drafting all of them spends
the subscription on text nobody sees. This derives the visible set from the client's own tables instead of
from judgement, and writes it as a committed artifact the way `ui_inventory.txt` is (regenerated by
`make visible-spells`, not read live), so cutting a batch needs no game install.

Three sources, each one a reason a spell's text reaches the screen:

- **`item`**: `ItemXItemEffect.ItemEffectID` → `ItemEffect.SpellID`, the spell whose description prints
  inside an item's tooltip ("Restores $o1 health over $d"). Forever moved this join out of `ItemEffect` into
  `ItemXItemEffect` (ADR-027).
- **`skill`**: `SkillLineAbility.Spell`, a spell a class or profession can learn, so it appears in the
  spellbook and at a trainer.
- **`trait`**: `TraitDefinition.SpellID`, a spell granted by a talent. **Not `Talent.db2`** (see below).

A spell is reported per source and in the union. The union is the scope; the per-source counts are what make
it auditable.

**`Talent.db2` is legacy on Forever and must not be used for this.** It holds the same 432 Vanilla rows on
both builds (identical layout hash; every row differs only by one field zeroed), and only 517 of the 1,357
spell ids in its `SpellRank` arrays still exist in Forever's `SpellName`. Forever's live talents are the
**trait** tables, which Classic Era ships nearly empty: `TraitDefinition` 9 rows → **656**, `TraitNode` 9 →
560, `TraitTree` 1 → 17. Scoping talents from `Talent.db2` would miss Forever's new ones and include gone
ones.

Column maps, pinned here with their evidence rather than in `io/client_tables.py`, because **nothing is
imported from these tables**: they carry no translatable text, so they need no CSV, no source stamp, no
hotfix decode and no provenance. `ItemXItemEffect` / `ItemEffect` keep theirs in
`client_tables`, where they do carry text.
"""

from __future__ import annotations

import argparse
import sys
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path

from wfj.io import casc, client_tables, db2


@dataclass(frozen=True)
class Map:
    """One table read only for ids: its FileDataID, and the field holding the spell id per layout hash."""

    name: str
    file_data_id: int
    spell_field: dict[int, int]  # layout hash → field index
    evidence: str


# `SkillLineAbility`: Forever prepended two fields (16 → 18) and everything shifted by 2. Verified the way
# ADR-027 verifies a move by cross-build agreement over the 6,047 ids both clients hold: Classic Era's field 1
# (SkillLine) matches Forever's field 3 on 6,047 of 6,047, and field 2 (Spell) matches field 4 on 6,035 of
# 6,047 (99.8%), with the next-best field at 0.0% in both cases. The 12 disagreements are rows where Forever
# changed which spell the skill line grants, which is content.
#
# `TraitDefinition`: the same layout hash on both builds (`0x060A9F4C`), so the field structure is the same by
# definition; what changed is that Forever fills it. Field 4 holds the spell: 647 of its 653 non-zero values
# are ids present in Forever's `SpellName` (529 distinct) and no other field is above 0%. Verified end to end
# as well, because Classic Era's 9 rows are too few to be an oracle: TraitDefinition 133102 → spell 11210 →
# `SpellName` "Arcane Subtlety", 133103 → 11222 "Arcane Focus", 133104 → 11237 "Improved Channeling"; Vanilla
# mage talents, and Classic Era's 9 rows carry the same nine ids in the same field. 362 of the 517 legacy
# `Talent` spell ids that still exist appear here, so the trait trees are Vanilla's talents rebuilt plus new
# ones.
MAPS = (
    Map(
        "SkillLineAbility",
        1266278,
        {0x0ED0E33F: 2, 0x224F7EA0: 4},
        "cross-build 6035/6047 = 99.8% at field 4, next best 0.0%",
    ),
    Map(
        "TraitDefinition",
        4420327,
        {0x060A9F4C: 4},
        "647/653 non-zero values are SpellName ids; end to end 133102 -> 11210 Arcane Subtlety",
    ),
)
SOURCES = ("item", "skill", "trait")


class VisibleError(ValueError):
    """A table needed for the scope could not be read, or its layout is not one we have verified."""


def _read(archive: casc.LocalArchive, name: str, fdid: int, strings=frozenset()) -> db2.Db2Table:
    try:
        buf, gaps = archive.read_file(archive.file_data_id(f"DBFilesClient\\{name}.db2", fdid))
        return db2.read(buf, string_fields=strings, encrypted=gaps, name=name)
    except (casc.CascError, db2.Db2Error) as e:
        raise VisibleError(f"{name}: {e}") from e


def _verified(archive: casc.LocalArchive, name: str) -> tuple[db2.Db2Table, dict[str, int | str]] | None:
    """A client table read through its VERIFIED column map (`client_tables.for_layout`, ADR-027) → (table,
    column name → field), or None when it is an `optional` table this build does not ship. Anything else that
    cannot be read (an encrypted section, an unverified layout) is a `VisibleError`, never a quiet fallback:
    an unreadable ItemXItemEffect would otherwise empty the item set on Forever without a word."""
    table = client_tables.TABLES[name]
    try:
        fdid = archive.file_data_id(table.path, fallback=table.file_data_id)
        buf, gaps = archive.read_file(fdid)
        header = db2.read_header(buf, table.name)
    except casc.CascError as e:
        if table.optional and "names 0 enUS files" in str(e):
            return None  # the same test `client_tables.extract` uses for TableAbsent
        raise VisibleError(f"{name}: {e}") from e
    try:
        mapped = client_tables.for_layout(table, header)
        read = db2.read(buf, string_fields=mapped.string_fields, encrypted=gaps, name=name)
    except (client_tables.TableError, db2.Db2Error) as e:
        raise VisibleError(f"{name}: {e}") from e
    return read, {c.name: c.source for c in mapped.columns}


def _spell_field(archive: casc.LocalArchive, m: Map) -> tuple[db2.Db2Table, int]:
    """(the table, the field holding its spell id), refusing a layout hash we have not verified."""
    try:
        buf, _ = archive.read_file(archive.file_data_id(f"DBFilesClient\\{m.name}.db2", m.file_data_id))
    except casc.CascError as e:
        raise VisibleError(f"{m.name}: {e}") from e
    layout = db2.read_header(buf, m.name).layout_hash
    if layout not in m.spell_field:
        known = ", ".join(f"0x{h:08X}" for h in m.spell_field)
        raise VisibleError(
            f"{m.name}: layout 0x{layout:08X} is not one its spell column was verified on ({known}). "
            "Re-verify with `python -m wfj.dev.verify_columns` before trusting the scope"
        )
    return _read(archive, m.name, m.file_data_id), m.spell_field[layout]


def visible(archive: casc.LocalArchive) -> dict[str, set[int]]:
    """{source: the spell ids it makes reachable}. Every id is a row of this client's `SpellName`."""
    names = _verified(archive, "SpellName")
    if names is None:
        raise VisibleError("SpellName: not shipped on this build")
    known = set(names[0].rows)

    got = _verified(archive, "ItemEffect")
    if got is None:  # not optional: never None, but the type says it may be
        raise VisibleError("ItemEffect: not shipped on this build")
    eff, cols = got
    spell_col = cols["SpellID"]
    eff_spell = {i: r[spell_col] for i, r in eff.rows.items()}
    join = _verified(archive, "ItemXItemEffect")
    if join is not None:
        x, xcols = join
        effect_col = xcols["ItemEffectID"]
        item = {eff_spell.get(r[effect_col], 0) for r in x.rows.values()}
    elif eff.relation:
        # Classic Era does the join inline: ItemEffect's own relationship map names the owning item
        item = {eff_spell[i] for i in eff.relation}
    else:
        raise VisibleError("ItemEffect: no relationship map and no ItemXItemEffect; no item can be joined")

    out = {"item": item}
    for m in MAPS:
        table, field = _spell_field(archive, m)
        out["skill" if m.name == "SkillLineAbility" else "trait"] = {
            r[field] for r in table.rows.values() if r[field]
        }
    return {k: {i for i in v if i in known} for k, v in out.items()}


def render(version: str, product: str, sets: dict[str, set[int]]) -> list[str]:
    """The artifact: a header naming the build and the per-source counts, then `<sources> <spell id>`."""
    union = sorted(set().union(*sets.values()))
    out = [
        f"# GENERATED by `python -m wfj.dev.visible_spells` from {version} ({product}).",
        "# A spell a player can be shown: its description prints in an item tooltip (item), a class or",
        "# profession can learn it (skill), or a talent grants it (trait). Every id is a row of this",
        "# build's SpellName. Regenerate with `make visible-spells`; commit the result.",
        "# "
        + " · ".join(f"{s}: {len(sets[s])}" for s in SOURCES)
        + f" · union: {len(union)}",
    ]
    for spell in union:
        out.append(",".join(s for s in SOURCES if spell in sets[s]) + f" {spell}")
    return out


def read_artifact(path: Path) -> dict[int, frozenset[str]]:
    """{spell id: the sources that make it visible} from a generated file."""
    out: dict[int, frozenset[str]] = {}
    for n, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split()
        if len(parts) != 2 or not parts[1].isdigit():
            raise VisibleError(f"{path.name}:{n}: {raw!r} is not `<sources> <spell id>`")
        sources = frozenset(parts[0].split(","))
        if not sources <= set(SOURCES):
            raise VisibleError(f"{path.name}:{n}: unknown source in {parts[0]!r}")
        out[int(parts[1])] = sources
    return out


def main(argv: Sequence[str] | None = None) -> int:
    p = argparse.ArgumentParser(prog="python -m wfj.dev.visible_spells")
    p.add_argument("--wow", required=True, type=Path, help="the folder holding .build.info")
    p.add_argument("--product", required=True, help="the client to derive the scope from")
    a = p.parse_args(list(argv) if argv is not None else None)
    try:
        archive = casc.LocalArchive(a.wow, a.product)
        sets = visible(archive)
    except (casc.CascError, client_tables.TableError, VisibleError) as e:
        print(f"visible-spells: {e}", file=sys.stderr)
        return 1
    print("\n".join(render(archive.info.version, a.product, sets)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
