-- GENERATED by `wfj generate` from data/quest/quest-0000.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("quest", {
  [1] = { "He said \"hi\"\\ok\n[tag] |cffff0000red|r\ttab\001end\r", nil, "改行\nあり", nil, nil, 0xd311f9a5, nil, 0x0badf00d, nil, nil, ".msmm" },
  [2] = { nil, "[[]]", nil, nil, nil, nil, 0xd311f9a5, nil, nil, nil, "m.mmm" },
})
