-- GENERATED by `wfj generate` from data/spell/spell-1215.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [1215377] = { "酸で敵を攻撃し、$N1のNatureダメージを与えます。", nil, 0x1ce273c6, nil, "um" },
  [1215378] = { "騎乗できるTigerを召喚、または解散させます。非常に速い乗り物です。", "地上での移動速度が$N1%上昇します。", 0x745feae3, 0x2195529a, "uu" },
  [1215380] = { "騎乗できるRaptorを召喚、または解散させます。非常に速い乗り物です。", "地上での移動速度が$N1%上昇します。", 0x955b85b6, 0x2195529a, "uu" },
  [1215404] = { "MetamorphosisまたはWay of Earthが有効な間、装備しているTimeworn防具の部位ごとに、Fireのダメージ呪文の効果が$N1%上昇します。", nil, 0xbd362e35, nil, "um" },
  [1215508] = { "周期的でないダメージ呪文を受けたとき、$N1%の確率で、その系統のダメージを$N3吸収する呪文シールドを$D1の間得ます。", nil, 0xf2962962, nil, "um" },
  [1215615] = { "Demonic GauntletとAcidic Gooを組み合わせます。", nil, 0x4274156d, nil, "um" },
  [1215969] = { "Darkwhisper GorgeでHederineの悪魔の精髄を集めます。", nil, 0xf3749f3b, nil, "um" },
})
