-- GENERATED by `wfj generate` from data/spell/spell-1299.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [1299026] = { "すべてのCurseとBaneを即座に取り除いて無効化し、$D1の間、受けるすべてのMagicalダメージを$N1%軽減します。", "CursesとBanesに対する免疫があります。受けるMagicalダメージが$N1%減少します。", 0xd2a2dff2, 0x502f53fa, "uu" },
  [1299095] = { nil, "Replica Ironforge Air Rifleで撃ってもかまわない相手です。", nil, 0xaa5a3d05, "mu" },
  [1299332] = { "対象に傷を負わせて出血させ、$D1かけて$N1のダメージを与えます。", "出血により、$N2秒ごとに$N1のダメージを受けています。", 0x47f171f5, 0xa4d4838c, "uu" },
  [1299341] = { "Bitter Baitlingを召喚します。", nil, 0xcee0200d, nil, "um" },
  [1299346] = { "$N1ヤード以内のパーティメンバーのRanged Attack Powerを$N2上昇させます。効果時間は$D1です。", "Ranged Attack Powerが$N1増加しています。", 0xac5e0ea5, 0x0e786fb6, "uu" },
  [1299348] = { "$N1ヤード以内のパーティメンバーのRanged Attack Powerを$N2上昇させます。効果時間は$D1です。", "Ranged Attack Powerが$N1増加しています。", 0xac5e0ea5, 0x0e786fb6, "uu" },
  [1299351] = { "$D1の間、水上を歩けるようになります。\n\n攻撃するかダメージを受けると、この効果は解除されます。", "水の上を歩いています。攻撃するかダメージを受けると、この効果は解除されます。", 0xa68ec1ff, 0xc31b4f3d, "uu" },
  [1299440] = { "$N1ヤード以内のすべての悪魔を$D1の間恐怖させます。", "恐怖に陥っています。", 0x5275dedd, 0x5a2205f2, "uu" },
  [1299443] = { "雷の力を操って対象を打ち、$D1の間スタンさせます。水中にいるプレイヤーは$N2倍の時間スタンします。", "スタンしています。", 0xdaaa3cd4, 0x27f95286, "uu" },
  [1299445] = { "ハンターが獣の相を身にまとい、追跡されなくなり、Melee Attack Powerを$N1上げます。同時に有効にできるAspectは1つだけです。", "追跡されません。Melee Attack Powerが$N1増加しています。", 0x885c9704, 0x6fd501b3, "uu" },
  [1299446] = { "ハンターが獣の相を身にまとい、追跡されなくなり、Melee Attack Powerを$N1上げます。同時に有効にできるAspectは1つだけです。", "追跡されません。Melee Attack Powerが$N1増加しています。", 0x885c9704, 0x6fd501b3, "uu" },
  [1299447] = { "ハンターが獣の相を身にまとい、追跡されなくなり、Melee Attack Powerを$N1上げます。同時に有効にできるAspectは1つだけです。", "追跡されません。Melee Attack Powerが$N1増加しています。", 0x885c9704, 0x6fd501b3, "uu" },
  [1299631] = { "対象を打ち据えて$N1のHolyダメージを与えます。アンデッドには$N2倍のダメージを与えます。", nil, 0xf4f8720a, nil, "um" },
  [1299850] = { "火の玉を投げつけ、$N1のFireダメージと、$D1かけてさらに$N2のダメージを与えます。", "$N2秒ごとに$N1のFireダメージを受けます。", 0xa6bc16f5, 0xfead54e5, "uu" },
  [1299869] = { "敵の対象から生命力を$N1奪います。アンデッドには$N2倍のダメージを与えます。", nil, 0x8ac422e0, nil, "um" },
  [1299948] = { "有害な呪文を唱えると、一定の確率で$D1かけて対象の敵から生命力を$N1奪います。", nil, 0xe7e2f96d, nil, "um" },
})
