-- GENERATED by `wfj generate` from data/spell/spell-0443.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [443265] = { "$D1かけて$N1のFireダメージを与えます。悪魔とBeastは$D2の間、その場でRootedの状態になります。", "$N2秒ごとに$N1のFireダメージを受けています。", 0xc1da90e1, 0x62dbdc65, "uu" },
  [443278] = { "アビリティや呪文を命中させた人型、野獣、ドラゴン族の敵に、一定の確率で種を植え付けます。種を植え付けてから30秒以内にそのクリーチャーが倒されると、死体からHealing Blossomが育ちます。", "アビリティや呪文が命中した敵の人型生物、獣、ドラゴン族に種を埋め込むことがあります。", 0x7356ebc3, 0xf4627924, "uu" },
  [443358] = { "$N2ヤード以内の最大$N1体の敵を攻撃し、それぞれに武器ダメージを与え、Whirlwindアビリティのクールダウンをリセットします。", nil, 0x58e4e62f, nil, "um" },
  [443632] = { "実質的なステルスレベルを3上昇させます。Disarm TrapとPickpocketの射程を$N2ヤード、Distractの射程を$N3ヤード延長します。", nil, 0x52f344aa, nil, "um" },
})
