-- GENERATED by `wfj generate` from data/spell/spell-0445.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [445181] = { "シャーマンが元素の精霊を見られるようにします。", "エレメンタルの精霊を探知します。", 0xeeb68834, 0x5c91d9a4, "uu" },
  [445459] = { "Explorer Impを召喚します。戦うことはできませんが、ポータルを通って別の世界を探検し、財宝を持ち帰ることができます。", nil, 0x8c314203, nil, "um" },
  [445748] = { "Fragment of AirをElemental Essenceと組み合わせます。穢れた祠を見つける手がかりになるかもしれません。", nil, 0x13e8c532, nil, "um" },
})
