-- GENERATED by `wfj generate` from data/spell/spell-1261.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [1261177] = { nil, "あなたはとても、とてもこっそりしています。", nil, 0x2b886deb, "mu" },
  [1261222] = { "鋭いグレイブを敵に向けて放ちます。", "出血しています。", 0x1ddb27a2, 0xd6c5aa1b, "uu" },
  [1261251] = { "敵を打ち据え、Holyダメージを与えます。", nil, 0x20941603, nil, "um" },
  [1261320] = { "敵にFireダメージを与えます。", nil, 0x6c371710, nil, "um" },
  [1261483] = { nil, "$D1ごとに体力を$N1、マナを$N2回復しています。", nil, 0xf627f070, "mu" },
  [1261692] = { "倒れたKhanを蘇らせます。", "蘇生されています。", 0x941c111c, 0x3e242633, "uu" },
  [1261773] = { "このクエストを完了すると、アカウントのすべてのキャラクターに称号「<Name> of the Magram」が与えられます。\n\nこの称号は、Magram Clan CentaurとExalted以上のときにのみ表示できます。", nil, 0x41006e61, nil, "um" },
  [1261774] = { "このクエストを完了すると、このキャラクターに称号「<Name> of the Gelkis」が与えられます。\n\nこの称号は、Gelkis Clan CentaurとExalted以上のときにのみ表示できます。", nil, 0x25a1c331, nil, "um" },
  [1261854] = { nil, "個人用バンクは使えません。", nil, 0x90318efa, "mu" },
})
