-- GENERATED by `wfj generate` from data/spell/spell-1228.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [1228294] = { "指定された三角測量の地点で装置を使い、Fizzlefuseのテレポーターの調整を手伝います。", nil, 0x3fe0358d, nil, "um" },
  [1228332] = { "この武器セットの外見を収集します。", nil, 0xda02ac39, nil, "um" },
})
