-- GENERATED by `wfj generate` from data/spell/spell-0453.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [453017] = { "回復がクリティカルになると一定の確率で近くの味方3人を$N2回復し、呪文がクリティカルヒットすると一定の確率で近くの敵3体に$N4の自然ダメージを与えます。", "呪文のクリティカル治療効果に、周囲の味方最大$N1人を$N2回復する可能性があります。", 0x376f5ceb, 0x25f66d43, "uu" },
  [453053] = { "Cat、Bear、Dire Bearフォームでのみ、Attack Powerが+$N1されます。", nil, 0xa798bce2, nil, "um" },
  [453635] = { "指輪にSword Specializationのルーンを刻みます：\n\n$I1\nSwordsとTwo-Handed Swordsのスキルが$N1上昇します。この効果は種族ボーナスや他の指輪のルーンとは重複しません。", nil, 0x619fe816, nil, "um" },
  [453688] = { "指輪にAxe Specializationのルーンを刻みます：\n\n$I1\nAxesとTwo-Handed Axesのスキルが$N1上昇します。この効果は種族ボーナスや他の指輪のルーンとは重複しません。", nil, 0x80944dc1, nil, "um" },
  [453689] = { "指輪にMace Specializationのルーンを刻みます：\n\n$I1\nMacesとTwo-Handed Macesのスキルが$N1上昇します。この効果は種族ボーナスや他の指輪のルーンとは重複しません。", nil, 0xf8361805, nil, "um" },
  [453690] = { "指輪にDagger Specializationのルーンを刻みます：\n\n$I1\nDaggersのスキルが$N1上昇します。この効果は種族ボーナスや他の指輪のルーンとは重複しません。", nil, 0x422d6569, nil, "um" },
  [453691] = { "指輪にFist Weapon Specializationのルーンを刻みます：\n\n$I1\nFist Weapons (Unarmed)のスキルが$N1上昇します。この効果は種族ボーナスや他の指輪のルーンとは重複しません。", nil, 0xba06bcf2, nil, "um" },
  [453692] = { "指輪にRanged Weapon Specializationのルーンを刻みます：\n\n$I1\nBows、Guns、Crossbows、Thrown武器のスキルが$N1上昇します。この効果は種族ボーナスや他の指輪のルーンとは重複しません。", nil, 0x139ba8eb, nil, "um" },
  [453694] = { "指輪にPole Weapon Specializationのルーンを刻みます：\n\n$I1\nStavesとPolearmsのスキルが$N1上昇します。この効果は種族ボーナスや他の指輪のルーンとは重複しません。", nil, 0x78d36c53, nil, "um" },
  [453695] = { "指輪にArcane Specializationのルーンを刻みます：\n\n$I1\n呪文の命中率が$N1%上昇します。他の指輪のルーンとは重複しません。", nil, 0xf9b5ffe6, nil, "um" },
  [453696] = { "指輪にFire Specializationのルーンを刻みます：\n\n$I1\n呪文の命中率が$N1%上昇します。他の指輪のルーンとは重複しません。", nil, 0x8e19242b, nil, "um" },
  [453697] = { "指輪にFrost Specializationのルーンを刻みます：\n\n$I1\n呪文の命中率が$N1%上昇します。他の指輪のルーンとは重複しません。", nil, 0x7c83ee46, nil, "um" },
  [453698] = { "指輪にNature Specializationのルーンを刻みます：\n\n$I1\n呪文の命中率が$N1%上昇します。他の指輪のルーンとは重複しません。", nil, 0x916cd76f, nil, "um" },
  [453700] = { "指輪にShadow Specializationのルーンを刻みます：\n\n$I1\n呪文の命中率が$N1%上昇します。他の指輪のルーンとは重複しません。", nil, 0x54313767, nil, "um" },
  [453702] = { "指輪にHoly Specializationのルーンを刻みます：\n\n$I1\n呪文の命中率が$N1%上昇します。他の指輪のルーンとは重複しません。", nil, 0x363fe6df, nil, "um" },
  [453703] = { "指輪にFeral Combat Specializationのルーンを刻みます：\n\n$I1\nFeral Combatのスキルが$N1上昇します。他の指輪のルーンとは重複しません。", nil, 0x7e65f7a7, nil, "um" },
})
