-- GENERATED by `wfj generate` from data/spell/spell-0348.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [348005] = { "$D2の間、$D1ごとに敵にNatureダメージを与えます。", "$D1ごとにNatureダメージを受けています。", 0x05ece599, 0xaf62b13e, "uu" },
  [348191] = { "毎秒$N1のfrostダメージを与えます。", "毎秒$N1のFrostダメージを受けます。", 0xeb1e7372, 0xeb1e7372, "uu" },
  [348789] = { "反マナの矢で敵を撃ちます。矢が消費したマナ一ポイントごとに、対象は$N1のダメージを受けます。", nil, 0x5ae7b2cb, nil, "um" },
})
