-- GENERATED by `wfj generate` from data/spell/spell-0434.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [434350] = { "Soft Soilに植えます。", nil, 0x80726cbb, nil, "um" },
  [434488] = { "$D1の間、近接攻撃が追加で7のFireダメージを与えます。", "近接攻撃が$N1の追加Fireダメージを与えます。", 0x26bc0e67, 0xb466b071, "uu" },
  [434495] = { "マウントをもっとお祭りらしい姿に変えます。", nil, 0x3ce08c15, nil, "um" },
  [434503] = { "Divine Prayer Beadを三つ組み合わせてロザリオを作ります。", nil, 0x16a8fa04, nil, "um" },
  [434508] = { "騎乗できるトナカイを呼び出し、または帰します。", "地上での移動速度が$N1%上昇します。", 0x031d184a, 0x2195529a, "uu" },
  [434752] = { "パーティーメンバーのもとへテレポートします。自分と対象の両方が宿屋か都市で休息している必要があります。", nil, 0xce3c6cf9, nil, "um" },
  [434754] = { "対象をOdd Melonに変身させます。", nil, 0xa08bd2d0, nil, "um" },
  [434814] = { "Tears of Theradrasと混ぜて、穢れを浄化できるElemental Salveを作ります。", nil, 0x647be6a7, nil, "um" },
  [434827] = { "穢れた物体に注いで浄化します。", nil, 0xb5f96daa, nil, "um" },
  [434837] = { "対象のarmorを貫き、$N1低下させます。", "Armorが$N1低下しています。", 0x12ac7561, 0x57b604c7, "uu" },
  [434839] = { "雷の粒を放出し、$N1のNatureダメージを与えます。", nil, 0x461c0247, nil, "um" },
  [434841] = { "秘術のエネルギーの爆発を放って$N1のArcaneダメージを与え、$D1の間、すべての耐性を$N2低下させ、受ける呪文ダメージをすべて$N3%増加させます。レベル45以下の敵にのみ効果があります。", "すべての耐性が$N1低下します。受ける呪文ダメージが$N2%増加します。", 0x2a22da8c, 0x7c55cc90, "uu" },
  [434842] = { "対象に$N1のNatureダメージを与えます。", nil, 0x37bddcc4, nil, "um" },
  [434851] = { "manaを回復します。", nil, 0x7569fc8c, nil, "um" },
  [434957] = { "珍しい虫を捕まえ、標本として保管します。", nil, 0x7c522522, nil, "um" },
  [434994] = { "Void Prismの近くで、Conjuror's Pendant 10個とSoul of the Voidを組み合わせます。", nil, 0x29d652dc, nil, "um" },
})
