-- GENERATED by `wfj generate` from data/spell/spell-1315.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [1315190] = { "短い間、戦闘で自分を守るBlack Dragon Whelpを呼び出します。", nil, 0x06da34e8, nil, "um" },
  [1315212] = { "緋色の炎に身を焼かれ、ホームに設定した場所へ戻ります。別の場所のInnkeeperに話しかけると、ホームの場所を変更できます。", nil, 0x379cab26, nil, "um" },
  [1315213] = { "Scarlet Hearthstoneを作成します。", nil, 0x27ea7a0d, nil, "um" },
  [1315267] = { "Right ClickでTallstrider Hatchlingを召喚、または解放します。", nil, 0x097b71e8, nil, "um" },
  [1315339] = { "夜間、知力が$N1増加します。", nil, 0xeb59d09c, nil, "um" },
  [1315451] = { "Right Clickでクロコリスクの赤ちゃんを召喚、または解放します。", nil, 0x14ea2ea0, nil, "um" },
  [1315557] = { "対象を魅了し、最大$D1の間、あらゆる行動をできなくします。ダメージを与えると効果は解除されます。Humanoidsにのみ有効です。", "魅了されています。", 0xaea65fef, 0xd83f67a3, "uu" },
  [1315767] = { "$D1の間、敵の対象の攻撃力を$N1低下させます。", "攻撃力が$N1低下しています。", 0xa38f5bbf, 0x3ac72513, "uu" },
  [1315778] = { "Winterspringで騎乗時の速度を$N1%上昇させます。", "騎乗中、移動速度 Increased：$N1%上昇しています。", 0x3faa9fa8, 0x122f2fc0, "uu" },
  [1315844] = { "$D1の間、Dodgeの確率を$N1%上昇させます。", "Dodge率が$N1%上昇します。", 0xa3828625, 0xdb1261dc, "uu" },
  [1315849] = { "骨を割り、自分を$N1、最も近くにいる味方を$N2回復します。", nil, 0x02d768f2, nil, "um" },
  [1315878] = { "$D1の間、敏捷性を$N1得ます。近くにエレメンタルがいる場合は、さらに$N3得ます。", "敏捷性が$N1増加します。", 0x79bffe8e, 0xabb77171, "uu" },
  [1315969] = { "呪文がMagical Resistancesを$N1貫通します。ForestとGrasslandの地域では、Spell Piercingがさらに$N2増加します。", nil, 0x1657413d, nil, "um" },
  [1315971] = { nil, "ForestまたはGrasslandの地域では、Spell Piercingがさらに$N1上昇します。", nil, 0x4e10bc74, "mu" },
  [1315972] = { "対象と自分を$D1スタンさせます。Ogresは$D2の間Stunned状態になり、クールダウンの$N3%が返還されます。", "スタンしています。", 0xb6db8b9d, 0x27f95286, "uu" },
  [1315989] = { "すべてのResistancesを$N1増加させます。ForestとGrasslandの地域では、すべてのResistancesがさらに$N2増加します。", nil, 0xf00683c4, nil, "um" },
  [1315990] = { nil, "ForestまたはGrasslandの地域では、すべてのResistancesがさらに$N1上昇します。", nil, 0x7c8354af, "mu" },
})
