-- GENERATED by `wfj generate` from data/spell/spell-1236.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [1236151] = { "$D1かけて対象のダメージを$N1回復します。", nil, 0x582e0822, nil, "um" },
  [1236156] = { "対象の魔法を解除し、味方からは有害な呪文を$N1個、敵からは有益な呪文を$N2個取り除きます。", nil, 0xf935d550, nil, "um" },
  [1236177] = { "敵を痛めつけ、$N1のダメージを与え、$D1の間移動速度を$N2%低下させます。", nil, 0x99e679bf, nil, "um" },
})
