-- GENERATED by `wfj generate` from data/spell/spell-0405.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [405092] = { "水中での呼吸時間が$N1%短くなります。", "息が苦しくなっています。水中での呼吸時間が$N1%短縮されます。", 0xbc9ab497, 0x71bf4264, "uu" },
  [405325] = { "印のついた場所に埋められた隠し物を掘り出します。", nil, 0x9cbb9257, nil, "um" },
  [405663] = { nil, "周囲のエレメンタルのエネルギーに守られています。", nil, 0xbe4f2e9b, "mu" },
  [405667] = { "アイテムを作成", nil, 0x78c2a138, nil, "um" },
  [405688] = { nil, "水中の急流によって移動速度が上昇しています。", nil, 0x8cfc822e, "mu" },
  [405953] = { nil, "$N2秒ごとに$N1のダメージを受けます。", nil, 0xef5a123f, "mu" },
})
