-- GENERATED by `wfj generate` from data/spell/spell-1257.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [1257010] = { "最近ぶん殴られた！", "最近ひっぱたかれました！", 0xa94a10a8, 0xa94a10a8, "uu" },
  [1257860] = { "Shadowgale Forestの上空を飛ぶManticoresを1体撃ち落とそうと試みます。", "ダウンしました！", 0x79e1f292, 0x458c090d, "uu" },
})
