-- GENERATED by `wfj generate` from data/spell/spell-1296.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [1296017] = { "未翻訳の巻物を解読します。", nil, 0x2551fb8b, nil, "um" },
  [1296202] = { "忠実なネズミの使い魔を$D1の間召喚します。使い魔がいる間、Intellectが$N2増加します。", "使い魔によってIntellectが$N1増加しています。", 0x8ee19c09, 0xbba5b326, "uu" },
  [1296225] = { "$N1時間、短剣に魔力を込め、攻撃が命中したときに時々敵を凍えさせるようにします。", nil, 0x208d06bd, nil, "um" },
  [1296534] = { "乗り物となるForsaken Chargerを召喚します。", "地上での移動速度が$N1%上昇します。", 0xcdd5e565, 0x2195529a, "uu" },
  [1296564] = { "対象のアンデッドを$D1スタンさせます。", "スタンしています。", 0xb0010e46, 0x27f95286, "uu" },
  [1296664] = { "対象のFurbolgを$D1の間魅了します。戦闘中でない対象にのみ有効です。", "魅了されています。", 0xea87f6cd, 0xd83f67a3, "uu" },
  [1296730] = { "対象にBlunderflameを浴びせ、$N1のFireダメージを与えます。", nil, 0xa0efa886, nil, "um" },
})
