-- GENERATED by `wfj generate` from data/spell/spell-1305.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [1305116] = { "緩く縛った墓の塵の袋をGreat Seaに投げ込みます。", nil, 0xce53b4dd, nil, "um" },
  [1305394] = { "致命傷を負わせ、$N1のPhysicalダメージを与えます。体力が$N3%未満の対象には$N2%増加したダメージを与えます。", nil, 0xbbacb806, nil, "um" },
  [1305398] = { "敵に影の矢を放ち、$N1のShadowダメージを与えます。", nil, 0xeeaaaf00, nil, "um" },
  [1305400] = { "難しい錠を開けます。", nil, 0x66957a86, nil, "um" },
  [1305416] = { "そっくりな分身で敵を欺き、$D1の間、近くのクリーチャーにそれを攻撃させます。", nil, 0x96d3cac5, nil, "um" },
  [1305424] = { "経験値を得られるDragonkinを倒すと、マナが$N1回復します。この効果は$N2秒に一度までしか発生しません。", nil, 0xa1ad9f9e, nil, "um" },
  [1305732] = { "回復呪文に、$D1の間、戦闘で自分を守るOnyxia Whelplingを呼び出す確率が付きます。", nil, 0x9d00a5a6, nil, "um" },
})
