-- GENERATED by `wfj generate` from data/spell/spell-0032.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [32309] = { "敵に毒を放ってNatureダメージを与え、さらに$D2の間、$D1ごとに追加のダメージを与えます。", "$D1ごとにNatureダメージを受けています。", 0x2c66ca3a, 0xaae6fcde, "uu" },
})
