-- GENERATED by `wfj generate` from data/spell/spell-1237.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [1237064] = { "弓または銃に永続的なスコープを取り付け、命中率を$N1%上昇させます。", nil, 0xb1a50f38, nil, "um" },
  [1237147] = { "近くのBallistaにIncendiary Bombを投げつけます。", nil, 0xeab64aa3, nil, "um" },
  [1237152] = { "武器にShadowの力を宿し、呪文の加速を$N1%、Shadow呪文によるダメージを最大$N2増加させます。", nil, 0x241d178a, nil, "um" },
  [1237156] = { "武器にShadowの力を宿し、呪文の加速を$N1%、Shadow呪文によるダメージを最大$N2増加させます。", nil, 0x3e70da97, nil, "um" },
  [1237159] = { "武器にShadowの力を宿し、呪文の加速を$N1%、Shadow呪文によるダメージを最大$N2増加させます。", nil, 0xcb9abc1b, nil, "um" },
  [1237268] = { "Consecration、Holy Wrath、Exorcism、Hammer of Wrathの呪文のmanaコストを$N1%減少させます。", nil, 0x78bd0c76, nil, "um" },
  [1237312] = { "敵にフロストファイアの矢を放ち、$N1のFrostfireダメージを与え、移動速度を$N2%低下させ、さらに$D1かけて$N3のFrostfireダメージを与えます。この呪文は対象のFrostとFireの耐性のうち低いほうで判定され、FrostとFireの両方のダメージとして扱われます。", "移動速度が$N1%低下しています。$N3秒ごとに$N2のFrostfireダメージを受けます。", 0xff979685, 0x3991e2af, "uu" },
  [1237313] = { "敵にフロストファイアの矢を放ち、$N1のFrostfireダメージを与え、移動速度を$N2%低下させ、さらに$D1かけて$N3のFrostfireダメージを与えます。この呪文は対象のFrostとFireの耐性のうち低いほうで判定され、FrostとFireの両方のダメージとして扱われます。", "移動速度が$N1%低下しています。$N3秒ごとに$N2のFrostfireダメージを受けます。", 0xff979685, 0x3991e2af, "uu" },
  [1237632] = { "$D1の間、軍馬に飛び乗り、移動速度を$N2%上昇させます。屋内や戦闘中でも使用できます。", "地上での移動速度が$N1%上昇します。", 0xa161a9f6, 0x2195529a, "uu" },
  [1237948] = { "死んだプレイヤーをhealth $N1、mana $N2の状態で蘇生させます。戦闘中は使用できません。", nil, 0xf0621701, nil, "um" },
  [1237949] = { "死んだプレイヤーをhealth $N1、mana $N2の状態で蘇生させます。戦闘中は使用できません。", nil, 0xf0621701, nil, "um" },
  [1237950] = { "死んだプレイヤーをhealth $N1、mana $N2の状態で蘇生させます。戦闘中は使用できません。", nil, 0xf0621701, nil, "um" },
  [1237951] = { "死んだプレイヤーをhealth $N1、mana $N2の状態で蘇生させます。戦闘中は使用できません。", nil, 0xf0621701, nil, "um" },
})
