-- GENERATED by `wfj generate` from data/spell/spell-1283.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [1283082] = { nil, "猪の肉でお腹がいっぱいです。", nil, 0x024a1c6e, "mu" },
  [1283101] = { nil, "猪の肉を食べすぎて叱られました。", nil, 0x05d58342, "mu" },
  [1283133] = { "弱らせたTwilight's Thrallを捕らえます。弱った敵にのみ有効です。", nil, 0xa33005e4, nil, "um" },
  [1283137] = { "餌を置いて海の怪物をおびき寄せます。", nil, 0xc2f265f5, nil, "um" },
  [1283391] = { nil, "どこか近くから、キャンプファイアの心地よい煙が漂ってきます。", nil, 0x9f6c6ac9, "mu" },
  [1283400] = { "Journeyman Campfireを製作します。", nil, 0xd3ced4e9, nil, "um" },
  [1283620] = { "指定した場所にProjected TextureのあるArea Triggerを作成します。永遠に、またはワールドを離れるまでのどちらか早いほうまで持続します。", nil, 0x1cbd6e8d, nil, "um" },
  [1283701] = { nil, "Arcane Salvagerの近くで過ごしたため、Disenchantingが強化されています。Arcane Salvagerの近くにいる間、分解で追加の素材が出る確率が上昇します。", nil, 0xdf677a13, "mu" },
  [1283919] = { "Tainted Foothillsのウォーロックの野営地に潜入できるよう、Jeremanが用意した「説得力のある」変装です。怪しい行動をとると変装が解けます。", "Ashen Reignの一員に変装しています。怪しい行動をとると変装が解けます。", 0x206392d8, 0xb9ac729c, "uu" },
  [1283932] = { "Right ClickでDiabloを召喚、または解放します。", nil, 0xf1cae78a, nil, "um" },
})
