-- GENERATED by `wfj generate` from data/spell/spell-1271.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [1271049] = { "$D1の間、進む方向を操作しながら空中を滑空して降下します。", "空中を滑空しています。", 0x0e9703cc, 0x795ecb87, "uu" },
  [1271103] = { "Vuldren Alphaを10分間あなたの仲間にするための調教を開始します。何らかの理由で獣の注意がそれると、調教は失敗します。", "Vuldrenを調教中です。", 0x266224f5, 0xf8f1a693, "uu" },
  [1271266] = { "最大$D1の間、使用者をステルスフィールドで包みます。戦闘中は使用できません。移動した後も、フィールドは最大$N2秒間持続します。", "隠密状態です。", 0x5c7a2b92, 0x150ed465, "uu" },
  [1271421] = { "不要なCraftsman's Writを書き直し、同じ等級のランダムな令状にします。", nil, 0x03dc560a, nil, "um" },
  [1271422] = { "不要なCraftsman's Writの内容を書き直し、Journeymanスキルの別の令状にします。", nil, 0xc5f5c3b3, nil, "um" },
  [1271423] = { "不要なCraftsman's Writの内容を書き直し、Expertスキルの別の令状にします。", nil, 0x82d40683, nil, "um" },
  [1271485] = { "近くの死体から戦利品を回収します。", nil, 0xeb0158d6, nil, "um" },
})
