-- GENERATED by `wfj generate` from data/spell/spell-0422.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [422171] = { "対象におやつを与えます。", nil, 0x553028f9, nil, "um" },
  [422387] = { "Plant Pumpkin Seeds", nil, 0xf05f36d2, nil, "um" },
  [422397] = { "対象に銛を投げます（射程$N1ヤード）", "最大体力と与えるダメージが大幅に減少しています。", 0x7b4e6704, 0x09814f56, "uu" },
  [422477] = { "余ったリーパーの部品とエレメンタルコアを組み合わせて、試作エンジンを作ります。", nil, 0x9e0358e6, nil, "um" },
  [422478] = { "ハーベストリーパーの試作機に取り付けます。", nil, 0x8cfaa23c, nil, "um" },
  [422488] = { "コヨーテの住処の近くに餌として置いてください", nil, 0x80f8c7e8, nil, "um" },
  [422746] = { nil, "倒したMurlocの魂を集められることがあります", nil, 0x1eb9c3c0, "mu" },
  [422996] = { "対象に古代の腐食性の毒を浴びせ、$D2の間、3秒ごとに$N1のNatureダメージを与え、対象のアーマーを$N3低下させます。", "アーマーが低下し、定期的にNatureダメージを受けます。", 0x79ecb000, 0x8a10a16c, "uu" },
})
