-- GENERATED by `wfj generate` from data/spell/spell-0330.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [330659] = { "Right Clickでパンダの子を呼び出したり帰したりします。", nil, 0x3bbaa8c6, nil, "um" },
})
