-- GENERATED by `wfj generate` from data/spell/spell-1216.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [1216026] = { "Blood-Caked Silver Coin 100枚をBlood-Caked Gold Coin 1枚に変換します。", nil, 0xb6a23357, nil, "um" },
  [1216027] = { "Blood-Caked Copper Coin 100枚をBlood-Caked Silver Coin 1枚に変換します。", nil, 0xfaa9213f, nil, "um" },
  [1216968] = { "戦闘中に攻撃を受けると、$N1%の確率で攻撃者に$N2のNatureダメージを与えます。", nil, 0xfb53f46d, nil, "um" },
  [1216997] = { "プレイヤーとそのペットから受けるすべてのダメージを$N1%減少させます。この効果は複数の効果源から重ねられません。", "プレイヤーとそのペットから受けるすべてのダメージが$N1%減少します。この効果は複数の効果源から重複しません。", 0x115db1dc, 0x115db1dc, "uu" },
})
