-- GENERATED by `wfj generate` from data/spell/spell-1278.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [1278028] = { "Gray Forest Wolfを手なずけ始め、$N1分間の仲間にします。何らかの理由で獣の注意がそれると、手なずけは失敗します。", "狼を調教中", 0x3e06b47d, 0xc47d033f, "uu" },
  [1278029] = { "Young Forest Bearを手なずけ始め、$N1分間の仲間にします。何らかの理由で獣の注意がそれると、手なずけは失敗します。", "熊を調教中", 0x5a218b31, 0xc1aa0199, "uu" },
  [1278062] = { "薬草採集家が野営地に設備を追加できるようになります。", nil, 0xe8b19224, nil, "um" },
  [1278067] = { "釣り人が野営地に設備を追加できるようになります。", nil, 0xdef21ef0, nil, "um" },
  [1278068] = { "皮はぎ職人が野営地に設備を追加できるようになります。", nil, 0xe4b31057, nil, "um" },
  [1278974] = { "右クリックで、Mount HyjalのUntainted Waterの水源からTharian's Vialに水を満たします。", nil, 0x31dc389a, nil, "um" },
})
