-- GENERATED by `wfj generate` from data/spell/spell-0438.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [438040] = { "対象にたまっているコンボポイントをすべて取り除き、最大$D1の間、蓄えておきます。蓄えたコンボポイントは、次に近接または遠隔のアビリティを命中させたプレイヤー以外の敵に移ります。", "コンボポイントは、このローグのアビリティが次に命中した目標に移されます。", 0xf772f571, 0xbc40dcd4, "uu" },
  [438105] = { "名誉を250獲得します。", nil, 0x17231a3c, nil, "um" },
  [438273] = { "移動を妨げる効果と、キャラクターの操作を失わせる効果をすべて解除します。", nil, 0x5922de69, nil, "um" },
  [438295] = { nil, "Dark Ridersの存在を感じ取ることができます。", nil, 0xcf6ec8c9, "mu" },
  [438305] = { "近くにいるDark Riderに姿を現させます。", nil, 0x4b0eba5c, nil, "um" },
})
