-- GENERATED by `wfj generate` from data/spell/spell-0431.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [431447] = { "頭部にGoreのルーンを刻みます：\n\n$I1\nLacerate、Swipe、Maulで対象を攻撃すると、$N1%の確率でMangle (Bear)のクールダウンがリセットされ、怒りを$N2得ます。Mangle (Cat)またはShredで対象を攻撃すると、$N3%の確率でTiger's Furyのクールダウンがリセットされます。", nil, 0x744cbcf4, nil, "um" },
  [431449] = { "頭部にImproved Barkskinのルーンを刻みます：\n\n$I1\nBarkskinを味方にも使用できるようになり、近接攻撃速度や詠唱時間へのペナルティがなくなり、変身中でも使用できるようになります。", nil, 0x313924c7, nil, "um" },
  [431451] = { "頭部にGale Windsのルーンを刻みます：\n\n$I1\nHurricaneのダメージが$N1%増加し、クールダウンがなくなり、マナコストが$N2%減少します。", nil, 0x1daa8dad, nil, "um" },
  [431461] = { "手首にImproved Frenzied Regenerationのルーンを刻みます：\n\n$I1\nFrenzied Regenerationが、Moonkin Formと変身していない状態を除くすべての形態で使用できるようになります。$D1の間、毎秒、現在のリソースを体力に変換するようになります。毎秒、最大で怒り $N2、エネルギー $N3、または基本マナの$N4%が、最大$N5%の体力に変換されます。", nil, 0x7c8d070b, nil, "um" },
  [431468] = { "手首にEfflorescenceのルーンを刻みます：\n\n$I1\nSwiftmendがEfflorescenceも発生させるようになり、Swiftmendの対象の位置から$N1ヤード以内のパーティーメンバー全員を、$D2の間$D1ごとに$N2回復します。", nil, 0x666a61dd, nil, "um" },
  [431601] = { "手首にFocus Fireのルーンを刻みます：\n\n$I1\nペットのFrenzyをすべて消費し、消費したFrenzyごとに、遠隔攻撃速度を$N1%上昇させ、ペットにFocusを$N2与えます。効果時間は$D1です。\n\nペットはBasic Attackを使うたびにFrenzyを得て、$D2の間、近接攻撃速度が$N4%上昇します。最大$N6回までスタックします。", nil, 0x402ff8e0, nil, "um" },
  [431611] = { "手首にT.N.T.のルーンを刻みます：\n\n$I1\nExplosive Shotとすべてのダメージ系の罠のダメージを$N1%増加させます。さらに、Explosive Trapの初期ダメージとImmolation Trapの持続ダメージの合計が、近接または遠隔Attack Powerの$N2%分増加します。", nil, 0xfc51a099, nil, "um" },
  [431622] = { "クリティカルの回復が対象に防御シールドを生み、回復量の$N1%を吸収します。効果時間は$D1です。", nil, 0xe1756dde, nil, "um" },
  [431650] = { "頭部にDivine Aegisのルーンを刻みます：\n\n$I1\nクリティカル回復により対象に防護シールドが生まれ、回復量の$N1%を吸収します。効果時間は$D1です。", nil, 0xc4df145c, nil, "um" },
  [431655] = { "対象に$N1のShadowfrostダメージを与え、その対象への次のMind Blastのクリティカル率を$N2%上昇させます。最大$N3回までスタックします。", "詠唱したプリーストのMind Blastのクリティカル率が$N1%上昇します。", 0x6285d513, 0x7e49ce65, "uu" },
  [431663] = { "ベルトにMind Spikeのルーンを刻みます：\n\n$I1\n対象を撃ち、$N1のShadowfrostダメージを与え、対象への次のMind Blastのクリティカル率を$N2%上昇させます。最大$N3回までスタックします。", nil, 0xe3ddcdbb, nil, "um" },
  [431669] = { "手首にSurge of Lightのルーンを刻みます：\n\n$I1\n呪文がクリティカルになると、$D1以内に詠唱する次のSmiteまたはFlash Healが即時詠唱になります。", nil, 0x456d61d2, nil, "um" },
  [431673] = { "手首にDespairのルーンを刻みます：\n\n$I1\n呪文による持続ダメージがクリティカルになるようになり、ダメージ呪文のクリティカルはすべて$N1%のダメージを与えます。", nil, 0xc08da534, nil, "um" },
  [431705] = { "手首にVoid Zoneのルーンを刻みます：\n\n$I1\n対象範囲にヴォイドゾーンを召喚し、$D1の間、その中にいる敵に毎秒$N1のShadowダメージを与えます。", nil, 0xde4479c0, nil, "um" },
  [431743] = { "頭部にPandemicのルーンを刻みます：\n\n$I1\nCorruption、Bane of Agony、Bane of Doom、Drain Soul、Drain Life、Siphon Life、Wrackのクリティカルダメージボーナスが$N1%増加します。", nil, 0xfc32fa36, nil, "um" },
  [431745] = { "頭部にBackdraftのルーンを刻みます：\n\n$I1\nConflagrateが、$D1の間、呪文の詠唱速度を$N1%上昇させるようになり、Immolateを消費しなくなります。", nil, 0x85225ee1, nil, "um" },
  [431747] = { "手首にUnstable Afflictionのルーンを刻みます：\n\n$I1\nShadowのエネルギーが対象をゆっくりと蝕み、$D1かけて$N1のダメージを与えます。さらに、Unstable Afflictionが解呪されると、解呪した者に$N3のダメージを与え、$D2の間沈黙させます。一つの対象に対して、ウォーロックごとに有効にできるUnstable AfflictionまたはImmolateは一つだけです。", nil, 0xfe30632b, nil, "um" },
  [431756] = { "手首にSummon Felguardのルーンを刻みます：\n\n$I1\nウォーロックの指揮下にあるFelguardを召喚します。\n\nFelguardは、他の悪魔の手下に発動する、または恩恵を与えるすべてのタレントと効果の恩恵を受けます。", nil, 0x2f46ea21, nil, "um" },
  [431758] = { "手首にImmolation Auraのルーンを刻みます：\n\n$I1\n敵が近接攻撃をしてくるたびに、近くの敵を焼いて$N1のダメージを与え（毎秒一回まで）、受ける魔法ダメージをすべて$N2%軽減し、与えるFireダメージを$N3%増加させます。効果時間は$D1です。", nil, 0xb234c15a, nil, "um" },
})
