-- GENERATED by `wfj generate` from data/spell/spell-1256.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [1256151] = { "右クリックでWimdyを召喚・解除します。", nil, 0x96d3031f, nil, "um" },
})
