-- GENERATED by `wfj generate` from data/spell/spell-0420.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [420493] = { nil, "ひらめきに満ちています。", nil, 0x12978998, "mu" },
  [420667] = { nil, "Hordeの旗を運んでいます。\n（死亡すると落とします）", nil, 0x15efcfe1, "mu" },
  [420794] = { "Comprehension Charmで呪文のメモを解読し、新しいEngraving呪文を習得します。", nil, 0x7ccaad21, nil, "um" },
  [420799] = { nil, "ひらめきに満ちています。", nil, 0x12978998, "mu" },
  [420877] = { nil, "救世主のために手は開かれるだろう", nil, 0x22a2e274, "mu" },
  [420878] = { nil, "手はあなたのために開かれた", nil, 0x667ff165, "mu" },
  [420964] = { "対象に銛を投げます（射程$N1ヤード）", "最大healthと与えるダメージが大幅に減少しています。", 0x7b4e6704, 0x09814f56, "uu" },
  [420998] = { "近くのパーティメンバーを攻撃したクリーチャーに$N1のHolyダメージを与えます。プレイヤーが同時に受けられるオーラは、パラディン一人につき一つだけです。オーラは解除するまで持続します。", "近接攻撃をしてきた相手に$N1のHolyダメージを与えます。", 0xb2ca9267, 0x210150aa, "uu" },
})
