-- GENERATED by `wfj generate` from data/spell/spell-1261.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [1261692] = { "倒れたKhanを蘇らせます。", "蘇生されています。", 0x941c111c, 0x3e242633, "uu" },
})
