-- GENERATED by `wfj generate` from data/spell/spell-1258.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [1258483] = { "Index Esoteriaを起動し、Shen'dar HighlandsのOverlook Standing Stonesで魔法のデータを収集します。", nil, 0xd78474f5, nil, "um" },
  [1258773] = { "Westfallの農場の井戸から水のサンプルを採取します。", nil, 0x345ca815, nil, "um" },
  [1258812] = { "Orgrul's Skeletonsに死霊術のエネルギーを注入しようと試みます。", nil, 0xbb88d223, nil, "um" },
  [1258822] = { "Deadminesの鋳造所のそばに爆薬を設置します。", nil, 0xc291176b, nil, "um" },
})
