-- GENERATED by `wfj generate` from data/spell/spell-1275.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [1275511] = { nil, "ひどい傷から血を流し続けています。", nil, 0xd1b3d02b, "mu" },
  [1275553] = { nil, "炎は時間とともに勢いを増しています。", nil, 0x2f1206c7, "mu" },
  [1275832] = { nil, "あなたはいるべきではない場所にいます……", nil, 0x0b90d906, "mu" },
  [1275865] = { nil, "あなたはいるべきではない場所にいます……", nil, 0x0b90d906, "mu" },
})
