-- GENERATED by `wfj generate` from data/spell/spell-0463.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [463005] = { "騎乗用の機械仕掛けのtallstriderを呼び出したり戻したりします。", "地上での移動速度が$N1%上昇します。", 0x58925d99, 0x2195529a, "uu" },
  [463006] = { "騎乗用のGolden Saber Catを呼び出したり戻したりします。", "地上での移動速度が$N1%上昇します。", 0x3745fb1e, 0x2195529a, "uu" },
  [463007] = { "騎乗できるRaptorを呼び出し、または帰します。", "地上での移動速度が$N1%上昇します。", 0x7d1c7f75, 0x2195529a, "uu" },
  [463008] = { "Eye of ShadowとEye of Divinityと組み合わせると、Benedictionになります。", nil, 0x449c37a0, nil, "um" },
  [463105] = { "発動中、$D1の間、使用者に防御$N1とアーマー $N2を付与します。", "アーマーが$N1増加しています。\nDefenseが$N2上昇しています。", 0x275cde53, 0xf094e7b1, "uu" },
  [463146] = { "Crusader Strike呪文を使うと、次のConsecration呪文のコストが$N1%減少します。", nil, 0x48dc6691, nil, "um" },
  [463448] = { "近くの敵にFrostダメージを与え、最大$D1の間、動けなくします。", "移動できません。", 0x1eb0ef79, 0x18deeb81, "uu" },
  [463556] = { "Copper Slaughter Coin 100枚をSilver Slaughter Coin 1枚に変換します。", nil, 0xd353ba95, nil, "um" },
  [463564] = { "$D1の間、盾のブロック値を$N1上昇させます。", "ブロック値が$N1上昇しています。", 0xe7882b6e, 0x64e8286f, "uu" },
  [463864] = { "Flowing Watersの魔法の印章を得て、$D1の間、レイドの呪文による与えるダメージと回復量を最大$N1増加させ、攻撃力を$N2増加させます。", "Flowing Watersの力を得ています。呪文によるダメージと治療量が最大$N1増加し、攻撃力が$N2上昇しています。", 0xdd734e9a, 0x36595d1e, "uu" },
  [463868] = { "対象の盾に塗布している間、呪文ダメージと回復量が最大24増加します。効果時間は30分です。", nil, 0xec9710d4, nil, "um" },
  [463869] = { "Conductive Shield Coatingを作成します。", nil, 0x7b4089f9, nil, "um" },
  [463871] = { "Shieldに永続的なエンチャントを施し、呪文のダメージを最大30、回復呪文の回復量を最大55増加させます。", nil, 0x260ff875, nil, "um" },
  [463946] = { "最大$N1体の対象に$N2のNatureダメージを与えます。", nil, 0xd382b11f, nil, "um" },
})
