-- GENERATED by `wfj generate` from data/spell/spell-0064.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [64659] = { "Venomhide Ravasaurを召喚/帰還します。", "地上での移動速度が$N1%上昇します。", 0x45a041db, 0x2195529a, "uu" },
})
