-- GENERATED by `wfj generate` from data/spell/spell-0465.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [465412] = { "近接攻撃に$N1の聖なるダメージを追加します。", nil, 0x5d5a7f1a, nil, "um" },
  [465414] = { "$D1の間、与えるダメージを$N1、攻撃速度を$N2%増加させます。", "近接ダメージと攻撃速度が上昇しています。", 0x1e1de541, 0x7fac8986, "uu" },
  [465417] = { "戦闘の構えを変え、Truthbearerを片手半剣として扱い、盾と一緒に使えるようにします。", nil, 0xf7d921bf, nil, "um" },
  [465418] = { "戦闘の構えを変え、Truthbearerを両手剣として扱います。", nil, 0xba5cc9b2, nil, "um" },
  [465447] = { "サバイバル用の野営地の土台を築きます。この野営地に追加の物資を持ってくると、避難所を建てられます。", nil, 0xac130273, nil, "um" },
  [465675] = { "Cenarion Circleとの評判を永続的に上昇させます。", nil, 0x8f12afce, nil, "um" },
  [465787] = { "強敵が落とした、奇妙なアイテムや見落とされたアイテムに気づく確率を得ます。", "強敵が落とした、変わったアイテムや見落としがちなアイテムに気付くことがあります。", 0x1ed51d7d, 0x98b8859a, "uu" },
  [465789] = { "時の外にある場所へ旅立ちます。Tanarisにいる必要があります。", nil, 0x4361d6e8, nil, "um" },
})
