-- GENERATED by `wfj generate` from data/spell/spell-1321.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [1321320] = { "幸運のコインを水に投げ入れ、$D1の間Fishing Skillを$N1上昇させます。", nil, 0x7f1bac15, nil, "um" },
  [1321323] = { "幸運のコインを水に投げ入れ、$D1の間Fishing Skillを$N1上昇させます。", nil, 0x9943fc23, nil, "um" },
})
