-- GENERATED by `wfj generate` from data/spell/spell-0442.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [442226] = { "対象を挑発して自分を攻撃させます。ただし、対象がすでに自分を攻撃している場合は効果がありません。", nil, 0x71de38fd, nil, "um" },
  [442233] = { "対象を挑発して自分を攻撃させます。ただし、対象がすでに自分を攻撃している場合は効果がありません。", nil, 0x71de38fd, nil, "um" },
})
