-- GENERATED by `wfj generate` from data/spell/spell-0345.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [345919] = { nil, "あなたはいるべきではない場所にいます……", nil, 0x0b90d906, "mu" },
})
