-- GENERATED by `wfj generate` from data/spell/spell-0349.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [349858] = { "時の織物を変化させ、竜退治、Dire Maul、Zul'Gurub、Felwoodによる有益なワールド効果を一時停止します。", nil, 0x51f8d523, nil, "um" },
  [349863] = { "一時停止したワールド効果を元に戻します。", nil, 0x89976410, nil, "um" },
})
