-- GENERATED by `wfj generate` from data/spell/spell-1303.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [1303075] = { "騎乗できるラベンダー色のkodoを召喚、または解放します。", "地上での移動速度が$N1%上昇します。", 0x402178c5, 0x2195529a, "uu" },
  [1303215] = { "騎乗できる隊商のkodoを召喚、または解放します。", "地上での移動速度が$N1%上昇します。", 0x4c609ee3, 0x2195529a, "uu" },
  [1303317] = { "Ironforgeの旗を掲げます。", nil, 0xdbe77c86, nil, "um" },
  [1303457] = { "専門職を試すための大量の素材と、レシピや素材を購入するためのお金とトークンを提供します。", nil, 0x925578dd, nil, "um" },
  [1303509] = { "Hunter Riseの南の崖にお香をまきます。", nil, 0x55017d5c, nil, "um" },
  [1303520] = { "Bundle of Herbs、Bundle of Dried Cedar Twigs、Sinew Thread、Ceremonial Flint and Tinderを組み合わせてPrepared Incenseを作ります。", nil, 0x8e38e0e9, nil, "um" },
  [1303543] = { "野営地にScarlet Bannerを立てます。近くにCampfireが必要です。", nil, 0xc1dc1b97, nil, "um" },
  [1303853] = { "危険物を、Gadgetzanやほかのゴミから安全な距離だけ離れた場所に廃棄します。", nil, 0xed0f38eb, nil, "um" },
  [1303869] = { "負傷したSlave Workerを殴って正気に戻した後、Hearthstoneを投げ渡します。", "大胆な脱出を試みています！", 0x2d946e0d, 0x105909c3, "uu" },
})
