-- GENERATED by `wfj generate` from data/spell/spell-1257.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [1257010] = { "最近ぶん殴られた！", "最近ひっぱたかれました！", 0xa94a10a8, 0xa94a10a8, "uu" },
  [1257019] = { "どうやら怒らせてしまったようです！", "怒らせてしまったようです！", 0xdd1e491f, 0xdd1e491f, "uu" },
  [1257055] = { nil, "恐怖に陥っています。", nil, 0x5a2205f2, "mu" },
  [1257106] = { "雷の矢で敵を撃ち、矢は近くにいる別の敵へと飛び移ります。この呪文は最大$N1体の対象に作用し、次の対象ほど大きなNatureダメージを与えます。", nil, 0x245b0721, nil, "um" },
  [1257130] = { "敵を打ち据え、Holyダメージを与えます。", nil, 0x20941603, nil, "um" },
  [1257860] = { "Shadowgale Forestの上空を飛ぶManticoresを1体撃ち落とそうと試みます。", "ダウンしました！", 0x79e1f292, 0x458c090d, "uu" },
})
