-- GENERATED by `wfj generate` from data/spell/spell-0418.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [418065] = { "Summon Soboz", nil, 0x5c0f8e85, nil, "um" },
  [418236] = { "Tame Beastがウサギにも効くようになります（コンパニオンペットとして）", "Tame Beastのアビリティがウサギにも効くようになります（コンパニオンペットとして）", 0x8940a015, 0x8940a015, "uu" },
  [418347] = { "Apothecary Notesを$N1枚組み合わせて、新しいengravingのレシピを作ります。", nil, 0xe30a4cd8, nil, "um" },
  [418489] = { "大熊の巣穴の中に餌として置いてください", nil, 0x638bcf42, nil, "um" },
  [418509] = { "経験値または名誉を得られるとどめの一撃を与えると、次の攻撃が必ずクリティカルになります。", "経験値またはhonorを得られる止めの一撃を決めると、次の攻撃が必ずクリティカルになります。", 0x11413859, 0x11413859, "uu" },
  [418599] = { "印のついた場所で宝を掘り出します", nil, 0xcb9fbb49, nil, "um" },
  [418600] = { "他の$N1枚の断片と組み合わせて、完全な地図を作ります。", nil, 0xdcc7f5cf, nil, "um" },
  [418738] = { "-15 火炎耐性", "Fire耐性 -15", 0xc9e11d43, 0xc9e11d43, "uu" },
})
