-- GENERATED by `wfj generate` from data/spell/spell-0104.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [104047] = { "右クリックでLunar Lanternを呼び出したり戻したりします。", nil, 0x055ef641, nil, "um" },
  [104049] = { "右クリックでFestival Lanternを呼び出したり戻したりします。", nil, 0x44f6351d, nil, "um" },
})
