-- GENERATED by `wfj generate` from data/spell/spell-1221.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [1221309] = { "Scarlet Crusadeの記章を身に着けます。作製したScarlet Militaryセットを$N1部位、またはTabard of the Scarlet Enclaveを身に着けている間、その変装はNew Avalonの多くの十字軍兵士を欺きます。", "Scarlet Crusadeの記章を身に着けています。", 0xf7e8edf2, 0x41ef629a, "uu" },
  [1221337] = { "緊急用の隠れ場所を展開します。その近くに立っている間、ほとんどの敵はあなたに気づきにくくなります。注意深い敵は、そう簡単にはだまされないかもしれません。\n\n戦闘中は使用できません。", nil, 0x0cd5325a, nil, "um" },
  [1221379] = { "レベル$N1までの悪魔を服従させ、命令に従わせます。服従している間、悪魔の攻撃間隔は$N2%長くなり、詠唱速度は$N3%遅くなります。効果時間は最大$D1です。同じ悪魔を繰り返し服従させると、そのたびに制御が難しくなります。", nil, 0x93ce24f8, nil, "um" },
  [1221404] = { "対象範囲から$N1ヤード以内にいる、隠れている敵と透明な敵をすべてあらわにし、$D1の間、魔法の闇を寄せつけません。", "隠れているユニットと透明なユニットが見えます。", 0xdfef21a9, 0xe485f4e9, "uu" },
})
