-- GENERATED by `wfj generate` from data/spell/spell-0066.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [66842] = { "Totem Barで指定したトーテムを最大$N1個まで同時に設置します。", nil, 0x22a79ee8, nil, "um" },
  [66843] = { "Totem Barで指定したトーテムを最大$N1個まで同時に設置します。Call of the Elementsとは異なるトーテムを呼び出せます。", nil, 0x16d3fadb, nil, "um" },
  [66844] = { "Totem Barで指定したトーテムを最大$N1個まで同時に設置します。Call of the ElementsやCall of the Ancestorsとは異なるトーテムを呼び出せます。", nil, 0x6628655d, nil, "um" },
})
