-- GENERATED by `wfj generate` from data/spell/spell-1322.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [1322000] = { "攻撃が命中すると、一定の確率で$D1の間、敵が受けるFireダメージを$N1増加させます。", nil, 0x0e7c457d, nil, "um" },
  [1322001] = { "$D1の間、敵が受けるFireダメージを$N1増加させます。", "受けるFireダメージが$N1増加しています。", 0x6ca87730, 0xbe4d5e70, "uu" },
  [1322004] = { nil, "スタンしています。", nil, 0x27f95286, "mu" },
  [1322005] = { nil, "スタンしています。", nil, 0x27f95286, "mu" },
  [1322007] = { "ウォーロックの指揮下にあるVoidwalkerを召喚します。", nil, 0xe766a608, nil, "um" },
  [1322054] = { "Skeletal Servantを$N1体召喚し、解除するまで術者に同行させます。", nil, 0x2e4fdb3c, nil, "um" },
  [1322218] = { "Great Forgeの炎で対象を燃え上がらせ、$N1のHolyfireダメージを与えます。Fire ElementalとEarth Elementalには$N2倍のダメージを与えます。", nil, 0x1fe0e4bc, nil, "um" },
  [1322295] = { "対象に炎を放ち、$N1のFireダメージを与えます。", nil, 0x9d8bd0af, nil, "um" },
  [1322297] = { "$D1の間、アーマーを$N1増加させます。", "アーマーが増加しています。", 0x92291afa, 0xd44e6a60, "uu" },
  [1322299] = { "$D1の間、アーマーを$N1増加させます。", "アーマーが増加しています。", 0x92291afa, 0xd44e6a60, "uu" },
  [1322303] = { "近くにあるHumanoidまたはUndeadの死体を真っ二つに叩き切り、体力を$N1、マナを$N2、怒りを$N3回復します。", nil, 0x52063f37, nil, "um" },
  [1322304] = { "巨大な水晶の拳で殴りつけ、円錐範囲に$N1のPhysicalダメージを与え、命中したすべてのターゲットを吹き飛ばします。", nil, 0x18fcd852, nil, "um" },
  [1322305] = { "体力を$N1、マナを$N2、怒りを$N3回復します。", nil, 0x08c6a32c, nil, "um" },
  [1322311] = { "Siphon the Graveの恩恵を受けられません。", "Siphon the Graveの恩恵を受けられません。", 0x77e9d499, 0x77e9d499, "uu" },
  [1322312] = { "Cookingの速度が$N1%上昇します。", nil, 0x2371bf1d, nil, "um" },
  [1322318] = { "近接攻撃が一定の確率で$N1の追加Shadowダメージを与えます", nil, 0xc298e39c, nil, "um" },
  [1322587] = { "チーズケーキを食べると幸せになります。", "わーい、チーズケーキです！", 0x81d403b4, 0xc0088836, "uu" },
  [1322605] = { "マナ$N1を即座にエネルギー$N2に変換します。Shifting Powerのコストは、Shapeshiftingのコストを減らす効果によって減少します。", nil, 0xa7e4f4f6, nil, "um" },
  [1322670] = { "Shifting Power呪文のクールダウンを$D1短縮します。", nil, 0x9860d8d1, nil, "um" },
})
