-- GENERATED by `wfj generate` from data/spell/spell-0460.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [460228] = { "実質的なステルスレベルを2低下させます。", nil, 0x4380924e, nil, "um" },
  [460332] = { "$D1の間、Staminaを$N1上昇させ、おまけに酔っ払います！", "Staminaが$N1増加しています。\nSpiritが$N2増加しています。", 0x2fc5d66d, 0x14cf7a1b, "uu" },
  [460335] = { "近接攻撃を受けたとき、$N1%の確率で近くのすべての敵に$N2のFireダメージを与えます。", nil, 0xefd071f6, nil, "um" },
  [460338] = { "火の玉を投げつけて$N1のFireダメージを与え、対象の魂を浄化します。対象が受けるFireとHolyのダメージを最大$N2増加させ、さらに$D1かけて$N3のダメージを追加で与えます。", "受けるFireとHolyのダメージが最大$N1増加し、$N3秒ごとに$N2のFireダメージを受けています。", 0x35d5fc87, 0x28b9dedf, "uu" },
  [460339] = { "Cat、Bear、Dire Bearフォームでのみ、Attack Powerが+$N1されます。", nil, 0xa798bce2, nil, "um" },
  [460343] = { "Cat、Bear、Dire Bearフォームでのみ、Attack Powerが+$N1されます。", nil, 0xa798bce2, nil, "um" },
  [460363] = { "Arkonos the CursedにModified Shadow Scalpelの焦点を合わせ、彼の防護の障壁を解除します。", nil, 0x36062b28, nil, "um" },
  [460375] = { "Orthasの歯を……こすります。気持ち悪い。", nil, 0xb362c709, nil, "um" },
  [460455] = { "$D1の間、攻撃速度を$N1%上昇させます。レベル55より上のキャラクターには効果がありません。", "攻撃速度が上昇しています。", 0x62825f65, 0x778d86da, "uu" },
  [460462] = { "Eye of SulfurasとSulfuron Hammerを組み合わせて、Ragnarosの伝説のハンマーSulfurasを作れます。", nil, 0xb742cf90, nil, "um" },
  [460963] = { "肩スロットのアイテムにfire耐性$N1を永続的に付与します。", nil, 0xab976a01, nil, "um" },
})
