-- GENERATED by `wfj generate` from data/spell/spell-1281.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [1281641] = { "Right Clickで音楽好きのカエルの友達を召喚、または解放します。", nil, 0x1c2273ec, nil, "um" },
})
