-- GENERATED by `wfj generate` from data/spell/spell-0034.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [34433] = { "影の魔物を生み出して対象を攻撃させます。Shadowfiendが攻撃すると、術者はmanaを$N1%受け取ります。範囲攻撃から受けるダメージが減少します。効果時間は$D1です。", nil, 0x58d1a805, nil, "um" },
})
