-- GENERATED by `wfj generate` from data/spell/spell-1315.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [1315190] = { "短い間、戦闘で自分を守るBlack Dragon Whelpを呼び出します。", nil, 0x06da34e8, nil, "um" },
  [1315212] = { "緋色の炎に焼かれ、ホームに設定した場所に戻ります。別の場所のInnkeeperに話しかけると、ホームの場所を変更できます。", nil, 0x0ceecbf8, nil, "um" },
  [1315213] = { "Scarlet Hearthstoneを作成します。", nil, 0x27ea7a0d, nil, "um" },
  [1315267] = { "Right ClickでTallstrider Hatchlingを召喚、または解放します。", nil, 0x097b71e8, nil, "um" },
  [1315339] = { "夜間、知力が$N1増加します。", nil, 0xeb59d09c, nil, "um" },
  [1315451] = { "右クリックでMinfernalを召喚・解除します。", nil, 0x6d502f06, nil, "um" },
  [1315557] = { "対象を魅了し、最大$D1の間、あらゆる行動をできなくします。ダメージを与えると効果は解除されます。Humanoidsにのみ有効です。", "魅了されています。", 0xaea65fef, 0xd83f67a3, "uu" },
  [1315767] = { "$D1の間、対象の敵の攻撃力を$N1低下させます。", "攻撃力が$N1低下しています。", 0x68d8d99c, 0x3ac72513, "uu" },
  [1315778] = { "Winterspringで騎乗中の移動速度が$N1%上昇します。", "騎乗中は移動速度が$N1%増加します。", 0x46e8d69f, 0x939516e9, "uu" },
  [1315844] = { "$D1の間、Dodgeの確率を$N1%上昇させます。", "回避率が$N1%増加しています。", 0xa3828625, 0x13f65298, "uu" },
  [1315849] = { "骨を割り、自分を$N1、最も近くにいる味方を$N2回復します。", nil, 0x02d768f2, nil, "um" },
  [1315878] = { "$D1の間、敏捷性が$N1上昇します。近くにエレメンタルがいる場合は、さらに$N3上昇します。", "敏捷性が$N1増加しています。", 0xc56ec730, 0xa84d6207, "uu" },
  [1315969] = { "呪文がMagical Resistancesを$N1貫通します。ForestとGrasslandの地域では、Spell Piercingがさらに$N2増加します。", nil, 0x1657413d, nil, "um" },
  [1315971] = { nil, "ForestまたはGrasslandの地域では、Spell Piercingがさらに$N1上昇します。", nil, 0x4e10bc74, "mu" },
  [1315972] = { "対象と自分を$D1スタンさせます。Ogresは$D2の間Stunned状態になり、クールダウンの$N3%が返還されます。", "スタンしています。", 0xb6db8b9d, 0x27f95286, "uu" },
  [1315989] = { "すべてのResistancesを$N1増加させます。ForestとGrasslandの地域では、すべてのResistancesがさらに$N2増加します。", nil, 0xf00683c4, nil, "um" },
  [1315990] = { nil, "ForestまたはGrasslandの地域では、すべてのResistancesがさらに$N1上昇します。", nil, 0x7c8354af, "mu" },
})
