-- GENERATED by `wfj generate` from data/spell/spell-0404.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [404275] = { "近くの敵にFrostダメージを与え、最大$D1の間、動けなくします。", "移動できません。", 0x1eb0ef79, 0x18deeb81, "uu" },
  [404316] = { nil, "移動速度が$N1%低下しています。", nil, 0xbd9449c1, "mu" },
  [404433] = { nil, "$N2秒ごとに$N1のダメージを受け、攻撃間隔が$N3%増加します。", nil, 0x82fe525e, "mu" },
  [404806] = { nil, "不安定な水の粒子が体の周りに集まっています。", nil, 0x6a1b0a06, "mu" },
})
