-- GENERATED by `wfj generate` from data/spell/spell-0053.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [53489] = { "Judgement、Crusader Strike、Divine Stormのクリティカルダメージを$N1%増加させ、近接攻撃がクリティカルヒットしたとき、次のFlash of LightかExorcismの詠唱時間を$D1短縮します。", "次のFlash of LightまたはExorcismの詠唱時間が$D1短縮されます。", 0x49a7d7a2, 0xfa575ac0, "uu" },
  [53601] = { "対象はダメージを受けるたびにSacred Shieldを得て、$N1のダメージを吸収し、最大$D1の間、パラディンのFlash of Lightのクリティカル率を$N2%上げます。この効果は$D2に一度しか得られません。効果時間は$D3です。この呪文は同時に一つの対象にしかかけられません。", "目標はダメージを受けるたびにSacred Shieldを得て、$N1のダメージを吸収し、パラディンのFlash of Lightのクリティカル率が$N2%上昇します。この効果は$D1に一回までしか得られません。", 0x914280a6, 0x7b7dc4ce, "uu" },
  [53672] = { "Holy Shockがクリティカルヒットすると、次のFlash of Lightの詠唱時間を$D1短縮するか、次のHoly Lightのクリティカル率を$N2%上げます。", "次のFlash of Lightの詠唱時間を$D1短縮するか、次のHoly Lightのクリティカル率を$N2%上昇させます。", 0xead2e02c, 0x3cc39d75, "uu" },
})
