-- GENERATED by `wfj generate` from data/spell/spell-0167.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [167152] = { "$D1かけて体力の$N1%とマナの$N2%を回復します。飲んでいる間は座っている必要があります。", "毎秒、体力を$N1%、マナを$N2%回復します。", 0xc98bf519, 0x9c6f1892, "uu" },
})
