-- GENERATED by `wfj generate` from data/spell/spell-0058.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [58597] = { "対象はダメージを受けるたびにSacred Shieldを得て、$N1のダメージを吸収し、最大$D1の間、パラディンのFlash of Lightのクリティカル率を$N2%上げます。この効果は6秒に一度しか得られません。効果時間は$D3です。", "ダメージを吸収し、詠唱したパラディンのFlash of Lightのクリティカル率を$N1%上昇させます。", 0x56cad033, 0xc8eb5579, "uu" },
})
