-- GENERATED by `wfj generate` from data/spell/spell-1233.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [1233908] = { "自分を大砲に装填します。まあ、安全そうです。", nil, 0x03f6f963, nil, "um" },
})
