-- GENERATED by `wfj generate` from data/spell/spell-1313.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [1313342] = { "味方の対象を$N1回復します。", nil, 0xbe4c0f4a, nil, "um" },
  [1313343] = { "味方の対象を$N1回復します。", nil, 0xbe4c0f4a, nil, "um" },
  [1313344] = { "味方の対象を$N1回復します。", nil, 0xbe4c0f4a, nil, "um" },
  [1313345] = { "味方の対象を$N1回復します。", nil, 0xbe4c0f4a, nil, "um" },
  [1313346] = { "味方の対象を$N1回復します。", nil, 0xbe4c0f4a, nil, "um" },
  [1313348] = { "味方の対象を$N1回復します。", nil, 0xbe4c0f4a, nil, "um" },
  [1313349] = { "味方の対象を$N1回復します。", nil, 0xbe4c0f4a, nil, "um" },
  [1313350] = { "味方の対象を$N1回復します。", nil, 0xbe4c0f4a, nil, "um" },
  [1313351] = { "味方の対象を$N1回復します。", nil, 0xbe4c0f4a, nil, "um" },
  [1313352] = { "味方の対象を$N1回復します。", nil, 0xbe4c0f4a, nil, "um" },
  [1313374] = { "鍛冶場で鍵を溶かし、Bronze Barsを$N1本にします。", nil, 0x8a94dcd7, nil, "um" },
  [1313379] = { "ターゲットに呪文をかけ、次にダメージを受けたときにターゲットを回復します。回復が発生すると、Prayer of Mendingは$N1ヤード以内のパーティーまたはレイドのメンバーに移ります。最大$N2回移り、移るたびに$D1持続します。この呪文は一度に1体のターゲットにしかかけられません。", nil, 0xc3608d43, nil, "um" },
  [1313381] = { "ターゲットに呪文をかけ、次にダメージを受けたときにターゲットを回復します。回復が発生すると、Prayer of Mendingは$N1ヤード以内のパーティーまたはレイドのメンバーに移ります。最大$N2回移り、移るたびに$D1持続します。この呪文は一度に1体のターゲットにしかかけられません。", nil, 0xc3608d43, nil, "um" },
  [1313503] = { "敵を打ち据え、Holyダメージを与えます。", nil, 0x20941603, nil, "um" },
})
