-- GENERATED by `wfj generate` from data/spell/spell-1268.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [1268650] = { "雷の矢で敵を撃ち、矢は近くにいる別の敵へと飛び移ります。この呪文は最大$N1体の対象に作用し、次の対象ほど大きなNatureダメージを与えます。", nil, 0x245b0721, nil, "um" },
  [1268651] = { "敵を打ち据え、Holyダメージを与えます。", nil, 0x20941603, nil, "um" },
  [1268652] = { "敵を打ち据え、Holyダメージを与えます。", nil, 0x20941603, nil, "um" },
  [1268774] = { "Dread Ravenに変身し、新しい能力を使えるようになります。", "狡猾なdread ravenの姿になっています。", 0xf7079fad, 0x2b551a56, "uu" },
  [1268815] = { "獰猛なクモのWild Godの姿になり、$D1の間その能力を得ます。", "凶暴なクモの姿になっています。", 0x7640f38c, 0x2af56ca3, "uu" },
  [1268826] = { "強大な雷のトカゲの姿に$D1の間なります。", "力強いthunder lizardの姿になっています。", 0x88b719ce, 0xed224c9e, "uu" },
})
