-- GENERATED by `wfj generate` from data/spell/spell-0031.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [31016] = { "コンボポイントごとにダメージを与えるフィニッシュ技です。ダメージはAttack Powerによって増加します：\n $N1ポイント：$N2-$N3ダメージ\n $N4ポイント：$N5-$N6ダメージ\n $N7ポイント：$N8-$N9ダメージ\n $N10ポイント：$N11-$N12ダメージ\n $N13ポイント：$N14-$N15ダメージ", nil, 0xb268c10a, nil, "um" },
  [31018] = { "フィニッシュ技。コンボポイントに応じたダメージを与え、余ったエネルギーを1ポイントにつき$N1の追加ダメージに変換します。ダメージはAttack Powerで増加します。\n $N2ポイント：$N3-$N4ダメージ\n $N5ポイント：$N6-$N7ダメージ\n $N8ポイント：$N9-$N10ダメージ\n $N11ポイント：$N12-$N13ダメージ\n $N14ポイント：$N15-$N16ダメージ", nil, 0x58b294b7, nil, "um" },
})
