-- GENERATED by `wfj generate` from data/spell/spell-0039.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [39104] = { "トーテムを大地に還し、Totemic Recallで破壊したトーテムそれぞれの詠唱に必要なマナの$N1%を得ます。", "$D1ごとにマナを$N1回復しています。", 0x2b160cfd, 0xb8d12796, "uu" },
})
