-- GENERATED by `wfj generate` from data/spell/spell-1267.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [1267046] = { "敵を打ち据え、Holyダメージを与えます。", nil, 0x20941603, nil, "um" },
  [1267113] = { "ダメージを$N1%軽減します。", "ダメージを受けません。", 0xf27200df, 0xf75b02dd, "uu" },
  [1267143] = { "敵に岩を投げつけ、Physicalダメージを与えます。", nil, 0x866d669f, nil, "um" },
  [1267193] = { "まだDalaranの街に入ることは許可されていません。", nil, 0x312c457f, nil, "um" },
  [1267199] = { "止まれ！Kirin Torの衛兵があなたを転送の対象に指定しました。", "スタンしています。", 0xad1fb213, 0x27f95286, "uu" },
})
