-- GENERATED by `wfj generate` from data/spell/spell-0421.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [421197] = { "近くの井戸に投げ入れて願い事をします", nil, 0xd9e84748, nil, "um" },
  [421262] = { nil, "あのパイが胃にもたれています……", nil, 0xc7597fda, "mu" },
  [421295] = { "大熊の巣穴の中に餌として置いてください", nil, 0x638bcf42, nil, "um" },
  [421311] = { "Tame Beastがシカにも効くようになります（コンパニオンペットとして）", "Tame Beastのアビリティがシカにも効くようになります（コンパニオンペットとして）", 0x26fbe948, 0x26fbe948, "uu" },
  [421406] = { "トーレンに決闘を挑みます", "受ける物理ダメージが増加しています", 0x21d0c0b2, 0xf95df00f, "uu" },
  [421424] = { "印のついた場所で宝を掘り出します", nil, 0xcb9fbb49, nil, "um" },
  [421425] = { "他の$N1枚の断片と組み合わせて、完全な地図を作ります。", nil, 0xdcc7f5cf, nil, "um" },
  [421436] = { "Glade Flowerを$N1本組み合わせて冠を作ります。", nil, 0xebce6cc7, nil, "um" },
  [421510] = { nil, "ひらめきに満ちています。", nil, 0x12978998, "mu" },
  [421535] = { nil, "ひらめきに満ちています。", nil, 0x12978998, "mu" },
  [421596] = { "Comprehension Charmで呪文のメモを解読し、新しいEngraving呪文を習得します。", nil, 0x7ccaad21, nil, "um" },
  [421599] = { "対象に撒き餌を与えます。", nil, 0x69e51170, nil, "um" },
})
