-- GENERATED by `wfj generate` from data/spell/spell-1234.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [1234299] = { "ExorcismとHoly WrathのGlobal Cooldownが$N1秒短縮されます。", "攻撃呪文のGlobal Cooldownが$N1秒短縮されます。", 0xd78a9116, 0xa6d72f7b, "uu" },
  [1234326] = { "Shock、Lightning、Lava Burst呪文のGlobal Cooldownが$N1秒短縮されます。", "攻撃呪文のGlobal Cooldownが$N1秒短縮されます。", 0x2c6b772b, 0xa6d72f7b, "uu" },
  [1234594] = { "約束された魂を受け取ります。", nil, 0x4fd08b9f, nil, "um" },
  [1234598] = { "野生の魔法を注ぎ込みます。", nil, 0x90fdaadc, nil, "um" },
})
