-- GENERATED by `wfj generate` from data/spell/spell-0427.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [427020] = { "Copper Barを$N1個加えて積み荷を完成させます。", nil, 0x470409ea, nil, "um" },
  [427076] = { "頭部にTaste for Bloodのルーンを刻みます：\n\n$I1\nRendがダメージを与えるたびに、Overpowerが$D1の間、または1回攻撃するまで使用可能になります。この効果は$D2に一度しか発生しません。", nil, 0x372b5a47, nil, "um" },
  [427078] = { "頭部にVigilanceのルーンを刻みます：\n\n$I1\nパーティーまたはレイドのメンバー一人に守護の視線を向け、そのメンバーが受けるダメージを$N1%軽減し、そのメンバーが生み出す脅威の$N2%を自分に移します。さらに、そのメンバーが攻撃を受けるたびにTauntのクールダウンがリセットされます。効果時間は$D1です。この効果は一度に一人の対象にしか付与できません。", nil, 0x61f07c95, nil, "um" },
  [427080] = { "頭部にShield Masteryのルーンを刻みます：\n\n$I1\n盾を装備している間、与える物理ダメージがすべて$N1%増加し、自分に使われるDisarm効果の持続時間が$N2%短縮されます。これは他のDisarm持続時間短縮効果とは重複しません。", nil, 0x9c5cde04, nil, "um" },
  [427081] = { "手首にRampageのルーンを刻みます：\n\n$I1\n暴れ回り、$D1の間攻撃力を$N1%増加させます。このアビリティはEnraged状態の間にしか使用できません。", nil, 0x0c6ff633, nil, "um" },
  [427082] = { "手首にSword and Boardのルーンを刻みます：\n\n$I1\nDevastateとRevengeがダメージを与えると、$N1%の確率でShield Slamのクールダウンをリセットし、$D1の間そのRageコストを$N2%減少させます。", nil, 0xa197703f, nil, "um" },
  [427084] = { "手首にWrecking Crewのルーンを刻みます：\n\n$I1\n近接クリティカルヒットでEnrage状態になり（Enraged状態が必要なアビリティが使用可能になります）、$D1の間Mortal Strike、Bloodthirst、Shield Slamのダメージが$N1%増加します。", nil, 0x5e77eb3f, nil, "um" },
  [427144] = { "このアイテムにはVoidの生の力が込められています。所持者が攻撃を受けると、このアイテムは高い確率で恐ろしい呪いをかけ、攻撃者は$N1秒間、あらゆるダメージを余分に受けるようになります。", nil, 0x21583d70, nil, "um" },
  [427592] = { "Scarlet Crusadeの一員に変装します。怪しい行動をとると変装が解けます。", "Scarlet Monasteryの一員に変装しています。", 0x6fd6b5d5, 0xcd5bf8dc, "uu" },
  [427712] = { "Corruption、Bane of Agony、Bane of Doom、Drain Soul、Drain Life、Siphon Life、Wrackのクリティカルダメージボーナスを$N1%増加させます。", nil, 0x860f8d69, nil, "um" },
  [427742] = { "クリーチャーを挑発し、Felguardを攻撃する確率を高めます。", nil, 0xf8aa5bd9, nil, "um" },
  [427744] = { "対象と、その最も近くにいる味方に、Felguardの武器ダメージに加えて$N1のダメージを与えるなぎ払い攻撃です。", nil, 0x1bb4f76b, nil, "um" },
  [427745] = { "敵に突撃し、$N1のダメージを与えて$D1スタンさせます。", nil, 0x481312e4, nil, "um" },
  [427746] = { nil, "スタンしています。", nil, 0x27f95286, "mu" },
})
