-- GENERATED by `wfj generate` from data/spell/spell-0449.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [449668] = { "Cat、Bear、Dire Bearフォームでのみ、Attack Powerが+$N1されます。", nil, 0xa798bce2, nil, "um" },
  [449980] = { "Holy Shockを使うと、$D1以内に詠唱する次のHoly Lightの詠唱時間が$N2秒短縮されます。", nil, 0xc809364f, nil, "um" },
})
