-- GENERATED by `wfj generate` from data/spell/spell-1313.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [1313342] = { "味方の対象を$N1回復します。", nil, 0xbe4c0f4a, nil, "um" },
  [1313343] = { "味方の対象を$N1回復します。", nil, 0xbe4c0f4a, nil, "um" },
  [1313344] = { "味方の対象を$N1回復します。", nil, 0xbe4c0f4a, nil, "um" },
  [1313345] = { "味方の対象を$N1回復します。", nil, 0xbe4c0f4a, nil, "um" },
  [1313346] = { "味方の対象を$N1回復します。", nil, 0xbe4c0f4a, nil, "um" },
  [1313348] = { "味方の対象を$N1回復します。", nil, 0xbe4c0f4a, nil, "um" },
  [1313349] = { "味方の対象を$N1回復します。", nil, 0xbe4c0f4a, nil, "um" },
  [1313350] = { "味方の対象を$N1回復します。", nil, 0xbe4c0f4a, nil, "um" },
  [1313351] = { "味方の対象を$N1回復します。", nil, 0xbe4c0f4a, nil, "um" },
  [1313352] = { "味方の対象を$N1回復します。", nil, 0xbe4c0f4a, nil, "um" },
  [1313374] = { "鍛冶場で鍵を溶かし、Bronze Barsを$N1本にします。", nil, 0x8a94dcd7, nil, "um" },
})
