-- GENERATED by `wfj generate` from data/spell/spell-1273.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [1273312] = { "Rog'mar Traineeに食料を与えます。", nil, 0x2442a699, nil, "um" },
})
