-- GENERATED by `wfj generate` from data/spell/spell-0464.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [464241] = { "次の攻撃アビリティの怒りコストを$N1減少させます。", "次の攻撃アビリティの怒りコストが$N1減少します。", 0xce888041, 0xce888041, "uu" },
  [464250] = { "敵に突進し、対象とその近くの仲間に$N1のダメージを与え、全員を吹き飛ばします。", nil, 0xad69abce, nil, "um" },
  [464279] = { "周囲の敵に通常ダメージに加えて$N1を与えます。", nil, 0x301ad2a4, nil, "um" },
  [464592] = { "近くの敵にFireダメージを与えます。", nil, 0x209abb75, nil, "um" },
  [464630] = { "$D1続くマナの嵐を呼び起こし、選んだ範囲内のすべての敵に$D2ごとに$N2のFrostダメージを与え、マナを$N3吸い取ります。", nil, 0xe9d85538, nil, "um" },
  [464650] = { nil, "スタンしており、とても寒い状態です。", nil, 0x9cb407ec, "mu" },
  [464743] = { "$D1の間、近くの敵の近接攻撃力と遠隔攻撃力を$N1低下させます。", "近接攻撃力と遠隔攻撃力が$N1低下しています。", 0x2eacb3df, 0x25ffd6c8, "uu" },
  [464945] = { "ShadowstrikeをThunderstrikeに変えます。", nil, 0xe0d5f71b, nil, "um" },
  [464946] = { "ThunderstrikeをShadowstrikeに変えます。", nil, 0x144434fe, nil, "um" },
})
