-- GENERATED by `wfj generate` from data/spell/spell-0423.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [423002] = { "Cat、Bear、Dire Bearフォームでのみ、Attack Powerが+$N1されます。", nil, 0xa798bce2, nil, "um" },
  [423003] = { "雷の粒を放出し、$N1のNatureダメージを与えます。", nil, 0x461c0247, nil, "um" },
  [423004] = { "突風を放ち、$N1のNatureダメージを与えます。", nil, 0x24083c31, nil, "um" },
  [423186] = { nil, "自然の力で自身の均衡を保っています。", nil, 0x2b38d4f5, "mu" },
  [423187] = { "Moon、Emerald Dream、WildのPowersの均衡を取り、新しいアビリティを習得します。", nil, 0xb3c699cf, nil, "um" },
  [423298] = { "泳ぐ速度を$N1%上げます。", "泳ぐ速度が$N1%上昇します。", 0xe184d52a, 0xe184d52a, "uu" },
  [423299] = { "物理攻撃でBeastsに与えるダメージを$N1増加させます。", nil, 0x35fca8b7, nil, "um" },
  [423300] = { "M'grrglが$D1の間同行し、闇からわずかに守ってくれます。", "M'grrglはあなたが気に入りました！\nShadow Resistanceが$N1上昇します。", 0x0eb12453, 0x48d168f4, "uu" },
  [423304] = { "獲物から生命力を吸い取り、$N1のダメージ分を回復します。", nil, 0xea366d8f, nil, "um" },
  [423474] = { "ImpのFireboltのダメージを$N1増加させます。", nil, 0xc780d6c3, nil, "um" },
  [423478] = { nil, "Stonetalon MountainsでYoung Pridewingsを手なずけることができます", nil, 0xa8ab6da5, "mu" },
  [423481] = { "隠密状態の敵を見破る能力がわずかに上昇します。", "隠密状態の敵を見破る能力がわずかに上昇しています。", 0xf1baa545, 0x99370680, "uu" },
  [423484] = { "ペットが与えるダメージを$N1%増加させます。", nil, 0xa112dde1, nil, "um" },
  [423549] = { "Greater Magic Wandに野生の魔力を込めます。", nil, 0x40589d5e, nil, "um" },
  [423632] = { "Waterlogged Captain's Chestを開けます。", nil, 0x97ea925d, nil, "um" },
})
