-- GENERATED by `wfj generate` from data/spell/spell-0466.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [466116] = { "杖を火の力に同調させます。", nil, 0xc2d7bd13, nil, "um" },
  [466117] = { "杖を冷気の力に同調させます。", nil, 0x51fe1133, nil, "um" },
  [466118] = { "杖を秘術の力に同調させます。", nil, 0x9875d928, nil, "um" },
  [466329] = { "素早いアッパーカットで敵を空中に打ち上げます。", nil, 0xb41711ba, nil, "um" },
  [466596] = { "忍者の暗殺者の姿になります。", "変装しています。", 0xdd706146, 0x005f62fd, "uu" },
  [466668] = { "新しい……待って。これはもう習得済みでは？", nil, 0x830d5ba5, nil, "um" },
})
