-- GENERATED by `wfj generate` from data/spell/spell-0398.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [398117] = { "おやつの袋を開けて対象のポケットにこっそり忍ばせ、この対象に対するBeastsのダメージを$N1増加させます。", "おいしそうな匂いがします！Beastsが与えるダメージが$N1増加します。", 0xe2383ce6, 0x8c9d9bae, "uu" },
  [398196] = { "遠隔武器を抜いて敵に素早く射撃し、通常の遠隔武器ダメージを与え、$D1の間、対象の移動速度を$N1%低下させます。コンボポイントを$N3得ます。\n\nQuick DrawはSinister Strikeで発動する、またはSinister Strikeを変化させるすべてのタレントと効果の恩恵を受けます。", "移動速度が$N1%低下しています。", 0x2fa6d8d6, 0x08fe79f0, "uu" },
  [398197] = { "Quick Drawのアビリティを得ます：\r\n\n$I1\r\n遠隔武器を抜いて敵に素早く射撃し、通常の遠隔武器ダメージを与え、$D1の間、対象の移動速度を$N1%低下させます。コンボポイントを$N3獲得します。\r\n\nQuick Drawは、Sinister Strikeによって発動する、またはSinister Strikeを強化するすべてのタレントと効果の恩恵を受けます。", nil, 0xb4295320, nil, "um" },
  [398603] = { "防具に強力なルーンを取り付けます。", nil, 0x2d87a488, nil, "um" },
  [398608] = { "武器に毒を塗ります。毒は$N1分間持続します。\n攻撃が命中するたびに$N2%の確率で敵を毒に冒し、$D1の間移動速度を$N3%低下させます。", nil, 0x6bb4a1f1, nil, "um" },
})
