-- GENERATED by `wfj generate` from data/spell/spell-0045.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [45440] = { "スチームトンクを呼び出して操作します。", "アクションバーを使って、他のリモコンおもちゃを攻撃します。", 0xcfe2a83a, 0xbb60bb78, "uu" },
})
