-- GENERATED by `wfj generate` from data/spell/spell-0350.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [350025] = { "敵に冷気の矢を放ち、$N1のFrostダメージを与え、$D1の間、移動速度を$N2%低下させます。", "移動速度が$N1%低下しています。", 0xf9aa34f5, 0xbd9406b8, "uu" },
  [350026] = { "敵に影の矢を放ち、$N1のShadowダメージを与えます。", nil, 0xc6f8d47d, nil, "um" },
})
