-- GENERATED by `wfj generate` from data/spell/spell-0406.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [406634] = { "騎乗できるAnimated Lobster Moltを呼び出し、または帰します。", "地上での移動速度が$N1%上昇します。", 0x8f33b9b6, 0x2195529a, "uu" },
  [406651] = { "他の$N1個の断片と組み合わせて、完全なルーンを作ります。", nil, 0x4c2b39fd, nil, "um" },
  [406680] = { nil, "移動速度が$N1%低下しています。", nil, 0xbd9449c1, "mu" },
  [406722] = { "影の中を抜けて敵の背後に再び現れようと試み、$D1の間、移動速度を$N1%上昇させます。", "移動速度が$N1%上昇します。", 0x9443ecbd, 0xd5c3ef85, "uu" },
  [406746] = { "前方のすべての敵に加圧された水を浴びせます。", nil, 0xed9b064c, nil, "um" },
  [406970] = { nil, "受けるダメージが50%減少します。", nil, 0x400c6ec2, "mu" },
  [406973] = { nil, "受けるダメージが$N1%減少します。", nil, 0xa4f10210, "mu" },
})
