-- GENERATED by `wfj generate` from data/spell/spell-0424.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [424035] = { "聖なる場所で光の神秘について瞑想できるようになります。", nil, 0x0f73053b, nil, "um" },
  [424036] = { "ムーンウェルでEluneの神秘について瞑想できるようになります。", nil, 0x6ccb1026, nil, "um" },
  [424037] = { "祭壇でロアの神秘について瞑想できるようになります。", nil, 0x0c46c3a0, nil, "um" },
  [424041] = { "墓地で不死の神秘について瞑想できるようになります。", nil, 0xd5b327b5, nil, "um" },
  [424336] = { nil, "自然の力で自身の均衡を保っています。", nil, 0x2b38d4f5, "mu" },
  [424472] = { nil, "死の瀬戸際にいます。", nil, 0x70aba022, "mu" },
  [424645] = { "呪文のメモを翻訳し、新しいルーン彫りのレシピにします。筆者の略記法の参考資料が必要です。", nil, 0xadb28b80, nil, "um" },
  [424718] = { "脚部にStarsurgeのルーンを刻みます：\r\n\n$I1\r\n星のエネルギーを放ち、$N1のArcaneダメージを与え、$D1の間、次の$N2回のStarfireのダメージを$N3%増加させます。\r\n\nStarsurgeは、WrathまたはStarfireによって発動する、またはそれらを強化するほとんどのタレントと効果の恩恵を受け、それらを発動させます。", nil, 0x9a8618a9, nil, "um" },
  [424760] = { { "ベルトにBerserkのルーンを刻みます：\r\n\n$I1\r\n|CFFFFFFFF必要：Cat Form、Bear Form、Dire Bear Form|R\r\nPrimal Biteが最大$N1体の対象に命中するようになり、クールダウンがなくなり、Combo Pointを生成するアビリティのクリティカル率が$N2%上昇します。効果中はFear効果が解除され、Fear効果に対する免疫を得ます。$D1持続します。", "ベルトにBerserkのルーンを刻みます：\r\n\n$I1\r\n|CFFFF2020必要：Cat Form、Bear Form、Dire Bear Form|R\r\nPrimal Biteが最大$N1体の対象に命中するようになり、クールダウンがなくなり、Combo Pointを生成するアビリティのクリティカル率が$N2%上昇します。効果中はFear効果が解除され、Fear効果に対する免疫を得ます。$D1持続します。", shape = { "3/1", "3/1" } }, nil, 0xcfb3cf54, nil, "um" },
  [424765] = { "ブーツにKing of the Jungleのルーンを刻みます：\r\n\n$I1\r\nTiger's Furyで即座にEnergyを$N1得るようになります。", nil, 0xd414c04d, nil, "um" },
  [424785] = { "敵を容赦なく切りつけて武器ダメージの$N1%を与え、対象を出血させて$D2の間、$N3秒ごとに$N2のダメージを与えます。最大$N5回までスタックします。スタックごとに、Saber SlashとSinister Strikeのダメージも$N6%増加します。コンボポイントを$N7獲得します。\n\nSaber SlashはSinister Strikeから発動する、またはSinister Strikeを強化するすべてのタレントと効果の恩恵を受けます。", "出血により、$N2秒ごとに$N1のダメージを受けています。\nSaber SlashとSinister Strikeから受けるダメージが$N3%増加しています。", 0x72e45558, 0x7fbbf470, "uu" },
  [424788] = { "シュレッダーの残骸から予備部品を回収します。", nil, 0x30b9e1d2, nil, "um" },
  [424799] = { "即座にオフハンド武器で攻撃して通常のオフハンド武器ダメージを与え、$N1%の確率でオフハンド武器の毒を対象に付与します。遅い武器ほど多くのエネルギーを必要とします。コンボポイントを$N2得ます。\n\nShivはSinister Strikeで発動する、またはSinister Strikeを変化させるすべてのタレントと効果の恩恵を受けます。", nil, 0xb5aa7d3f, nil, "um" },
  [424919] = { "即座にオフハンド武器で攻撃して通常のオフハンド武器ダメージを与え、$D1の間、またはパリィに成功するまで、パリィ率を$N1%上昇させます。Main Gaucheの使用後$D2の間、Sinister StrikeのEnergyコストが$N4減少し、発生させる脅威が$N5%増加し、Rolling with the Punchesのスタックを得られるようになり、Sinister StrikeとEviscerateの与えるダメージが$N6%増加します。コンボポイントを$N7得ます。\n\nMain GaucheはSinister Strikeで発動する、またはSinister Strikeを変化させるほとんどのタレントと効果の恩恵を受けます。Main Gaucheの効果はMain Gauche自体のコストを軽減したり強化したりしません。", "Parry率が$N1%上昇しています。", 0xc4245e6a, 0xea59a9be, "uu" },
  [424984] = { "手袋にSaber Slashのルーンを刻みます：\n\n$I1\n敵を激しく斬りつけて武器ダメージの$N1%を与え、対象を出血させて$D2の間$D1ごとに$N2のダメージを与えます。最大$N5回までスタックします。スタックごとに、Saber SlashとSinister Strikeのダメージも$N6%増加します。コンボポイントを$N7獲得します。\n\nSaber Slashは、Sinister Strikeから発動する、またはSinister Strikeを変化させるすべてのタレントと効果の恩恵を受けます。", nil, 0x9ee44fa7, nil, "um" },
  [424988] = { "手袋にCutthroatのルーンを刻みます：\n\n$I1\nBackstabは$N1%の確率で、$D1以内の次のAmbushをStealthなしで使用可能にします。", nil, 0xe753d816, nil, "um" },
  [424990] = { "手袋にMain Gaucheのルーンを刻みます：\n\n$I1\nオフハンド武器で即座に攻撃して通常のオフハンド武器ダメージを与え、$D1の間、または受け流しに成功するまで、受け流しの確率を$N1%上昇させます。Main Gauche使用後$D2の間、Sinister StrikeのEnergyコストが$N4減少し、生み出す脅威が$N5%増加し、Rolling with the Punchesのスタックを付与し、Sinister StrikeとEviscerateの両方のダメージが$N6%増加します。コンボポイントを$N7獲得します。\n\nMain Gaucheは、Sinister Strikeから発動する、またはSinister Strikeを変化させるほとんどのタレントと効果の恩恵を受けます。Main Gaucheの効果はMain Gauche自身のコストを軽減せず、強化もしません。", nil, 0x279ea807, nil, "um" },
  [424992] = { { "胸部か法衣にSlaughter from the Shadowsのルーンを刻みます：\n\n$I1\nBackstabとAmbushのEnergyコストを$N1減少させ、プレイヤー以外が操作する対象に与えるダメージを$N2%増加させます。Mutilateには適用されません。", "胸部か法衣にSlaughter from the Shadowsのルーンを刻みます：\n\n$I1\nBackstabとAmbushのEnergyコストを$N1減少させ、プレイヤー以外が操作する対象に与えるダメージを$N2%増加させます。他のルーンで習得したアビリティには適用されません。", shape = { "2/0", "2/0" } }, nil, 0x9ddaea85, nil, "um" },
})
