-- GENERATED by `wfj generate` from data/spell/spell-0384.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [384135] = { "レイドメンバー全員が、Kel'Thuzadとその副官たちから追加の報酬を見つける機会を得ます。\n\nこの効果は重なり、まる一週間続きます。", nil, 0x38da2bad, nil, "um" },
  [384255] = { "タレントの変更を適用します。", "タレントの変更を適用します。", 0x9ee07359, 0x9ee07359, "uu" },
})
