-- GENERATED by `wfj generate` from data/spell/spell-0458.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [458454] = { "残響を捧げます。", nil, 0x10968b43, nil, "um" },
  [458821] = { "武器に30分間持続する毒を塗ります。攻撃のたびに$N2%の確率で敵を毒に冒し、$D1かけて$N3のNatureダメージを与え、敵が受けるArcane、Fire、Frost、Nature、Shadowのダメージを$N5%増加させます。1体の対象に最大$N6回までスタックします。\n\nOccult PoisonはDeadly Poisonとして扱われ、Deadly Poisonで発動する、またはDeadly Poisonを強化するすべてのタレントと効果の恩恵を受けます。", nil, 0xac6b5ded, nil, "um" },
  [458822] = { "武器に30分間持続する毒を塗ります。\n攻撃のたびに30%の確率で敵を毒に冒し、$D1かけて$N3のNatureダメージを与え、敵が受けるArcane、Fire、Frost、Nature、Shadowのダメージを$N5%増加させます。1体の対象に最大$N6回までスタックします。\n\nOccult PoisonはDeadly Poisonとして扱われ、Deadly Poisonで発動する、またはDeadly Poisonを強化するすべてのタレントと効果の恩恵を受けます。", nil, 0xdba5bb61, nil, "um" },
  [458856] = { "友好的な対象を$N1回復します。対象への過剰回復の$N2%は、$D1持続する吸収シールドに変換されます。Divine Lightを複数回唱えても、このシールドは累積しません。\n\nDivine LightはHoly Lightで発動する、またはHoly Lightを強化するすべてのタレントと効果の恩恵を受けます。", nil, 0x5eb11dfb, nil, "um" },
})
