-- GENERATED by `wfj generate` from data/spell/spell-1322.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [1322007] = { "ウォーロックの指揮下にあるVoidwalkerを召喚します。", nil, 0xe766a608, nil, "um" },
})
