-- GENERATED by `wfj generate` from data/spell/spell-0335.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [335924] = { "得られる経験値が$N1%増加しています。", "(CN Only)\n獲得経験値が$N1%増加します。", 0x2bdeacf1, 0xaa504b7f, "uu" },
})
