-- GENERATED by `wfj generate` from data/spell/spell-0150.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [150544] = { "現在のエリアで使えるお気に入りの騎乗動物を呼び出したり帰したりします。お気に入りの騎乗動物がない場合は、コレクション全体から選ばれます。", nil, 0x3e39df14, nil, "um" },
})
