-- GENERATED by `wfj generate` from data/spell/spell-1246.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [1246026] = { "青々とした植物の治癒と成長を助けます。", "援護を受けています。", 0x3948b615, 0x1d37f16a, "uu" },
  [1246031] = { "近くのkoboldの足跡を地図上に表示します。", "近くのコボルドの足跡がマップに表示されます。", 0x877e0a8a, 0x4200f668, "uu" },
})
