-- GENERATED by `wfj generate` from data/spell/spell-1287.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [1287099] = { "壊れた戦争機械に魔法の種をまき、自然がそれを取り戻すのを早めます。", nil, 0xe5fbb7ab, nil, "um" },
  [1287321] = { "近くの墓にろうそくを置きます。", nil, 0x597d60a5, nil, "um" },
  [1287327] = { "牡鹿の最後の亡骸を供え、自然へ還します。", nil, 0x159829e0, nil, "um" },
  [1287557] = { "Empowered Brutes、Twilight Ritualists、Twilight Ritual CirclesからTwilightの魔力を吸収します。", nil, 0xda1fd62f, nil, "um" },
  [1287561] = { "魔法の呪文と効果によるダメージと回復量を最大$N1増加させます。ForestとGrasslandの地域ではこの効果が三倍になります。", nil, 0xc854c672, nil, "um" },
  [1287571] = { "$D1の間、すべての能力値を$N1増加させます。ForestとGrasslandの地域では効果と効果時間が二倍になります。", "すべての能力値が$N1上昇しています。", 0x11ac73fe, 0x8e6b2103, "uu" },
  [1287704] = { nil, "ForestまたはGrasslandの地域では、Attack Powerがさらに$N1上昇します。", nil, 0xc5b620c2, "mu" },
  [1287768] = { "$D1の間、攻撃力を$N1上昇させます。", "攻撃力が$N1上昇します。", 0x760ba7f2, 0x7d819cdc, "uu" },
  [1287808] = { "$D1の間、Dragon Breath呪文から受ける魔法ダメージを$N1%減少させます。", "Dragon Breath呪文から受ける魔法ダメージが$N1%減少します。", 0xc0fdbbbd, 0x3b184543, "uu" },
  [1287840] = { "$D1の間、Spell Hitの確率を$N1%上昇させます。", "Spell Hit率が$N1%上昇しています。", 0x18dbbc83, 0xdaedfbaa, "uu" },
  [1287842] = { "$D1の間、最大healthを$N1増加させます。StrongholdsとCitiesではこの効果が二倍になります。", "Healthが$N1増加しています。", 0x2ff64b55, 0x9cbb49a4, "uu" },
  [1287963] = { "指定した場所に$D1持続する光の輪を呼び出します。過去の亡霊を明らかにします。", nil, 0x0773cb4c, nil, "um" },
})
