-- GENERATED by `wfj generate` from data/spell/spell-1252.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [1252525] = { "壊れやすい調合物を対象範囲に投げつけ、$D1の間、Caustic Smogの雲を発生させます。雲の中にいる敵は$N3秒ごとに$N2のNatureダメージを受けます。", nil, 0xa6d05600, nil, "um" },
  [1252544] = { "壊れやすい調合物を対象範囲に投げつけ、$D1の間、Disorienting Smogの雲を発生させます。雲の中にいる敵はHit Chanceが$N2%低下します。レベル$N3を超える対象には効果がありません。", nil, 0x9e622aba, nil, "um" },
  [1252554] = { "ドラゴンの炎のげっぷを放ち、前方の狭い円錐範囲内に即座に$N1のFireダメージを与えます。効果を受けた対象は$D2の間、$N3秒ごとに$N2の追加ダメージを受けます。", "$N2秒ごとに$N1のFireダメージを受けています。", 0x416cdf81, 0x2ca459b7, "uu" },
  [1252558] = { "Elementalsに対するSpell Damageを$N1増加させます。効果時間は$D1です。", "Elementalsに対するSpell Damageが$N1増加しています。", 0x6b518420, 0x84aaaa37, "uu" },
  [1252559] = { "Beastsに対するAttack Powerを$N1増加させます。持続時間は$D1です。", "Beastsに対するAttack Powerが$N1増加しています。", 0xc2c3cf7e, 0x65f19e6b, "uu" },
  [1252576] = { "食べて。", "なんだか変な気分です。", 0xf9e7e9c9, 0x4def5211, "uu" },
})
