-- GENERATED by `wfj generate` from data/spell/spell-0399.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [399954] = { "Runeが刻まれたChestスロットのアイテムを装備すると、このスロットのアビリティが有効になります。", nil, 0xd9c27ae4, nil, "um" },
  [399956] = { "即座に両手の武器で攻撃し、武器ダメージの$N1%に加えて各武器でさらに$N2のダメージを与えます。Poisonedの対象へのダメージは$N3%増加します。Comboポイントを$N4得ます。", nil, 0xa12beab4, nil, "um" },
  [399966] = { "Runeが刻まれたLegsスロットのアイテムを装備すると、このスロットのアビリティが有効になります。", nil, 0x73ddef7a, nil, "um" },
  [399967] = { "Runeが刻まれたHandsスロットのアイテムを装備すると、このスロットのアビリティが有効になります。", nil, 0x55d903a3, nil, "um" },
  [399985] = { "対象の背後にテレポートして攻撃し、対象に武器ダメージの$N1%を与えます。隠密状態である必要があります。コンボポイントを$N2得ます。", nil, 0x8e972e2d, nil, "um" },
  [399986] = { "敵に手裏剣を投げ、Attack Powerの$N1%に等しいダメージを与え、さらに周囲の対象を最大$N2体攻撃します。命中した対象一体ごとにコンボポイントを$N3得ます。", nil, 0x22f72854, nil, "um" },
})
