-- GENERATED by `wfj generate` from data/spell/spell-0366.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [366305] = { nil, "Static Electricityを帯びて脈動しており、10スタックになると周囲のプレイヤーに電撃を浴びせ、Natureダメージを与えます。", nil, 0x70a9b801, "mu" },
  [366719] = { nil, "ダメージを与えるとStatic Electricityのスタックが付与されます。", nil, 0xf6bcad6b, "mu" },
  [366881] = { "召喚の円を使ってincubusを呼び出します。", nil, 0xcff16dcb, nil, "um" },
  [366894] = { "召喚の円を使ってincubusを呼び出します。", nil, 0xcff16dcb, nil, "um" },
  [366902] = { "召喚の円を使ってincubusを呼び出します。", nil, 0xcff16dcb, nil, "um" },
  [366909] = { "$D1ごとに$N1のFireダメージを与えます。", "$D1ごとに$N1のFireダメージを受けます。", 0xa9aeaf55, 0xa9aeaf55, "uu" },
  [366969] = { "$D1ごとに$N1のNatureダメージを与えます。", "$D1ごとに$N1のNatureダメージを受けます。", 0x9d4ac814, 0x9d4ac814, "uu" },
  [366994] = { "$D1ごとに$N1のShadowダメージを与えます。", "$D1ごとに$N1のShadowダメージを受けます。", 0x89116fee, 0x89116fee, "uu" },
  [366995] = { "$D1ごとに$N1のArcaneダメージを与えます。", "$D1ごとに$N1のArcaneダメージを受けます。", 0xda5c3e9c, 0xda5c3e9c, "uu" },
  [366996] = { "$D1ごとに$N1のFrostダメージを与えます。", "$D1ごとに$N1のFrostダメージを受けます。", 0x57de0f0b, 0x57de0f0b, "uu" },
})
