-- GENERATED by `wfj generate` from data/spell/spell-0078.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [78156] = { "体力$N1のTremor Totemを足元に召喚します。トーテムは周囲の地面を揺らし、$N2ヤード以内のパーティーメンバーからFear、Charm、Sleepの効果を取り除きます。", nil, 0xc1259d2b, nil, "um" },
  [78159] = { "体力$N1のWindfury Totemを術者の足元に召喚します。トーテムは$N3ヤード以内のパーティーとレイドのメンバー全員に近接攻撃の加速$N2%を与えます。効果時間は$D1です。", "近接ヘイストが$N1%上昇します。", 0x4a946e59, 0x535a2ca1, "uu" },
})
