-- GENERATED by `wfj generate` from data/spell/spell-0414.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [414644] = { "敵の対象を切り裂き、$D1かけて$N1の出血ダメージに加え、対象にすでにかかっているLacerate一回ごとに武器ダメージの$N3%を与えます。大量の脅威を発生させます。この効果は同じ対象に最大$N4回まで重なります。", "$N2秒ごとに$N1のダメージを受けます。", 0x58e2b595, 0x8522e0de, "uu" },
  [414673] = { "Rejuvenation、Swiftmend、Wild Growthのグローバルクールダウンを$N1秒短縮します。", nil, 0x1c2bf810, nil, "um" },
  [414683] = { "味方の対象を$N1回復します。", nil, 0xbe4c0f4a, nil, "um" },
  [414684] = { "敵を燃やして$N1のNatureダメージを与え、さらに$D1かけて$N2の追加Natureダメージを与えます。", "$N2秒ごとに$N1のNatureダメージを受けます。", 0x3aa7711e, 0x1062340a, "uu" },
  [414687] = { "敵を燃やして$N1のNatureダメージを与え、さらに$D1かけて$N2の追加Natureダメージを与えます。", "$N2秒ごとに$N1のNatureダメージを受けます。", 0x3aa7711e, 0x1062340a, "uu" },
  [414689] = { "敵を燃やして$N1のNatureダメージを与え、さらに$D1かけて$N2の追加Natureダメージを与えます。コンボポイントを$N4得ます。", "$N2秒ごとに$N1のNatureダメージを受けます。", 0x9cd4ca30, 0x1062340a, "uu" },
  [414724] = { "平原の霊を目覚めさせます", nil, 0x6a4a51d5, nil, "um" },
})
