-- GENERATED by `wfj generate` from data/spell/spell-1301.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [1301046] = { "攻撃に、次の攻撃で$N1回の追加攻撃を得る確率が付きます。オークへの攻撃ではこの効果が$N2倍発動しやすくなります。", "Franclorn Forgewrightの霊が宿っています。Dwarvishでしか話せません。", 0xeafe5bce, 0xbc49dc4f, "uu" },
  [1301126] = { "自分に対するFear効果の命中率を$N1%低下させます。", nil, 0xd3bb670e, nil, "um" },
  [1301127] = { "遠隔武器の命中率が$N1%上昇します。", nil, 0x24c1db5c, nil, "um" },
  [1301167] = { "最大$N1のダメージを吸収し、$D1の間自分をStun状態にします。Stunが切れると、$D2の間、移動速度が$N3%上昇します。", nil, 0x584acd6f, nil, "um" },
  [1301195] = { "Silvermoon Shimmerwineをグラスに注ぎます。", "Silvermoon Shimmerwineを一杯楽しんでいます。", 0x40582d15, 0xf294aede, "uu" },
  [1301625] = { "$D1の間、Lavaの上に立ったり泳いだりして受けるダメージをすべて無視します。", "Lavaから受けるダメージをすべて無視します。", 0xf0ba0a53, 0x087e5fb4, "uu" },
  [1301636] = { "騎乗できる荷運びのkodoを召喚、または解放します。", "地上での移動速度が$N1%上昇します。", 0xfbdfeb5d, 0x2195529a, "uu" },
  [1301683] = { "最大$D1の間、対象の機械生物を乗っ取って操ります。操っている間、対象の攻撃速度は遅くなります。レベル$N2を超える対象には効果がありません。", "上書きされています。", 0x7f04cd90, 0x5dc664db, "uu" },
  [1301707] = { "追跡されません。", "追跡されません。", 0x9bd2adf2, 0x90c3da9a, "uu" },
  [1301784] = { "Trias' Cheeseの二階のドアの外に置きます。", nil, 0x0ae35f91, nil, "um" },
})
