-- GENERATED by `wfj generate` from data/spell/spell-0324.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [324270] = { nil, "$D1ごとに$N1のダメージを受けます。\n周囲の味方に広がります。", nil, 0xf772803c, "mu" },
  [324271] = { nil, "$D1ごとに$N1のダメージを受けます。\n周囲の味方に広がります。", nil, 0xb9894381, "mu" },
})
