-- GENERATED by `wfj generate` from data/spell/spell-1285.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [1285372] = { "ローグが姿を消し、$D1の間、強化されたステルスモードに入ります。移動を妨げる効果も解除します。Vanish（Rank 2）より効果的です。", "隠密が強化されています。", 0xd5429bbb, 0xad8eb7ec, "uu" },
  [1285835] = { "クリスタルを導いています。", nil, 0x241a97d5, nil, "um" },
  [1285853] = { "プレイヤーがgalestriderに乗れるようになります。", nil, 0x69124a9d, nil, "um" },
  [1285903] = { "あなたは狩られています……幸運を。", "狩られています。ここにいないほうがよさそうです。", 0x20b750e0, 0x6a42debc, "uu" },
  [1285919] = { "発射するグレイブを装填します。", nil, 0x9e48aef1, nil, "um" },
  [1285922] = { "発射するグレイブを装填します。", nil, 0x9e48aef1, nil, "um" },
})
