-- GENERATED by `wfj generate` from data/spell/spell-0471.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [471149] = { "悪夢に呑まれた別の場所へ入ります。", "任務区域に戻ってください。戻らなければ$D1後にテレポートされます。", 0x339fbd21, 0x57e7cc86, "uu" },
  [471400] = { "Magnificent Trollshineを作成します。", nil, 0x2e9829a1, nil, "um" },
  [471401] = { "対象の盾に塗布している間、呪文ダメージと回復量が最大36増加し、Spell Criticalの確率が1%上昇します。効果時間は30分です。", nil, 0x6c2a8aac, nil, "um" },
  [471402] = { "魔法の呪文と効果によるダメージと回復量を最大$N1増加させます。さらに呪文でクリティカルヒットを出す確率を$N2%上げます。", nil, 0x299ae61d, nil, "um" },
  [471698] = { "内なる闇と同調し、内なる悪魔をよりうまく制御できるようにします。", "あなたの魂は悪魔と一つになっています……", 0x4255a78a, 0x872359eb, "uu" },
  [471699] = { "内なる闇に同調し、内なる悪魔をよりうまく制御できるようにします。", "あなたの魂は悪魔と一つになっています……", 0xa0b0ec43, 0x872359eb, "uu" },
})
