-- GENERATED by `wfj generate` from data/spell/spell-0452.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [452428] = { nil, "呪文のクリティカルダメージ効果に、周囲の敵$N2体に$N1のnatureダメージを与える可能性があります。", nil, 0xcde08b30, "mu" },
  [452432] = { "近接の自動攻撃時に一定の確率で、敵の対象から生命力を$N1奪います。", "近接の自動攻撃が命中すると、敵の目標から生命力を$N1奪うことがあります。", 0xb79b58ed, 0xff4b9560, "uu" },
  [452433] = { "Rae'larをGla'sirに変化させます。", nil, 0x7a65c730, nil, "um" },
  [452434] = { "Gla'sirをRae'larに変化させます。", nil, 0x64263662, nil, "um" },
  [452466] = { "召喚したトーテムが、それぞれの属性の恩恵を与えます。", "召喚されたトーテムがそれぞれの属性の恩恵を与えます。", 0x5d8a8187, 0x5d8a8187, "uu" },
  [452474] = { "$D1の間、Suzerainを掲げ、受ける呪文ダメージを$N2%減少させます。Dragon's Breathを受けるとRage of the Suzerainを得て、$D2の間、Dragonに与えるダメージが$N3%増加します。", "呪文ダメージが$N1%減少しています。", 0x976c6839, 0x871a2cb4, "uu" },
})
