-- GENERATED by `wfj generate` from data/spell/spell-0364.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [364107] = { "Root Effectsが効きません。", "Root Effectsに対する免疫があります。", 0x01906f80, 0x01906f80, "uu" },
  [364161] = { "$D1の間、対象の知力を$N1上げます。", "知力が$N1増加します。", 0x9663f4be, 0xec5dd10a, "uu" },
  [364163] = { "$D1の間、味方の対象のアーマーを$N1、すべての能力値を$N2、すべての抵抗力を$N3上げます。", "アーマーが$N1、すべての能力値が$N2、すべての耐性が$N3上昇します。", 0x48c4c0cd, 0xa07843b3, "uu" },
  [364455] = { "体力が$N1%増加しています。", "|cFFffd200Bonus Event: Season of Mastery|r\n\n体力が$N1%増加します。", 0x334d75a3, 0x58597bce, "uu" },
  [364658] = { nil, "最近盗難が続いているため、周囲の敵は持ち物のほとんどを別の場所に隠しています。", nil, 0xf38f60c3, "mu" },
  [364812] = { "対象の魔法を解除し、味方からは有害な呪文を$N1個、敵からは有益な呪文を$N2個取り除きます。", nil, 0xf935d550, nil, "um" },
  [364820] = { "$D1ごとに$N1のFireダメージを与えます。", "$D1ごとに$N1のFireダメージを受けます。", 0xa9aeaf55, 0xa9aeaf55, "uu" },
  [364838] = { "$D1ごとに$N1のFireダメージを与えます。", "$D1ごとに$N1のFireダメージを受けます。", 0xa9aeaf55, 0xa9aeaf55, "uu" },
  [364895] = { "近くの敵にFireダメージを与えます。", nil, 0x209abb75, nil, "um" },
  [364908] = { "闇の魔法を使い、味方を$N1回復します。", nil, 0x484a54a0, nil, "um" },
})
