-- GENERATED by `wfj generate` from data/spell/spell-1312.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [1312002] = { "敵の対象に$N1のFrostダメージを与えます。Frozenの対象には$N2%増加したダメージを与えます。", nil, 0x3353dc3d, nil, "um" },
  [1312176] = { "鍛冶場の炎で対象を焼き、$N1のFireダメージを与えます。", nil, 0x05f874c3, nil, "um" },
  [1312330] = { "聖なる泉の力で対象を打ち据え、$N1のHolyダメージを与えます。", nil, 0x9b566f35, nil, "um" },
  [1312438] = { "敵に影の矢を放ち、$N1のShadowダメージを与えます。", nil, 0xc6f8d47d, nil, "um" },
  [1312670] = { { "Orgrimmarに戻ります。使い切りです。", "Stormwindに戻ります。使い切りです。", shape = { "0/0", "0/0" } }, nil, 0x5a558133, nil, "um" },
  [1312698] = { "体力を$N1%回復します。", nil, 0xbfc764d3, nil, "um" },
  [1312702] = { "マナを$N1%回復します。", nil, 0xce81cf6a, nil, "um" },
  [1312719] = { "$D1かけて体力を$N1%、マナを$N2%回復します。飲んでいる間は座っている必要があります。", "毎秒、体力を$N1%、マナを$N2%回復しています。", 0xc98bf519, 0x8179b4fa, "uu" },
  [1312745] = { "同じくReplica Ironforge Air Rifleを装備しているほかのプレイヤーをStunさせようと試みます。", nil, 0x71aea935, nil, "um" },
  [1312880] = { "Right Clickでクロコリスクの赤ちゃんを召喚、または解放します。", nil, 0x14ea2ea0, nil, "um" },
  [1312955] = { "戦闘中に攻撃を受けると、攻撃者に$N1のFireダメージを与えます。", nil, 0xddbd4603, nil, "um" },
})
