-- GENERATED by `wfj generate` from data/spell/spell-1243.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [1243356] = { "宝を掘り出します。", nil, 0x954d90f3, nil, "um" },
  [1243960] = { "Vek'zolを召喚します。", nil, 0x98732f71, nil, "um" },
})
