-- GENERATED by `wfj generate` from data/spell/spell-1281.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [1281530] = { "$D1の間、マウントを借りられます。", { "地上での移動速度が$N1%上昇します。", shape = { "1/0" } }, 0x9bd8c14a, 0x2195529a, "uu" },
  [1281641] = { "Right Clickで音楽好きのカエルの友達を召喚、または解放します。", nil, 0x1c2273ec, nil, "um" },
  [1281744] = { "命中率が$N1%上昇します。", nil, 0x8e26e034, nil, "um" },
  [1281765] = { "5秒後に花開く魔法の種を植えます。$D2ごとにTreantが生み出されます。", nil, 0x9e1d641f, nil, "um" },
  [1281781] = { "敵を根で絡め取り、最大$D2の間動けなくし、$D1ごとにNatureダメージを与えます。", "移動できません。\n$D1ごとにNatureダメージを受けています。", 0xdee22147, 0xe6768e6a, "uu" },
  [1281782] = { "近くの敵を攻撃するTreantを定期的に召喚します。", nil, 0x542ac3ed, nil, "um" },
  [1281887] = { "最近Entangledの効果を受けました。", nil, 0x462460ad, nil, "um" },
})
