-- GENERATED by `wfj generate` from data/spell/spell-0042.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [42609] = { "右クリックでsinister squashlingを召喚/退散します。", nil, 0x53b9546c, nil, "um" },
})
