-- GENERATED by `wfj generate` from data/spell/spell-0419.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [419126] = { "Dueling to the Deathの勝利で集めた戦利品の数を表示します。", nil, 0x820f9bf0, nil, "um" },
  [419288] = { nil, "ひらめきに満ちています。", nil, 0x12978998, "mu" },
  [419307] = { nil, "瞑想によって心が広がり、世界中で見つかるMemoriesから新しい呪文を習得できる明晰さを得ています。", nil, 0x0f1e11e9, "mu" },
  [419308] = { nil, "ムーンウェルの水があなたの心を落ち着かせています。ここでひざまずいてEluneの神秘について瞑想しましょう。", nil, 0x760c07a5, "mu" },
  [419417] = { "ホームに設定した場所へ戻ります。別の場所のInnkeeperに話しかけると、ホームの場所を変更できます。", nil, 0xf92eb2a9, nil, "um" },
})
