-- GENERATED by `wfj generate` from data/spell/spell-0447.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [447274] = { "Cat、Bear、Dire Bearフォームでのみ、Attack Powerが+$N1されます。", nil, 0xa798bce2, nil, "um" },
  [447296] = { "Insect Swarm呪文の効果時間が$N1秒延長されます。", nil, 0xb6ad8827, nil, "um" },
  [447472] = { "Satyrweedのサンプルを3個組み合わせて、チンキを調合します。", nil, 0xab7e29b3, nil, "um" },
  [447475] = { "クリーチャーからSatyrの穢れを取り除きます。", nil, 0xcbba2d5f, nil, "um" },
  [447537] = { "集めた秘薬を組み合わせて、新しいEngraving呪文を習得できるルーンを作ります。", nil, 0xfc4e9192, nil, "um" },
  [447556] = { "集めた秘薬を組み合わせて、Undying Slumberを終わらせることのできる壊れやすい杖を作ります。", nil, 0xf32edb13, nil, "um" },
  [447563] = { "対象の目をくらませ、最大$D1の間、方向を見失ってさまよわせます。ダメージを与えると効果が解けます。", nil, 0x9dce52b1, nil, "um" },
  [447590] = { "Calefactus the Unleashedを弱らせます。", "その場から動けません。$N2秒ごとに$N1のFireダメージを受けます。", 0xbcba3518, 0xbc987a18, "uu" },
  [447894] = { "敵を毒に冒して$N1のNatureダメージを与え、$D1の間、Nature耐性を$N2低下させ、受けるHolyとNatureのダメージを$N3%増加させます。レベル55以下の敵にのみ効果があります。", "Nature耐性が$N1低下しています。受けるHolyとNatureの呪文ダメージが$N2%増加しています。", 0x76472134, 0xf85c0bd5, "uu" },
})
