-- GENERATED by `wfj generate` from data/spell/spell-0399.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [399699] = { "兜のクリティカル率を30分間、2%上げます。", nil, 0xc6823f92, nil, "um" },
  [399954] = { "Runeが刻まれたChestスロットのアイテムを装備すると、このスロットのアビリティが有効になります。", nil, 0xd9c27ae4, nil, "um" },
  [399956] = { "即座に両手の武器で攻撃し、武器ダメージの$N1%に加えて各武器でさらに$N2のダメージを与えます。Poisonedの対象へのダメージは$N3%増加します。Comboポイントを$N4得ます。", nil, 0xa12beab4, nil, "um" },
  [399962] = { "Mutilateの能力を得ます：\n\n$I1\n両方の武器で即座に攻撃し、それぞれの武器で武器ダメージの$N1%に加えて$N2の追加ダメージを与えます。Poisonedの対象へのダメージが$N3%増加します。Comboポイントを$N4獲得します。", nil, 0x017062fe, nil, "um" },
  [399965] = { "毒にいくつかの改良を加えます：\n\n対象に他の毒を与えるとき、Deadly Poisonも与えます。\n\n武器に毒が塗られていない場合、Instant Poisonが塗られているかのように、一定の確率でInstant Poisonが発動します。\n\nDeadly PoisonとInstant Poisonが、Attack Powerによって増加したダメージを得るようになります。\n\nあなたのDeadly Poisonは、他のRogueのDeadly Poisonを受けている対象にも有効になります。", nil, 0xd4dbe68d, nil, "um" },
  [399966] = { "Runeが刻まれたLegsスロットのアイテムを装備すると、このスロットのアビリティが有効になります。", nil, 0x73ddef7a, nil, "um" },
  [399967] = { "Runeが刻まれたHandsスロットのアイテムを装備すると、このスロットのアビリティが有効になります。", nil, 0x55d903a3, nil, "um" },
  [399969] = { "Deadly Brewの能力を得ます：\n\n$I1\n毒にいくつかの改良を加えます：\n\n対象に他の毒を与えるとき、Deadly Poisonも与えます。\n\n武器に毒が塗られていない場合、Instant Poisonが塗られているかのように、一定の確率でInstant Poisonが発動します。\n\nDeadly PoisonとInstant Poisonが、Attack Powerによって増加したダメージを得るようになります。\n\nあなたのDeadly Poisonは、他のRogueのDeadly Poisonを受けている対象にも有効になります。", nil, 0x20d1c1da, nil, "um" },
  [399985] = { "対象の背後にテレポートして攻撃し、対象に武器ダメージの$N1%を与えます。隠密状態である必要があります。コンボポイントを$N2得ます。", nil, 0x8e972e2d, nil, "um" },
  [399986] = { "敵に手裏剣を投げ、Attack Powerの$N1%に等しいダメージを与え、さらに周囲の対象を最大$N2体攻撃します。命中した対象一体ごとにコンボポイントを$N3得ます。", nil, 0x22f72854, nil, "um" },
})
