-- GENERATED by `wfj generate` from data/spell/spell-1266.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [1266339] = { "Evenshadeの日誌に欠けているページを加えます。", nil, 0x7643c4e2, nil, "um" },
})
