-- GENERATED by `wfj generate` from data/spell/spell-1323.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [1323075] = { "Kyleに昼食を届けます！", nil, 0x43ed5da4, nil, "um" },
})
