-- GENERATED by `wfj generate` from data/spell/spell-0366.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [366881] = { "召喚の円を使ってincubusを呼び出します。", nil, 0xcff16dcb, nil, "um" },
  [366894] = { "召喚の円を使ってincubusを呼び出します。", nil, 0xcff16dcb, nil, "um" },
  [366902] = { "召喚の円を使ってincubusを呼び出します。", nil, 0xcff16dcb, nil, "um" },
})
