-- GENERATED by `wfj generate` from data/spell/spell-0457.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [457012] = { "霊液で覆います。", nil, 0x3a8ea46c, nil, "um" },
})
