-- GENERATED by `wfj generate` from data/spell/spell-1256.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [1256151] = { "Right ClickでDiabloを召喚、または解放します。", nil, 0xf1cae78a, nil, "um" },
})
