-- GENERATED by `wfj generate` from data/spell/spell-0406.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [406634] = { "騎乗できるAnimated Lobster Moltを呼び出し、または帰します。", "地上での移動速度が$N1%上昇します。", 0x8f33b9b6, 0x2195529a, "uu" },
  [406651] = { "他の$N1個の断片と組み合わせて、完全なルーンを作ります。", nil, 0x4c2b39fd, nil, "um" },
  [406746] = { "前方のすべての敵に加圧された水を浴びせます。", nil, 0xed9b064c, nil, "um" },
})
