-- GENERATED by `wfj generate` from data/spell/spell-1320.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [1320269] = { "対象を殴りつけ、$N1のPhysicalダメージを与えます。対象がこちらを向いている場合は$N2倍のダメージを与えます。", nil, 0x04e243bc, nil, "um" },
  [1320330] = { "すべての魔法の呪文と効果による回復量を最大$N1、ダメージを最大$N2増加させます。StrongholdsとCitiesではこの効果が二倍になります。", nil, 0xdf4764d4, nil, "um" },
  [1320332] = { nil, "StrongholdまたはCityでは、与える治療量が最大$N1、呪文ダメージが最大$N2増加します。", nil, 0xf6167773, "mu" },
  [1320498] = { "近くの敵にThunderstompを放ち、$N1のNatureダメージを与えます。", nil, 0x96e923c5, nil, "um" },
  [1320579] = { "$D1の間、近くの敵の速度を$N1%低下させます。Desertの地域では$N3%まで低下します。", "移動速度が$N1%低下しています。", 0x124abd59, 0x09876d53, "uu" },
  [1320643] = { "水中で息が続く時間が通常より$N1%長くなります。", "水中で呼吸できます。", 0x8f8e90b1, 0x37a59b8c, "uu" },
  [1320658] = { "silithidの巣を開き、群れを解き放ちます。", nil, 0x22f9e378, nil, "um" },
  [1320726] = { "Feral Combatが+$N1上昇します。", "Feral Combatが+$N1上昇しています。", 0x3029c093, 0x302accb7, "uu" },
  [1320758] = { "右クリックでSpawn of Grubthorを召喚・解除します。", nil, 0x2f66ba80, nil, "um" },
  [1320808] = { "対象を負傷させ、$N1のダメージを与えます。", nil, 0xdaa3fed4, nil, "um" },
  [1320824] = { "対象を負傷させて出血させ、$D1かけて$N1のダメージを与えます。", "$D1ごとに$N1の出血ダメージを受けています。", 0x47f171f5, 0x72a94853, "uu" },
  [1320864] = { "この槍は使う前に鍛え直す必要があります。槍を鍛え直すには、Mithril Bars 40個、Truesilver Bars 10個、Aquamarine 8個、Solid Grinding Stone 4個、Elemental Fire 2個が必要です。", nil, 0xb280519c, nil, "um" },
  [1320898] = { "Unstable Mana Riftに投げ込みます。", nil, 0xee05b862, nil, "um" },
  [1320922] = { "以下のリストにあるいずれかの束で木箱を満たします：|cnIQ1:- Bronze Tube\r ×$N1- Whirring Bronze Gizmo\r ×$N2- Bronze Framework\r ×$N3- Gold Power Core ×$N4", nil, 0xa780e349, nil, "um" },
  [1320925] = { "$D2の間、$D1ごとに対象を焼き、$N1のFireダメージを与えます。", "$D1ごとに$N1のFireダメージを受けています。", 0x9a11784e, 0x5a5656de, "uu" },
})
