-- GENERATED by `wfj generate` from data/spell/spell-1222.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [1222018] = { "Sulphur Ventに置きます。", nil, 0x2250071d, nil, "um" },
  [1222050] = { "Suspicious Collection Equipmentのそばに置きます。", nil, 0x125a20ff, nil, "um" },
  [1222974] = { "持続ダメージ呪文によるダメージを$N1%増加させます。", nil, 0x13698c8f, nil, "um" },
  [1222988] = { "Earthbind Totemを設置すると、近くの対象を$D1の間Immobilizeします。", nil, 0x9162eb04, nil, "um" },
  [1222994] = { "持続ダメージ呪文によるダメージを$N1%増加させます。", nil, 0x13698c8f, nil, "um" },
  [1222997] = { "持続ダメージ呪文によるダメージを$N1%増加させます。", nil, 0x13698c8f, nil, "um" },
})
