-- GENERATED by `wfj generate` from data/spell/spell-0433.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [433427] = { "生き延びている限り、自然の猛威から身を守ります。", "心がぽかぽかと温かくなります。", 0x0590d635, 0xa188eb32, "uu" },
  [433551] = { "古代の苗木に水を与えます。", nil, 0xf84149f3, nil, "um" },
  [433672] = { "対象を挑発して自分を攻撃させます。ただし、対象がすでに自分を攻撃している場合は効果がありません。", nil, 0x71de38fd, nil, "um" },
  [433813] = { "次にSoul Shardを消費する呪文は、Soul Shardを消費せずに唱えられます。", "次にSoul Shardを消費する呪文は、Soul Shardsを消費せずに詠唱できます。", 0x4defdf27, 0x4defdf27, "uu" },
  [433883] = { "Copper Blood Coin 100枚をSilver Blood Coin 1枚に変換します。", nil, 0xdb882cf5, nil, "um" },
  [433884] = { "Silver Blood Coin 100枚をGold Blood Coin 1枚に変換します。", nil, 0xcdf2465b, nil, "um" },
})
