-- GENERATED by `wfj generate` from data/spell/spell-0432.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [432139] = { "肩スロットのアイテムに永続的なエンチャントを施し、攻撃速度を$N1%上昇させます。", nil, 0x2fdeb6e9, nil, "um" },
  [432190] = { "頭スロットのアイテムに永続的なエンチャントを施し、CatまたはBearの姿に変身した際にエネルギーを20、または怒りを5獲得させます。", nil, 0x8b0dbf5f, nil, "um" },
  [432234] = { "頭部にTidal Wavesのルーンを刻みます：\n\n$I1\nChain HealまたはRiptideを詠唱すると、Tidal Wavesのチャージを$N1得ます。Tidal Wavesは、Healing Waveの詠唱時間を$N2%、Chain Healの詠唱時間を$N3%短縮し、Lesser Healing Waveのクリティカル効果率を$N4%上昇させます。", nil, 0x8a2b3c8f, nil, "um" },
  [432236] = { "手首にRolling Thunderのルーンを刻みます：\n\n$I1\nLightning BoltとChain Lightningは、$N1%の確率で発動中のLightning Shieldにチャージを追加します。最大$N2 Chargesまで蓄積できます。\n\nEarth Shockは、$N3を超えるLightning Shieldのチャージをすべて放出し、そのダメージを対象に与え、放出したチャージごとに最大マナの$N4%を回復するようになります。", nil, 0xe55dbaeb, nil, "um" },
  [432238] = { "手首にStatic Shockのルーンを刻みます：\n\n$I1\nLightning Shieldのチャージが$N1になり、近接攻撃は$N2%の確率（二刀流中は$N3%の確率）でそのチャージを一つ発動させ、即座に対象にダメージを与えます。", nil, 0x307f3a02, nil, "um" },
  [432241] = { "手首にOverchargedのルーンを刻みます：\n\n$I1\nLightning Shieldがチャージを失わなくなり、$D1のクールダウンを持つようになり、$N2ヤード以内のすべての敵にダメージを与えます。", nil, 0xa17d3e6e, nil, "um" },
  [432259] = { "オフハンド武器で近接ダメージを与えるたびに、$N1%の確率でエネルギーを$N2獲得します。", nil, 0xfbdf1f47, nil, "um" },
  [432291] = { "頭部にFocused Attacksのルーンを刻みます：\n\n$I1\n近接または遠隔でクリティカルを与えるたびに、エネルギーを$N1得ます。", nil, 0x8516edd3, nil, "um" },
  [432293] = { "頭部にCombat Potencyのルーンを刻みます：\n\n$I1\nオフハンド武器で近接ダメージを与えるたびに、$N1%の確率でエネルギーを$N2得ます。", nil, 0x495bf4a6, nil, "um" },
  [432295] = { "頭部にHonor Among Thievesのルーンを刻みます：\n\n$I1\nパーティー内のプレイヤーが呪文またはアビリティでクリティカルヒットを与えると、現在の対象へのコンボポイントを一つ得ます。この効果は毎秒一回までしか発生しません。", nil, 0x2bd127e7, nil, "um" },
  [432297] = { "手首にCut to the Chaseのルーンを刻みます：\n\n$I1\nEviscerateとEnvenomにより、Slice and DiceまたはBlade Danceの持続時間が5コンボポイントの最大値まで更新されます。両方が有効な場合は、残り時間が短い方だけが更新されます。", nil, 0x7d169149, nil, "um" },
  [432299] = { "手首にCarnageのルーンを刻みます：\n\n$I1\n自分のBleed効果のいずれかを受けている対象へのアビリティのダメージが$N1%増加します。また、Ruptureは与えたダメージの$N2%分、自分を回復します。", nil, 0xf0efc132, nil, "um" },
  [432301] = { "手首にUnfair Advantageのルーンを刻みます：\n\n$I1\n攻撃を回避または受け流すたびにUnfair Advantageを得て反撃し、メインハンド武器のダメージの$N1%を与え、コンボポイントを$N2得ます。これは毎秒一回までしか発生しません。", nil, 0xf11d0a7e, nil, "um" },
})
