-- GENERATED by `wfj generate` from data/spell/spell-0367.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [367062] = { "指定した場所に松明を投げ、火を起こします。", nil, 0x069f4ed7, nil, "um" },
})
