-- GENERATED by `wfj generate` from data/spell/spell-0464.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [464945] = { "ShadowstrikeをThunderstrikeに変えます。", nil, 0xe0d5f71b, nil, "um" },
  [464946] = { "ThunderstrikeをShadowstrikeに変えます。", nil, 0x144434fe, nil, "um" },
})
