-- GENERATED by `wfj generate` from data/spell/spell-0346.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [346285] = { "これはすべてただのごっこ遊びです。\nあなたは自分がより強く、よりたくましくなったと想像します。\nPlagueにも耐えられると確信しています……", "これはすべてただのごっこ遊びです。\nあなたは自分がより強く、よりしぶとくなったと想像しています。\nそれに、本当はそこまで寒くありません……\n体力が$N1増加します。\nダメージが$N2%増加します。\n回復量が$N3%増加します。\nFrost耐性が$N4増加します。", 0x282a3728, 0x7682f743, "uu" },
})
