-- GENERATED by `wfj generate` from data/spell/spell-0383.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [383895] = { nil, "ダメージが$N1%増加します。\n体力が$N2%増加します。", nil, 0x9915aaee, "mu" },
})
