-- GENERATED by `wfj generate` from data/spell/spell-1280.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [1280003] = { "Windsong Crawlerを手なずけ始め、$N1分間の仲間にします。何らかの理由で獣の注意がそれると、手なずけは失敗します。", nil, 0x0ce34286, nil, "um" },
  [1280046] = { "Ornery Galestriderを手なずけ始め、$N1分間の仲間にします。何らかの理由で獣の注意がそれると、手なずけは失敗します。", nil, 0xc9301e21, nil, "um" },
  [1280481] = { "道具を盗むキツネを$D1の間、動けなくします。", "移動できません。", 0x40fc8f06, 0x18deeb81, "uu" },
})
