-- GENERATED by `wfj generate` from data/spell/spell-1276.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [1276954] = { "この容器には、Wetlands南部の滝の近くにある汽水湖の水を満たす必要があります。", nil, 0x8adbc028, nil, "um" },
})
