-- GENERATED by `wfj generate` from data/spell/spell-0364.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [364812] = { "対象の魔法を解除し、味方からは有害な呪文を$N1個、敵からは有益な呪文を$N2個取り除きます。", nil, 0xf935d550, nil, "um" },
})
