-- GENERATED by `wfj generate` from data/spell/spell-1244.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [1244625] = { "Ley Line Riftから魔力を吸い上げます。", nil, 0xc3bcd1fd, nil, "um" },
  [1244863] = { "healthを即座に$N1回復しますが、その量の$N2%を時間をかけて受けることになります。\n\nこの効果の症状は、$D1の毒か、$D2の病気として現れます。", nil, 0x998c6850, nil, "um" },
  [1244864] = { "healthを即座に$N1回復しますが、その量の$N2%を時間をかけて受けることになります。\n\nこの効果の症状は、$D1の毒か、$D2の病気として現れます。", nil, 0x998c6850, nil, "um" },
  [1244865] = { "healthを即座に$N1回復しますが、その量の$N2%を時間をかけて受けることになります。\n\nこの効果の症状は、$D1の毒か、$D2の病気として現れます。", nil, 0x998c6850, nil, "um" },
  [1244866] = { "healthを即座に$N1回復しますが、その量の$N2%を時間をかけて受けることになります。\n\nこの効果の症状は、$D1の毒か、$D2の病気として現れます。", nil, 0x998c6850, nil, "um" },
  [1244867] = { "healthを即座に$N1回復しますが、その量の$N2%を時間をかけて受けることになります。\n\nこの効果の症状は、$D1の毒か、$D2の病気として現れます。", nil, 0x998c6850, nil, "um" },
})
