-- GENERATED by `wfj generate` from data/spell/spell-0363.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [363731] = { "体力が$N1%増加しています。", "|cFFffd200Bonus Event: Season of Mastery|r\n\n体力が$N1%増加します。", 0x334d75a3, 0x58597bce, "uu" },
  [363757] = { "体力が$N1%増加しています。", "|cFFffd200Bonus Event: Season of Mastery|r\n\n体力が$N1%増加します。", 0x334d75a3, 0x58597bce, "uu" },
  [363880] = { "$D1ごとに体力を$N1回復し、筋力を$N3上げます。効果時間は$D2です。", nil, 0xe80845d1, nil, "um" },
  [363881] = { "$D1かけて体力を$N1回復します。この回復量は最初が最も多くなります。最後まで回復すると、$D2の間、筋力が$N3増加します。", "$D1かけて体力を$N1回復しています。", 0xc6345c7d, 0xf8430e70, "uu" },
})
