-- GENERATED by `wfj generate` from data/spell/spell-0470.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [470037] = { "内なる炎と同調し、Catの姿を、より炎に満ちた外見に置き換えられるようにします。", "炎の姿をまといつつあります……", 0x285a3d7d, 0xcbb2b456, "uu" },
  [470078] = { "Crusader Strike呪文が、最大マナの$N1%を追加で回復します。", nil, 0xe7ed3766, nil, "um" },
  [470079] = { "Starfallによるダメージを$N1%増加させますが、その半径が$N2%縮小します。", nil, 0x57f4abd8, nil, "um" },
  [470080] = { "Ferocious Biteアビリティが追加のエネルギーをダメージに変換しなくなり、Dodge、Miss、Parryのときにエネルギーを$N1返還します。", nil, 0xd8d1e9ae, nil, "um" },
  [470081] = { "Shieldを装備している間、Rockbiter Weaponでの近接攻撃がMaelstrom Weaponのルーンを$N1%多く発動させます。", nil, 0x6514c9b2, nil, "um" },
  [470105] = { "Elemental Focusのタレントのチャージが最大$N1になり、発動時にチャージが$N2に設定されます。", nil, 0x6b2aa54f, nil, "um" },
  [470235] = { "Windfury Weaponの攻撃による攻撃力ボーナスを$N1増加させます。", nil, 0xa5087cac, nil, "um" },
  [470240] = { "メインハンドの武器にFrostbrand Weaponが有効な間、Water Shieldが発動すると、$D1以内に次に唱えるChain Lightning呪文の詠唱時間が$N2%短縮され、ダメージが$N3%増加します。最大5回までスタックします。", nil, 0x475ff82f, nil, "um" },
  [470246] = { "Holy Shock呪文でダメージを与えると、$D1以内に次に唱えるHoly Wrathの詠唱時間とマナコストが$N2%減少し、ダメージが$N3%増加します。最大5回までスタックします。", nil, 0x1759506a, nil, "um" },
  [470263] = { "Avenger's Shieldが命中する対象の数が$N1減りますが、その対象には$N2回命中します。", nil, 0x4d101a0f, nil, "um" },
  [470266] = { "Nourishの回復量を最大$N1増加させます。", nil, 0x3bf51ee9, nil, "um" },
  [470269] = { "Lacerateの初撃と、スタックごとの周期ダメージを$N1増加させます。", nil, 0xd65b62b3, nil, "um" },
  [470345] = { "$D1かけて$N1のダメージを回復します。", "$N2秒ごとに$N1のダメージを回復します。", 0xcb31688f, 0x4b6eb5c1, "uu" },
  [470362] = { "$D1かけて体力を$N1回復します。食事中は座っている必要があります。10秒間食事を続けると、$D2の間、Spell Damageも$N4上昇します。", "毎秒体力を$N1回復します。", 0xcf7a6227, 0xfde4540f, "uu" },
  [470369] = { "$D1かけて体力を$N1回復します。食事中は座っている必要があります。10秒間食事を続けると、$D2の間、Healingの量も$N4上昇します。", "毎秒体力を$N1回復します。", 0x74db8454, 0xfde4540f, "uu" },
  [470497] = { "Nefarianの皮から鱗を切り取ります。戦いでNefarianが大きく弱っているときにのみ使用できます。", nil, 0xc2204a7e, nil, "um" },
})
