-- GENERATED by `wfj generate` from data/spell/spell-0043.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [43308] = { "近場の釣り場がminimapに現れます。", "Fishを探しています。", 0xdd2472bd, 0xe5f3a7f3, "uu" },
})
