-- GENERATED by `wfj generate` from data/spell/spell-1229.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [1229305] = { "Mount of the High CommanderであるClimhazzardを召喚します。速度が$N1%上昇します。", "地上での移動速度が$N1%上昇します。", 0x1e8d4e88, 0x2195529a, "uu" },
  [1229308] = { "騎乗できるScarlet Steedを召喚、または解散させます。非常に速い乗り物です。", "地上での移動速度が$N1%上昇します。", 0xc130c7fd, 0x2195529a, "uu" },
  [1229340] = { "Will of The Ashbringerとの接触を試みます。", nil, 0x15e33fe8, nil, "um" },
  [1229402] = { "ベルトを再利用可能な仕掛けで強化する方法を習得します。", nil, 0xbaa982af, nil, "um" },
  [1229432] = { "Camp Tentを作製します。", nil, 0x689e3f0e, nil, "um" },
  [1229504] = { "Faction Bannerを作製します。", nil, 0xd67a2145, nil, "um" },
  [1229517] = { "Camp Chairを作製します。", nil, 0x0819b343, nil, "um" },
  [1229705] = { "Incense Candleを作製します。", nil, 0x53987f01, nil, "um" },
  [1229737] = { "Basic Campfireを作製します。", nil, 0x7d3775e0, nil, "um" },
  [1229745] = { "Fish Bowlを作製します。", nil, 0x06662444, nil, "um" },
})
