-- GENERATED by `wfj generate` from data/spell/spell-1258.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [1258367] = { "敵に骨を投げつけ、Physicalダメージを与えます。", nil, 0x26b57c00, nil, "um" },
  [1258429] = { "Fillion Flamebreezeを運んでいます。動きが重く、攻撃されるとFillionを降ろして逃げざるを得なくなることがあります！\n\n何としても戦闘を避けてください。", "Fillion Flamebreezeを運んでいます。荷物が重く、攻撃されるとFillionを落として逃げることになるかもしれません！\n\n何としても戦闘を避けてください。", 0x4132f51b, 0x4132f51b, "uu" },
  [1258447] = { nil, "データを収集中……", nil, 0x6e783355, "mu" },
  [1258478] = { "敵を打ち据え、Holyダメージを与えます。", nil, 0x20941603, nil, "um" },
  [1258483] = { "Index Esoteriaを起動し、Shen'dar HighlandsのOverlook Standing Stonesで魔法のデータを収集します。", nil, 0xd78474f5, nil, "um" },
  [1258494] = { "呪文と効果による回復量が最大$N1、呪文と効果によるダメージが最大$N2増加します。", nil, 0x0d145ac0, nil, "um" },
  [1258496] = { "精神 +$N1。", nil, 0xce2f9b3c, nil, "um" },
  [1258510] = { "$D1の間、走る速度が$N1%上昇します。", "活力を与える風に触れました。走る速度が$N1%上昇します。\n\n敵対的な行動をとると、この効果は終わります。", 0x61fe647b, 0x7d501c7c, "uu" },
  [1258518] = { "ドルイドの結界を通り抜け、Mount Hyjalへ入ります。", nil, 0xf9ad16b6, nil, "um" },
  [1258520] = { "Pounceで飛びかかり、$D1の間対象をスタンさせ、$D2かけて$N2のダメージを与えます。忍び歩き状態で対象の背後にいる必要があります。コンボポイントを$N4獲得します。", "スタンしています。", 0x97420bb2, 0x27f95286, "uu" },
  [1258773] = { "Westfallの農場の井戸から水のサンプルを採取します。", nil, 0x345ca815, nil, "um" },
  [1258784] = { "Imbued TearsとPetrified Barkを組み合わせてRudimentary Necromancy Staffを作成します。", nil, 0x67cc52ab, nil, "um" },
  [1258812] = { "Orgrul's Skeletonsに死霊術のエネルギーを注入しようと試みます。", nil, 0xbb88d223, nil, "um" },
  [1258822] = { "Deadminesの鋳造所のそばに爆薬を設置します。", nil, 0xc291176b, nil, "um" },
})
