-- GENERATED by `wfj generate` from data/spell/spell-0365.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [365122] = { "$D1の間、術者の攻撃速度を$N1%、術者が与えるPhysicalダメージを$N2増加させます。", "与える物理ダメージが$N1増加しています。\n攻撃速度が$N2%上昇しています。", 0x1d3f8a49, 0xbc6c8e1d, "uu" },
  [365663] = { "敵のアーマーを削り、Sunder Armorごとに$N1下げます。最大5回まで重ねられます。効果時間は$D1です。", "アーマーが低下しています。", 0xb4e55d0c, 0xc3d1fc4c, "uu" },
})
