-- GENERATED by `wfj generate` from data/spell/spell-0036.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [36936] = { "トーテムを大地に還し、Totemic Recallで破壊した各トーテムの詠唱に必要なmanaの$N1%を得ます。", nil, 0x7e7acb66, nil, "um" },
})
