-- GENERATED by `wfj generate` from data/spell/spell-1290.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [1290131] = { "Right Clickで仲間を召喚、または解放します。", nil, 0x7f158c13, nil, "um" },
  [1290242] = { "負傷した兵士の手当てをします。", nil, 0xeacfd796, nil, "um" },
  [1290261] = { "武器の種類に応じて、近接武器攻撃に効果が付与されます。\n\n|CFFFFFFFFAxe/Polearm:|R クリティカルヒットの\n 確率が$N1%上昇します。\n\n|CFFFFFFFFMace/Staff:|R 攻撃が対象のアーマーの\n $N2%を無視します。\n\n|CFFFFFFFFSword:|R 近接攻撃が成功すると、\n $N3%の確率で対象に\n 追加攻撃を行います。", nil, 0x27838c1f, nil, "um" },
  [1290859] = { "$D1かけて体力を$N1、マナを$N2回復します。食事中は座っている必要があります。Darkspear Islandsの中でのみ使用できます。", nil, 0xf40fa690, nil, "um" },
  [1290860] = { "$D1かけて体力を$N1、マナを$N2回復します。食事中は座っている必要があります。Darkspear Islandsの中でのみ使用できます。", nil, 0xc9e5c5cc, nil, "um" },
  [1290861] = { "$D1かけて体力を$N1、マナを$N2回復します。食事中は座っている必要があります。Darkspear Islandsの中でのみ使用できます。", "毎秒体力を$N1、マナを$N2回復します。", 0x10d1e095, 0x41faa520, "uu" },
  [1290863] = { "$D1かけて$N1のダメージを回復します。Darkspear Islandsの中でのみ使用できます。", "$D1ごとに$N1のダメージを回復しています。", 0xaa1d1278, 0xc0a38409, "uu" },
  [1290865] = { "$D1かけて$N1のダメージを回復します。Darkspear Islandsの中でのみ使用できます。", "$D1ごとに$N1のダメージを回復しています。", 0xaa1d1278, 0xc0a38409, "uu" },
  [1290867] = { "$D1かけて$N1のダメージを回復します。Darkspear Islandsの中でのみ使用できます。", "$D1ごとに$N1のダメージを回復しています。", 0xaa1d1278, 0xc0a38409, "uu" },
  [1290950] = { "対象を傷つけて$N1のダメージを与え、$D1の間、すべての呪文の詠唱時間を$N2%増加させます。", "詠唱時間が$N1%長くなっています。", 0x4dfe9f76, 0x1c80d8ef, "uu" },
})
