-- GENERATED by `wfj generate` from data/spell/spell-1260.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [1260031] = { "Accursed Skullにかけられた死霊術の呪いを解こうと試みます。", nil, 0x9b828052, nil, "um" },
  [1260189] = { "呪文と攻撃に$N1%の確率で対象からHealthを吸収する効果が付きます。吸収量は最大Healthの$N2%までです。", nil, 0x9589e941, nil, "um" },
  [1260201] = { "呪文と攻撃に$N1%の確率で対象からHealthを吸収する効果が付きます。吸収量は最大Healthの$N2%までです。", nil, 0x9589e941, nil, "um" },
  [1260270] = { "$D1かけて最大Healthの$N1%を回復します。移動、行動、被ダメージのいずれかで効果は中断されます。", "$D1かけて最大Healthの$N1%を回復しています。", 0x5eacd496, 0x992721f4, "uu" },
})
