-- GENERATED by `wfj generate` from data/spell/spell-1284.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [1284017] = { "近くにいるすべての獣の位置をミニマップに表示します。一度に有効にできる追跡は1種類だけです。", "獣を探知しています。", 0x7a0f6d82, 0x5bdf0ba6, "uu" },
  [1284035] = { "フェルの汚染に冒された病気の動物を治療します。", nil, 0xc145bd63, nil, "um" },
  [1284377] = { "毎秒$N1のFrostダメージを与えます。", "毎秒$N1のFrostダメージを与えます。", 0x407cfe6f, 0x407cfe6f, "uu" },
  [1284381] = { "近くの敵に通常のダメージに加えて$N1のダメージを与え、吹き飛ばして$D1の間スタンさせます。", "スタンしています。", 0x476b69d8, 0x27f95286, "uu" },
  [1284384] = { "対象は死亡します", nil, 0x0fda4706, nil, "um" },
  [1284435] = { nil, "与える物理ダメージが$N1増加しています。\n攻撃速度が$N2%上昇しています。", nil, 0xbc6c8e1d, "mu" },
  [1284536] = { "次に使用するHoly Novaはマナを消費しません。", "次のHoly Novaのマナコストがなくなります。", 0x3b7cd96d, 0x3b7cd96d, "uu" },
  [1284560] = { "Darkspear Flagを持っています。\nこの旗を支配下の拠点に運ぶとVictory Pointsを獲得できます。", "Darkspear Flagを持っています。\nこの旗を支配下の拠点に運ぶと、Victory Pointsを得られます。", 0x4d8866b3, 0x4d8866b3, "uu" },
  [1284701] = { "フェルの灰で実験された動物にConcoction of Cleansingを使用します。", nil, 0x8ab34ce5, nil, "um" },
  [1284734] = { "走る速度と泳ぐ速度を$N1%上昇させます。", "走る速度と泳ぐ速度が$N1%上昇しています。", 0x8cde9701, 0x9f1cfad8, "uu" },
  [1284783] = { "Barkskin Burrowのfurbolgとの評判を永続的に上げます。", nil, 0x900cff67, nil, "um" },
})
