-- GENERATED by `wfj generate` from data/spell/spell-0134.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [134735] = { nil, { "クリティカル回復で受ける回復量が$N1%減少します。\n受けるダメージが$N2増加します。", "クリティカル回復で受ける回復量が$N1%減少します。", shape = { "2/0", "1/0" } }, nil, 0x7ccfc727, "mu" },
})
