-- GENERATED by `wfj generate` from data/spell/spell-1262.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [1262975] = { "Rock Gardenを製作します。", nil, 0x5f07d9f6, nil, "um" },
  [1262978] = { "Cookie's Feastを製作します。", nil, 0xe774a718, nil, "um" },
  [1262980] = { "Greenhouseを製作します。", nil, 0x8e33bc5a, nil, "um" },
  [1262982] = { "Trapper's Workbenchを製作します。", nil, 0xd8ee93ab, nil, "um" },
  [1262985] = { "Field Guideを製作します。", nil, 0x08c12d8d, nil, "um" },
  [1262990] = { "Fishing Rackを製作します。", nil, 0xed8e62ff, nil, "um" },
  [1262996] = { "Toxin Studyを製作します。", nil, 0x20d9d40a, nil, "um" },
  [1262998] = { "Fishing Hutを製作します。", nil, 0x3b1eb705, nil, "um" },
})
