-- GENERATED by `wfj generate` from data/spell/spell-0455.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [455876] = { "煤を磨き落とします。", nil, 0x2b57291d, nil, "um" },
})
