-- GENERATED by `wfj generate` from data/spell/spell-1227.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [1227019] = { "Fel-Touched Flowerを三つ組み合わせて、悪魔の影を一時的に見えるようにするポーションを作ります。", nil, 0xd8072b95, nil, "um" },
  [1227022] = { "使用者がFelwoodの中で悪魔の影を一時的に見られるようにします。", "一時的に悪魔の影を探知します。", 0xe41c07dc, 0xadfae0b1, "uu" },
  [1227080] = { "Carrie Hearthfireの一番人気のごちそうのレシピの作り方を習得します。", nil, 0x86b738e2, nil, "um" },
  [1227369] = { "$D2の間、Searing PainとShadow Cleaveの詠唱時間とグローバルクールダウンを$N1秒短縮します。", "$D2の間、Searing PainとShadow Cleaveの詠唱時間とグローバルクールダウンが$N1秒短縮されています。", 0x18f4cfb0, 0x18f4cfb0, "uu" },
})
