-- GENERATED by `wfj generate` from data/spell/spell-0362.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [362859] = { "クエストで得られる経験値が$N1%増加しています。", "|cFFffd200Season of Mastery|r\n\nクエストで獲得する経験値とゴールドが$N1%増加します。ダンジョンクエストとEliteクエストではボーナス経験値を獲得できます。", 0x21ffc30d, 0x9213b1f9, "uu" },
})
