-- GENERATED by `wfj generate` from data/spell/spell-1242.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [1242634] = { "相手の攻撃をパリィした後に使用可能になる攻撃です。武器ダメージの$N1%に$N2を加えたダメージを与え、対象を$D1の間移動不能にします。Counterattackはブロック、回避、パリィされません。", "動けません。", 0xbfd6d532, 0x7d75228d, "uu" },
})
