-- GENERATED by `wfj generate` from data/spell/spell-0063.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [63624] = { "Second Talent Specializationを習得します。", "Second Talent Specializationを習得します。", 0xff7c2da5, 0xff7c2da5, "uu" },
  [63644] = { "Secondary Talent Specializationに切り替えます。", "Secondary Talent Specializationに切り替えます。", 0x9e9d4a4e, 0x9e9d4a4e, "uu" },
  [63645] = { "Primary Talent Specializationに切り替えます。", "Primary Talent Specializationに切り替えます。", 0x10b2821a, 0x10b2821a, "uu" },
})
