-- GENERATED by `wfj generate` from data/spell/spell-0077.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [77746] = { "Fireのトーテムが、$N1ヤード以内のパーティーとレイドのメンバーの呪文力を$N2%上げるようになります。", nil, 0xf8f56d4c, nil, "um" },
  [77747] = { "Fireのトーテムが、$N1ヤード以内のパーティーとレイドのメンバーの呪文力を$N2%上げるようになります。", "呪文の威力が$N1%上昇します。", 0x1c74433c, 0x232b01bb, "uu" },
})
