-- GENERATED by `wfj generate` from data/spell/spell-0243.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [243819] = { "お気に入りのペットを呼び出したり帰したりします。お気に入りのペットがいない場合は、コレクション全体から選ばれます。", nil, 0xbf957e76, nil, "um" },
})
