-- GENERATED by `wfj generate` from data/spell/spell-0474.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [474116] = { "$N1のNatureダメージを吸収します。効果時間は$D1です。", "natureダメージを$N1吸収します。", 0x61752927, 0x3df0dfc8, "uu" },
  [474127] = { "周期的でないNatureのダメージ呪文がクリティカルヒットすると、一定の確率で$D1の間、呪文ダメージが$N1上昇します。", nil, 0xab841da9, nil, "um" },
  [474142] = { "周期的でないダメージ呪文を使うと、$D1の間、呪文ダメージが$N1上昇します。対象がプレイヤーの操作するものであれば、代わりに$D2の間、呪文貫通が$N3上昇します。", nil, 0x34e80ede, nil, "um" },
  [474196] = { "ダメージ呪文の詠唱時に一定の確率で、Visions of the Qiraji Prophetsを呼び出します。", nil, 0xfb7b94d5, nil, "um" },
  [474236] = { "$D1以内に唱える次の呪文が即時詠唱になります。", "次の呪文が即時詠唱になります。", 0x0b45c4ad, 0x71a46f0d, "uu" },
  [474386] = { "移動を妨げる効果と、キャラクターの操作を失わせる効果をすべて解除します。", nil, 0x5922de69, nil, "um" },
})
