-- GENERATED by `wfj generate` from data/spell/spell-1283.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [1283133] = { "弱らせたTwilight's Thrallを捕らえます。弱った敵にのみ有効です。", nil, 0xa33005e4, nil, "um" },
  [1283137] = { "餌を置いて海の怪物をおびき寄せます。", nil, 0xc2f265f5, nil, "um" },
  [1283400] = { "Journeyman Campfireを製作します。", nil, 0xd3ced4e9, nil, "um" },
  [1283932] = { "Right ClickでDiabloを召喚、または解放します。", nil, 0xf1cae78a, nil, "um" },
})
