-- GENERATED by `wfj generate` from data/spell/spell-0048.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [48108] = { "Fireball、Fire Blast、Scorch、Living Bomb、Frostfire Boltで呪文のクリティカルを2回連続で出すたびに、一定の確率で、$D1以内に唱える次のPyroblastが即時発動になります。", "次のPyroblastの呪文が即時詠唱になります。", 0x200c4cec, 0xbf94c763, "uu" },
})
