-- GENERATED by `wfj generate` from data/spell/spell-0065.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [65183] = { "Venomhide Hatchlingを呼び出します。Un'Goro Crater、Tanaris、Silithusでのみ使用できます。", nil, 0xe64abc24, nil, "um" },
})
