-- GENERATED by `wfj generate` from data/spell/spell-1319.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [1319047] = { "Attack Powerが+$N1されます。アンデッドの対象に対しては二倍になります。", nil, 0x235b154d, nil, "um" },
  [1319256] = { "Loren Ravenlockを召喚し、Umbrinothとの戦いを手伝わせます。", nil, 0xd36af0d1, nil, "um" },
  [1319311] = { { "$D1かけて体力を$N1回復します。食事中は座っている必要があります。10秒以上食事をすると満腹状態になり、$D3の間、アーマーが$N4上昇します。さらに、敵を倒して得る経験値が$N6%増加します。", "$D1かけて体力を$N1回復します。食事中は座っている必要があります。10秒以上食事をすると満腹状態になり、$D3の間、アーマーが$N4上昇します。", shape = { "6/3", "5/3" } }, nil, 0xa37508da, nil, "um" },
  [1319421] = { "Deathguardの一員を激励します。", "任務に戻りました。", 0x664cd0c8, 0xda9be9e6, "uu" },
  [1319423] = { "Stranglethorn ValeとRivergladesで移動速度が$N1%上昇します。", "移動速度が$N1%上昇しています。", 0x1dd0ad7e, 0xd5c3ac7c, "uu" },
  [1319426] = { "Stranglethorn ValeとRivergladesで移動速度が$N1%上昇します。", "移動速度が$N1%上昇しています。", 0x1dd0ad7e, 0xd5c3ac7c, "uu" },
  [1319427] = { "Stranglethorn ValeとRivergladesで移動速度が$N1%上昇します。", "移動速度が$N1%上昇しています。", 0x1dd0ad7e, 0xd5c3ac7c, "uu" },
  [1319453] = { "誰かが開けられるように、お祝いのプレゼントを置きます。", nil, 0xfade3fef, nil, "um" },
})
