-- GENERATED by `wfj generate` from data/spell/spell-1241.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [1241582] = { "両方の武器で即座に攻撃し、それぞれの武器で武器ダメージの$N1%に加えて$N2の追加ダメージを与えます。Poisonedの対象にはダメージが$N3%増加します。Combo Pointを$N4獲得します。", nil, 0x31535b05, nil, "um" },
  [1241584] = { "両手の武器で即座に攻撃し、武器ダメージの$N1%に加えて、それぞれの武器でさらに$N2のダメージを与えます。Poisoned状態の対象に対するダメージが$N3%増加します。Comboポイントを$N4獲得します。", nil, 0xed0e4713, nil, "um" },
})
