-- GENERATED by `wfj generate` from data/spell/spell-1224.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [1224125] = { "敵を沈黙させ、$D1の間呪文を唱えられなくします。", "呪文を詠唱できません。", 0x92e27777, 0x6d133d61, "uu" },
  [1224315] = { "その場に縛り付けられています。", "その場に根を張っています。", 0xeb220d13, 0xeb220d13, "uu" },
  [1224410] = { "対象の武器または盾に塗布している間、アンデッドに対する呪文ダメージが最大60増加します。効果時間は1時間です。", nil, 0xa4a14416, nil, "um" },
  [1224422] = { "対象の武器または盾に塗布している間、アンデッドに対する攻撃力が100増加します。効果時間は1時間です。", nil, 0x1020c5f4, nil, "um" },
  [1224428] = { "Scourgeの軍勢が力を増しています。", "Scourgeの軍勢と交戦しています。\n\nSeal of the Dawnから得られる恩恵はRank $N1を超えません。", 0xc72f3794, 0xa8fb80a9, "uu" },
  [1224553] = { "Holy ShockとHoly Lightの呪文のクリティカル率を$N1%上昇させます。", nil, 0x0a423554, nil, "um" },
  [1224692] = { "呪文によるすべての回復量を$N1%、受けるすべての回復量を$N2%増加させます。", nil, 0x4065c70b, nil, "um" },
  [1224697] = { "スタミナの合計を$N1%増加させ、Divine Shield、Divine Protection、Templar's Bulwarkの呪文のクールダウンを$N2秒短縮します。", nil, 0x6ff8c6b6, nil, "um" },
  [1224716] = { "Backstabのクリティカル率を$N1%、Mutilateのクリティカル率を$N2%上昇させ、Backstabに$N3%の確率でCombo Pointを追加で一つ加える効果を与えます。", nil, 0xdad38dd6, nil, "um" },
  [1224782] = { "SapとBlindのアビリティのエネルギーコストを$N1%減少させます。", nil, 0x0a58f6d1, nil, "um" },
})
