-- GENERATED by `wfj generate` from data/spell/spell-0413.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [413259] = { "影の魔法を爆発させて対象の敵と周囲の敵にダメージを与え、$D2の間、$N2秒ごとに対象から$N4ヤード以内のすべての敵に$N1のShadowダメージを与えます。", "$N1ヤード以内のすべての目標にshadowダメージを与えています。", 0x7be62c43, 0xcd4e304c, "uu" },
  [413260] = { "対象の敵の周囲で影の魔法を爆発させ、$D2の間、1秒ごとに対象の周囲$N4ヤード以内のすべての敵に$N1のShadowダメージを与えます。", "$N1ヤード以内のすべての目標にshadowダメージを与えています。", 0x0c1e5ae9, 0x5403259a, "uu" },
  [413338] = { nil, "ひらめきに満ちています。", nil, 0x12978998, "mu" },
  [413429] = { nil, "ひらめきに満ちています。", nil, 0x12978998, "mu" },
  [413432] = { nil, "ひらめきに満ちています。", nil, 0x12978998, "mu" },
  [413651] = { "Prairie Flowerを$N1本組み合わせて冠を作ります。", nil, 0x26d07a9c, nil, "um" },
  [413839] = { nil, "ひらめきに満ちています。", nil, 0x12978998, "mu" },
})
