-- GENERATED by `wfj generate` from data/spell/spell-0451.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [451398] = { nil, "Dark Iron Dwarfの変装の仕上げ。", nil, 0x79de3b54, "mu" },
  [451439] = { "ダメージを与えるフィニッシュ技は、コンボポイントごとに$N1%の確率でエネルギーを$N2回復させます。", "ダメージを与えるフィニッシュ技は、コンボポイントごとに$N1%の確率でエネルギーを$N2回復させます。", 0x3337749b, 0x3337749b, "uu" },
  [451714] = { { "Goblin Mortarの作り方を習得します", shape = { "0/0" } }, nil, 0x08e69178, nil, "um" },
})
