-- GENERATED by `wfj generate` from data/spell/spell-0301.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [301089] = { "Hordeの旗を運んでいます。自陣の基地へ持ち帰って奪取しましょう。", "Hordeの旗を運んでいます。自陣に持ち帰って奪取しましょう。", 0xb3934403, 0xb3934403, "uu" },
  [301091] = { "Allianceの旗を運んでいます。自陣の基地へ持ち帰って奪取しましょう。", "Allianceの旗を運んでいます。自陣に持ち帰って奪取しましょう。", 0x044823fc, 0x044823fc, "uu" },
  [301100] = { "落とされた旗を拾えません。", "落ちた旗を拾うことができません。", 0x05dc3374, 0x05dc3374, "uu" },
  [301101] = { "落とされた旗を拾えません。", "落ちた旗を拾うことができません。", 0x05dc3374, 0x05dc3374, "uu" },
})
