-- GENERATED by `wfj generate` from data/spell/spell-0381.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [381598] = { "スケルトンの軍馬を呼び出し、または帰します。この軍馬は召喚者に従順で、Naxxramas内でマウントとして使用できます。騎乗者に敵対行動をとると、軍馬は恐怖で逃げ出します。", "地上での移動速度が$N1%上昇します。", 0x67eeda0f, 0x2195529a, "uu" },
  [381599] = { "スケルトンの軍馬を呼び出し、または帰します。この軍馬は召喚者に従順で、Naxxramas内でマウントとして使用できます。騎乗者に敵対行動をとると、軍馬は恐怖で逃げ出します。", "速度が$N1%上昇します。", 0x67eeda0f, 0xe31f6c8b, "uu" },
})
