-- GENERATED by `wfj generate` from data/spell/spell-0033.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [33389] = { "騎乗スキル75が必要な基本の地上騎乗動物に乗れるようになります。", nil, 0x0703beb2, nil, "um" },
  [33392] = { "騎乗スキル150が必要な速い地上騎乗動物に乗れるようになります。", nil, 0xaa2f0f41, nil, "um" },
})
