-- GENERATED by `wfj generate` from data/spell/spell-1279.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [1279399] = { "乗り物となる軍馬を召喚します。", "地上での移動速度が$N1%上昇します。", 0x0e0de767, 0x2195529a, "uu" },
  [1279523] = { "フェルの汚染に冒された病気の動物を治療します。", nil, 0xc145bd63, nil, "um" },
})
