-- GENERATED by `wfj generate` from data/spell/spell-1288.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [1288237] = { "習得した専門職で集めた看板を$D1の間、掲げます。", nil, 0x16306bbe, nil, "um" },
  [1288261] = { "習得した専門職で集めた看板を$D1の間、掲げます。", nil, 0x16306bbe, nil, "um" },
  [1288298] = { { "アカウントの全キャラクターのOrcish Tradeskill Signトイに、この専門職のサインを追加します。\n\nこのサインを表示したいキャラクターは、その専門職を習得している必要があります。", "アカウントの全キャラクターのDwarven Tradeskill Signトイに、この専門職のサインを追加します。\n\nこのサインを表示したいキャラクターは、その専門職を習得している必要があります。", shape = { "0/0", "0/0" } }, nil, 0x414b01b3, nil, "um" },
  [1288322] = { "読む価値などまったくない長いページの束に、署名し、イニシャルを書き、日付を入れます。\n\n信頼できる筋からのものなので、たぶん大丈夫でしょう。", nil, 0xa2e6d836, nil, "um" },
})
