-- GENERATED by `wfj generate` from data/spell/spell-0363.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [363881] = { "$D1かけて体力を$N1回復します。この回復量は最初が最も多くなります。最後まで回復すると、$D2の間、筋力が$N3増加します。", "$D1かけて体力を$N1回復しています。", 0xc6345c7d, 0xf8430e70, "uu" },
})
