-- GENERATED by `wfj generate` from data/spell/spell-1282.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [1282398] = { "Greenhouseに種を植えて、時間をかけて育てます。", nil, 0x30332618, nil, "um" },
  [1282482] = { "特定のエンチャントを受けた対象を燃え盛る光で焼き、聖なる攻撃と呪文から受けるダメージを増加させます。", "holy攻撃と呪文から受けるダメージが$N1%増加しています。", 0x23218b58, 0x22450bf3, "uu" },
  [1282503] = { "燃え盛る風の渦で対象を焼き、$N1のHolystormダメージを与えます。WolvesとWorgenには$N2倍のダメージを与えます。", nil, 0xeb0f77c3, nil, "um" },
  [1282576] = { "爆薬を仕掛けます。", nil, 0x9cd1a292, nil, "um" },
  [1282736] = { "Greenhouseに種を植えて、時間をかけて育てます。", nil, 0x30332618, nil, "um" },
  [1282737] = { "Greenhouseに種を植えて、時間をかけて育てます。", nil, 0x30332618, nil, "um" },
  [1282738] = { "Greenhouseに種を植えて、時間をかけて育てます。", nil, 0x30332618, nil, "um" },
})
