-- GENERATED by `wfj generate` from data/spell/spell-0419.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [419288] = { nil, "ひらめきに満ちています。", nil, 0x12978998, "mu" },
  [419417] = { "ホームに設定した場所へ戻ります。別の場所のInnkeeperに話しかけると、ホームの場所を変更できます。", nil, 0xf92eb2a9, nil, "um" },
})
