-- GENERATED by `wfj generate` from data/spell/spell-1317.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [1317006] = { "回復呪文を唱えたとき、直前の回復が別の呪文だった場合、その呪文の基本コストの$N1%に等しいManaを得ます。", nil, 0x30029238, nil, "um" },
  [1317256] = { "今後のアップデートで追加予定です。", nil, 0xd09c1e2a, nil, "um" },
  [1317257] = { "強力な蹴りで近接武器ダメージの$N1%を与え、$D1の間、移動速度を$N2%増加させます。", "移動速度が$N1%増加しています。", 0xfe94c845, 0xd64d68fa, "uu" },
  [1317268] = { "半径$N2ヤード以内の対象に$N1のHolyダメージを与えます。時々裏目に出て、対象に光の力を与えてしまうことがあります。", nil, 0xf26ada37, nil, "um" },
  [1317269] = { "光でグレネードを祝福します。", nil, 0xbc391109, nil, "um" },
  [1317279] = { "Heavy Thoriumの延べ棒とFel CrystalをLegionite Barに変成します。", nil, 0xa74829ba, nil, "um" },
  [1317285] = { "Battle RingとThe Maulで受けるダメージを$N1%軽減します。", "Battle RingまたはThe Maulでは、受けるダメージが$N1%減少します。", 0xc18b39cc, 0x6ce139d9, "uu" },
  [1317424] = { "対象を$N1回復します。", nil, 0xbdf1d263, nil, "um" },
  [1317432] = { "$N1のFireダメージを与えます。Earth Elementals、Fire Elementals、Mountain Giantsには$N2倍のダメージを与えます。", nil, 0x1cab7316, nil, "um" },
  [1317441] = { "すべてのResistancesを$N1増加させます。ForestとGrasslandの地域では、すべてのResistancesがさらに$N2増加します。", nil, 0x03fece2e, nil, "um" },
  [1317442] = { nil, "ForestまたはGrasslandの地域では、すべてのResistancesがさらに$N1上昇します。", nil, 0x7c8354af, "mu" },
  [1317443] = { "呪文がMagical Resistancesを$N1貫通します。ForestとGrasslandの地域では、Spell Piercingがさらに$N2増加します。", nil, 0xf4899f94, nil, "um" },
  [1317444] = { nil, "ForestまたはGrasslandの地域では、Spell Piercingがさらに$N1上昇します。", nil, 0x4e10bc74, "mu" },
  [1317446] = { "Ooze Covered Thorium Veinsを採掘したとき、低い確率で追加の鉱石を見つけます。", nil, 0x94aa5d0e, nil, "um" },
  [1317486] = { "Dustwallow MarshとSwamp of Sorrowsで移動速度が$N1%上昇します。", "移動速度 Increased：$N1%上昇しています。", 0xecf527a9, 0x666adc1e, "uu" },
  [1317583] = { "攻撃が高確率で対象を毒に侵し、$D2の間、$N2秒ごとに$N1のNatureダメージを与えます。", "$N2秒ごとに$N1のNatureダメージを受けます。", 0x73c8a5f6, 0xf6322bec, "uu" },
  [1317605] = { "Dalaranの明かりを灯します。", nil, 0xea6a4b6d, nil, "um" },
  [1317740] = { "近くに宝箱があれば、最も近いものを見つけます。屋外でのみ使用できます。", nil, 0x4c47d05a, nil, "um" },
  [1317999] = { nil, "ForestまたはGrasslandの地域では、Attack Powerがさらに$N1上昇します。", nil, 0xc5b620c2, "mu" },
})
