-- GENERATED by `wfj generate` from data/spell/spell-1245.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [1245244] = { "$D1の間、呪文のダメージを最大$N1上げます。", "呪文とアビリティによる魔法ダメージが最大$N1増加します。", 0xbfd948e7, 0xa5bf5341, "uu" },
  [1245249] = { "$D1の間、Physicalダメージを$N1増加させます。", "近接ダメージが$N1増加しています。", 0xaefc85da, 0x3366aaa7, "uu" },
  [1245320] = { "Strange Dust $N1山をMotes of Magic $N2個に分けます。", nil, 0x5b1b13eb, nil, "um" },
  [1245321] = { "下級の魔法のワンドを作成します。", nil, 0xa031b8d5, nil, "um" },
  [1245608] = { "Miningスキルを$N1上昇させます。Miningスキルを$N2より上には上げられません。Miningをまだ習得しておらず、ほかの専門職を2つ習得していない場合は、Miningを習得します。", nil, 0x85844474, nil, "um" },
  [1245609] = { "Herbalismスキルを$N1上昇させます。Herbalismスキルを$N2より上には上げられません。Herbalismをまだ習得しておらず、ほかの専門職を2つ習得していない場合は、Herbalismを習得します。", nil, 0x0f7bd4a7, nil, "um" },
  [1245610] = { "Skinningスキルを$N1上昇させます。Skinningスキルを$N2より上には上げられません。Skinningをまだ習得しておらず、ほかの専門職を2つ習得していない場合は、Skinningを習得します。", nil, 0x0f033a92, nil, "um" },
})
