-- GENERATED by `wfj generate` from data/spell/spell-0285.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [285224] = { nil, "Chromieがあなたを過去に繋ぎ止めておけるのは限られた時間だけです。力が尽きた場合は、彼女が十分なエネルギーを取り戻すまで待ってから、再び戻ってくる必要があります。", nil, 0x7a85694d, "mu" },
})
