-- GENERATED by `wfj generate` from data/spell/spell-0441.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [441448] = { nil, "帯電しています！", nil, 0xe6d88bd0, "mu" },
  [441449] = { "術者の前方の円錐範囲にいる敵に$N1のFireダメージを与えます。", nil, 0xad2ec576, nil, "um" },
  [441450] = { "反マナの矢で敵を撃ち、矢は近くにいる別の敵へと飛び移ります。矢が消費したマナ一ポイントごとに、対象は$N1のダメージを受けます。この呪文は最大$N2体の対象に作用します。", nil, 0xc4e5d106, nil, "um" },
  [441453] = { "$D1の間、敵を動けなくし、電撃を浴びせてNatureダメージを与えます。", "移動できません。", 0x0d2f2b19, 0x18deeb81, "uu" },
  [441454] = { "魔法の衝撃波を放ち、近くの敵にArcaneダメージを与えます。", nil, 0xb94462fd, nil, "um" },
  [441739] = { nil, "幽霊になったような気分です。", nil, 0xfcf0fb0b, "mu" },
  [441785] = { "あなたは貢ぎ物にされました。", "貢ぎ物にされました。", 0x93f5f924, 0x93f5f924, "uu" },
  [441927] = { nil, "幽霊になったような気分です。", nil, 0xfcf0fb0b, "mu" },
})
