-- GENERATED by `wfj generate` from data/spell/spell-0079.jsonl. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("spell", {
  [79429] = { "Elemental Resistanceのトーテムを召喚します。", "耐性が増加しています。", 0x99090e6f, 0x591d68d8, "uu" },
  [79431] = { "Elemental Resistanceのトーテムを召喚します。", "耐性が増加しています。", 0x99090e6f, 0x591d68d8, "uu" },
})
