-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["f52b46daa9db6023"] = { "6日目:\n\n早朝、ThorsenはSergeant Yohwaと長々と話していた。私はまだ眠っているふりをしなければならず、話が聞こえる所まで近づけなかった。だが、Thorsenの先日の外出について話していたのだろう。\n\n昼食のときに奴をじっと見ていたが、Yohwaも同じことをしているのに気づいた。その後、DorenがThorsenを呼び出した。この3人は秘密を共有している。DorenとYohwaは、Thorsenがあなた方の工作員と会っていることを知っているに違いない。\n\n奴は反乱軍のために密偵をしているのだ。", "." },
  ["f5620e7ef2ed8df5"] = { "第2章 - IcebloodとTower Point\n\n第一の層が崩れれば、「アーティチョーク」の第二の層がむき出しになる。前線近くに建つFrostwolfの塔を破壊すれば、後方の側面に群がるLegionnaireと巡回兵を無力化できる。\n\n塔は堅固に守られ、それぞれにDrek'Tharの精鋭の司令官が一人ずついる。奴らを殺さねばならない。そうすればFrostwolfの防衛の解体が早まるだろう。", "." },
  ["f575944328868a6f"] = { "時が経つにつれ、Ner'zhulはBurning Legionの手に委ねられた氏族の運命を悟り、このオークのシャーマンはKil'jaedenに逆らい始めた。Ner'zhulに怒った悪魔は、シャーマン自身の弟子であり、Ner'zhulよりもはるかに堕落しやすいGul'danに目を向けた。", "." },
  ["f57636df8d22b9fc"] = { "Kalimdorの燃える野で戦いが荒れ狂うなか、恐ろしい事態が起きた。その出来事の詳細は時の流れの中で失われたが、Dragon Aspect of the EarthであるNeltharionが、Burning Legionとの決定的な戦いの最中に狂ったことは知られている。暗い外皮から炎と怒りが噴き出し、彼の体は裂け始めた。自らをDeathwingと名乗り直した燃える竜は同胞に牙をむき、5つの竜族を戦場から追い払った。", "." },
  ["f5b826c5a3ab3d29"] = { "夜明けの霧が消え、Age of Memoryが進むにつれ、半神Cenariusは世界の野を自らの道を行くために去っていった。Shu'halo（トーレン）は彼の旅立ちを悲しみ、彼が教えたドルイドの道の多くを忘れてしまった。世代を重ねるにつれ、彼らは木々や大地の野生の生き物と語り合う方法を忘れた。世界の深き奥底からの暗いささやきが、再び彼らの耳へと漂い上ってきた。", "." },
})
