-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["e5559f1b21107ae8"] = { "Highlord OmokkはSpirestoneを支配しているが、それはUrokの魔法によるものだ。UrokはOmokkに、彼に挑むいかなるogreも打ち殺せる呪文を授けた。Omokkはその呪文を幾度も使い、犠牲者の頭蓋骨を、Omokkの部屋の上にある力の場に山と積んでいる。\n\nそこが、Urokに立ち向かうためにそなたが行かねばならぬ場所だ。", "." },
  ["e5964a628fc715fd"] = { "そうすることで、Illidanは悪魔の姿を得て、その力を大いに増大させた。彼はまた、Gul'danの古い記憶の一部も手に入れた。とりわけTomb of Sargerasの記憶である。それは、Dark TitanであるSargerasの遺骸が眠ると噂される島の地下牢であった。", "." },
  ["e5ac45e804393b86"] = { "評議会がそなたをArgus Wakeの長に、人間とドワーフの地における彼らの戦略を統べる者に任じたのは賢明であった。そして我は、Alteracにおいてそなたの意志の手として仕えることを光栄に思う。\n\nSargerasの名において、\n\nNagaz、\nArgus Heirophant", "." },
  ["e5e6ea087c6f818a"] = { "政治的な混乱のさなか、収容所の看守の多くは、捕虜のオークたちに不穏な変化が起きていることに気づき始めた。オークが収容所から逃げ出そうとしたり、仲間内で争ったりすることは、時とともに大きく減っていた。オークはますます無関心で無気力になっていったのである。", "." },
})
