-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["5519191550a29b98"] = { "第2章 - 双子の塔\n\n思い違いをするな。Vanndar Stormpikeは狡猾な敵であり、決して愚か者ではない。前線を突破しても、第二の防衛目標を破壊せねばならない。Dun Baldarの外にいるStormpike GuardsmenとStormpikeの巡回兵を統べているのは、StonehearthとIcewingの双子の塔である。", "." },
  ["551a95ea2a7969ac"] = { "巨大な戦いがAzsharaの首都の周りで荒れ狂うなか、妄執に囚われた女王はSargerasの到来を待ちわびていた。Legionの主はWell of Eternityを抜け、荒廃した世界へ入る準備をしていた。そのあまりに巨大な影がWellの水面に迫るにつれ、Azsharaは最も強力なHighborneの信奉者たちを集めた。1つの集中した呪文で魔法を結びつけることによってのみ、Sargerasが入れるほど大きな門を作り出せるのだった。", "." },
  ["554470d8390b4a93"] = { "<HTML>\n<BODY>\n<H1>Horde徴兵登録</H1>\n<BR></BR>\n<P>この者はHordeの名において、驚くべき力と技を示した。ただちにCrossroadsでの任務に配属すべきである。</P>\n<BR></BR>\n<BR></BR>\n<P>敬具:</P>\n<BR></BR>\n<BR></BR>\n<BR></BR>\n<BR></BR>\n<P>問題ないと思う。<BR></BR>\n- Takrin Pathseeker</P>\n</BODY>\n</HTML>", "." },
  ["556538a973765e47"] = { "Kor Gem - 聞いた話では、その宝石は一部の呪文使いが魔法のためのエネルギーを蓄えるのに使い、魔法をさらに恐ろしいものにしているそうだ。私がかつて助けたナイトエルフのThundris Windweaverなら、もっと詳しく教えてくれるだろう。あなたは私の代理として話すことになるのだから。宝石に蓄えられたエネルギーのうち1つが、あなたの武器作りに使えると私は思っている。\n\n最後に話したとき、Thundrisは、ナイトエルフの故郷の影の下で海岸沿いに広がる堕落した森、Darkshoreの奥深くにある町Auberdineにいた。", "." },
  ["55ed1edd712360a4"] = { "Nethergardeの完成からわずか数か月後、dark portalのエネルギーが凝集し、Draenorへの新たな門が開いた。残ったオークの氏族は、長老シャーマンNer'zhulの指導のもと、再びAzerothへと押し寄せた。Ner'zhulの力を高める数々の魔法の遺物を盗み出そうとしていたオークたちは、Draenorに新たなポータルを開き、滅びゆく赤い世界から永遠に脱出しようと計画していた。", "." },
})
