-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["1ba195d06496a4a3"] = { "Sir S. J. Erlgadinは人間の貴族の出である。彼の父、Count Erlgadinは、その寛大さで名を馳せた。Second Great War後のStormwind再建の際、Stonemasons' Guildの労働環境の改善を働きかけたのは、その伯爵であった。", "." },
  ["1bba22b7a01672ac"] = { "私は狂いつつあるのか？ 今日、魂をよく見るために、最も信頼していた巡回兵の1人の首を刎ねた。切断された気道を覗き込んでいると、ふと気づいた。私はもう何日も何も食べていなかったのだ！", "." },
  ["1bd31b39ffdaac1f"] = { "Lord Stoutmantle——\n\nEdwin VanCleefが率いたStonemason's Guildは、人間の中でも最も腕の立つ建築者たちで構成されていました。Stonemasonsは、First Warの際にオークによって焼き払われたStormwindの街の再建に力を尽くしました。VanCleefと彼の職人たちは比類なき建築者であり、その仕事と技巧はCathedral of LightやStormwind Keepそのものの建物に表れています。", "." },
  ["1bfd296bc2123de1"] = { "Ner'zhulは従順で、自らの役割を果たすことに意欲的であるように見えたが、Kil'jaedenはこの手駒の忠誠心を疑い続けていた。Lich Kingを肉体のないまま水晶の器に閉じ込めておけば、当面は行いの正しさを保証できたが、悪魔は彼から目を離してはならないと知っていた。そのためKil'jaedenは、自らの精鋭の悪魔の近衛である吸血鬼めいたdreadlordsを呼び寄せ、Ner'zhulを監視させ、彼が恐るべき任務を確実に果たすよう見張らせた。", "." },
})
