-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["dc5b32b1a74b85e8"] = { "Lotharが最も信頼した副官Turalyonは、Lotharの血に染まった盾を手に取り、悲しみに暮れる同胞を奮い立たせて猛烈な反撃に出た。LordaeronとAzerothの両方のぼろぼろの軍旗の下、Turalyonの部隊はDoomhammerの残存兵力の大半を、輝かしくも凄惨な潰走のうちに殺戮した。", "." },
})
