-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["a9132fe9c4d9cde3"] = { "過酷な極北の荒野を何か月も歩き続けた末、Kel'Thuzadはついに暗いIcecrownの氷河にたどり着いた。彼は大胆にもNer'zhulの暗黒の城塞に近づき、アンデッドの衛兵たちがまるで彼の来訪を待っていたかのように黙って通したことに衝撃を受けた。", "." },
  ["a99d895b1f7eeca6"] = { "襲撃者……四方から。\n\n奴らの目を見れば分かる。Timbermawは邪悪。敵。\n\n部族を守らねば。Winterfallを守らねば。侵入者をこの地から追い払わねば。", "." },
  ["a9acc285f8782ec1"] = { "samophlange制御コンソールは、燃料、気体、液体および関連機械の流れを自動的に調整するために使用できる。初期設定が完了すれば、軽微な保守だけで心配なく稼働するはずである。\n\n制御コンソールの構成部品の簡単な一覧(左から右へ)\n\nI. 主電源レバー\n\n入の位置でsamophlangeが作動する。レバーを切の位置にしても、制御機構は自動的には停止しない。これは単に", "." },
})
