-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["ba0b5949266e993d"] = { "世界のGreat Sunderingに続く長い数世紀は、トロールという種族にとって苦難の時代であった。砕けた王国では飢饉と恐怖が日常茶飯事だった。追い詰められたGurubashiのトロールは、古の神秘的な力に助けを求めた。トロールの両王国は原始の神々の大いなる万神殿を信仰の中心としていたが、Gurubashiはその中で最も暗黒な神の支配下に落ちた。", "." },
  ["ba20442bef27a4cf"] = { "Second Warのこの遺物は、HordeがIronforge Mountainの征服にどれほど危うく迫ったかを、強く思い起こさせる。", "." },
  ["ba70cf77e24b047b"] = { "何が彼らを目覚めさせたのかは定かではないが、Uldamanの中に封じられていたearthenは、やがて自ら課した眠りから起き上がった。これらのearthenは、眠っている間に自分たちが大きく変わってしまったことに気づいた。岩のような皮膚は柔らかくなって滑らかな肌となり、石と大地を操る力は衰えていた。彼らは定命の生き物となっていたのである。", "." },
  ["ba964235067bcdd7"] = { "Curgleへ\n\nあなたの新しい発明品を心待ちにしていました。私の研究を記録するのに使い始めるのが待ちきれません。\n\nどうか私の使者に託してください。\n\n敬具\n\nDaryn Lightwind", "." },
  ["baa579dd88e695ec"] = { "自らの軍勢と強大な赤いドラゴンたちをAllianceに解き放つことを計画していたNekrosは、Hordeを再び統合し、Azerothの征服を続けることを望んでいた。だがその構想は実現しなかった。人間のメイジRhoninに率いられた抵抗者の小集団が、Demon Soulを破壊し、DragonqueenをNekrosの支配から解放することに成功したのである。", "." },
  ["baf607ec0ca4dee7"] = { "Ironpatchに砲撃の命令を出す。一斉砲撃でBlackwaterの船は一隻たりとも港に出入りできまい。\n\nThe Crimson Veilが砲弾を撃ち尽くしたら、援護のためにThe Riptideの横につけ、必要に応じて予備を回す。\n\nSalthoofと手下どもが町に火を放ち、総員が甲板に揃ったら、出帆して、仕上げにSavage CoastからBayにもう一度砲撃を浴びせてやる。\n\n--Fleet-Master Firallon", "." },
})
