-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["a7a5533e9f06e29e"] = { "現在、新たな不死のLich KingとなったArthasはNorthrendに住まい、Icecrownの城塞を再建していると噂されている。彼の信頼する副官Kel'ThuzadはPlaguelandsでScourgeを指揮している。Sylvanasと反逆のForsakenが押さえているのは、戦火に荒れた王国のわずかな一部であるTirisfal Gladesだけである。", "." },
  ["a7b1f4a9e9b29e10"] = { "行方不明：Corporal Keeshan\n\nStonewatch Keepでの血みどろの戦いの最中に最後に目撃されたCorporal Keeshanは、Blackrock Orcに引きずられていったと報告されている。\n\nCorporal Keeshanは、Lakeshireの北、Burning Steppesへ通じる峠のすぐ西にあるBlackrockの野営地で、捕虜として囚われていると考えられている。\n\nMagistrate Solomonの命により、Corporal Keeshanの救出に協力した者には、Marshal Marrisより報酬が与えられる。", "." },
  ["a7f1f1891e8abac5"] = { "私の日記\n\nこの数週間の恐怖は、ほとんど耐えがたいほどだ。この本に言葉を書き込むことで、なぜ狂気を遠ざけておけるのだろう？ 物言わぬ友に罪を告白しているようなものなのかもしれない。あるいは、苦悶に満ちた考えを心から解き放ち、紙の上に閉じ込めているのかもしれない。\n\nこれより前にも日記をつけていたが、それは私が二度と戻れない場所に残されたままだ。だから新たに始めよう。ただし今度は、本当の始まりから書くことにする。", "." },
})
