-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["5d96bc8042826c49"] = { "繁栄と歳月の経過をもってしても、Dark Ironの同族への恨みはほとんど和らがなかった。Thaurissanとその妻である女魔術師Modgudは、IronforgeとGrim Batolの両方に対して二方面からの攻撃を仕掛けた。Dark IronsはKhaz Modanのすべてを自分たちのものにしようと決意していた。", "." },
  ["5dbc7cd9659765a2"] = { "脅威、おそらくはありふれた死のカルトの一つにすぎないと思っている。我々がShadow Councilの……糸の1本にすぎないとは、彼は知る由もない。\n\n子供の頃、ある虫の話を聞かされたことがある。その虫はただのハエ、ほとんど気にも留められない小さな点にしか見えないのに、ひと噛みでたやすく命を奪うのだという。見過ごし、膿むままに放っておいたものこそが、最も深く人を傷つけるのだ。", "." },
  ["5dd3df88008e01a1"] = { "Dun Modr of the Wetlands\n\n愛するSaraへ\n\n数日のうちに、我々がThandol Spanの警備に就くことになるのはほぼ間違いない。二度と君に手紙を書けなくなるかもしれないので、私がもうこの世にいなくなったときに君の目に触れるかもしれない数行を、書かずにはいられないのだ。", "." },
})
