-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["077afb269dcb6578"] = { "当初、AnachronosはBronze Flightを下等な種族の争いに関わらせることを拒んだ。Anachronosがナイトエルフと手を組むことに同意したのは、Qirajiが無謀にもCaverns of Timeを攻撃してからのことであった。", "." },
  ["07efb9c0068e83ed"] = { "5日目\n\n忌々しい熊にやられた！ 真昼に、吠えながら背後から突進してきやがった。\n\n風上から来ていれば、においで気づいたはずだ。あいつの悪臭はひどいもんだった！ 疥癬だらけの毛皮と腐った息のにおいだけで、目が回りそうになった！\n\nなんとか追い払ったが、脚をひどく噛まれた。もう動けないし、エールは尽きたし、結局鉱石も見つからなかった。ちくしょう！", "." },
})
