-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["3cf698c2eda485b5"] = { "Quel'Thalasのエルフを統治するCouncil of Silvermoonは、DalaranのMagocratの領主たちと秘密の協定を結んだ。エルフたちはMagocratsに、古代Kalimdorの歴史と、今なお世界を脅かす歴史であるBurning Legionについて語った。彼らは人間たちに、魔法を使う限り、Legionの悪意ある手先から市民を守る必要があると告げた。", "." },
})
