-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["0b3a2f215f72867b"] = { "工作員は掃討を開始し、相当数のworgの存在を確認した。この脅威を減らすため、狩猟部隊の派遣を推奨する。\n\nThe Dead Fieldと呼ばれる農場で、アンデッドのgnollが発見された。農場での彼らの目的は不明だが、その動きと準備態勢から、軍事行動が差し迫っていると考えられる。観察していた間、gnollの中に目立った指導者は見当たらなかった。指導者か増援の到着を待っているものと推測される。", "." },
  ["0b3c2e1e69cdb401"] = { "Helianaへ\n\nこの私、Vargusは、あなたの望みに反して、まだ生きている。この馬鹿げた鎧を着て田舎をうろつき回るのは大嫌いだ。\n\n最新の命令では、穀物だか何だかそんなくだらないもののためにAndorhalへ向かうことになっている。よりによってAndorhalの食糧庫など、なぜ私が気にしなければならないのか？ 軍隊にいるという考え自体が馬鹿げている。\n\nご安心を、Aunt Heliana。あなたの遺産のために私は必ず戻る。たとえひどい傷を負い、食べ物もなく置き去りにされようとも、純然たる恨みが私を前へと駆り立ててくれるだろう。\n\nVargus", "." },
  ["0b5a99a6a5db0366"] = { "<HTML>\n<BODY>\n<H1 align=\"center\">Hordeの士官階級</H1><BR/>\n<P align=\"center\">第1部</P>\n<IMG src=\"Interface\\PvPRankBadges\\PvPRank14\" align=\"left\"/><BR/>\n<P align=\"right\">High Warlord</P><BR/><BR/>\n<IMG src=\"Interface\\PvPRankBadges\\PvPRank13\" align=\"left\"/><BR/>\n<P align=\"right\">Warlord</P><BR/><BR/>\n<IMG src=\"Interface\\PvPRankBadges\\PvPRank12\" align=\"left\"/><BR/>\n<P align=\"right\">将軍</P><BR/><BR/>\n<IMG src=\"Interface\\PvPRankBadges\\PvPRank11\" align=\"left\"/><BR/>\n<P align=\"right\">中将</P><BR/><BR/>\n<IMG src=\"Interface\\PvPRankBadges\\PvPRank10\" align=\"left\"/><BR/>\n<P align=\"right\">チャンピオン</P><BR/><BR/>\n</BODY>\n</HTML>", "." },
  ["0b6e7fc958584277"] = { "3日目\n\nあのうなり声は一晩じゅう続き、今日も一日じゅう俺についてきて、鉱石探しの邪魔をした。熊に後をつけられている気がする！\n\n近くに来てくれればいい。この鶴嘴を頭にぶち込んでやる！", "." },
  ["0bd31da37a88f42d"] = { "この金床はJordan Stilwellの所有物です。絶対に使用しないでください！\n\n- Jordan", "." },
})
