-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["198aa5ebd31f67fc"] = { "その結社は、ハイエルフがLordaeronで最初に定住した場所である薄暗いTirisfal Gladesで秘密の会合を開いた。そこで彼らは、その秘密の一派をGuardians of Tirisfalと名付けた。Guardiansに選ばれた定命の勇者たちには、エルフと人間の双方の魔法による驚異的な力が授けられた。Guardianは常に一度に一人しか存在しなかったが、その力はあまりに膨大で、世界のどこでLegionの手先が見つかろうとも、たった一人で撃退できるほどであった。", "." },
  ["198c2caec1b716c5"] = { "Blacknails——\n\n海が我々を待っている。北からお前の物資が必要だ。すべて剥ぎ取れ。線路の杭の一本、水桶の一つに至るまでだ。金属が要る。BBから荷が届くはずだったが、ずいぶん遅れている。俺のために踏ん張ってくれ、Blacknails。今回は物資を直接「納屋」へ送れ。無駄にする時間はない。\n\n——VanCleef", "." },
  ["198fc5b2a5934a68"] = { "彼の古い戦友Durotanが追放から戻り、Gul'danの裏切りについて再び警告した。すぐさま報復に出たGul'danの刺客たちはDurotanとその家族を殺害し、幼い息子だけが生き残った。Doomhammerの知らぬことだったが、Durotanの幼い息子は人間の士官Aedelas Blackmooreに見つけられ、奴隷として連れ去られていた。\n\nそのオークの赤子は、いつの日か、その民が知る中で最も偉大な指導者へと成長することになる。", "." },
})
