-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["a640f0bc3c131f43"] = { "Bloodsailの命令書\n\n野郎ども、この言葉をよく聞きやがれ。Booty Bayを狙えるのは一度きりだ。\n\nOl' Dunkenは北へ偵察に出して、合図を待つよう言ってある。\n\nDamsel's Luckは補給のため南の岬の沖に錨を下ろす。Captain Stillwater、あのチビ助は、手下どもに略奪品を全部運び上げる準備をさせろ。Brutus、あの間抜けもきっちりやってくれるだろうよ。", "." },
  ["a6536269bfbe068e"] = { "Guardianの力はあまりに強大であったため、Guardianshipの衣鉢を継ぐ後継者の候補を選ぶことが許されていたのはCouncil of Tirisfalだけであった。Guardianが年老いすぎたり、混沌との秘密の戦いに疲れたりするたびに、Councilは新たな勇者を選び、管理された条件のもとで、Guardianの力を正式にその新たな担い手へと注ぎ込んだ。", "." },
  ["a679e2eef09d6cd7"] = { "掃討を続けるうち、工作員はIvarの農場で足止めされた。Ivar、その家族の大半、そして使用人たちはScourgeに屈し、その手先と化していた。\n\n工作員は襲撃を受け、待ち伏せした者たちを打ち倒すことには成功したものの、深刻な傷を負った。とりわけ工作員Quinnの傷が重い。", "." },
  ["a67e617be027e063"] = { "日記さんへ\n\nごめん、眠っちまった。それで、怒りながら飛んで、あのくだらない本の章をばらまいていたんだ。Darkwhisperの下に悪魔がいるのが見えたから、最初の章を魔法の紙の竜巻にして、そいつの体を百万のかけらに切り刻んでやることにした！ 解放された気分だった。魔法＋紙＝楽しい。\n\nそれでかなりご機嫌になったから、Eastern Kingdomsまで飛んでいくことにした。最初の行き先はMolten Coreだ。Narainはいつもあの場所の話をしていたからな！「Molten Coreがどうの、Ragnarosがこうの……」", "." },
})
