-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["1518318754b03c25"] = { "あらゆる魔法を信用していなかったThoradinだが、やむを得ずエルフたちを援助することに同意した。ほとんど間を置かず、エルフの魔術師たちがArathorに到着し、人間の一団に魔法の道を教え始めた。", "." },
  ["1535b33fd9352ca2"] = { "Agashamへ\n\n我々の計画は何としても秘密にしておかねばならない！ 他のトーレンの部族に我々のつながりを知られれば、大変なことになる。\n\n署名\n\nHarbinger Elm", "." },
  ["156e80c7587b5387"] = { "小さな世界に秩序がもたらされ、自分たちの仕事は終わったと満足したTitanたちは、Azerothを去る準備をした。しかし旅立つ前に、彼らは世界で最も偉大な種族に、Kalimdorを見守る務めを託した。いかなる力もその完璧な静けさを脅かすことのないように。その時代には、多くの竜族がいた。", "." },
  ["156f11de4364bb51"] = { "この印章が無事に届くことを願っています、{class}。筆をとったのは、私たちの民が、剣や薙刀、その他あらゆる武器に長けた者を必要としているからです。私たちの民がAzerothの他の種族と再び交わるようになってから、あまりに多くのことが起こり、あらゆる種類の守り手がいっそう必要になっています。\n\nそこであなたの出番です。もっとお話ししたいのですが、直接会って話すべきだと思います。Aldrassilの中……下の階で私を探してください。\n\n-ウォリアーのトレーナー、Alyissia", "." },
  ["158f7bb42a19c8c6"] = { "Kel'Thuzad配下のカルト信者たちは、死んで闇の主に仕えるために蘇ることを切望していた。彼らはアンデッドとなることで得られる不死を思って歓喜した。疫病が広がるにつれ、北の地ではますます多くの凶暴なゾンビが蘇った。Kel'ThuzadはLich Kingの増大する軍勢を眺め、それをScourgeと名付けた。まもなくその軍勢はLordaeronの門へと進軍し……人間を世界から一掃することになるのだから。", "." },
  ["15c1b2983ed454a2"] = { "Jorgenへ\n\r恐れていたことが現実となり、彼らは私が思いもしなかった手段に出ました。ここまで迫ってくるとは考えもしませんでしたが、実際に迫ってきたのです。\n\rどうかこの手紙を届けた者を助け、「あの方」のもとへ送ってください。正直なところ、事の重大さゆえに、あの方も力を貸してくださると思います。ほかの脅威であれば、あの方はきっとこれまでどおり、私たちとこの美しい街の問題を無視し続けたでしょう。\n\rありがとう、年老いた釣り人さん。いつもながら、あなたには恩があります。\n\rあなたの友\n\rDeLavey", "." },
  ["15cb41c17a964603"] = { "Wellの不思議なエネルギーに引き寄せられた、野生で遊牧の人型種族は、その穏やかな岸辺に粗末な住まいを築いた。時が経つにつれ、Wellの宇宙的な力はこの奇妙な部族に影響を及ぼし、彼らを強く、賢く、ほとんど不死の存在にした。部族は、自分たちの言葉で-星の子ら-を意味するKaldoreiという名を名乗った。芽生えた社会を祝うため、彼らは湖の周囲に壮大な建造物や神殿を築いた。", "." },
  ["15fb1641861d817c"] = { "<HTML>\n<BODY>\n<H1 align=\"center\">HORDEの下士官・兵階級</H1><BR/>\n<IMG src=\"Interface\\PvPRankBadges\\PvPRank05\" align=\"left\"/><BR/>\n<P align=\"right\">First Sergeant</P><BR/><BR/>\n<IMG src=\"Interface\\PvPRankBadges\\PvPRank04\" align=\"left\"/><BR/>\n<P align=\"right\">Senior Sergeant</P><BR/><BR/>\n<IMG src=\"Interface\\PvPRankBadges\\PvPRank03\" align=\"left\"/><BR/>\n<P align=\"right\">Sergeant</P><BR/><BR/>\n<IMG src=\"Interface\\PvPRankBadges\\PvPRank02\" align=\"left\"/><BR/>\n<P align=\"right\">Grunt</P><BR/><BR/>\n<IMG src=\"Interface\\PvPRankBadges\\PvPRank01\" align=\"left\"/><BR/>\n<P align=\"right\">Scout</P><BR/><BR/>\n</BODY>\n</HTML>", "." },
})
