-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["6e305ceafe927185"] = { "序文(続き)……\n\n火鉢そのものは、Brazier of Beckoningとまったく同じように機能する。5つの呪われた場所のいずれかの範囲内に置くだけで、死者の霊を呼び出すだろう。\n\n余談だが、君が知りたがるだろうと分かっているので書いておく。Banner of Provocationも、Blackrock Depthsの闘技場で同じように使うことができる。そこへ行った折には、機会があるたびに、私の代わりにTheldrenとその手下どもを懲らしめてやってくれ。\n\nさらなる知識を望むなら、読み進めるがいい。", "." },
  ["6ed7e1fa7f2ad34b"] = { "自らの軍勢が集結し、あらゆる命令に従う準備が整ったのを見届けると、Sargerasは荒れ狂う軍勢をGreat Darkの広大な虚空へと解き放った。彼はその膨れ上がる軍勢をBurning Legionと呼んだ。今日に至るまで、宇宙を渡る不浄なBurning Crusadeにおいて、彼らがどれほどの世界を喰らい、焼き尽くしたのかは定かではない。", "." },
})
