-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["cb15630e98fe4b45"] = { "Feast of Winter Veil\n\nAzerothの晩秋から冬にかけての季節は、多くの文化において変化の時とされている。とりわけドワーフとトーレンは、やがて訪れるWinter Veil、すなわち大地が雪に覆われ再生の時の到来を告げるという伝説を、祝いの時として重んじている。Azerothの種族が共有する伝説の解釈はさほど違わないが、それをどう祝うかは、種族そのものと同じくらい多様である。", "." },
  ["cb312d0494f8f8da"] = { "The Bleeding Sparrow：積荷目録\n\n(20) ラム酒の樽。行き先：Theramore\n(50) 小麦粉の袋。行き先：Theramore\n(2) ノームの工具詰め合わせの木箱。行き先：Ratchet\n(30) 綿布の反。行き先：Theramore\n(4) 香辛料の木箱。行き先：Theramore\n(3) 乗客。行き先：Theramore", "." },
  ["cbad3ba8491e82d3"] = { "Apothecary Lydon殿\n\nこの手紙が速やかにあなたのもとに届き、持参した者も無事であることを願っています。遠いKalimdorで、あなたの腕が必要になると思われる事態が起きました。\n\n手短に申し上げます。\n\n我らのトーレンの同盟者の故郷Mulgoreからほど遠くないStonetalon Mountainsで、危機が進行しています。ゴブリンが運営するVenture companyが、あの山々で激しく採掘と伐採を行い、山の精霊たちを怒らせているのです。", "." },
  ["cbb8129bb59002db"] = { "Kil'jaedenがGreat Dark Beyondの中に穏やかに浮かぶ豊かな世界Draenorを見出したのは、この時のことである。シャーマン的な氏族社会を営むオークと、平和を好むdraeneiの故郷であるDraenorは、広大であると同時に牧歌的な世界だった。", "." },
  ["cbbb4210ab398bc4"] = { "自身も熟練した魔術師であるKaelは、衰えゆくAllianceに不信を抱くようになった。high elfは故郷を失ったことを嘆き、倒れた同胞をたたえてblood elfと名乗ることにした。だがScourgeを食い止めようと努める中で、彼らは自らに力を与えていたSunwellから切り離されたことにひどく苦しんだ。", "." },
  ["cbca8a8a95dfceba"] = { "Scorched Spider Fangs:\n\nThelgen Rock付近の洞窟で見つかるincendicite鉱石が、そこに棲む蜘蛛を焦がしている。\n\nその牙の毒は沸き立ち、牙そのものと反応して、非常に硬い物質を生み出す。", "." },
  ["cbdb3e7b7394aa14"] = { "この島を支配するあの獣は、実に恐ろしく強い。ここにいる他の生き物たちは、SkymanもJagueroも等しく奴の前で縮こまっている。今でも奴の咆哮が聞こえ、そのたびに身がすくむ。\n\nこの生き物たちは、島に来る者を必ずや阻むだろう。祖霊たちを信じなければならない。", "." },
})
