-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["9225443e49cbd3ab"] = { "Ner'zhulがAllianceへの新たな攻勢を企てていると確信したLordaeronのKing Terenasは、オークの脅威を完全に終わらせるべく、軍をDraenorへ送り込んだ。KhadgarとGeneral Turalyonに率いられたAlliance軍は、燃え盛る大地の各地でオークと激突した。エルフのRanger Alleria、ドワーフのKurdran、歴戦の兵士Danathの助けがあっても、KhadgarはNer'zhulが他の世界へのポータルを開くのを阻むことはできなかった。", "." },
  ["923884f7c49649c8"] = { "それからNer'zhulは、Lordaeronの人間の文明に疫病を広めるよう作られた遺物を生み出した。彼はそれをKel'Thuzadに与え、その魔術師に遺物を国中に広めるよう命じた。彼のCultの信徒たちは、何としてもその遺物を守ることになっていた。", "." },
  ["92635fd9e1fd743e"] = { "私は遠征隊に、翌日は豹狩りをすると約束していた。その毛皮はAzeroth中で需要が高いからだ。体の丈夫なハンターや罠猟師、毛皮商人たちが皆、Allianceの名のもとに勇敢に命を捧げに出ているのだから、そうした需要があるのも当然である。", "." },
  ["9297e67ead957025"] = { "自らをドワーフと称した最後のearthenたちは、Uldamanの広間を去り、目覚めた世界へと踏み出した。深き場所の安全と驚異に今なお心を奪われていた彼らは、その地で最も高い山の下に広大な王国を築いた。", "." },
})
