-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["652142a5fbbd607e"] = { "彼らの混沌とした軍勢は世界の表面で荒れ狂い、巨大なTitanたちと激突した。エレメンタルは定命の者の理解を超えるほど強大だったが、その総力をもってしても強大なTitanたちを止めることはできなかった。エレメンタルの王たちは一人、また一人と倒れ、その軍勢は散り散りになった。", "." },
  ["653d03c598b7e0f9"] = { "閣下——\n\nWestfallの誰もが貴殿の損失を悼んでおりますが、我々もまたWestfallで自らの戦いに苦しんでおります。農民たちは盗賊と機械仕掛けのゴーレムに追い払われました。Stormwindは兵を引き上げ、民は無防備のまま残されました。私はStormwindに見捨てられたのを受けて、この地に残されたものを守るためPeople's Militiaを招集したのです。民兵団をRedridgeへ連れて行けば、Westfallは確実に破滅するでしょう。\n\n遺憾ながら\nGryan Stoutmantle", "." },
  ["6541db44dce060e5"] = { "Lok-tar、同胞よ。エレメンタルがお前を手招きし、シャーマンの道を示すよう私に命じている。我らの祖先の霊は彼方から見守り、お前が我らの仲間に加わったことを知って誇りに胸を膨らませている。\n\n準備ができたら、Denの入り口の近くで私を探せ。そこで私は同族の者たちを鍛えている。それまで、風がお前の背を押さんことを。\n\n-シャーマンのトレーナー、Shikrik", "." },
  ["6562aadd36701c4b"] = { "<HTML>\n<BODY>\n<H1 align=\"center\">\n第1章：NORTHERN PYLON\n</H1>\n<BR/>\n<BR/>\n<IMG src=\"Interface\\Pictures\\11482_crystals_mini_north\" align=\"left\"/>\n<P align=\"right\">Northern<BR/>\nPylonは<BR/>\n黄、赤、<BR/>\n緑の<BR/>\nクリスタルを受け入れる。</P>\n<BR/>\n<BR/>\n<BR/>\n<BR/>\n<P align=\"left\">このパイロンは、黄のクリスタルを主な動力源として生み出せるエネルギーに重点を置いている。</P>\n</BODY>\n</HTML>", "." },
  ["6589aec43c7ff49b"] = { "都市のレイラインの力で強化されたIllidanは、Eyeを使い、はるか遠くNorthrendにあるLich Kingの城塞Icecrownに向けて破壊の呪文を放った。Illidanの攻撃はLich Kingの守りを打ち砕き、世界の屋根そのものを引き裂いた。最後の瞬間、兄MalfurionとPriestess TyrandeがMaievを助けに駆けつけたことで、Illidanの破壊の呪文は止められた。", "." },
})
