-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["4082eacc0841e416"] = { "2つのaqiriの都市国家が生まれた――北の荒野のAzjol-Nerubと、南の砂漠のAhn'Qirajである。トロールはKalimdorの地下に他のaqiriの植民地があるのではないかと疑っていたが、その存在が確かめられることはなかった。", "." },
  ["409689ed5170eebe"] = { "Devlinは、Scourgeに立ち向かおうとすれば我々は破滅すると警告していた。奴らが初めてTirisfal Gladesに入ってきたとき、我が家が包囲されるずっと前のことだ。去るよう我々に懇願していたのかもしれないし、ほくそ笑んでいたのかもしれない。\n\nDevlinの考えはいつも分かりにくかった。子供の頃から、あいつは我々にとって謎だった。", "." },
  ["40a4c4486cb96190"] = { "Uther the Lightbringer ここに眠る\n最初のパラディン - Order of the Silver Handの創設者\n\nUtherはLordaeron王国を守るために生き、そして死んだ。最も愛した弟子に裏切られたが、我らは彼の魂が今も生き続けていると信じている。荒廃した我らの地に影が迫る今もなお、彼は我らを見守り続けている。彼の光はすべての人間の光であり、我らが彼の範を敬い続ける限り、決して消えることはない。\n- 名もなき者", "." },
  ["40c065b5d72d44e6"] = { "その名は最も暗きAzerothに光をもたらした。\n\nその勇気は悲嘆の壁を打ち砕いた。\n\nSilver Handが世に為しうる最上の務めは\n\n己を捧げる騎士を世に送り出すことであった。", "." },
})
