-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["0d1d2680f9d4e2fd"] = { "収容所の看守長Aedelas Blackmooreは、自らの監獄要塞Durnholdeから捕虜のオークたちを見張っていた。彼がとりわけ関心を寄せていたオークが一人いた。18年近く前に見つけた、あの孤児の赤子である。Blackmooreはその若い雄を気に入りの奴隷として育て、Thrallと名付けた。Blackmooreはそのオークに戦術、哲学、そして戦闘を教えた。Thrallは剣闘士としての訓練まで受けた。その間ずっと、腐敗した看守はそのオークを武器へと作り上げようとしていた。", "." },
  ["0da106e61c3cecba"] = { "教団の現状、第127号\n\nまことに喜ばしい日だ！ 我らはSilithusで試され、そして合格したのだ！\n\n最北の野営地が壊滅したという報せは、信仰の薄い者たちの心を揺るがすかもしれない。だが、この殺戮を悲劇と見なしてはならない。断じて！", "." },
  ["0dfa5e8e8a564128"] = { "我が宝物庫で見つかるであろうNemesisとStormrageの武具を楽しむがよい。これだけは信じてくれたまえ。父にできなかったことを私が成し遂げたと知ることは、私にとって大いなる喜びなのだ……\n\n敬具\n\nLord Victor Nefarius\n「Nefarian」", "." },
})
