-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["4f2da8197008d50f"] = { "薄汚いtroggsを騙すのはたやすい。奴らはわれらの同族を憎んでいるから、なおさら奴らを操り、駒として使いやすい。そもそも手を組めたこと自体驚きだが、われらの同族のほうが奴らの存続にとってはるかに大きな脅威だからな……少なくとも今のところは。\n\nだが攻撃が始まれば、両陣営とも弱り、われら自身の猛攻にさらされやすくなる。Helm's Bed Lakeの南にある農家を押さえ、次の指示を待て。\n\nIronforgeはわれらのものになる。", "." },
  ["4ff1f23dec6b27a0"] = { "副官であるUther the Lightbringer、Admiral Daelin Proudmoore、そしてTuralyonの助けを得て、LotharはLordaeronの人間に近い種族たちにも迫り来る脅威を納得させることができた。Allianceは、Ironforgeの不屈のドワーフと、Quel'Thalasの少数のhigh elvesの支援を取り付けることに成功した。", "." },
})
