-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["7b00694c8fdca4bf"] = { "最終的に、Sylvanasと彼女に従う反逆のアンデッド(Forsakenとして知られる)は、廃墟となったLordaeronの首都を自分たちのものとした。破壊された都市の地下に自らの砦を築いたForsakenは、Scourgeを打ち破り、Kel'Thuzadとその手下をこの地から追い払うことを誓った。", "." },
  ["7b5bc22e4f0b6787"] = { "長年にわたり、ナイトエルフたちは古の故郷をできる限り再建するため、たゆまず働いた。壊れた神殿や道は草木に覆われるに任せ、彼らはHyjalの麓の緑豊かな木々と陰る丘の間に新たな家を建てた。やがて、大いなるSunderingを生き延びた竜たちが、秘密の住処から姿を現した。", "." },
  ["7b9779f5bdd41047"] = { "Supervisor Fizsprocket殿、President Razdunkの承認を得た、ご請求の機材の一覧を同封いたしますのでご確認ください。\n\n社長より、Venture CompanyがKalimdor全土に事業を展開することに強い利害を持っている点を改めてお伝えし、強調するよう申しつかっております。Barrensの採掘・掘削拠点は収益性も効率も高いことが証明されましたが、貴殿の管轄であるMulgoreからは、いまだ十分な生産量が届いておりません。\n\n諮問委員会は、事業の立ち上げの難しさを理解しております。", "." },
})
