-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["04161d43c6f4a0f7"] = { "混乱と苦悩が深まるなか、Sargerasは、Titanの秩序を乱そうとするもう一つの集団と対峙しなければならなかった。Nathrezimである。吸血鬼のような悪魔からなるこの闇の種族（dreadlordとしても知られる）は、住民に憑依して影へと堕とすことで、人の住む数多くの世界を征服した。", "." },
  ["043584a9b008c232"] = { "Circle of Greater Binding\n\nCircle of Greater Bindingは、魔力の強い場所で作り出さねばならない。そうした場所が、Dire Maulとも呼ばれるEldre'Thalasの廃墟の奥深くにある。Eldre'Thalasには強大な力を持つ存在、Immol'tharが封じられている。円陣を作り出す儀式は、その牢獄の台座の上で執り行わねばならない。\n\nPedestalまで戦いながら進み、それからJ'eeveeを瓶から出してやること。", "." },
  ["04508547939f1fe6"] = { "StormreaverとTwilight's Hammerの氏族の後ろ盾を得て、Gul'danはTomb of Sargerasを海底から引き上げることに成功した。しかし、その古く水浸しの霊廟を開いたとき、彼を待ち受けていたのは狂った悪魔たちだけだった。", "." },
  ["04f2d9d8c55fc010"] = { "噂では秘術には堕落と邪悪がつきまとうというけれど、私たちがすでに味わった苦しみに比べれば何でもないわ。私たちはもう犠牲者ではないのよ、{name}。自らの運命を支配するのは私たち自身。Sylvanasが私たちのために道を切り開いてくれた。私たちの意志は私たち自身のものであり、もうあの外道Arthasの奴隷ではないと証明してくれたのよ。\n\n教会で私を探しなさい。さらに教えてあげるわ……あなたがそれを望むならね。\n\n- メイジのトレーナー、Isabella", "." },
})
