-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["583fefc4939fe6ab"] = { "Hillsbrad町登記簿\n\n我らHillsbradの民は、偉大なる君主、IronforgeのKing Magni BronzebeardとStormwindのKing Anduin Wrynnが維持するAllianceへの忠誠と献身を、厳粛に誓う。\n\n本書には、偉大なるAlterac Mountainsの麓にあるこの麗しき町を治めるための町の登記を記す。また、王たちと偉大にして全能なるAllianceに税を納めた者の記録としても用いる。", "." },
  ["585527f6544cf056"] = { "Williamへ\n\n最後に話してから何年も経ちましたが、あなたも弟さんも元気で、薬屋も繁盛していることと思います。\n\nWilliam、あなたにお願いしたいことがあるのです。手短に言うと、私の孫のTommy Joeが、若いMaybell Maclureに心を奪われてしまいました。二人は互いに深く想い合っているのですが……私たちの家族は、そう、私たちの家族は何年も争い続けているのです。", "." },
  ["586130b76d9b1940"] = { "Well of Eternityが崩壊した際に追放されていたBurning Legionの邪悪な手先たちは、Dalaranの魔術師たちの無分別な呪文詠唱によって、再びこの世界へと誘い込まれた。これらの比較的弱い悪魔は大挙して現れたわけではなかったが、Dalaranの街路にかなりの混乱と混沌をもたらした。", "." },
  ["586bd320bb117205"] = { "仲間のTitanたちは彼の誤りを説き、荒れ狂う感情を鎮めようとしたが、彼はその楽観的な信念を独りよがりの妄想として退けた。永遠に彼らのもとを飛び出したSargerasは、宇宙における自らの居場所を求めて旅立った。Pantheonは彼の離反を悲しんだが、失われた兄弟がどこまで突き進むことになるのか、Titanたちには予想すらできなかった。", "." },
  ["58b179b700716b86"] = { "邪悪で陰謀に長けたdreadlordたちは、国々を操って盲目的な憎悪と不信に陥れ、国全体を互いに敵対させた。SargerasはNathrezimをたやすく打ち負かしたが、彼らの堕落は彼に深い影響を与えた。", "." },
})
