-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["113e3d54e32f0a72"] = { "終章\n\nこれをすべて成し遂げれば、残るは玉ねぎの中心、甘い芯だけだ。Vanndar Stormpikeは守る者もなく孤立する。軍規により、処刑の前には降伏を求めねばならない。奴に会ったら、降伏の件を必ず口にしておけ……それから殺せ。", "." },
  ["116f8c6fade16003"] = { "日記さんへ\n\nよし、もう大丈夫だ。手下の一人を、小さな女の子みたいに泣くまでぶちのめしてやった。\n\nうーん……なんだかちょっと悪いことをした気がする。待てよ！ ちくしょう、俺は悪の天才なんだぞ！ 悪だぞ、分かるか？ 自分にがっかりだ。すぐ戻る。", "." },
  ["11a605143cc5c8a0"] = { "Lich Kingは新たな手下に満足した。彼は忠誠と服従と引き換えに、Kel'Thuzadに不死と大いなる力を約束した。暗黒の知識と力を渇望するKel'Thuzadは、最初の大いなる使命を引き受けた。それは人間の世界へ赴き、Lich Kingを神として崇める新たな宗教を創設することだった。", "." },
  ["11c15ed1db218cc3"] = { "Honorable Headmaster Crillianへ\n\nかつての師匠へ、あなたの弟子が近頃何をしているかをお知らせしたく、筆を執りました。あなたの助言に従い、私は愛するStormwindの門の外へ旅をして、知識と知恵を深めようとしてまいりました。旅路は私を多くの場所へと導きましたが、ここ、素敵な町Moonbrookに居を構えることに決めました。収穫の時期が近づき、周りに広がるWestfallの畑はこの上なく美しい眺めです。", "." },
  ["11d0316cdad84322"] = { "<HTML>\n<BODY>\n<H1 align=\"center\">HORDEの下士官・兵階級</H1><BR/>\n<IMG src=\"Interface\\PvPRankBadges\\PvPRank05\" align=\"left\"/><BR/>\n<P align=\"right\">First Sergeant</P><BR/><BR/>\n<IMG src=\"Interface\\PvPRankBadges\\PvPRank04\" align=\"left\"/><BR/>\n<P align=\"right\">Senior Sergeant</P><BR/><BR/>\n<IMG src=\"Interface\\PvPRankBadges\\PvPRank03\" align=\"left\"/><BR/>\n<P align=\"right\">Sergeant</P><BR/><BR/>\n<IMG src=\"Interface\\PvPRankBadges\\PvPRank02\" align=\"left\"/><BR/>\n<P align=\"right\">Grunt</P><BR/><BR/>\n<IMG src=\"Interface\\PvPRankBadges\\PvPRank01\" align=\"left\"/><BR/>\n<P align=\"right\">Scout</P><BR/><BR/>\n</BODY>\n</HTML>", "." },
})
