-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["6a0f16a491e5f3b3"] = { "分野の研究\n\nノームとゴブリンは互いから自分たちの知識を守ることに執着しており、両方の分野に同時に触れることはほぼ不可能である。どちらの種族も、政治的な立場にかかわらず、これらの分野の知識を、相手の分野を追究しないことに同意した者にしか開放しない。たとえば、学ぶ者がノーム工学を選べば、ゴブリン工学の知識がその者に開かれることは決してない。", "." },
  ["6a39ef6de25a13e0"] = { "高貴なる旦那様へ\n\nお子様方の家庭教師をお探しとのお話が、ここGoldshireにいる私のもとへも届きました。私は今、Lion's Pride Innに仮住まいをしております。この地域の不幸な情勢により、Moonbrook Schoolhouseの校長の職を離れざるを得なくなりました。どうか、お子様方の家庭教師を務めたいという私の申し出をお受けください。必要とあらば、AcademyのHeadmaster Crillianが私の能力についてお話しくださるはずです。", "." },
  ["6ab6d34b6f3a3106"] = { "Marduk the Blackの運命\n\nMardukはSecond Warを生き延び、ルーンの刻まれた忌まわしい剣で多くの死と苦しみをもたらした。Mardukは今なお生きているが、その剣はCorin's Crossing近くでの戦いで失われた。あるドワーフの隊長が魔法のかかった盾でその剣を打ち砕き、Mardukを戦場から敗走させ、Allianceにその日の勝利をもたらしたのである。\n\nMardukの剣は大地に沈んでそれを穢し、地を侵食して峡谷を生んだ。今ではInfectis Scarとして知られている。", "." },
  ["6ad16335ece85f87"] = { "獣を手なずけ、射撃の名手で、腕利きの追跡者……この人生で他に何を成し遂げたいってんだ？ そいつを全部こなすには、かなりの頭と、とんでもない忍耐が要る。\n\nハンターの道は楽なもんじゃねえ、そいつは確かだ。俺たちの一番下っ端のライフル兵並みになりたいだけでも、たっぷり訓練が要る。だからこそ俺がいるのさ。\n\nColdridge Valleyを見下ろすAnvilmarの中で俺を探せ。待ってるぞ。\n\n-ハンターのトレーナー、Thorgas Grimson", "." },
  ["6aedeade911d13b0"] = { "散り散りになったオークの氏族はたちまち一網打尽にされ、警備された収容所に入れられた。Hordeは完全に打ち負かされたかに見えたが、平和が続くことを強く疑う者もいた。今やいくらか名の知れた大魔導師となっていたKhadgarは、Alliance最高司令部を説き伏せてNethergardeの砦を築かせた。Dark Portalの廃墟を見張り、Draenorからの侵攻が二度と起こらないようにするためである。", "." },
  ["6af27a6d399249e4"] = { "<HTML>\n<BODY>\n<H1 align=\"center\">\nNORTHERN PYLON 配置図\n</H1>\n<BR/>\n<IMG src=\"Interface\\Pictures\\11482_crystals_north\"/>\n</BODY>\n</HTML>", "." },
})
