-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["7540ec5e74e84df7"] = { "Admiral Barean Westwind\nScarlet Fleetの大提督\nKul'Tirasの市民\nNorthrendのFrozen Coast沖にて消息を絶つ", "." },
  ["75599248d39cd35d"] = { "Scytheが引き抜かれた後、坑道に変化が波のように広がった。揺らめく松明の光は歪み、我々の声の大きさは思うようにならなくなった。ある時は男のささやきが坑道じゅうに轟いて耳を塞がねばならず、またある時は叫び声がほんの数歩先にも届かず、風の気配のように消えていった。\n\n気味が悪かった。だが、この奇妙さに首をひねっている暇は長くはなかった。それは、我々を本当に坑道から追い出したものの前触れにすぎなかったのだ。Worgenである。", "." },
  ["75a754f7fc866295"] = { "The Control of the Beast：\n\nFelhound Trackerは獣の咆哮にしか反応しない。Felhound TrackerにAzshariteの鉱床を追跡させるには、力いっぱい咆哮を浴びせねばならない！（Felhound Trackerをターゲットにして /roar）\n\nFelhound Trackerは鉱床を見つけると、周囲にいる存在などほとんど気にも留めずに鉱床へ突進する。Felhoundを守る必要はないが、見失わないよう近くにいたほうがよいだろう。", "." },
  ["75f0409c1cc7fadf"] = { "その後の数か月、Ner'zhulはNorthrendに住むすべての人間を支配下に置くことで、アンデッド化の疫病の実験を続けた。アンデッドの軍勢が日ごとに膨れ上がる中、彼は真の試練の時が近づいていることを知っていた。", "." },
})
