-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["4e98015ed63e49f9"] = { "Davil Lightforgeの運命\n\nDavil LightforgeはThe Battle of Darrowshireで命を落としたが、その勇気は戦争を通じてAllianceを奮い立たせた。\n\n彼の書、すなわちパラディンの聖典は、Scarlet Crusadeの兵によって回収された。それは今、Scarlet Crusadeが支配するHearthglenの町役場に収められており、Davilの強さにあやかろうとする十字軍の兵たちにしばしば読まれている。", "." },
  ["4eddca263415293a"] = { "ああSara、もし死者がAzerothに戻り、愛する者たちの周りを人知れず飛び回ることができるのなら、私はいつも君のそばにいよう。最も喜ばしい日にも、最も暗い夜にも、最も幸せな時にも、最も沈んだ時にも、いつも、いつまでも。そしてもし柔らかな風が君の頬に触れたなら、それは私の息だ。涼しい風が君の脈打つこめかみをなでるなら、それは通り過ぎる私の魂だ。\n\nSara、私の死を嘆かないでくれ。私は先に行って君を待っているのだと思ってほしい。我々はまた会えるのだから。\n\n--Sully", "." },
  ["4ef93a61a515b323"] = { "Frostwolf Artichoke：Stormpike Gloryの物語\n-著：Vanndar Stormpike\n\nFrostwolfとは何か？答えは簡単だ。Frostwolfとは、我らの至高なる帝国の大義を阻もうとする野蛮人どもである。\n\nアーティチョークと同じく、Frostwolfはトゲだらけの堅い守りを持っている。そしてアーティチョークと同じく、ひとたび外側の層を剥がしてしまえば、芯がむき出しになり、上等なガーリックディップで食べられるばかりとなるのだ。\n\n美味である！", "." },
})
