-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["e40220852ccf2e8c"] = { "幾世紀が過ぎるうちに、ナイトエルフの新たな社会は力を増し、彼らがAshenvaleと呼ぶようになった若い森の隅々へと広がっていった。Great Sundering以前に数多く存在したfurbolgやquilboarといった生き物や種族の多くも再び姿を現し、この地で栄えた。ドルイドたちの慈悲深い指導のもと、ナイトエルフは星空の下で、かつてない平和と静穏の時代を享受した。", "." },
  ["e4bae32a11748aa6"] = { "数か月が過ぎ、さらに多くのオークの捕虜が捕らえられて収容所に入れられた。収容所があふれ始めると、AllianceはAlterac Mountainsの南の平原に新たな収容所を建設せざるを得なくなった。増え続ける収容所を適切に維持し物資を供給するため、King TerenasはAllianceの国々に新たな税を課した。", "." },
  ["e4eeac5b6a02591d"] = { "通達：\n\n直ちにThran Khormanのもとへ出頭せよ。彼は建物A3、地元住民にはAnvilmarとしても知られる場所にいる。Khormanとの接触に成功した後、来たるべき戦争、我らの故郷Gnomereganを奪還するための戦争に向けて準備を進めよ！\n\n全ての努力と必須任務は、この指令の達成に集中させること。達成の暁には、新たな任務が与えられる。", "." },
})
