-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["2b86fffa935fdd56"] = { "俺の古いウイスキーの水差しを見つけたなら、お宝はもうすぐだ！ 瓶から西を向いて、岸辺まで歩いていけ。水際に着いても止まるなよ！ 俺の宝箱がある島が見つかるまで、まっすぐ西へ泳ぐんだ！", "." },
  ["2bebdc51cc03198a"] = { "およそ3000年ぶりに、ばらばらだったArathorの諸国は再び共通の旗の下に一つとなった。Alliance軍の最高司令官に任じられたLord Lotharは、Hordeの到来に備えて軍勢を整えた。", "." },
  ["2bf5bbab7cec9852"] = { "遺物が配置されるや、疫病は大地に染み込み、何も知らぬ住民を蝕み始めた。Kel'Thuzadが見守る中、Lich Kingの軍勢は急速に膨れ上がり、彼はほどなく国土の広い範囲を支配下に収めた。この軍勢はScourgeと呼ばれるようになった。その唯一の目的が、Azeroth全土から人間を一掃することだったからである。", "." },
})
