-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["2608ef1e8d1703a3"] = { "敬愛するMagistrate Solomon殿\n\n死者を悼み、貴殿とともに悲しんでおります。王に状況をお伝えするよう、私自ら取り計らいましょう。Lakeshireへ援軍を送れることを心より願っております。陛下は近頃めったにお姿を見せず、どこか奇妙な振る舞いをなさっています。これは貴殿を信頼してお伝えすることです。\n\nそれでは、その時まで\n\nGeneral Marcus Jonathan\nKingdom of Stormwind", "." },
  ["26797096ea488cc9"] = { "これらの品、Star、Hand、Heartを持ってきてくれれば、Yagyin Digestの写本を一冊与えよう。\n\n-Keeper", "." },
  ["26990877ac8ea849"] = { "かつては、人間が我らの地へやって来て我らの流儀を学ぶなど馬鹿げたことだと思っていた。だがこの魔法使い、この邪悪な男は、ここへやって来て生き延びたばかりか、我らの知識の一部まで手に入れたのだ。どうやってなのかは、いまだに分からない……\n\n調査の間に彼の目的を突き止めることはできなかったが、その計画は単純なものだったようだ。ドルイドの魔法を使ってfurbolgと親しくなり、やがて彼らを支配しようとしたのだ。それが我が同胞を害そうとしてのことなのか、あるいは何か別の悪意ある目的のためなのか、私の道が尽きる前に突き止めたいと思う。", "." },
  ["26ad007f7280f866"] = { "すべての炎の精霊の不死の主、Ragnaros the Firelordは、世界がまだ若かった頃にTitansによって追放されていた。今、Thaurissanの呼びかけによって解き放たれたRagnarosは、再びこの世に噴き出した。RagnarosのAzerothへの終末的な再誕はRedridge Mountainsを打ち砕き、その荒廃の中心に荒れ狂う火山を生み出した。", "." },
})
