-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["dbd920442fecaf73"] = { "まもなく、Ajeckは豹を南西へと追跡した。我々は銃を構え、獲物を待ち受けながら静かに歩いた。近くの木立で小枝の折れる音がして、すぐに我々の注意を引いた。何かがそこにいる。Barnilに厳しい視線を一つ送るだけで、私の考えは伝わった。Barnilはゆっくりとライフルを下ろした。この獲物は我々のためのものではない。人間の仲間たちのためのものだ。数えきれない豹が、我々の硝煙を上げる銃口の前で命を落としてきた。この獲物は人間たちのためのものなのだ。", "." },
  ["dbf7dff5e2c7de4a"] = { "ISALIEN(続き)……\n\n不運にも、彼女と相棒のhippogryphであるEmpyreanが都に足を踏み入れたとき、Alzzin the Wildshaperとその手下どもに襲われた。彼女はそこで倒れ、二度と起き上がることはなかった。Lord Valthalakが自らの本質の一部をアミュレットに封じ込めるために用いた邪悪な魔法の秘密を、Isalienがそれ以上解き明かさなかったのは、むしろ幸いだったのかもしれない。\n\nAlzzinが棲む屋根のない広間は、これら呪われた場所の1つである。", "." },
})
