-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["5147351b23c35a51"] = { "儀式の道具\n\n任務を始める前に、次の魔法の道具を揃えておかねばならない。\n\nJ'eevee's Jar\nA Black Lodestone\nXorothian Glyphs\n\n私の従者Gorzeekiが、代価と引き換えにそれらを用意してくれる。これらの道具がすべて揃わぬうちは、儀式のどの手順にも手をつけてはならない。どれも欠かせぬものだ。\n\n次のページから、それぞれの道具の使い方を記す。", "." },
  ["51da3f4c7140a5d7"] = { "Krakkenは咆哮し、その声は海の嵐のように轟いた。\n\n\"我らは来たり。\"\n\nMin'lothは揺るがず立ち、魔法を呼び起こした。I'laliaへ送られた波は割れて両側へと流れ、その先の密林を水没させた。Min'lothは続いて手下たちに束縛の呪文を唱えさせ、何十ものトロールの声が上がって喧騒が響き渡った。\n\nそして、ひとつの声が他のすべてを圧して響いた。", "." },
})
