-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["6434c2c85f370bb2"] = { "第1章 - 前線\n\nStormpikeの軍を解体するのは、玉ねぎの皮をむくのによく似ている。芯にたどり着くには、まず一番外側の皮から剥がしていかねばならない。\n\n主にStormpike MountaineersとAlliance Sentinelsからなる前線は、隊長の掩蔽壕とつながっている。これらの部隊に力を与え、戦線が攻め込まれたときに援軍を送り込んでいるのはCaptain Balinda Stonehearthだ。隊長を討てば、前線の兵力は崩れ去るだろう。", "." },
  ["6482add600162637"] = { "Zul'Gurubへ持ち帰ったことで、新たなTidebearerが選ばれた。こうしてその営みは幾世代にもわたって続いた。Stoneは潮とともに現れ、Tidebearerは潮の中へと去っていったのである。\n\n現代においてもStone of the Tidesの話はあちこちで伝えられているが、これほどの力を持つ物がなぜこれほど規則的に現れるのか、そして誰の意図によるものなのか、疑問に思わずにはいられない。", "." },
  ["64edc67700ed485c"] = { "Sargerasは、若者の力が現れるまで時を待った。Medivhが十代になる頃には、彼はその魔法の腕前でAzerothでたいへんな人気者となっており、2人の友とたびたび冒険に出かけていた。Azerothの王子Llaneと、Arathiの血統の最後の子孫の一人であるAnduin Lotharである。3人の少年は王国中で絶えずいたずらを働いたが、一般の市民からはとても好かれていた。", "." },
})
