-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["a271f008c1bd0d80"] = { "すべての準備が整うと、SargerasはAzerothへの壊滅的な侵攻を開始した。Burning Legionのウォリアーの悪魔たちはWell of Eternityを通って世界になだれ込み、眠るナイトエルフの都市を包囲した。ArchimondeとMannorothに率いられたLegionはKalimdorの地に群がり、その後には灰と悲しみしか残らなかった。", "." },
  ["a28b603f4e182cd0"] = { "Sara、君への私の愛は不滅だ。それは、全能なる存在でなければ断ち切れないほどの強い綱で、私を縛りつけているようだ。そして王国への愛が強い風のように私を包み、それらの鎖ごと、抗いがたく私を戦場へと運んでいく。", "." },
  ["a29085c92dfe9bed"] = { "Kingdom of IronforgeがAllianceの勝利にどれほど頼っているかを私は知っている。そして、Great Warsの流血と苦難を通じて我々に先立った者たちに、どれほど大きな恩義があるかも。私は、このAllianceを守り、その恩を返すためなら、この人生のあらゆる喜びを捨てる覚悟がある。心から、その覚悟があるのだ。", "." },
  ["a2ab710f897af861"] = { "「Scythe of Eluneだ」とRidersの一人が、斧を石で研ぐような、耳障りで甲高い声で叫んだ。そして最後の言葉――Elune――は、その響きに喉を詰まらせるかのように、しわがれていた。\n\nその声を聞いて、私は恐怖に襲われた。その声のおぞましさのせいでもあり、そして……そのRiderの言うScytheに心当たりがあったからだ。数日前に私がRoland's Doomの岩の間から引き抜いた、あの呪われた代物に違いない。Black Ridersが探していたのはそれだったのだ！\n\nそしてそれこそが、Svenの家族を死なせることになるものだった。", "." },
  ["a2f5f9c8e1874f1e"] = { "Stoutmantleへ――\n\n赤の他人をよこしてDefiasの一味の話をさせるとは、いい度胸だな。かつてお前は俺の命を救ったが、今度はその命を大きな危険にさらしている。\n\nだが、お前には借りがある。Defias Brotherhoodはお前が思っているより大きい。WestfallからElwynn Forestまで、あらゆる鉱山が奴らの支配下にある。KoboldsとGnollsは奴らの汚れ仕事をさせるために引き入れられた。奴らはゴブリンに金属の怪物を造らせ、Westfallの畑に置いて、地元の住民の迷信につけ込もうとしている。", "." },
})
