-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["134bee8139ea3760"] = { "無責任に扱えば魔法は本質的に危険だということには同意していたものの、Azsharaと彼女のhighborneは、無謀にも呪文の技を実践し始めた。Cenariusと多くの賢明なナイトエルフの学者たちは、明らかに不安定な魔法の術をもてあそべば災いしか生まないと警告した。だがAzsharaとその信奉者たちは、頑なに、増大しつつある力を広げ続けた。", "." },
  ["1386498c78696293"] = { "Prophetは強大で、我らの祖先の霊と交信する。だが、あの男は愚か者だ！自らが持つ真の力を分かっていない。あの男はAmulet of Spiritsを身につけている――その力の大半はそこから来ているのだ。\n\n私が知ったところでは、その護符は強力だが、不完全である。", "." },
  ["139fbbc9f038b045"] = { "Legacy Heart\n\nMogh the UndyingはStranglethornにいるトロールの呪術医だ。そして奴は、その秘密を解き明かせる者から死を遠ざけるといわれるLegacy Heartを持っている。MoghはRuins of Zul'Mamweにいる。できるものなら奴を倒し、Legacy Heartを私のもとへ持ってこい。", "." },
  ["13e61dfbfdbf9b95"] = { "だがKrakkenは古い。とてつもなく古いのだ。彼らは大地が初めて海から生まれた時を覚えていた。\n\n彼らはOld Onesが支配していた時を、そしてTravelersが来て彼らを打ち倒した時を覚えていた。魔法がまだ新しかった時を覚えていた。\n\n彼らは古く、多くの秘密を抱いている。そしてMin'lothの呪文は強かったが、それはそのトロールと同じく、定命のものであった。\n\nそして、呪文は破れた。", "." },
})
