-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["d731c1802c85f3a0"] = { "StonefieldsとMaclures両家の争いが、Tommy JoeとMaybellの芽生えたばかりの恋を殺してしまうのではないかと心配なの。暗い知らせと戦争の噂が私たちの上に垂れ込めているこんな時代だからこそ、若さと愛は育まれなければならないわ。\n\nそこでお願いなんだけど、あなたの腕を使って、この若い恋人たちが互いを求める手助けになる薬か霊薬を調合してほしいの。\n\nありがとう、William。それから、仕事の合間に時間ができたら、ぜひ遊びに来てちょうだい。昔話でもして笑い合いましょう。\n\n-Mildred", "." },
  ["d7a63e9e7f7e99cb"] = { "この功績証明書は、{name}がsearing gorgeの災いであるMargol the Ragerを討ち取ったことを証するものである。\n\nIronforge博物館はこの功績を認め、所持者の寛大な貢献に感謝する。\n\n-Head Curator Thorius Stonetender", "." },
})
