-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["bd2e250524cd147f"] = { "Solomonへ\n\nこの布告を携える者には、Stormwindの代理保安官としての正式な地位が与えられた。黒竜族とBlackrockのオークとの関わりを示す証拠を探すため、この者を使ってよい。証拠が見つかった場合、この代理保安官はその証拠をStormwindの私のもとへ持ち帰ること。その時点で、Lakeshireを支援するに足る兵力を派遣する命令を下す。\n\n敬具\n\nHighlord Bolvar Fordragon", "." },
  ["bd8e540e898b8334"] = { "Ofgut Stonefist\n\nDark Keeper Ofgutの鉄槌の前に倒れた者は数えきれない。\n\nWest Garrisonの兵士たちは、彼が通ると畏れて頭を垂れる。彼らのうち誰が、Ofgutの目をのぞき込み、闇の鍵がささやく秘密を見ることができようか。", "." },
})
