-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["b204e62e797e64aa"] = { "反乱は鎮圧されたものの、Hordeは被った甚大な損失を取り戻すことができなかった。Gul'danの裏切りは、Allianceに希望だけでなく、態勢を立て直して反撃する時間をも与えたのである。", "." },
  ["b23b123d6683439b"] = { "新たな世界の危険からKalimdorを守るため一人残されたTyrandeは、ナイトエルフの姉妹たちの中から強力な戦闘部隊を集めた。Kalimdorの防衛に身を捧げた、恐れを知らず高度に鍛えられた女ウォリアーたちは、Sentinelsとして知られるようになった。彼女たちはAshenvaleの薄暗い森を自分たちだけで巡回することを好んだが、急を要する時に呼び寄せられる多くの味方がいた。", "." },
  ["b273a25f1c67e404"] = { "Asterionといった。彼はBashal'Aranの民の間に住み、しばしばAmeth'Aranを訪れては、その民の必要と望みに応えていた。\n\nこうして、Well of Eternityのほとりで双子の町は育ち栄えたが、その一方で、星の下の世界はゆっくりと狂気へと落ちていった。", "." },
  ["b2afd52ea2a83439"] = { "Goodsteel's Balanced Flameberge -\n\n最後に、これまでの鍛冶の仕事で最高傑作のひとつを取り戻したい。このflamebergeは見事な剣でな、実に高潔で偉大なウォリアーだと思った男に授けたんだ。ところがそいつは、Jarquaiとかいうmurlocにこてんぱんにやられちまった。そんな名前だったはずだ。\n\nSwamp of Sorrowsの海岸沿いを旅していたとき、そいつはその生き物に攻撃を仕掛けようと思い立った。だが失敗して逃げ出したらしい。しかも武器を置いていったもんだから、そのmurlocに持っていかれたってわけだ。", "." },
  ["b2f321c296ff4ff6"] = { "Essence of the Exile:\n\nこの精髄は、Arathi Highlandsの追放された精霊たちが持つ3つのお守りを融合させることで得られる。精霊からThundering、Burning、Cresting Charmsを集め、それぞれ8個ずつ私の大釜に入れよ。\n\nそのお守りから、追放者の精髄が形作られる。", "." },
})
