-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["3845d43c27cb6359"] = { "妻子を失った悲しみと自己嫌悪に苛まれながら、Duskwoodをさまよっている。今ではMor'Ladimと名乗るその者は、心なき復讐心と憎しみを抱いてDuskwoodを徘徊し、見境なく殺人を犯すことで知られている。", "." },
  ["38893c4061449206"] = { "Titanたちは、世界を形づくる手助けをさせるため、いくつもの種族に力を与えた。大地の下に底知れぬ洞窟を掘るため、Titanたちは魔法の生きた石からドワーフに似たearthenを創り出した。海を浚い、海底から陸地を持ち上げるため、Titanたちは巨大だが穏やかなsea giantを創り出した。長い時代にわたってTitanたちは大地を動かし形づくり、ついに1つの完璧な大陸が残った。", "." },
  ["389c234f7a1b2f52"] = { "捕らわれたオークたちは張りつめ、再び戦いたいと焦っていたが、古い監獄要塞Durnholdeを拠点とする収容所の看守たちが平穏を保ち、しっかりとした秩序らしきものを維持していた。", "." },
  ["38a7f556c8bea838"] = { "Kil'jaedenは、Ner'zhulが人間という種族を世界から一掃する暗黒の使命を果たしたならば、呪いから解放し、宿るための新たな健やかな肉体を与えると約束した。", "." },
  ["38b66cc326989d02"] = { "ドラゴンより俺たちを恐れる奴もいる。腕利きの鍛冶屋より俺たちを羨む奴もいる。戦場での俺たちの強さを讃える奴もいれば、俺たちの信仰を喜ぶ奴もいる。飲み比べで潰されるのがただ悔しいって奴もいるがな！ だがこれは覚えておけ、{class}、お前はAzeroth全土でも最も精鋭の守り手の一人なんだ。俺たちが聖なる光を強めるのと同じだけ、聖なる光も俺たちに力を与えてくれる。\n\nこの土地に少し慣れたら、もっと話してやろう。Valleyを見下ろすAnvilmarの中で俺を探せ。\n\n-パラディンのトレーナー、Bromos Grummner", "." },
  ["38bc97216e8372f5"] = { "トナカイを生きたまま返してほしけりゃ、身代金はさっさと払うことだ。Southsea Piratesは支払いが遅れるのが気に食わねえ。それに、あのけだものがてめえらの流儀の海賊稼業にとってどれだけ値打ちがあるか、こっちは知ってるんだ。\n\n1000ゴールドをTanarisのLost Rigger Coveの入り口まで持ってこい。トナカイを救い出そうとすれば、Metzenにはとても短い板の上をとても長く歩いてもらうことになるぜ。\n\nイヤーッ……\n\nSouthsea Pirates", "." },
  ["38e078263643939c"] = { "竜たちは、Silithusの遥か上空、Ahn'Qirajの砦から数千フィートも上の成層圏で集った。\n\nそこにはAspect of TimeたるNozdormuの子、Anachronosがいた。\n\nEmerald Dreamからは、Aspect of NatureたるYseraの子、Merithraが来た。\n\nAspect of LifeたるAlexstraszaの子、CaelestraszがRed Dragonflightを代表した。\n\nAspect of MagicたるMalygosの子、ArygosがBlue Dragonflightを代表した。", "." },
})
