-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["707da7eac675965f"] = { "Thrall率いるオークは、KalimdorのBarrensを横断する旅の途中で相次ぐ挫折に見舞われた。Cairne Bloodhoofとその強大なトーレンのウォリアーたちと友好を結んだものの、多くのオークは長年彼らを苦しめてきた悪魔の血の渇望に屈し始めた。Thrallの最も偉大な副官Grom Hellscreamでさえ、卑しい本能に身を委ねてHordeを裏切った。", "." },
  ["70810e843f69df0b"] = { "気高いオークの氏族は広々とした草原を渡り歩き、娯楽として狩りをした。一方、好奇心旺盛なdraeneiは、そびえ立つ断崖や峰々の中に素朴な都市を築いた。Kil'jaedenは、適切に育て上げれば、Draenorの住人がBurning Legionに仕える大きな可能性を秘めていると見抜いていた。", "." },
  ["709da0925c4d9b73"] = { "何世代にもわたる憎しみに倦んでいたオークと人間は、まったく耳を貸さなかった。Medivhはそれぞれの種族と別々に向き合わざるを得ず、預言と策略を用いて、彼らを海の向こうの伝説の地Kalimdorへと導いた。オークと人間はまもなく、長く隠されていたKaldoreiの文明に出会った。", "." },
  ["70cee36a70f23da8"] = { "<HTML>\n<BODY>\n<H1 align=\"center\">ALLIANCEの軍階級</H1><BR/>\n<P align=\"center\">士官</P><BR/>\n<P align=\"center\">Grand Marshal</P>\n<P align=\"center\">Field Marshal</P>\n<P align=\"center\">Marshal</P>\n<P align=\"center\">Commander</P>\n<P align=\"center\">Lieutenant Commander</P>\n<P align=\"center\">Knight-Champion</P>\n<P align=\"center\">Knight-Captain</P>\n<P align=\"center\">Knight-Lieutenant</P>\n<P align=\"center\">Knight</P><BR/>\n<P align=\"center\">下士官・兵</P><BR/>\n<P align=\"center\">Sergeant Major</P>\n<P align=\"center\">Master Sergeant</P>\n<P align=\"center\">Sergeant</P>\n<P align=\"center\">Corporal</P>\n<P align=\"center\">Private</P>\n</BODY>\n</HTML>", "." },
})
