-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["c4d426d47f730d1f"] = { "いまやWarchief Doomhammerに率いられたHordeは、故郷の世界Draenorからogresを連れてきて、不遇をかこっていたAmaniの森のトロールを配下に引き入れた。ドワーフの王国Khaz ModanとLordaeronの南部を蹂躙する大規模な遠征に乗り出したHordeは、あらゆる抵抗をたやすく打ち砕いた。", "." },
})
