-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["f84803af0f2c9208"] = { "邪悪で血に飢えた霊、Hakkar the Soulflayerはトロールの呼び声を聞き、彼らを助けることにした。HakkarはGurubashiに血の秘密を授け、彼らがStranglethorn Valeの大部分とSouth Seasのいくつかの島々にまで文明を広げるのを助けた。Hakkarは彼らに大いなる力をもたらしたが、その見返りにさらに多くを求めた。", "." },
  ["f8aafdec8f8fe4b8"] = { "過去を解き明かすため、私はこの謎を解く失われた手がかりを見つけることを期待して、現在の生物を調べ始めた。Lake SkulkerとLake Creeperは、Lake Lordamereの中央の島々に棲む古代の生物である。それらの体には苔が生えており、その苔は一部の化石に残る微量の物質に似ている。この関連が何を意味するのか推測するには、さらなる研究が必要である。", "." },
  ["f8b57bd38e090088"] = { "数か月のうちに、HordeはDraenorに住むdraeneiをほぼ一人残らず根絶やしにした。オークの凄まじい怒りを逃れることができたのは、散り散りになったわずかな生存者だけだった。勝利に酔ったGul'danは、Hordeの力と威勢を大いに喜んだ。それでも彼は、戦うべき敵がいなければ、栄光ある殺戮への抑えがたい欲望のあまり、Hordeが果てしない内輪揉めで自滅してしまうことを知っていた。", "." },
  ["f8dab9e175692083"] = { "Ner'zhulの魂を無力なまま停滞の中に捕らえ、Kil'jaedenは彼に最後の機会を与えた。Legionに仕えるか、さもなくば永遠の責め苦を受けるか。Ner'zhulはまたしても、無謀にも悪魔の契約に同意した。Ner'zhulの魂は、Twisting Netherの最果てから集められた、金剛石のように硬い氷を特別に加工した塊の中に封じられた。", "." },
})
