-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["aaf04514c6f4c8eb"] = { "お前の魂がNetherへ解き放たれなかったことを、ありがたく思え、{name}。そして、この巻物を書く手間をかける価値がお前にあると私が判断したことを、なおさらありがたく思うがいい。\n\nかつてお前が知っていた人々、おそらくは大切に思っていた人々は、もういない！ 今や自然ならざるものとなった残りの生涯を、そのことと共に「生きて」いくすべを学ばねばならん。まずはそれに折り合いをつけるすべを学ぶことを勧める。\n\nこの先の試練に備えができたと思うなら、Deathknellの教会で私を探せ。\n\n- プリーストのトレーナー、Dark Cleric Duesten", "." },
})
