-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["ae1f65480fe57e45"] = { "準備ができたら、起爆装置を押せ。\n\n箱の筐体の中に、銅線と銀線をMelthusianアンテナ・アレイと一緒に通して、強い信号が出るようにしておいた。これで十分な距離が取れるはずだ。ただ、近くのゴブリンどもには気をつけろ。奴らの目の届くところでお前を見つけたら、俺の作品を快くは思わないだろうからな。\n\nああ、念のため言っておくが、爆発する時に荷馬車の近くにいるなよ……痛いぞ。", "." },
  ["ae445e6c5653a024"] = { "Karazhanから帰還の途にあったLotharと彼のウォリアーたちは、人命の損失を食い止め、かつて栄光に満ちていた故国を救いたいと願っていた。だが彼らの帰還は遅すぎ、愛する王国が煙を上げる廃墟と化しているのを目にした。オークのHordeは田園地帯を荒らし続け、周辺の土地を自らのものとした。身を潜めざるを得なくなったLotharと仲間たちは、いかなる代償を払おうとも故国を取り戻すと、厳かな誓いを立てた。", "." },
  ["ae6373dc5de2a8d1"] = { "Hand of Dagun\n\nDagunは深い海の生き物で、Dustwallow MarshのMurlocに崇められている。彼らはシャーマンが魔法をかけた特別な海藻を使って、奴を海面へおびき出す。Murlocを狩り、魔法の海藻を集め、それをMurlocの祭壇に置け。Dagunが現れたとき、お前はそこで待ち構えているというわけだ。\n\nその手が欲しい。", "." },
  ["ae86d7a51c183814"] = { "三番目の派閥であるDark Iron氏族は、魔術師にして領主であるThaurissanが率いていた。Dark Ironsは山の下の最も深い闇の中に潜み、BronzebeardとWildhammerの双方の同族に対して陰謀を巡らせていた。", "." },
  ["ae8d63d48953f5f4"] = { "<HTML>\n<BODY>\n<H1 align=\"center\">HORDEの士官階級</H1><BR/>\n<P align=\"center\">第2部</P>\n<IMG src=\"Interface\\PvPRankBadges\\PvPRank09\" align=\"left\"/><BR/>\n<P align=\"right\">Centurion</P><BR/><BR/>\n<IMG src=\"Interface\\PvPRankBadges\\PvPRank08\" align=\"left\"/><BR/>\n<P align=\"right\">Legionnaire</P><BR/><BR/>\n<IMG src=\"Interface\\PvPRankBadges\\PvPRank07\" align=\"left\"/><BR/>\n<P align=\"right\">Blood Guard</P><BR/><BR/>\n<IMG src=\"Interface\\PvPRankBadges\\PvPRank06\" align=\"left\"/><BR/>\n<P align=\"right\">Stone Guard</P><BR/><BR/>\n</BODY>\n</HTML>", "." },
  ["aead5bb0f75b4b97"] = { "オークがBurning LegionのためにAzerothの世界を征服できなかったことで、Kil'jaedenはAzerothの王国全土に混沌の種をまく新たな軍勢を生み出さざるを得なくなった。この新たな軍勢は、Hordeを苦しめたのと同じつまらない対立や内輪揉めに陥ることがあってはならなかった。その使命においては、無慈悲かつ一途でなければならない。今度こそ、Kil'jaedenに失敗は許されなかった。", "." },
  ["aeecfc8b64580dfa"] = { "これらの彫刻が施されたレリーフは、Uldamanの最初の部屋群で得られた最も重要な発見だったかもしれない。その彫刻は、ゴーレムのようなearthenとドワーフ族の間のつながりを明確に示している。さらなる証拠が見つかれば、我々が神話のtitanによって創造されたという説が真実であると証明されるかもしれない。", "." },
})
