-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["b53d95914dfef089"] = { "Jesse Moralesを偲んで", "." },
  ["b553408c1b227621"] = { "我々は夜明けとともに出発し、Tkashi Ruinsを過ぎて南へ向かった。BarnilはBloodscalp Tribeの者たちに出くわすのではないかと懸念を口にした。私はBarnilに、Bloodscalpsは部族の宿敵であるSkullsplittersを滅ぼすことのほうに関心があるのだと念を押した。言うまでもなく、Barnilは少しも安心しなかった。だが私には、弾を込めたライフルと、火薬の詰まった鞄と、3人の凄腕のハンターがついていたので、敵の待ち伏せの心配などなかった。", "." },
  ["b59927221da03622"] = { "その後、そのRiderの肩はわずかに落ちた。まるで内に宿っていた霊が抜け出たかのように。そして先ほどの甲高い声で、最後の言葉が発せられた。\n\n「主はお告げになった。殺せ」", "." },
  ["b5b60166deadad51"] = { "自分たちの数えきれない業を覆そうとするSargerasの使命を知らぬまま、Titanたちは世界から世界へと渡り歩き、それぞれの惑星を思うままに形づくり、秩序を与え続けた。その旅の途中で、彼らは小さな世界に行き当たった。後にその住人たちがAzerothと名づけることになる世界である。", "." },
})
