-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["e227e8d32486ce4d"] = { "このページに何かを書くのは久しぶりだ。依然として有望なものは何もない。昨日、Sunstrider Isleの生徒の一人、Felendrenという者が、師たちの助言に耳を貸さず、あの病に屈したという知らせを受けた。\n\n我々の努力を倍にせねばならない。", "." },
  ["e246993cb0d8905d"] = { "Allianceの艦隊司令官\n\nStormwindの友", "." },
  ["e25b3998505fd068"] = { "<HTML>\n<BODY>\n<H1 align=\"center\">HORDE &amp; ALLIANCEの軍階級</H1>\n<BR/>\n<BR/>\n<IMG src=\"Interface\\PvPRankBadges\\PvPRankHorde\" align=\"left\"/>\n<BR/>\n<P align=\"right\">Throm'ka! この</P>\n<P align=\"right\">書には</P>\n<P align=\"right\">数多くの一覧が載っている。</P>\n<P align=\"right\">Hordeと、ちっぽけな</P>\n<P align=\"right\">Allianceの</P>\n<P align=\"right\">軍階級の一覧だ。</P>\n<P align=\"right\">まずは</P>\n<P align=\"right\">Horde、次にAllianceだ。</P>\n<P align=\"right\">それぞれ士官と下士官・兵の階級を載せてある。当然のことだが、最も強い者が一番上に、弱い者はその下に記されている。</P>\n</BODY>\n</HTML>", "." },
  ["e2d3ef98ad676c7b"] = { "傷は深くなかったが、それでもひどく出血した。怪我をした指に包帯を巻く前に、かなりの量の血が作業台にこぼれてしまった。\n\nそして、この新たな汚れを片付けているとき、私は実に奇妙なことに気づいたのである……", "." },
  ["e2effaf3876ddf56"] = { "AjeckとSir Erlgadinは、Dwarven Rifleで効率よく狩る方法を学びたがっていた。私は人間の二人に、原始的な飛び道具をベースキャンプに置いてこさせた。Barnilと私は、Ironforgeの最高級の銃器を彼らに持たせた。", "." },
})
