-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["6625073f5f231c8d"] = { "ようこそ、若き{class}よ。風があなたの来訪を告げてくれました。大地はあなたの強さを讃えました。そして今、古の精霊たちがあなたのこれからの偉業を囁いています。我らの民は常に、賢く偉大な指導者を必要としています。そしてその両方の美徳を求めて、しばしば我らのような者を頼るのです。あなたにその気があるなら、我らの道をもっと教えましょう。\n\nRed Cloud MesaのCamp Naracheで私を探してください。そのときにもっと話しましょう。\n\n-シャーマンのトレーナー、Meela Dawnstrider", "." },
  ["662a26ee286b4809"] = { "Cliffwatcher Longhornへの緊急連絡\n\nCamp E'thokのCentaurの大部隊が、我々の補給キャラバンのひとつを襲撃した。キャラバンの者は全員失われ、物資もすべて奪われた。これはCentaurによる大胆かつ前例のない攻撃であり、さらなる襲撃があるのではないかと危惧している。", "." },
  ["66b27657edf55b6d"] = { "Vorfalk Irongourd\n\nVorfalkはGrim Guzzlerの貯蔵室で働いている。Dark Keeperたちへの彼の献身は深い。\n\n彼の魂が強くあらんことを。", "." },
})
