-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["2d55674ade8897a2"] = { "<HTML> <BODY> <H1 align=\"center\"> クリスタル・パイロン取扱説明書 </H1> <BR/> <P align=\"center\"> 「Un'Goro Craterのパワークリスタルの集め方と使い方」 </P> <BR/> <BR/> <P align=\"left\">第1章：Northern Pylon </P> <BR/> <P align=\"left\">第2章：Eastern Pylon </P> <BR/> <P align=\"left\">第3章：Western Pylon </P> <BR/> </BODY> </HTML.", "." },
  ["2d55675ade8897b2"] = { "<HTML>\n<BODY>\n<H1 align=\"center\">\nクリスタル・パイロン取扱説明書\n</H1>\n<BR/>\n<P align=\"center\"> 「Un'Goro Craterのパワークリスタルの集め方と使い方」 </P>\n<BR/>\n<BR/>\n<P align=\"left\">第1章：Northern Pylon </P>\n<BR/>\n<P align=\"left\">第2章：Eastern Pylon </P>\n<BR/>\n<P align=\"left\">第3章：Western Pylon </P>\n<BR/>\n</BODY>\n</HTML>", "." },
  ["2d96b19261a09d89"] = { "Ner'zhulと彼に忠実なShadowmoon氏族は、新たに生み出されたポータルのうち最大のものを通り抜けた。そのとき、大規模な火山の噴火がDraenorの大陸を引き裂き始めていた。燃える海が盛り上がって砕けた大地をかき乱し、責め苛まれた世界は、ついに黙示録的な大爆発に呑み込まれた。", "." },
  ["2d9c37734a7d910a"] = { "怒りのあまり、SargerasはeredarとNathrezimの牢獄を打ち砕き、忌まわしい悪魔たちを解き放った。狡猾な生き物たちは闇のTitanの計り知れない怒りの前にひれ伏し、どんな悪しき方法でも彼に仕えると申し出た。強大なEredarの中から、Sargerasは悪魔の破壊の軍勢を率いる2人の勇者を選んだ。", "." },
})
