-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["7d18143a29f65c7a"] = { "Arcanite Buoyの作り方：\n\nArcaniteを少しBuoyと混ぜる。幸運を祈る！\n\nこんなに簡単だとは思わなかっただろう？ 欠けた鱗の借りはまだ返していないからな、旧友よ。\n\n-Azuregos\n\n追伸：arcanite buoyを実際に作る方法を君が見つけられるといいのだが。今のでたらめは、私がその場ででっち上げたものだからな。彼らがどうやってMawsを見つけるつもりなのか、私には見当もつかない。", "." },
  ["7d5b071ec8466195"] = { "長い月日をかけて準備を整えた末、Kel'ThuzadとそのCult of the Damnedは、ついにLordaeronに不死の疫病を解き放ち、最初の一撃を加えた。Utherと仲間のパラディンたちは、疫病を止める方法を見つけようと感染地域を調査した。その努力にもかかわらず疫病は広がり続け、Allianceを引き裂こうとしていた。", "." },
})
