-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["201e6c3920159a23"] = { "<HTML>\n<BODY>\n<H1 align=\"center\">\n第2章：Eastern Pylon\n</H1>\n<BR/>\n<BR/>\n<IMG src=\"Interface\\Pictures\\11482_crystals_mini_east\" align=\"left\"/>\n<P align=\"right\">Eastern<BR/>\nPylonは<BR/>\n青、黄、<BR/>\n緑の<BR/>\nクリスタルを受け入れる。</P>\n<BR/>\n<BR/>\n<BR/>\n<BR/>\n<P align=\"left\">Pylonは、青いクリスタルを主な動力源として生み出されるエネルギーに集中する。</P>\n</BODY>\n</HTML>", "." },
  ["2084ed277722c33c"] = { "あなたが戦ったあの元兵士について、ようやくいくつか情報を掘り起こしました。この家系はきちんと記録されていなかったので、跡をたどるのは大変でしたが、ついに血縁者を見つけました。\n\n信じられますか？ Light's Hope ChapelのCaretaker Alenが、実はChristophの息子なのです。父親の話を聞けば、彼の心も安らぐかもしれません。もしまたPlaguelandsでArgent Dawnのために働くことがあれば、どうか彼と話してあげてください。それは優しさというものです。", "." },
  ["20afc939e19b9b33"] = { "やがて、悪魔の存在がTwisting NetherからTitanの世界へと入り込むようになり、Pantheonは最も偉大なウォリアーであるSargerasを、最前線の守り手に選んだ。溶けた青銅でできた高潔な巨人Sargerasは、数えきれない千年紀にわたって務めを果たし、見つけ次第これらの悪魔を探し出しては滅ぼした。永劫の時の中で、Sargerasは強大な2つの悪魔の種族に出会った。どちらも物理宇宙に対する力と支配を手に入れようとしていた。", "." },
  ["20c20f67849753aa"] = { "心の中に鳴り響く狂騒によって、Ner'zhulはさらに強大になった。まるで彼らの魂が、彼にとって欠かせない糧となっているかのようだった。ゾンビたちの行動を操り、望むままの目的へと導くことなど、子供の遊びにすぎないとわかった。", "." },
  ["20f17fa45d1ac5fe"] = { "MOR GRAYHOOF(続き)……\n\n後になって、Morが実は落下を生き延びていたことが分かった。だが我が良き友に幸せな結末は訪れなかった。彼はTazz'Alaorのトロールどもに捕らえられたのだ。ほどなくして、War Master Vooneに拷問されている最中に、Valthalakの暗殺者の一団が飛び込んできて、とどめを刺した。\n\nMor Grayhoofの霊の残響を呼び起こそうとするなら、War Master Vooneの部屋が呪われた場所である。", "." },
  ["20f904cfbbb2f4b9"] = { "かつて高潔だったその心を蝕む堕落によって、Sargerasの巨大な姿さえも歪んでいった。目も髪も髭も炎を噴き上げ、金属の青銅の肌は裂けて、燃え盛る憎悪の果てしない炉をあらわにした。", "." },
})
