-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["9d8b08df0816f988"] = { "<HTML>\n<BODY>\n<BR/>\n<BR/>\n<P align=\"left\">ここにDurotan眠る。Frostwolf Clanの初代族長にして、我らが誉れ高き大族長Thrallの父である。彼は我らの中で最も勇敢な者であった。我らの民を奴隷にせんとする者たちに裏切られたのだ。Durotanは我らが自由を勝ち取るために命を捧げた。我らは彼を、そして彼が息子を通じて我らに遺したものを讃える。</P>\n<BR/>\n<P align=\"left\">FrostwolvesのFar Seer、Drek'Thar </P>\n</BODY>\n</HTML>", "." },
  ["9d8d2014b95917d4"] = { "Arathorianの二番目の都市国家であるDalaranは、Stromの北の地に建設された。駆け出しの魔法使いの多くが、Stromの窮屈な束縛を後にしてDalaranへと向かい、そこで新たな力をより自由に使うことを望んだ。この魔術師たちはその技を用いてDalaranの魔力を帯びた尖塔を築き上げ、研究の探求に耽った。", "." },
  ["9ddb35746ea03187"] = { "彼らは愛する故郷を失ったことに心の底から憤っていた。King BronzebeardはWildhammersにIronforgeの領内に住む場所を提供したが、Wildhammersは頑として拒んだ。Khardrosは民を率いてLordaeronの地へと北上した。Hinterlandsの緑豊かな森に定住したWildhammersはAerie Peakの都市を築き、そこで自然とより親しくなり、その地の強大なgryphonと絆を結ぶまでになった。", "." },
})
