-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["e016c7bf9cbf1fb6"] = { "Miner Orwell\n債務未払い。Azurelodeからの次回の鉱石納入時に支払い予定。\n\nMiner Fitzgerald\n債務未払い。Azurelodeからの次回の鉱石納入時に支払い予定。\n\nCitizen Netherand\n債務はすべて支払い済み。\n\nCitizen May\n債務はすべて支払い済み。\n\nForeman Bonds\n債務未払い。Azurelodeからの次回の鉱石納入時に支払い予定。", "." },
  ["e071090f7f172429"] = { "エルフたちはThoradinに、トロールの軍勢は膨大であり、トロールがQuel'Thalasを滅ぼせば、次は南の地を攻撃しに向かうだろうと告げた。軍事的な援助をひどく必要としていた窮地のエルフたちは、戦闘部隊との戦いへの助力と引き換えに、選ばれた一部の人間に魔法の扱いを教えることを急ぎ承諾した。", "." },
  ["e0805a1ec8f00240"] = { "部族が、故郷が恋しい。この密林の暑さに比べれば、開けた平原を渡る風や、Thunder Bluffに沈む夕日を喜んで迎えるだろう。\n\nすぐ近くに海の水が見えるが、それは体も苛立ちも少しも冷ましてはくれない。ただ、ここに囚われていることを思い出させるだけだ。", "." },
})
