-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["c14416fc8da957d9"] = { "鷲よりも速く、そのトナカイたちはやって来た。\n\n彼は口笛を吹き、叫び、その名を呼んだ。\n\n「さあ、Mercer！ さあ、Chilton！ さあ、JordanとKaplan！\n\n行け、Nagle！ 行け、Pardo！ 行け、GoodmanとMetzen！\n\nポーチのてっぺんへ！ 壁のてっぺんへ！\n\nさあ、駆けてゆけ！ 駆けてゆけ！ みんな駆けてゆけ！」", "." },
  ["c14e348cbf6824ed"] = { "Arthasは想像を絶する力を持つ兜を頭にかぶり、新たなLich Kingとなった。Ner'zhulがずっと計画していたとおり、Ner'zhulとArthasの魂は融合し、ただ一つの強大な存在となった。Illidanとその軍勢は屈辱のうちにOutlandへ逃げ帰るほかなく、一方Arthasは、世界がかつて知る中で最も強大な存在の1つとなった。", "." },
  ["c19d3a6c6f3742f9"] = { "「でも道は遠いし、子供たちがいたら足手まといになる。この子たちは置いていかなくては」\n\n彼女の策は単純だったが、単純な策ほど成功の見込みが高いものだ。うまくいけば、Ridersを農場から遠ざけられる。彼女自身は助からないが、子供たちは無事でいられる。そしてうまくいくはずだった。Ridersが彼女の気高い嘘を信じさえすれば。\n\n私は光の信徒であったことなど一度もないが、あの恐ろしいRidersに立ち向かうSvenの妻のために、必死に祈った。\n\n「どうか」と私は祈った。「奴らが信じますように」", "." },
  ["c1aa1acb0dff6da8"] = { "<HTML>\n<BODY>\n<H1 align=\"center\">軍の階級に関する論考</H1>\n<BR/>\n<BR/>\n<IMG src=\"Interface\\PvPRankBadges\\PvPRankAlliance\" align=\"left\"/>\n<BR/>\n<P align=\"right\">以下に記すのは</P>\n<P align=\"right\">Allianceの</P>\n<P align=\"right\">軍の階級であり、</P>\n<P align=\"right\">続いて</P>\n<P align=\"right\">Hordeの種族について</P>\n<P align=\"right\">知られている</P>\n<P align=\"right\">情報を記す。いずれも</P>\n<P align=\"right\">2つの</P>\n<P align=\"right\">部に分けて示す。士官、次いで兵の順に、それぞれ階級を上位から下位へ並べる。Allianceよ、永遠なれ！</P>\n</BODY>\n</HTML>", "." },
  ["c1e9097627eb8b8d"] = { "Razorfen Kraulと呼ばれる、悪臭を放つ茨だらけの藪の中へ乱暴に引きずり込まれた。粗末な造りの小屋に放り込まれ、瀕死のナイトエルフと一緒に捕らえられている。\n\n持ち物はこの日誌と羽根ペン、懐中時計のほかには何もない……\n\n誰か来る……", "." },
})
