-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["37c1b1f90e868cf4"] = { "Ivarの古い家に防御陣地を築き、Raneがさらなる襲撃に備えて見張る間、Erlandが偵察任務を続けた。\n\nその後Erlandは北の果樹園でWorgに追い詰められ、別のForsakenの工作員の助けによってようやく逃れた。その工作員こそ、この報告書を届ける者である。", "." },
  ["37cab6d2cf6d59f5"] = { "4000年近くにわたり、ハイエルフたちは人里離れた王国の安全の中で平和に暮らした。しかし、執念深いトロールたちはそう簡単に打ち負かされはしなかった。彼らは森の奥深くで企みを巡らせ、戦闘部隊の数が増えるのを待った。ついに、強大なトロールの軍勢が薄暗い森から突撃し、再びQuel'Thalasの輝く尖塔を包囲した。", "." },
})
