-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["fb3ed87fd10bed0c"] = { "崩れゆく古都Stromの城壁の中に残されたArathiの子孫たちは、Khaz Modanの岩山を越えて南へ旅立つことに決めた。長い季節を重ねた末にその旅はついに終わり、彼らは自分たちがAzerothと名付けることになる大陸の北部に定住した。肥沃な谷に彼らはStormwindの王国を築き、それはたちまち自立した一大勢力となった。", "." },
})
