-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["145c7fd619b010ff"] = { "5日目\n\n若いのに野営地の見張りをさせ、俺は洞窟へ忍び寄って辺りを見て回った。トロールどもの数はいささか厄介だ。洞窟からトロールを一掃するなら、Mountaineersを大挙して呼ばねばならないかもしれない。\n\nそういえば最近、troggsのことを書いていなかった。この辺りでは数を増しているが、あまりに原始的なので、大した脅威にはならない。それが本当かどうかは、時が教えてくれるだろう。", "." },
  ["145dc5063dd483d4"] = { "以下は、Elwynnの鉱山から我らのWestfall本部へのDefiasの金の回収の手順と日程である。\n\n回収日程：\n\n日曜日：12:30pm\n水曜日：12:30pm\n\n指定された各日までに、Elwynnの鉱山で得た金はBrackwellのカボチャ畑に集められる。この回収を担当する工作員「Collector」は、彼が持つ刻印入りの指輪で見分けられる。私が彼に与えた指輪だ。", "." },
  ["14ad1d6071bdec85"] = { "お前たちの大事なペットは、このSearing Gorgeの容赦ない暑さの中で、あまり具合が良くないようだ……我々の要求にすぐに応じるのが賢明だぞ。\n\nstar rubiesを5つと、700ゴールドを持ってこい。両方を、何の印もない無地の包み一つに入れるのだ。一週間以内に、その包みをStonewrought Passの門に置いていけ。\n\n我々の要求に応じなければ、MetzenはDark Iron DwarvenのWinter Veilの伝統的な宴のメインディッシュになるだろう。\n\nうーん……トナカイ……", "." },
  ["14b1dc813aa1bdd2"] = { "Holia Sunshield\n\nScarlet Crusadeの守護者\n\nDreadlord Beltherisを討ち果たす中で戦死", "." },
})
