-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["d436c11174d4c9cb"] = { "Jaina Proudmooreの下に残ったAllianceの軍勢は、Kalimdorの南部に落ち着いた。Dustwallow Marshの東の沖合に、彼らは堅牢な港湾都市Theramoreを築いた。そこで人間とドワーフの同盟者たちは、常に自分たちに敵意を向けるであろう土地で生き延びようと努めた。DurotarとTheramoreの守り手たちは互いに仮の休戦を守っていたが、植民地のもろい平穏は長くは続かない運命にあった。", "." },
  ["d4792a104ca2ff17"] = { "トロールの伝説 第III巻\n\rStone of the Tides\n\n著\n\rArchmage Ansirem Runeweaver\n\rDalaran\n\n序文\n\n古のGurubashi Empireは、魅力的で興味をそそる数多くの伝説の源であった。それらの伝説は疑いなく彼らの環境にまで遡ることができる。彼らの信仰体系と社会的慣習を調べると、自然環境に対する深い崇敬の念が見てとれるからである。\n\n私はこれまで数多くの", "." },
  ["d479cd59405f8a76"] = { "Dath'Remarに率いられたハイエルフたちは、Kalimdorを後にしてMaelstromの嵐に挑んだ。彼らの船団は長い年月にわたって世界の残骸の間をさまよい、その旅の途上で数々の謎や失われた王国を発見した。Sunstrider(「昼を歩む者」の意)の名を名乗るようになっていたDath'Remarは、同胞のための新たな故郷を築くべく、強いレイの力を持つ場所を探し求めた。", "." },
  ["d4968560eafb45ab"] = { "怒りに燃えたAlexstraszaのドラゴンたちはGrim Batolを引き裂き、Dragonmaw氏族の大部分を焼き尽くした。Alliance軍が生き残ったオークを捕らえ、待ち構える収容所に放り込むと、再統合というNekrosの壮大な企みは崩れ去った。Dragonmaw氏族の敗北はHordeの終わり、そしてオークの猛々しい血の渇きの終わりを告げるものだった。", "." },
})
