-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["098b8293db4b819b"] = { "Fellari Swiftarrow\n\rScarlet Crusadeのレンジャー隊長\n\rQuel'Thalasの市民\n\rSilverpineの森にて消息を絶つ", "." },
  ["09e16f1edd6f587e"] = { "Lich KingであるNer'zhulは、自分に残された時間が短いことを知っていた。Frozen Throneに囚われた彼は、Kil'jaedenが自分を滅ぼすために手先を送り込むだろうと疑っていた。Illidanの呪文による損傷はFrozen Throneを引き裂いており、そのためLich Kingの力は日ごとに失われていた。自らを救おうと必死になった彼は、最も偉大な定命のしもべを呼び寄せた。死の騎士Prince Arthasである。", "." },
})
