-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["ad12759681749799"] = { "MOR GRAYHOOF\n\nトーレンのドルイドにして最初に倒れた者\n\nMor Grayhoofは、The Veiled Bladeの中で常に揺るぎなく信頼できる仲間だった。Lord Valthalakの邪悪な手下どもに最初に倒されたのが彼だったことは、不幸というほかない。\n\nValthalakから逃げる我々を、亡霊の暗殺者と追跡者からなる、まさに軍勢と呼ぶべき一団が追ってきた。控えめに言っても、Blackrock Spireからの逃走は混乱を極めた。不運にもその途中、Morはどういうわけか足を踏み外した。もっとも、私は彼が突き落とされたのだと疑っている。いずれにせよ、彼は塔の下層の奥深くへと落ちていった。", "." },
  ["ad88d2353057d841"] = { "Ner'zhulの抵抗に苛立ったKil'jaedenは、自らの民をLegionの手に引き渡す別のオークを探した。狡猾な悪魔の王は、ついに求めていた従順な弟子を見つけた。Ner'zhulの野心に満ちた弟子、Gul'danである。Kil'jaedenは、完全な服従と引き換えに、計り知れない力をGul'danに約束した。", "." },
  ["adc1ee7ad9bfd35b"] = { "だが、仕留めた栄光に長く浸ってはいられなかった。地平線に目を向けると、哀れなBarnilのすぐ上、丘の稜線にいくつもの影が姿を現したのだ。\n\n「逃げろ、Barnil！」と私は叫んだ。Ajeck、Sir Erlgadin、そして私は、Barnilの頭上を越えて追ってくるraptorどもへ、弾丸と矢とボルトを一斉に放った。混乱のさなか、我々の誰かが一匹を仕留めた。", "." },
  ["adcb967c9ca56eb9"] = { "Medivhが14歳になった時、彼の中の宇宙的な力が目覚め、その魂に潜んでいた、隅々まで浸透したSargerasの魂と衝突した。Medivhは緊張病の状態に陥り、それは何年も続いた。", "." },
})
