-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["4500229ab3e968cf"] = { "この時点で疲れてきたから、飛行機械の向きを変えて家に向かった。でも、その前にもう2か所寄り道をした。Tainted ScarでLord Kazzakとあいつの悪魔どもの上をかすめ飛んでやって（あいつはそれをされるのが大嫌いなんだ）、もう一章をOnyxiaの煙突に突っ込んでやった。\n\n疲れた。もう寝る。", "." },
  ["45c0b4e029906853"] = { "Thane Madoran Bronzebeardが治めるBronzebeard氏族は、上王と緊密な結びつきを持ち、代々Ironforge Mountainの守り手として立っていた。Thane Khardros Wildhammerが治めるWildhammer氏族は、山の麓の丘陵や岩山に住み、都の内部でより大きな支配力を得ようとしていた。", "." },
  ["45eac528bfc7bb71"] = { "すべては、Roland's Doomと呼ばれる坑道であの呪われた大鎌を見つけたことから始まった。そう、それが始まりだった。それまで、Defias BrotherhoodはDuskwoodでの我々の働きぶりに満足していた。Scytheを見つける前は、この地の恐ろしさなどNorthshire Valleyと同じくらい穏やかなものに思えた。\n\nだが、坑道の瓦礫の山から突き出たScytheの柄を見つけ、忌々しいことにそれを引き抜いてからというもの、Roland's Doomは忌まわしい死の場所となったのだ！", "." },
})
