-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["7e3ce46098441c51"] = { "同じくSunderingを生き延びていたIllidanは、Malfurionとナイトエルフたちよりずっと前にHyjalの山頂に到達していた。世界の魔法の流れを保とうとする狂気の企てのなかで、IllidanはWell of Eternityの貴重な水が入った小瓶の中身を、その山の湖に注ぎ込んでいたのだ。", "." },
  ["7e49a90e860f0de6"] = { "Ironforge Mountainのドワーフたちは、長い幾世紀にもわたって平和に暮らした。しかし、彼らの社会は山の都市の限られた空間の中では大きくなりすぎた。強大なHigh KingであるModimus Anvilmarは正義と知恵をもってすべてのドワーフを治めていたが、ドワーフの社会の中には3つの強力な派閥が生まれていた。", "." },
})
