-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["29173f1824fce640"] = { "Bloodscalp Tusks：\n\nStranglethorn ValeのBloodscalp Trollsの牙には、稀有な性質がある。Bloodscalpどもの邪悪さはその牙に凝縮されており、粉末に挽けば、その忌まわしい力を解き放てるかもしれない。", "." },
  ["29fef013c68eb1ad"] = { "逃れようと、偉大な牡鹿は空へと跳び上がった。だが逃げおおせたかに思えたその時、その力強い角が星々に絡まり、彼はしっかりと捕らえられてしまった。蹴り、もがいたものの、Apa'roは天から身を解き放つことができなかった。ちょうどその時、兄An'sheを夜明けへと追っていたMu'shaが彼を見つけた。Mu'shaはもがく力強い牡鹿を見て、たちまち恋に落ちた。", "." },
})
