-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["e65e27ffcd190d5f"] = { "Harthal Truesight\nScarlet Crusadeのパラディン卿\nAzerothの市民 - Silver Handの騎士\n呪われた都市Stratholmeに入るのを最後に消息を絶つ", "." },
  ["e6dc01cb64605480"] = { "Earthmotherの目は、彼女が息吹によって生み出した大地を照らしていた。右の目An'she（太陽）は大地に温もりと光を与えた。左の目Mu'sha（月）は、夜明けにうごめく生き物たちに安らぎと眠りを与えた。その眼差しの力はあまりに強く、Earthmotherは空が一巡りするたびに、夢見る片方の目を閉じた。こうして、彼女の慈愛に満ちた眼差しは、世界の最初の夜明けに昼を夜へと変えたのである。", "." },
})
