-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["f4057b774c970a48"] = { "Thorsenにこれ以上情報を与えてはならない。そして奴を始末しなければならない。奴はもはや我らが大佐の役には立たない。機会があれば私がThorsenを片付けるが、この手紙を受け取ったなら、私にはまだその機会がなかったということだ。その場合は、Thorsenと我々の工作員との次の接触を、奴の命取りにすることを勧める。Kurzen万歳。-M", "." },
  ["f46def3be4c308d6"] = { "Kil'jaedenは、オークの氏族の準備がほぼ整ったことを知っていたが、彼らの究極の忠誠を確かなものにする必要があった。彼は密かにShadow Councilに命じ、破壊と憤怒の生ける器であるMannoroth the Destructorを召喚させた。Gul'danは氏族の族長たちを集め、Mannorothの猛り狂う血を飲めば完全に無敵となれると説き伏せた。", "." },
  ["f47d4886cff2ddf1"] = { "己の直感に従うことを選んだLotharは、その魔法使いの若き弟子Khadgarの助けを得て、Medivhの塔の砦Karazhanに攻め込んだ。KhadgarとLotharは取り憑かれた守護者を打ち倒すことに成功し、彼こそが争いの元凶であったことを確かめた。", "." },
  ["f4ca3fe2e1628782"] = { "Dorgar Stoenbrow\n\nScarlet Crusadeのウォリアー\n\nRed Cavernsの主\n\nMountains of Alteracにて最後に目撃される", "." },
  ["f4d05f591202f904"] = { "Dalaranでの悪魔の活動についてMagocratsから知らせを聞くと、エルフたちはすぐさま最も強力な魔法使いたちを人間の地へと派遣した。エルフの魔法使いたちはDalaranのエネルギーの流れを調べ、目にしたあらゆる悪魔の活動について詳細な報告を作成した。彼らは、世界に解き放たれている悪魔はほんのわずかにすぎないが、人間が魔法の力を振るい続ける限り、Legionそのものは深刻な脅威であり続けるだろうと結論づけた。", "." },
  ["f4e901d2bf18266e"] = { "Archbishop Alonsus Faol\n\nChurch of Lightの慈悲深き後援者。\n\nArchbishop FaolはLordaeronのStratholmeで善き働きを始めたが、Stormwindの人々にとっても偉大な友であった。Second War後の暗黒の日々に、彼はBrotherhood of Northshireの再編を助け、Stormwindの街そのものを再建するための莫大な資金を集めた。\n\nこの大聖堂は聖なる光の砦であるだけでなく、1人の男の高潔な精神と寛大さを永く伝える証としてここに立つ。", "." },
})
