-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["1eaab0aeb06f7f4c"] = { "力にみなぎり、再び世界を自由に歩けるようになったIllidanは、大いなる摂理の中で自らの居場所を見つけようと旅立った。だがKil'jaedenがIllidanの前に立ちはだかり、断ることのできない申し出をした。Kil'jaedenはMount HyjalでのArchimondeの敗北に怒っていたが、復讐よりも大きな懸念を抱えていた。", "." },
  ["1ec79caf72c8dad5"] = { "彼らは空と荒れ狂う大気を息吹によって生み出した。それはすべて、混沌から秩序を生み出すための、計り知れず遠大な計画の一部であった。彼らは原始的な種族にさえ力を与え、自らの作品の手入れをさせ、それぞれの世界の完全性を保たせた。\n\nPantheonとして知られる精鋭の一派に統べられたTitanは、創造の最初の時代に、Great Dark Beyondのあちこちに散らばる一億もの世界に秩序をもたらした。", "." },
})
