-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["c0563ef6ab013f3a"] = { "Layoへ\n\nこの立派な冒険者から、寛大な助力を得ました。この冒険者を、人手としてSilithusのあなたのもとへ送りました。そこに眠る秘密を解き明かすあなたの取り組みの中で、これほど貴重な人手が無駄にならぬよう取り計らってください。Circleは進展の知らせを心待ちにしています。\n\nCenariusがあなたを見守りますように……\n\nRabine", "." },
})
