-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["f007dae3477ae1b8"] = { "Uldaman、5日目\n\n……そのtroggは、殺された「同胞」からトパーズを奪うと、広間の正面近くの横穴へと進んでいった……\n\n……すぐさま、部屋の奥にある大きく目立つ壺にトパーズを入れた……\n\n……よりにもよって、ドワーフだ！しかも3人。彼らは今、troggから身を守るためにバリケードを築いている。彼らに呼びかけるのは自殺行為だっただろう。弱った今の私では、忌まわしいtroggどもに押し潰されかねない。だが、三つ目の宝石が分かり次第、私は……", "." },
  ["f04b00b070fcee31"] = { "これはWestfall地域の広大な土地の権利書である。以下に記された者たちに、指定された区域の所有権、ならびにその境界内で生み出されたすべての産物と建てられたすべての建造物の所有権を認めるものである。\n\n署名者：\n\nTheodore Furlbrow\n Verna Furlbrow", "." },
  ["f076442242369fc7"] = { "Darrowshire年代記\n\nDarrowshireは、西にあるDarrowmere Lakeにちなんで名づけられた、Lordaeronの南の丘陵地にひっそりと佇む村である。慎ましくも勤勉な住民で知られたDarrowshireは、Second Warまで、Lordaeronの歴史の表舞台に出ることはなかった。\n\nその戦いで英雄たちが生まれた。そして英雄たちが失われた。", "." },
  ["f0bee38412d0c954"] = { "ZuldazarのZanzaよ、我らは汝に呼びかける。\n\nLoa Zanzaよ、汝の助けを求める者たちを祝福したまえ。Zandalarianの\n民と手を結ぼうとする者たちを祝福したまえ。\n\nこの危急の時に我らを助けたまえ。Loaよ、我らを助けたまえ。我らの敵を打ち倒す力を与えたまえ。今ひとたびBlood Godを打ち破る力を与えたまえ。", "." },
})
