-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["c6800e053fc22c6d"] = { "その叫びが聞こえるか？\n\nHordeのための鬨の声\n\n勝利か死か！\n\n我らは忘れまい\n\n死を前にした彼の強さを\n\n彼の夢は今、現実となった。", "." },
  ["c6bd178a3a12a2b8"] = { "そのような失態の一つの際、ErlgadinがBarnilの肩に重い手を置いた。Ajeckと私は何気なく目をやり、その男が不注意なBarnilにしかるべき叱責を与えているのだろうと思った。しかしErlgadinは、近くの倒木のほうへゆっくりと首で合図した。こちらを見返していたのは、剃刀のように鋭い牙の並ぶ口の上にある、2つの鋭い黒い目だった。", "." },
})
