-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["d8205c4d622b3f56"] = { "彼が求めたのは名声を高めることではなく、\n\n同胞の上に立つ君主の座でもなかった。\n\n彼はLordaeronのために戦うことを選んだ。\n\n同胞がもはや戦わずに済むことを願って。", "." },
  ["d8c8f907676d532c"] = { "いずれにせよ、彼は計画の実現にある程度成功したらしい。我が同胞に試す前に、まずfurbolgで企てを試そうとしたのだろうか？ furbolgが、彼の欲しがる何かを持っていたのだろうか？ 誰にも分からない。\n\n自ら作った品(何かの杖か棒のようなもの)を使って、彼はAshenvaleのfurbolgの部族に入り込もうとした。ある時点で、ここがまだ詳しく分かっていないところなのだが、furbolgを操って行動させようとしていたところを、彼は彼らに見破られた。その行動が向けられていた相手は", "." },
})
