-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["b33822d767c52e60"] = { "Agashamへ\n\nLordaeronから来る我々の手の者が、まもなくお前の使節と会う。会談にふさわしい場所が見つかり次第、知らせる。\n\n署名\n\nHarbinger Grakus", "." },
  ["b38ada3161c3c0c2"] = { "もっと。もっと必要だ……\n\nWinterfallは……弱く……ない……", "." },
})
