-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["2a28758161ed64d0"] = { "ここにWarsong Clanの族長、Grommash Hellscream眠る\n\n多くの意味で、我らが民の呪いはGromに始まり、Gromに終わった。\nその名は我らの古き言葉で「巨人の心臓」を意味した。彼はその名に100倍もふさわしい男であった。\n悪魔Mannorothの前にただ一人立ちはだかり\n――その血をもって我らの自由を勝ち取ったのだから。\n\nLok'Tar ogar、兄者よ。Warsongの名が永遠に色褪せぬように。\n\n-Hordeの大族長、Thrall", "." },
})
