-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["0105829b41883dcf"] = { "守護者とみなされる青銅竜の一族は、文明のある地域に強く惹かれる。このドラゴンとその一族は生来非常に忍耐強く、常に観察に頼り、性急に動く前に計画を立てて行動する。より強大な敵に脅かされたとき、Nozdormuは必ず時の流れと定命の種族を守ろうとする。", "." },
  ["010bacffd9d7ba09"] = { "長い年月を経て、ハイエルフはついにKalimdorを思わせる土地を見つけた。その大陸の北の森の奥深くに、彼らはQuel'Thalasの王国を築き、Kaldoreiの同胞たちのそれをもしのぐ強大な帝国を創り上げることを誓った。不幸なことに、彼らはほどなく、Quel'Thalasがトロールたちがいまだ神聖視する古代のトロールの都市の上に築かれていたことを知った。ほとんど直後から、トロールたちはエルフの入植地を大挙して攻撃し始めた。", "." },
  ["01210d98b7a2a2d3"] = { "Lich Kingの衰弱によって力を奪われていたものの、ArthasはLordaeronでの内戦に関わっていた。bansheeのSylvanas Windrunnerに率いられた現存するアンデッド軍の半数が、アンデッドの帝国の支配権を狙って反乱を起こしたのである。Lich Kingに呼ばれたArthasは、Plaguelands全土で戦争が激化する中、Scourgeを副官Kel'Thuzadの手に委ねて去らざるを得なかった。", "." },
  ["01461df9ceaadb92"] = { "Vial of Phlogiston:\n\n鎧作りの最終段階には、きわめて高温の炉が必要になる。必要な熱を生み出すには、phlogistonの小瓶がなければならない。\n\nこの物質を作れると知られているのは、伝説のQuilboar、Roogugだけだ。奴は戦わずしてそれを手放しはしないだろう。RoogugはBarrens南部のRazorfen Kraulの奥深くに棲んでいる。", "." },
  ["015316f3053d4f27"] = { "King LlaneはHordeの力を甚だしく見くびっており、自らの王国が緑の肌の侵略者の手に落ちるのをなすすべもなく見ているしかなかった。最終的にKing Llaneは、Shadow Councilでも最も腕の立つ暗殺者の一人、ハーフオークのGaronaによって暗殺された。", "." },
})
