-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["fcd17422baae0e5c"] = { "報告：狼\n\nNorthshireでは動物による襲撃の報告が増えている。Eaganは、谷の狼たちはDuskwoodから追われてここへ来たのだと考えている。\n\n狼が人間を獲物とすることはまれだが、その数の多さゆえに農夫たちとの間でいくつか事件が起きている。また、多くの家畜が姿を消している。", "." },
})
