-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["5c55cd14af2fc67b"] = { "Jin'Zilへ\n しばらくぶりだが、Bloodfeatherどもの最後の一羽が始末されたことを知らせておこうと思ってな。だが礼は俺に言うなよ、この手紙を届けた者が仕留めたんだ。望むなら、キャラバンがBarrensを一巡りした後で、あいつの首をお前に届けさせてもいい。お前はブードゥーの術にああいう物を好むからな。\n 達者でな、旧友よ。\n\n-Darsok Swiftdagger", "." },
  ["5cd0e76163001284"] = { "SNUFFLENOSE COMMAND STICK(tm)\n\nsnufflenose gopherは驚くべき動物です。どんなに気難しいplainstriderからも愛情を引き出すだけでなく、埋まったblueleaf tuberの匂いを最大50ヤード先から嗅ぎつけることができるのです！\n\ngopherに塊茎を探しに行かせたいなら、特許取得済みの（別売りの）snufflenose command stickをお使いいただけます。\n\n使い方は次のページへ……", "." },
  ["5cd122390adb01f8"] = { "plainstriderの鳥の中で最も大きいGeruは、数が少なく、めったに出会うことがない。", "." },
})
