-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["2f777f5bbc4aefd5"] = { "Carlin Redpathの運命\n\nCaptain Joseph Redpathの弟Carlinは、Darrowshireの戦いで倒れた。だがひどい傷を負いながらも、彼は死んではいなかった。\n\n戦いから数日後、Argent Dawnの者たちが、渇きと熱で弱りきってCorin's Crossingの近くをさまよっていたCarlinを見つけた。彼らは傷の手当てをし、彼をLight's Hope Chapelへと連れて行った。\n\nその慈悲に感謝したCarlinはArgent Dawnの一員となり、今はScourgeに対する復讐の戦いを続けている。", "." },
})
