-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["8d0e1530daa3ac8d"] = { "Gnome Engineering\n\nノームという種族は、周囲の世界を操り制御するための品の設計に秀でる傾向がある。爆発物や武器についても一通りの理解はあるものの、Gnome Engineeringが重きを置くのは、文字どおり生活をより楽に、より便利にしようとする品である。それは、理論上の可能性をノームの知恵によって現実にする流派である。もっとも、可能性の中には完全には実現しないものもある。", "." },
  ["8d26a67758bdd6e6"] = { "Greatfather Winterの伝説\n\n「Winter Veil」という言葉は、多くの文化でGreatfather Winterと呼ばれる超自然的な存在に由来するといわれる。季節の終わりに彼が大地を歩くと、冬そのものが彼のはためく外套となった。彼の通った跡には大地が雪に覆われたことから、Greatfather Winterは大地に冬のヴェールをかけるのだと言われている。Azerothの一部は雪に埋もれるかもしれないが、それは大地に再生と新生のための時を与えるのである。", "." },
  ["8d47cddf4ba727c9"] = { "しかしGul'danは、HellscreamやOrgrim Doomhammerといった族長たちが全体の覇権を争うであろうことを知っていたため、この新たなHordeを治める傀儡の大族長を立てた。とりわけ堕落し凶暴なオークの将であるBlackhand the Destroyerが、Gul'danの傀儡に選ばれた。Blackhandの指揮のもと、Hordeは素朴なdraeneiを相手に自らの力を試すべく出陣した。", "." },
  ["8d7671a0c929aa03"] = { "2つの王国は数年の間は密接な結びつきを保ったが、WildhammersはGrim Batolで目撃した恐怖によって大きく変わっていた。彼らは山の中に広大な王国を掘り進める代わりに、Aerie Peakの斜面で地上に暮らすようになった。残った2つのドワーフの氏族の間の思想の違いは、やがて両者が袂を分かつことにつながった。", "." },
  ["8dbaefd60f1db0f0"] = { "どこまで話したか？ そうだ、Dun Baldarの掩蔽壕（Dun Baldarにある）は、Vanndarが最も信頼する精鋭の護衛部隊、Stormpike Defendersを統べている。その2つの塔を破壊すれば、Vanndarを助けに送られる援軍は消え失せる。", "." },
  ["8de7cc88aa41a219"] = { "私が記す魔物は、worgenである。\n\n古い田舎の言い伝えは、この生き物のことを語っているのかもしれない。村はずれの森や沼地をうろつく獣のような狼男の話を聞いたことのない農家の子どもなど、いるだろうか？\n\nそしてそうした話の中には真実が隠れているのかもしれない――おそらくそれは、われらを怖がらせるための作り話を装った、worgenへの警告なのである。", "." },
})
