-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["f92878a5ba1c0e5d"] = { "恐ろしい荒廃と、南の山々に広がる炎を目の当たりにしたKing MadoranとKing Khardrosは、Ragnarosの凄まじい怒りに立ち向かうことを望まず、軍を止めて急ぎそれぞれの王国へと引き返した。", "." },
  ["f94402a9d2d71ace"] = { "彼らはTitanの形成者Khaz'gorothに敬意を表して、その地をKhaz Modan、すなわち「Khazの山」と名付けた。Titanの父のための祭壇を建てるにあたり、ドワーフたちは山の中心に強大な炉を造り上げた。こうして、その炉を囲んで発展した都市は、以後Ironforgeと呼ばれることとなった。", "." },
  ["f9faa8120c625670"] = { "……実に奇妙で、抑えようのない感情だ。今日のような気持ちになったことは一度もない。Gilesの歴史の授業を手伝っていると、Tilloaは外で花壇の手入れをしていた。数分後、彼女は中に入ってきて、私の開いた手のひらに緋色のベゴニアを一輪のせ、微笑みかけた。その微笑みに、私の心臓は胸の中で震えているかのようだった。……", "." },
  ["f9fb09f0b8b25197"] = { "Skitterweb Tunnelsの先、Spirestoneの領域の上にある力の場へ行け。そこにはUrokの敵や好敵手の頭蓋骨が積まれている。Omokkの首を刺したpikeを打ち立てねばならぬのは、その場所だ！\n\n首が据えられれば、Urokは必ず現れる……だがまず、奴は手下どもを差し向けてくるであろう。それを打ち倒せば、やがてUrok自身が呼び出される。\n\nUrokを殺し、我が魔力を取り戻せ。力が戻れば、そなたに報いよう。", "." },
})
