-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["2c0b8fd94c0aec24"] = { "手にしたとき、私は混沌の幻視を見た。狼男たち……worgenが、恐るべき敵と戦っていた。worgenはその原始的な種族にふさわしく獰猛に戦ったが、その敵はひるむことがなかった。Lords of the Emerald Flameである。\n\nそしてその時、私はScytheの真の力に気づいた。それに意識を集中させることで、worgenと意思を通わせることができるようになったのだ。だが、私が彼らと通じるのに用いたのは言葉ではなかった。何か別のもの……言葉では言い表せないものだった。\n\n大切なのは、worgenが私の声を聞き、", "." },
  ["2c2da9d5091cdc57"] = { "攻撃は目的地から数マイル手前で起こると思っておけ。そこで我々の???同盟者???が待ち伏せている。なぜあんな生き物と手を組まされたのか分からんが、我々自身も脅されて従わされているような気がしてならない。結局のところ、どうでもいいことだ。標的を手中に収めれば、Stormwindを奪った奴らからこの国を取り戻す日も近い！", "." },
  ["2c661698d7584def"] = { "Stonewatch Keepの喪失は、非常に深刻なものでした。以前の報告で、オークのBlackrock Clanと、Morganthとして知られるウォーロックとの同盟について詳しくお伝えしました。Blackrock Orcsは恐るべき凶暴さで戦いました。間違いなく、Morganthの邪悪な魔法に煽られていたのでしょう。陛下の最も勇敢な兵士の多くがKeepを守ろうとして命を落としましたが、結局どうすることもできませんでした。", "." },
  ["2c769483ede5227c"] = { "以下は、Brock's School of Mining and SurveyingでPlatinum Starの成績を収め、Honorary Miner's Pickを授与された生徒の一覧である：\n\nMelia Stoneshaker\nBardin Ironband\nUmi Togglevolt\nRumi Togglevolt\nVorel Steelspire", "." },
  ["2c9498779d425ec4"] = { "The Mallet of Zul'Farrak\n\nMallet of Zul'Farrakを作るには、まずAltar of Zulへ赴き、トロールのKeeperから聖なる槌を手に入れねばならない。\n\n次に、その聖なる槌をトロールの都Jintha'alorの頂にある祭壇へ運ばねばならない。\n\n祭壇で聖なる槌を使うと、槌に力が注ぎ込まれ、Mallet of Zul'Farrakへと姿を変える。", "." },
  ["2cb182b592fdee3c"] = { "……というわけで、Scarlet Highlordの伝説の剣Ashbringerはそこで見つかるってわけさ。\n\nただの釣りの一日で、こんなもんに出くわすなんて驚きだろ？", "." },
  ["2cc28ecdc728b1ee"] = { "トロールが陸の領地から離れたがらなかったことなのか、あるいはそうした航海に必要な技術を彼らが発達させられなかったことなのかは、さらなる調査と分析を要するものであり、本稿の範囲を超えている。\n\nしかし、これほど大きな存在を無視することはできない。そしてStranglethorn Valeに広がるトロールの遺跡での新たな発見は、これまで知られておらず記録もされていなかった、彼らと海との関係の一側面を示している。\n\nStone of the Tides\n\n最近の調査で発見されたのは、", "." },
})
