-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["0e6c67dca5196caf"] = { "邪悪な人型の蜘蛛の種族によって築かれた古代の地下王国Azjol-Nerubは、精鋭のウォリアー近衛を差し向けてIcecrownを攻撃し、覇権を求めるLich Kingの狂った企てを終わらせようとした。大いに苛立たしいことに、Ner'zhulは邪悪なnerubiansが疫病に対してだけでなく、彼の精神による支配に対しても耐性を持つことに気づいた。", "." },
  ["0e760070d02fe21b"] = { "Cenariusは大地の子らに、木々や植物と語り合う術を教えた。Shu'haloはドルイドとなり、大地を癒やすために偉大な魔法の業を行った。何世代にもわたり、Shu'haloはCenariusとともに狩りをし、世界の下でうごめく影から世界を守った。", "." },
  ["0ec371a222fa45bb"] = { "もう安心だぜ、兄弟。Jen'shanはお前がハンターの道を学びたがってるって知ってる。教える準備はできてるぜ……お前に聞く気があるならな。\n\nValley of Trialsまで俺を探しに来な。Jen'shanがお前の訓練を始めて、ハンターの道がどんだけ強えか見せてやる。\n\n-ハンターのトレーナー、Jen'shan", "." },
  ["0ef470e35dcd752f"] = { "Highborneの無謀な魔法の使用は、Well of Eternityから渦巻くエネルギーの波紋をGreat Dark Beyondへと送り出した。流れゆくその波紋は、恐るべき異界の精神に感知された。Sargeras——あらゆる生命のGreat Enemy、Destroyer of Worlds——はその強力な波紋を感じ取り、遥か彼方のその発生源へと引き寄せられた。", "." },
})
