-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["3b2c72e7aa0819f3"] = { "Klavenが箱に閉じ込めているものが何であれ、それが塔の住人たちに悪影響を及ぼしているようだ。他の衛兵たちにも同様の弱みがあるのではないか、そしておそらくKlaven自身もその余波の犠牲になっているのではないかと考えている。\n\nAgent Amber Kearnen\nSI:7 Ground Level Operative, R8", "." },
  ["3bdab1272406fed3"] = { "宛先：秘術を学ぶ新入生諸君\n\n諸君は、同胞が新たな居住地で再び足場を築くのを助けるよう召集されるその時まで、ノームのMarryk Nurribitのもとを訪ね、その指導を受けることが求められる。臆することなく、厳しい試験手続きと、住居の確保および地元住民とのあらゆる形の交友を築く困難な順応過程に備えられたい。\n\n諸君の任務と能力に関する質問は、Marrek Nurribitに問い合わせること。", "." },
})
