-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["1c66b4bab76dbe3f"] = { "10000年の時を経て、強大な悪魔Archimondeとその軍勢は再びAzerothの世界に姿を現した。だがDalaranは彼らの最終目的地ではなかった。Kil'jaeden自らの命令のもと、Archimondeと悪魔たちはアンデッドのScourgeを追ってKalimdorへ向かい、World TreeであるNordrassilを破壊しようとした。", "." },
  ["1c83ebf5c21adbbd"] = { "<HTML> <BODY> <H1 align=\"center\">Hordeの下士官・兵の階級</H1><BR/> <IMG src=\"Interface\\PvPRankBadges\\PvPRank01\"/><BR/> <P align=\"right\">First Sergeant</P><BR/><BR/> <IMG src=\"Interface\\PvPRankBadges\\PvPRank04\"/><BR/> <P align=\"right\">Senior Sergeant</P><BR/><BR/> <IMG src=\"Interface\\PvPRankBadges\\PvPRank03\"/><BR/> <P align=\"right\">Sergeant</P><BR/><BR/> <IMG src=\"Interface\\PvPRankBadges\\PvPRank02\"/><BR/> <P align=\"right\">兵卒</P><BR/><BR/> <IMG src=\"Interface\\PvPRankBadges\\PvPRank01\"/><BR/> <P align=\"right\">斥候</P><BR/><BR/> </BODY> </HTML>", "." },
  ["1c9b2f3c6f230700"] = { "Star of Xil'yeh\n\nGrel'borg the MiserがStarを持っている。奴はAlterac MountainsのRuins of Alteracで日々を過ごし、がらくたを探し回っている強欲なogreだ。奴の収集品のほとんどは役に立たないが、ひとつだけ、Star of Xil'yehには貴重な力がある。", "." },
  ["1ca5631139ac135a"] = { "Stranglethorn Valeのトロール遺跡において、\"Stone of the Tides\"と呼ばれる物への言及である。トロールの伝説のさまざまな断片をつなぎ合わせると、このStoneと、それが古のGurubashi Empireにとって持っていた重要性について、かなり完全な姿を描き出すことができる。\n\nStone of the Tidesは、その持ち主に川、雨、潮といったさまざまな形の水を操る力を与えたらしい。Stone of the Tidesの使用にまつわる物語から、私はこう推測している。それは", "." },
})
