-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["69828f9a5d00b770"] = { "The Battle of Darrowshire\n\nThe Battle of Darrowshireは、Second Warのさなか、Scourgeの軍勢がLordaeron全土を荒らし回っていた頃に起きた。DarrowshireはAllianceの主力から切り離されていたが、町には一個中隊の兵、Silver Handのパラディンの一団、そしてCaptain Joseph Redpathが率いる不屈の地元民兵隊という援軍があった。", "." },
  ["6993fb795753d887"] = { "忠実なカルト信者に守られた大釜は、疫病の発生源となり、何も知らないLordaeron北部の農地や都市に疫病をじわじわと広げていくことになる。\n\nLich Kingの計画は完璧に成功した。Lordaeron北部の村々の多くは、たちまち汚染された。Northrendでそうだったように、疫病にかかった住民たちは死に、Lich Kingの従順な奴隷として蘇った。", "." },
  ["69ac9f300615e1af"] = { "Keeperがあなたの見つけた手紙を回してくれました、{name}。その後の経過を知りたいのではないかと思いまして。\n\n手紙にあった「Vargus」の最後の生き残りの家族が、Silithusの砂漠、Cenarion Holdに住んでいることが突き止められました。Garon Hutchinsという名で通っています。\n\n次にあの荒野へ出向く際には、彼と話してみてください。私たちが知ったことに興味を持つかもしれません。", "." },
  ["69def289e1549646"] = { "Charred Horns:\n\n焦げた蜘蛛の牙と同じく、KalimdorのStonetalon MountainsにあるCharred Valeに棲むchimaeraの焦げた角にも、非常に珍重される性質がある。\n\n叩いて平らにし、適切に処理すれば、物理的な力にきわめて強くなる。", "." },
})
