-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["a36cf46ab73179d5"] = { "守備隊は弱っていったが、Silver Handの門弟であるパラディンたちに救われた。その指導者Davil Crokfordは、Darrowshireの生まれであった。彼は襲撃が迫っていると聞くと、配下を率いて村へ駆けつけ、守り手たちと共にHorgusのしもべどもを食い止めた。\n\nHorgus自身が戦いに加わると、Davilがこれを迎え撃った。両者は何分にもわたって戦い、ついにDavilが勝利を収めたが、彼は致命傷を負い、ghoulの王を倒して間もなく息を引き取った。", "." },
  ["a37ee17d0a6cdd6d"] = { "邪悪な力がこれらを生み出した、\nその者はDreadmist Peakに悠然と座す、\nその者は汝と汝の友を嘲笑う、\nその者のelementalに終わりはない、\n\nほどなく汝はこのメイジと対峙せねばならぬ、\nその怒りを終わらせるのは死のみなのだから。", "." },
  ["a3986791e155cb7e"] = { "アンデッドのAzerothにおける始まりは、実のところPrince Arthasの堕落から始まったのではない。それよりずっと前に始まっていたのである。Lordaeronの没落をもたらした出来事は、その時点よりはるか以前から動き出していた。それはオークの氏族とBurning Legionの到来とともに始まったのだ。", "." },
  ["a3a05fda3f2922cb"] = { "Hordeが内部から崩れつつあると見たLord Lotharは、残る兵力を結集し、Doomhammerを南へ、Stormwindの荒廃した中心部へと押し戻した。そこでAlliance軍は、退却するHordeを火山の要塞Blackrock Spireに追い詰めた。Lord LotharはSpireのふもとで戦死したが、その副官Turalyonが土壇場でAlliance軍を奮い立たせ、Hordeを陰鬱なSwamp of Sorrowsへと追い返した。", "." },
  ["a3a7f8a7c8d52216"] = { "Dalaranの同僚たちは、Keganとその信奉者たちが持ち込んだ血石の研究には慎重で、4人の避難者を隔離したうえ、血石は彼らの身につけさせたままにしていた。だが、Keganの誠実さに応えるべく、私は彼の血石のペンダントを研究することにした。", "." },
})
