-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["0a0db49a6c00ab50"] = { "生涯を通じてEdwin VanCleefを個人的に知る者として言わせていただくと、彼を敵として相手にするのは実に骨の折れる仕事です。実のところ、彼は私の幼なじみで、いつか私と肩を並べる道を選ぶかもしれないと考え、私自ら影の技を仕込んだのです。VanCleefがDefias Brotherhoodを率いているのなら、光が我らの魂に慈悲を与えたまわんことを。\n\nMaster Mathias Shaw\nStormwind Assassin's Guild", "." },
  ["0a32ecd2ccc1af2d"] = { "呪文はKrakkenを縛ることはできず、ただ彼らを激怒させた。永劫の時の中で、定命の者が彼らに痛みを与えたことはなく、そのトロールの呪文は痛みをもたらしたのだ。\n\nそうして彼らはMinlothの呪文の束縛を振り払い、咆哮し、怒りのままに打ちかかった。\n\n深みから巨大な波がせり上がり、陸へと駆けるにつれ、轟きが響いた。波がI'lalaiに達すると、その影が都を覆った。\n\nだが、都を滅ぼす前に、Krakkenは動きを止め、身構えた。", "." },
  ["0a6dad9dbd99b039"] = { "Dark Ironの軍勢は同族の砦に激しく打ちかかり、あと一歩で両方の王国を奪うところであった。しかし最終的に、Madoran Bronzebeardが自らの氏族を率いて、Thaurissanの魔術の軍勢に決定的な勝利を収めた。Thaurissanとその配下たちは、Grim Batolで起きている出来事を知らぬまま、自分たちの都市の安全な場所へと逃げ帰った。そこでは、Modgudの軍勢もKhardrosとそのWildhammerのウォリアーたちを相手に、同じく苦戦することになるのであった。", "." },
  ["0a71086817c1d958"] = { "Arthasと死者の軍勢が南へと向きを変えた時には、Quel'Thalasに生きたエルフは1人も残っていなかった。9000年以上にわたって存続してきたhigh elfの輝かしい故郷は、もはや存在しなかった。", "." },
  ["0a891dab30b0f788"] = { "Sir Anduin Lothar、Uther the Lightbringer、Admiral Daelin Proudmooreに率いられたAllianceの軍は、オークを南の荒廃した地Azerothへと押し戻した。Azerothは、オークの容赦ない猛攻の前に最初に陥落した王国である。\n\nSir Lothar率いるAlliance軍は、Doomhammerの氏族をLordaeronから追い出し、オークが支配するAzerothの地へと押し返した。Lotharの軍はオークの火山の城塞Blackrock Spireを包囲し、その防御に攻城戦を仕掛けた。", "." },
  ["0af5d551eacf6926"] = { "Westfall Stew\n\nStringy Vulture Meat 3つ分\nGoretusk Snout 3つ\nMurloc Eye 3つ\nOkra 3つ\n\nすべてを混ぜ合わせて沸騰させる。出す前に少なくとも2時間は煮込むこと。", "." },
})
