-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["e110f4617e655d67"] = { "終章\n\n「アーティチョークの心臓部にガーリックバターとマヨネーズをたっぷりかける。熟成された強いエールを添えて召し上がれ。」\n\nDrek'Tharは今や孤立し、傍らには2匹の犬がいるだけだ。戦いを助けるためにFrostwolf Relief Hutを奪い、Drek'Tharを倒せ。将軍が倒れたとき、この地はついに正当な持ち主、Stormpikeのものとなるのだ。", "." },
  ["e1131a7d4313ab8e"] = { "だが、Keganは他の話題については大いに語りたがった。とりわけ、滅亡前のLordaeronで育った頃のことを。\n\nその失われた王国が今や荒廃し、死に絶えているにもかかわらず、彼はなおも深い愛着を抱いている。\n\nKeganへの好意が募るにつれ、私は試験結果を辛抱強く待つことができた。", "." },
  ["e1351b127394107f"] = { "トロールの戦闘部隊にも、必要とあれば人里離れたエルフにも引けを取らないと確信したArathiの武将たちは、Lordaeronの南部に強大な要塞都市を建設することに決めた。Stromと名付けられたその都市国家は、Arathiの国Arathorの首都となった。Arathorが繁栄するにつれ、広大な大陸の各地から人間たちがStromの庇護と安全を求めて南へと旅してきた。", "." },
  ["e150e8e6071fcfb5"] = { "玉ねぎの皮むき\nStormpikeを解体するための手引き\n-Drek'Thar著\n\nこのページには、戦術と政略に関する豊富な知識が詰まっている。学ぶ兵士とは、経験の肩に寄りかかる兵士である。本書をAlterac Valleyでの戦いの手引きとせよ。", "." },
  ["e166e8ea6c6a9acf"] = { "<HTML>\n<BODY>\n<H1 align=\"center\">ALLIANCEの士官階級</H1><BR/>\n<P align=\"center\">第1部</P>\n<IMG src=\"Interface\\PvPRankBadges\\PvPRank14\" align=\"left\"/><BR/>\n<P align=\"right\">大元帥</P><BR/><BR/>\n<IMG src=\"Interface\\PvPRankBadges\\PvPRank13\" align=\"left\"/><BR/>\n<P align=\"right\">野戦元帥</P><BR/><BR/>\n<IMG src=\"Interface\\PvPRankBadges\\PvPRank12\" align=\"left\"/><BR/>\n<P align=\"right\">元帥</P><BR/><BR/>\n<IMG src=\"Interface\\PvPRankBadges\\PvPRank11\" align=\"left\"/><BR/>\n<P align=\"right\">司令官</P><BR/><BR/>\n<IMG src=\"Interface\\PvPRankBadges\\PvPRank10\" align=\"left\"/><BR/>\n<P align=\"right\">副司令官</P><BR/><BR/>\n</BODY>\n</HTML>", "." },
  ["e1b3dbd4cff12518"] = { "2体の像は、Ragnarosの灼熱の存在によって火山地帯と化した南の地へと続く峠を守り立つこととなる。それらは、ドワーフの王国を攻撃しようとするすべての者への警告であると同時に、Dark Ironsがその罪にどれほどの代償を払ったかを思い起こさせるものでもあった。", "." },
  ["e1cd32df9ecacb7d"] = { "2者の間に契約が結ばれた。Kel'Thuzadは、Lich Kingに仕える見返りとして、不死と絶大な力を得ることになった。Kel'Thuzadの最初の任務は、Lordaeronにおける自らの富と影響力を使い、Cult of the Damnedを創設することであった。教団は、Cult of the Damnedの神であるNer'zhulに誓いを立てる限り、すべての信者に平等と永遠の命を約束した。", "." },
  ["e1eeb9417569935e"] = { "General Turalyon\n\nLord Anduin Lotharのかつての副官。Silver Handの騎士。オークの故郷Draenorへ進軍したAlliance Expeditionの総大将。死亡したものとみなされる。\n\nEsarus thar no'Darador' - 血と名誉にかけて我らは仕える。\n旧友よ、そなたは正義と美徳の右腕であった。そなたの名は我らが広間で永遠に讃えられるであろう。\n\n- Silver Handの騎士、Lord Uther the Lightbringer", "." },
})
