-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["ed9acf80e5990539"] = { "Kil'jaedenはNer'zhulの氷の器をAzerothの世界へと投げ落とした。硬い水晶は夜空を横切り、荒涼とした極北の大陸Northrendに激突して、Icecrownの氷河の奥深くに埋まった。激しい落下によって歪み傷ついた凍てつく水晶は玉座のような姿となり、やがてその中でNer'zhulの復讐に燃える魂が目覚めた。", "." },
  ["edb844140c150879"] = { "Antonidasは、オークに共通する無気力は実際には病ではなく、彼らを恐るべき血に飢えたウォリアーにしていた不安定なウォーロックの魔法から種族全体が離脱したことによる結果なのだと論じた。", "." },
})
