-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["f1520ca411e22f11"] = { "世界には、NorthrendからのLich Kingの精神の呼びかけを聞き取った強大な者たちが、わずかながら各地に散らばっていた。その中で最も著名だったのが、Dalaranの大魔導師Kel'Thuzadである。彼はDalaranを治める評議会、Kirin Torの古参の一員であった。彼は禁じられた死霊術の研究にこだわったため、長年にわたり異端児と見なされていた。", "." },
  ["f176d1292b4d6f46"] = { "今こそ、この困難な時にLakeshireの善良な民を支えてくださるよう、陛下にお願い申し上げます。領土を守るための新たな兵士と、戦場で失われた武器に代わる新たな軍備が必要です。食糧と建築資材も底をつきかけております。どうか主よ、人間と卑しきオークとの間の最後の砦が持ちこたえられるよう、お力添えください。敵をKingdom of Stormwindに入れてはなりません。", "." },
  ["f1de67f64abfdd6b"] = { "Princess of the DeepたるAku'maiは、Old Godsに仕えている。彼女はBlackfathom Deepsに棲み、その古の叡智で洞窟に祝福を与えている。古の定命の者たちによってDeepsへと連れてこられたAku'maiは、神性の象徴である。彼女が持つのはOld Godsの力と凶暴さのほんの一片にすぎないが、それでもなお計り知れない。\n\nゆえに彼女は崇められる。そして恐れられ、愛されている。\n\n--Lorgalis", "." },
})
