-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["5732991b8c3df657"] = { "私の望みは、この種の石が魔法の性質を持つことを同僚たちのために確かめることであった。我々Dalaranの魔術師が血石の力を利用したくないとしても、敵がいつかそれを我々に向けて使うかもしれない以上、せめてその性質は知っておくべきである。\n\nこうして私の研究は始まった。", "." },
  ["573fe1907aa660eb"] = { "Magistrate Rutherford Burnside\n債務はすべて清算済み。\n\nBlacksmith Avery Verringtan\n債務はすべて清算済み。\n\nClerk Horrace Whitesteed\n債務はすべて清算済み。\n\nCouncilman Gillis\n債務はすべて清算済み。\n\nCouncilman Hooks\n債務はすべて清算済み。\n\nFarmer Getz\n債務はすべて清算済み。\n\nFarmer Ray\n債務未払い。収穫時に農産物での支払いを約束。\n\nFarmer Lyion\n債務未払い。土地から立ち退き処分。", "." },
  ["574acbe4060c3366"] = { "Liferoot:\n\nこれは荒野で採取するか、Dustwallow MarshのWithervine Beastsから手に入れることができる。その力は、Cyclonianの生命の精髄をこの世界へ引き寄せるのに必要となる。", "." },
  ["577c499d640b29e2"] = { "私は、Northlandsが変わり果てた腐敗の大釜の中で、さらに大きく暗い悪が煮え立っているのではないかと恐れております。Kingdom of Stormwindが行動を起こすことが肝要です。さもなくば我々は、生者にとって薄れゆく記憶となるか、敵の奴隷となるでしょう。\n\n署名\n\nMagistrate Solomon\nTownship of Lakeshire\nKingdom of Stormwind", "." },
  ["578080fa884afad7"] = { "Zimrel Darktooth\n\n闇の鍵の狂気がZimrelを捉えるとき、彼を鎮められるのは死にゆく者の悲鳴だけである。\n\nその犠牲に報い、闘技場の上には常に彼の席がある。我らの血の競技が、彼の心の怒りを和らげんことを。", "." },
  ["57c6f7777ac11b50"] = { "これこそが本書の目的である。すなわち、われらの地を滅ぼさんとするそれら異界の魔物どもを記録し、それに出くわした探検家が、自分が何に立ち向かうのかを知ることができるようにすることだ。\n\nゆえに、自らをAzerothの守護者と任ずる者は、読み進めよ。そして敵を知れ。\n\n-Ur\nDalaranのメイジ", "." },
  ["57e6ea9e04690abd"] = { "VanCleef……<判読できない文字>\n\n私を呼び出しただと？？ 奴は自分を何様だと思っている？？ 私はKlaven Mortwakeだ！ 虫けらに指図されてなるものか！\n\n<この本の残りのページは失われている>", "." },
})
