-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["188fa9aa8fbca660"] = { "権力に飢え、神の座そのものを手に入れることに取り憑かれたGul'danは、究極の力の秘密が眠ると信じる海底のTomb of Sargerasを必死に探し求めた。すでに同胞のオークたちをBurning Legionの奴隷となる運命へと陥れていたGul'danは、Doomhammerに対する本来の務めなど少しも顧みなかった。", "." },
  ["1897fe0fc3357ea5"] = { "語録\n\n「ゴブリン工学について知りたいって? 奴らの中でも最も優秀なエンジニアの一人に聞いてみるといい。たしか名前は『Nubby Stumpfingers』だ。なぜそんな名前なのか知りたいかい? それこそがゴブリン工学さ」\n\n-- ノームのエンジニア、Ringo Tragediction\n\n「俺たちゴブリンのことを好きに言うがいい。だが、これだけは言っておく。俺たちには爆薬がある!」\n\n-- ゴブリンの爆撃手、Yazz Nitrospork", "." },
  ["18bfe6e8af1a7cef"] = { "Bael Modanの発掘\n\nExplorers' Leagueが派遣した最初の調査隊の見立ては、まさに正しかった。この地の地中には、我らの民にとって計り知れない価値を持つ遺物が眠っている。Bael Modanの砂と岩の下で知を探求すれば、疑いなく多くの答えが見つかるだろう。\n\nしかし、この地域の地質のため、我々は極端な手段を用いざるを得ない。砂の堆積の多くは、過酷な環境と変わりやすい気候によって固まってしまっている。", "." },
  ["18c0fe7d81c19ac2"] = { "月日が経つにつれ、Kel'Thuzadは疲れ果て、重荷を負わされたLordaeronの労働者たちの中に、新たな教団への熱心な志願者を数多く見いだした。Kel'Thuzadが目的を果たすのは驚くほどたやすかった。その目的とは、市民の聖なる光への信仰を、Ner'zhulの暗い影への信心に移し替えることである。Cult of the Damnedが規模と影響力を増すにつれ、Kel'Thuzadはその活動をLordaeronの当局から確実に隠した。", "." },
  ["18ebaf2dfab71d89"] = { "Master Carevinへ\n\nこの書状の持ち主は、光において高潔であり、Duskwoodの境を脅かすアンデッドや悪魔と戦う力を持ち、光の大義のためにCarevin家に加わる意志があることを、自ら示しました。\n\nつきましては、この光のウォリアーにさらなる任務を与えてはいかがでしょうか——たとえば、光の敵に手を貸している疑いのある町の者たちの調査などを。\n\n敬具\nCalor", "." },
})
