-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["f34b704009f7c426"] = { "ドワーフ\n\n己の起源の研究に常に没頭しているドワーフは、この季節をGreatfather Winterその人を讃えるものとして祝う。彼らは彼を、Azerothの古の存在であるtitanの一人が人の姿をとったものと考えている。ドワーフはこの神秘的な存在との何らかの血のつながりを主張しており、それと同じように、雪に覆われた故郷Dun MoroghこそがGreatfather Winterの祝福の最たる例だと考えている。", "." },
  ["f3628329c7a56cb3"] = { "私はRaptorsから逃れる場所を海岸線に求めて、一行を海のほうへと導いた。慌てるあまり、我々は北へ流されすぎて、危険なほど高い場所に出てしまった。過ちは犯された。その責任は私にあった。我々は切り立った崖のすぐ手前で立ち止まった。Raptorsはほんの数歩後ろに迫っていた。", "." },
  ["f3ec6301fa07152d"] = { "人間の7つの国の政治と対立が盛衰を繰り返す間も、Guardiansの系譜は混沌に対する絶え間ない警戒を続けた。長い年月の間に多くのGuardiansがいたが、どの時点においても、Tirisfalの魔法の力を持つのはただ一人であった。その時代の最後のGuardiansの一人は、影に立ち向かう強大なウォリアーとして名を馳せた。", "." },
})
