-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["bea759b528ce280a"] = { "Grom HellscreamやKilrogg Deadeye(Bleeding Hollow氏族)といった歴戦の族長たちに率いられた新たなHordeは、Allianceの防衛軍の不意を突き、田園地帯を暴れ回った。Ner'zhulの精密な指揮のもと、オークたちは必要な遺物を素早くかき集め、安全なDraenorへと逃げ帰った。", "." },
  ["beae61b19caf8258"] = { "Master Longbeardへ\n\nご存じのとおり、我らStormpike家は優れたものを見る目があり、貴殿の盾の品質はよく存じております。\n\nそこで、ぜひ貴殿にそのような盾を作っていただきたく存じます。仕様は次のページに記しました：", "." },
  ["beaf601af7050c8c"] = { "<HTML>\n<BODY>\n<H1 align=\"center\">\n第3章：WESTERN PYLON\n</H1>\n<BR/>\n<BR/>\n<IMG src=\"Interface\\Pictures\\11482_crystals_mini_west\" align=\"left\"/>\n<P align=\"right\">Western<BR/>\nPylonは<BR/>\n赤、緑、<BR/>\n青の<BR/>\nクリスタルを受け入れる。</P>\n<BR/>\n<BR/>\n<BR/>\n<BR/>\n<P align=\"left\">このパイロンは、赤のクリスタルを主な動力源として生み出せるエネルギーに重点を置いている。</P>\n</BODY>\n</HTML>", "." },
  ["becd1a1293db5a14"] = { "<HTML>\n<BODY>\n<H1 align=\"center\">\n西のクリスタルの組み合わせ\n</H1>\n<BR/>\n<P align=\"left\">効果は2種類ある。ダメージからの防御を高めるものと、敵の防御を弱めるものだ。</P>\n<BR/>\n<P align=\"left\">CRYSTAL WARD：赤と緑のクリスタルが必要。<BR/>アーマーが上昇する。</P>\n<BR/>\n<P align=\"left\">CRYSTAL YIELD：青と赤のクリスタルが必要。<BR/>特定の対象のアーマーを下げることができる。\n</P>\n</BODY>\n</HTML>", "." },
  ["bef020a7ec6b661f"] = { "Ashenvaleを取り締まる務めでTyrandeは多忙であったが、そばにMalfurionがいないため、喜びはほとんどなかった。ドルイドたちが眠る長い幾世紀が過ぎるにつれ、悪魔による二度目の侵略への彼女の恐れは募っていった。Burning Legionが今もなお空のGreat Darkの彼方のどこかにいて、ナイトエルフとAzerothの世界への復讐を企てているのではないかという不安な感覚を、彼女は拭い去ることができなかった。", "." },
})
