-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["de70c5f9c59f3ab2"] = { "この石化した鉤爪は、Stranglethornの南の海岸沖で発見された。生態学者たちは、これを古代のsun rocの鉤爪だと考えている。この生き物は原始的なトーレンの神話群に大きく登場するが、この鉤爪の存在は、それがかつて実在したことを示唆している。", "." },
  ["de7f4a1194a37911"] = { "十年以上が過ぎた。その間、Lich Kingはその広大な力を用いてNorthrendの生き物たちの精神を支配し、凍てついた玉座の上に巨大な城塞を築くよう命じた。Northrendの全土を支配下に置いた今、Lich KingはLordaeronへの浸透を始めねばならないと悟った。氷に囚われたまま、かつてのオークのシャーマンは、操り支配するためのさらなる精神を探し始めた。その呼び声は大陸を越えて届いた。", "." },
})
