-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["b61e0122a18e7173"] = { "Ner'zhulとその追随者たちは、Great Dark Beyondに散らばるすべての世界をつなぐ霊妙な次元、Twisting Netherに入った。不運にも、Kil'jaedenとその悪魔の手下たちが彼らを待ち構えていた。Ner'zhulの傲慢な反抗に復讐すると誓っていたKil'jaedenは、老シャーマンの肉体を少しずつ、ゆっくりと引き裂いていった。", "." },
  ["b66a7679fe5bf65c"] = { "Wellの強力なエネルギーはたちまち燃え上がり、凝集して新たなWell of Eternityとなった。新たなWellは未来の世代への贈り物だと信じて歓喜していたIllidanは、Malfurionに追い詰められて衝撃を受けた。Malfurionは兄弟に、魔法は本質的に混沌としたものであり、それを使えば必ず広範な堕落と争いを招くと説いた。それでもIllidanは魔法の力を手放すことを拒んだ。", "." },
  ["b69d85682d2aceeb"] = { "こうして、Amani EmpireとGurubashi Empireの大きな部分は、現在のQuel'ThalasとStranglethornの地に（それぞれ）今も残っている。Azj'Aqirの王国であるAzjol-NerubとAhn'Qirajもまた、現在のNorthrendとTanarisに（それぞれ）生き延びている。\n\nトロールの両文明は、かつて知っていた太古の世界の壊滅的な破壊にたじろいだ。不屈のトロールは荒廃した都市を再建し、かつての力の一部を取り戻そうと動き出した。", "." },
  ["b6cc427f56eed334"] = { "なあ、{class}、オークの叫び声を聞いたことはあるか？ 喉笛を食いちぎろうとしてくるgnollから家を守ったことは？ ああ、きつい話に聞こえるだろう？\n\nまあ、大切な人たちを守りたいなら俺の助けが必要になる。俺はNorthshireの修道院の中にいる。俺の知識は安くないが、十分な経験があるなら、Stormwindやその先を脅かすものと戦うのに役立つ型や技をいろいろと教えてやれる。\n\nウォリアーのトレーナー、Llane Beshere", "." },
})
