-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["fd139cae5bb9d53a"] = { "エルフと人間の連合軍は、Alterac Mountainsの麓で圧倒的なトロールの戦闘部隊と激突した。戦いは何日も続いたが、Arathorの不屈の軍勢は決して疲れることなく、トロールの猛攻の前に一歩も退かなかった。エルフの領主たちは、敵に向けて魔法の力を解き放つ時が来たと判断した。", "." },
  ["fd2f90efafcce039"] = { "やがてCenariusはShu'haloと友になり、巡りゆく世界について語り聞かせた。大地の子らは彼を兄弟として知り、生命の野と、偉大なEarthmotherに愛された生き物たちを守る手助けをすると誓った。", "." },
  ["fd96efbd04c90941"] = { "第4章 - East and West Frostwolf Towers\n\n今や、君と勝利との間に立ちはだかる層は一つだけだ。Drek'Tharが最も信頼する強力な護衛部隊、Frostwolf Guardiansである。\n\nFrostwolf Guardiansは、東と西のFrostwolfの塔に予備として控える小隊から送り出される。その塔を破壊すれば、残ったFrostwolf Guardiansが恥辱のうちに逃げ去るのを目にするだろう。", "." },
})
