-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["24ca5cf040668555"] = { "LegionがAshenvaleに侵攻した際、Illidanは10000年に及ぶ幽閉の末、墳墓の牢獄から解き放たれた。彼は仲間をなだめようとしたが、すぐに本性を現し、Skull of Gul'danとして知られる強力なウォーロックの遺物のエネルギーを取り込んだ。", "." },
  ["24dd20fec63251ad"] = { "Smithing Hammer - Plagueが訪れ、Arthasが裏切る前、私はSilverpineの美しい森の奥深くにあるPyrewoodという町に住んでいた。森はもう、かつての美しさには遠く及ばない。私が鋼の秘密を学んだ砦も、とうの昔に堕落して穢れ、想像を絶する邪悪な怪物どもに占拠されてしまった。\n\n妻と私は、今ではShadowfang Keepと呼ばれる場所から逃げ出したとき、最も大切な持ち物のいくつかを置いてきてしまった。", "." },
  ["24e536b06da14cf1"] = { "星の子らは、長きにわたりEternal Wellのきらめく水のほとりに住んでいた。永遠の黄昏の光であり、月の化身にして女神であるEluneが、その御業から休まれる時にはその水の中に宿られることを、誰もが知っていた。Eluneに愛された星の子らはWellのほとりに住まいを築き、そのまなざしは常に空へ、月明かりの夜へと向けられていた。\n\n数多くの町や住まいが築かれたが、", "." },
})
