-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["7938e4ebd14f80bf"] = { "Kil'jaedenはNer'zhulの魂を、Twisting Netherから集めた氷の塊の中に閉じ込めた。魂が氷に囚われている間に、彼はそこへさらなる力を注ぎ込んだ。肉体を失い、かくも途方もない力を与えられたことが、Ner'zhulの変貌を決定づける境目となった。", "." },
  ["797faf9793aa21d8"] = { "Kil'jaedenがAzerothへの侵攻に向けてHordeを備えさせる一方で、Medivhは自らの魂をかけてSargerasと戦い続けていた。Stormwindの高潔な君主であるKing Llaneは、かつての友の精神を蝕んでいるかに見える闇に警戒を強めていった。", "." },
  ["7982ba68b091e760"] = { "表彰状：\n\n本書類の持参人は、熱意と功績をもってNorthshireに尽くしたことにより、Stormwind Armyの保安官補の地位を授与されるものとする。この者がElwynn Forestにおいても役に立つことを確信している。\n\n署名：\n-Marshal Douglas McBride\nStormwind Army、Northshire", "." },
  ["79cf6e2846b62498"] = { "世代が移り変わる中、GuardiansはArathorとQuel'Thalasの地のいたるところで、Burning Legionの目に見えない脅威から人類の大衆を守った。Arathorは成長し繁栄し、その間に魔法の使用は帝国中に広まっていった。一方、Guardiansは悪魔の活動の兆しに注意深く目を光らせていた。", "." },
  ["79d7a0f90846ef32"] = { "旅の途中、Thrallは長年にわたり隠者として暮らしていた年老いた大族長、Orgrim Doomhammerを見つけた。Thrallの父の親友であったDoomhammerは、この若く先見の明あるオークに従い、捕らわれた氏族の解放を手助けすることを決めた。多くの歴戦の族長たちに支えられ、ThrallはついにHordeを再生させ、自らの民に新たな霊的なアイデンティティを与えることに成功した。", "." },
})
