-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["3d0a92cc62e43716"] = { "私が気づいたのは、その余波がきわめて致命的だということだ。想像してみろ、もし<判読できない文字> ハハハ！", "." },
  ["3d2897df3a8d63b1"] = { "自らが生み出したLich Kingが制御できないほど強大になりつつあると感じたKil'jaedenは、IllidanにNer'zhulを滅ぼし、アンデッドのScourgeを完全に終わらせるよう命じた。その見返りとして、Illidanは計り知れない力と、Burning Legionの残る君主たちの間での真の地位を得ることになっていた。", "." },
  ["3d4522f1845de514"] = { "Durotanの死に激怒したOrgrimは、Hordeを悪魔の堕落から解き放とうと立ち上がり、最終的にGul'danの腐敗した傀儡Blackhandを殺して、Hordeの大族長の座に就いた。彼の果断な指導のもと、容赦なきHordeはついにStormwind Keepを包囲した。", "." },
  ["3dd54a2b7c6d15e7"] = { "儀式の完了\n\n儀式の進み具合は、円陣の縁に沿って現れる魔法のルーンで確かめられる。ルーンが9つ現れれば儀式は完了し、新たに力を得たCircleからエネルギーが立ち昇るのが見えるだろう。\n\nそこでXorothian Glyphsを発動させてXorothへのポータルを開き、dreadsteedを引きずり出すことができる。\n\ndreadsteedを倒し、その魂を解き放て。その魂と対峙すれば魂は従い、お前はその召喚の秘密を授かるだろう。", "." },
})
