-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["2106c80137570ae1"] = { "このデータのセキュリティ等級はあまりに高く、それを表す新しい数の発明を待っている状態である！", "." },
  ["2136d41b213e22a3"] = { "Lady Mara Fordragon\n\nStormwindの高位聖職者\n\nFirst War後にLordaeronへ逃れた難民たちの後援者。\n\n彼女は我らの未来の輝ける母であった。光の中に安らかに眠らんことを。", "." },
  ["215979b0e5b665f7"] = { "あらゆる生命の守護者であるTitanのEonarは、自らの力の一部を赤き巨竜Alexstraszaに与えた。以後、AlexstraszaはLife-Binderとして知られ、世界のあらゆる生き物を守るために尽くすことになる。その至高の知恵と、あらゆる生き物への限りない慈愛により、AlexstraszaはDragonqueenの冠を授かり、同族を統べる力を与えられた。", "." },
  ["21ede6d0f75e6f93"] = { "5日目:\n\n今日のThorsenはひどく動揺していた。昨日の外出で何を見たにせよ、誰に会ったにせよ、それが奴を怯えさせたに違いない。\n\n工作員が奴と話したのだろうと思っていたが、持ち場を代わってやっていた間にどこへ行っていたのかと尋ねても、Thorsenは黙ったままだった。奴は私を友だと信じ、危険な秘密から私を守っているつもりでいる。\n\n奴の忠誠は向ける先を誤っているが、固い。我々のもとへ戻れば、Kurzenの軍にとって貴重な戦力となるだろう。", "." },
})
