-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["9710c91691bc151a"] = { "その若きオークは悪魔の魔法の熱心な学徒となり、史上最も強大な定命のウォーロックへと成長した。彼は他の若いオークたちに秘術を教え、オークのシャーマン的な伝統を根絶しようと努めた。Gul'danが同胞に示したのは新たな種類の魔法、破滅の臭いを放つ恐るべき新たな力だった。", "." },
  ["972dead9975f01b8"] = { "彼の誇りは完全に打ち砕かれた。Staghelmはその生涯で二度目となる、恐怖によってしか生じえない胃の底のざわめきを感じた。そしてTanarisにおいて、StaghelmはNozdormuの子Anachronosのもとを訪れ、Bronze Flightの助力を懇願したのである。", "." },
  ["9741a73a6e0df187"] = { "Queen Azsharaは、自らの魔法の恐るべき恍惚に呑まれてSargerasの抗いがたい力の虜となり、自分の世界に彼を招き入れることに同意した。彼女のHighborneの従者たちでさえ、魔法による避けられない堕落に身を委ね、Sargerasを自らの神として崇め始めた。Legionへの忠誠を示すため、Highborneは女王を助け、Well of Eternityの深みに渦巻く巨大なポータルを開いた。", "." },
  ["9742154e9863aad9"] = { "行き場を失ったKaelとblood elfたちは、Illidanを再び捕らえた看守Maievに立ち向かうため、Lady Vashjを追ってOutlandへ向かった。nagaとblood elfの軍勢を合わせ、彼らはMaievを打ち破り、Illidanを彼女の手から解放した。Outlandを拠点としたIllidanは、Lich KingとそのIcecrownの要塞に対する二度目の攻撃のために軍勢を集めた。", "." },
  ["9752018048f15b44"] = { "Aspectについて学んだことを、後の人々が参照できるようここに記す。これが役に立つことは間違いない。時が経つにつれ、これらのドラゴンは我々の世界にはるかに大きな影響を及ぼすようになると感じているからだ。", "." },
  ["97dd5f8312dcbfca"] = { "Valeの上に月が輝く\nジャングルにその光を投げかけ\n誇り高きウォリアーたちが呼び声に応え\n我らが国と聖なる地を守るところに。\n\nValeの上に月が輝く\n戦いの叫びのはるか上に\n敵と同胞の区別なく\n血が流されるところに。", "." },
})
