-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["bf820df32b658ca1"] = { "我々が彼らの縄張りを侵さない限り、彼らは我々にとって実質的な脅威にはならないというのが私の考えである。これはドワーフの民にとって好ましくない状況かもしれないが、軍事資源が分散していることを考えれば、トロールの根絶の優先度を下げ、troggsとDark Ironsがもたらす脅威に引き続き注力するのが賢明であろう。\n\nまた、Anvilmarについての弟Grelinの報告書の写しも同封する。\n\n署名\nSenir Whitebeard", "." },
})
