-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["824457e192a7408d"] = { "こうした小競り合いはたいてい短く終わったが、敵対する両種族の弱みと強みを明らかにするには十分だった。LlaneとLotharはオークの数について正確な情報を集めることができず、どれほど大きな軍勢と戦わねばならないのかを推測するしかなかった。", "." },
  ["829831402f41cfa3"] = { "だが、同族を支配する5つの竜族があった。Titanたちが芽吹いたばかりの世界の守り手に選んだのは、この5つの竜族だった。Pantheonの最も偉大な者たちは、それぞれの竜族の長に自らの力の一部を授けた。これらの威厳ある竜たち（以下に挙げる）は、Great Aspects、すなわちDragon Aspectsとして知られるようになった。", "." },
})
