-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["b708e72a354af1c8"] = { "第1章 - 前線\n\nFrostwolfの防衛の前線は、Frostwolf Warriorsで構成されている。ウォリアーたちは、Captain Galvangarの砦、Iceblood Garrisonから前線へ送り込まれる。この防衛の層を取り除く最も効率的な方法は、Iceblood Garrisonを破壊することだ。\n\n砦を包囲し、Captain Galvangarを倒せ。それが済めば、前線は崩れ去るだろう。", "." },
  ["b7117ecfd2c613eb"] = { "最後に、発破薬の要請を改めて申し上げねばなりません。手持ちが非常に乏しく、発掘の進捗が大きく妨げられております。発破薬の補給がまもなく届くと伺いましたが、いまだに受け取っておりません。\n\n遅れの理由をお聞かせ願えますでしょうか？\n\n敬具\nProspector Darteus Ironband", "." },
  ["b72b1a85e4732ac1"] = { "Arellas Fireleaf\nScarlet Crusadeの大魔術師\nQuel'Thalasの市民\nNecromancer Diesalvenと永遠の戦いを続ける", "." },
  ["b72e6551ffdbc464"] = { "high elfのAlleria Windrunner、ドワーフのKurdran Wildhammer、そして歴戦の兵士Danath Trollbaneの助けを得てもなお、KhadgarはNer'zhulが他の世界へのポータルを開くのを阻止できなかった。", "." },
  ["b78616c397be0763"] = { "Grishへ\n\n休暇の申請は受理された。家族と過ごす休暇の間、お前の持ち場を見張らせるために、予備のトーレンのウォリアーを送る。1週間後に戻って報告せよ！\n\n-Maggran Earthbinder", "." },
  ["b7cefdf73e27dadc"] = { "しかし、解決策はいたって単純だ。木材パルプを吸収材として使い、微量のニトログリセリンと硝酸ナトリウムを混ぜ合わせれば、最も密な塊さえ打ち砕ける強力な爆薬ができる。\n\n作業は騒々しく迷惑なものになるだろうが、我々の探索は地元の住民の快適さよりもはるかに重要だ。実際、厄介者となっていた牛男どもの一団を、すでにこの地域から追い払わねばならなかった。", "." },
  ["b7de9bc46d54cfdf"] = { "過酷な生い立ちにもかかわらず、若きThrallは強く機転の利くオークへと成長し、奴隷の生き方は自分のためのものではないと心の奥で分かっていた。大人へと成長するにつれ、彼は会ったこともない自らの同胞、オークたちについて学んだ。敗北の後、その大半は収容所に入れられていたのだ。噂では、オークの指導者Doomhammerは、Lordaeronから脱出して身を隠したという。ただ一つ、無法者となった氏族だけが、Allianceの監視の目を逃れようとしながら、今なおひそかに活動していた。", "." },
  ["b7efed7943da537d"] = { "AjeckとSir Erlgadinは身構え、揺れる木々の根元の逆立った茂みに銃を向けていた。真昼の太陽が我々に重く照りつけていた。Erlgadinが撃鉄を引くと、そのこめかみから汗がゆっくりと一筋流れ落ちた。カチリという音と同時に、濃い茂みが割れ、大きな黒豹——見事な個体だ——が平原へと飛び出してきた。", "." },
})
