-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["89580560cb9936bc"] = { "眠りについているドルイドたちをさらに探すうち、Malfurionはかつて弟Illidanを鎖でつないだ古の墳墓の牢獄を見つけた。IllidanがLegionとの戦いに力を貸すと確信したTyrandeは、彼を解き放った。Illidanはしばらくの間は彼らに協力したが、やがて自らの目的を追うために逃げ去った。", "." },
  ["8971bc0ff77d91e9"] = { "この日、我々は新しい豹の足跡をたどって南へ向かった。まもなく、巨大な吊り橋が架かる渓谷に着いた。その工学の驚異を見て、この地域についてのBrannの描写豊かな著作を思い出さずにはいられなかった。土着のトロールは原始的で無学な種族だと思われがちだが、橋の見事な職人技を眺めていると、トロールの建築者たちが一見不可能な偉業を成し遂げた技量のほどが私にも分かった。", "." },
  ["8982bdb56880cbc7"] = { "おめでとうございます！\n\nあなたは、素晴らしいsnufflenose gopherの誇らしい新しい飼い主になりました！ 臆病な生き物ではありますが、あなたの新しいペットのふわふわの可愛らしさと驚くべき嗅覚を、きっと愛おしく思っていただけるはずです。\n\n次のページからは、あなたのgopherについて以下の情報をご紹介します：\n\n1. 餌やりとお世話\n2. 風変わりな（そして可愛らしい）行動\n3. 特許取得済みSnufflenose Command Stick(tm)の使い方\n\n改めて、おめでとうございます。がっかりはさせません。\n\n-Marwig Rustbolt\nSnuff Inc.オーナー", "." },
  ["898eb941492eb5f6"] = { "Simone the Seductress：\n\nSimoneはUn'Goro Craterを穢している。その変装に騙されてはならない。用心して近づき、戦いを挑め。", "." },
})
