-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["d11c4e72e85c67b7"] = { "私はAspectとその創造主であるtitanについて、多くの研究を重ねてきた。人間が一生のうちになしうる限りの研究である。titanがこの世界を去ったとき、Aspectは5体いた。彼らはAzerothの世界を守る任を負った強大なドラゴンである。その物語は壮大で多岐にわたり、これほどの情報を集めた今でも、この壮麗な生き物についてはまだ学ぶべきことが多く残っていると分かっている。", "." },
  ["d1dd85fcf0a9b7d9"] = { "Amulet of Spiritsの力を使って彼らを実体化させ、宝石を奪い取れ！ その後、宝石をAmulet of Spiritsに嵌めて、私のもとへ持ち帰るのだ。Amulet of Unionを手にすれば、私は部族を再編できるほどの力を得て、我らはついに祖先が望んだ姿になれるのだ！", "." },
})
