-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["8c7b5832433c3203"] = { "Abyssal Dukes\n\nAbyssal Dukesとの接触を許されるのは、地位の徽章を持つ侍祭のみである。地位の徽章は、最初にそれを授けられた本人のみが使用できる。\n\nAbyssal Dukesと許可なく交信した、あるいは地位の徽章を無断で使用したTwilight's Hammerの構成員は、私自らが処罰する。", "." },
  ["8c7fb6d0b54b1814"] = { "大陸の中心に、Titanたちはきらめくエネルギーの湖を造った。彼らがWell of Eternityと名づけたその湖は、世界の生命の泉となるはずだった。その強力なエネルギーは世界の骨格を育み、豊かな土壌に生命が根づく力を与えるだろう。やがて、植物や木々、怪物、そしてあらゆる種類の生き物が、原初の大陸で栄え始めた。", "." },
  ["8ca3076632c5e85a"] = { "見事に刻まれた墓碑銘の上に、「裏切り者」という言葉が乱暴に引っかいて書かれている。墓碑銘にはこうある：\n\nYurivここに眠る。\n父であり、夫であり、パラディンであった。\n彼の子らよ、光への彼の献身が疑いようのないものであったことの証人となれ。\n彼は、自らがしないことを子らに求めることは決してなかった。", "." },
  ["8cb669ab3f520567"] = { "Old Godsの悪への傾倒に心を乱されたPantheonは、エレメンタルとその闇の主たちに戦いを挑んだ。Old Godsの軍勢を率いたのは、最も強大なエレメンタルの副官たちであった。Ragnaros the Firelord、Therazane the Stonemother、Al'Akir the Windlord、そしてNeptulon the Tidehunterである。", "." },
})
