-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["6801a4d3ae4a60be"] = { "{name}、お元気でしょうか。少し調べたところ、あなたが見つけたあのメモを書いた人々について、いくつか情報が分かりました。\n\nSamlaの父親は、自らの信仰の道に従ってThunder Bluffへ巡礼するForsakenとトロールたちを率いています。名前はMiles Welshといい、Pools of Visionで仲間のアンデッドと共にいます。\n\n一方Torgalには、従姉妹のElissa Dumasという遺族がいます。私の知る限りでは人付き合いを避ける人物で、DarnassusのTemple of the Moonで日々を過ごしています。\n\n訪ねられる人は、ぜひ訪ねてみてください、{name}。彼らはTorgalやSamlaの運命を知らないままかもしれません。", "." },
  ["680b42f1fe7c253c"] = { "Orman of Stromgarde\nScarlet Crusadeの初代総隊長\nStromgardeの市民\nIcecrown Glacierの入り口にて消息を絶つ", "." },
  ["68128df4cc234432"] = { "IV. 流量制御\n\n流量を増減させる。これはsamophlange制御機構によって自動的に制御される。\n\nV. 温度計\n\nシステム全体の稼働温度を表示する。", "." },
  ["687572aba1973e8c"] = { "新たなポータルに力を与えるため、彼はAzerothからいくつもの魔力を帯びた遺物を必要とした。それらを手に入れるため、Ner'zhulはDark Portalを再び開き、貪欲な手下たちをその向こうへ突撃させた。", "." },
  ["688b27b5b5d6fad7"] = { "<HTML>\n<BODY>\n<BR/>\n<BR/>\n<P>\n我が敬愛する師、Horatio M. Montgomery, M.D.を偲んで。治療師、Teacher、友。\n</P>\n<BR/>\n<H1 align=\"center\">\n50 BTFT - 25 ATFT\n</H1>\n<BR/>\n<P>\n「世界は病める者と疲れ果てた者で満ちている。治療師として、いや、医学に携わる男として女として、その『itis』を彼らすべてから一掃することこそ、我々の務めなのだ。」 \n</P>\n<BR/>\n<P>\n- H.M.M., M.D., PhD, JD, Grandmaster Farmer, Dancer Extraordinaire, Animalsの友\n</P>\n<BR/>\n</BODY>\n</HTML>", "." },
  ["68b98fd630c0bbb8"] = { "はるか北（現在Northrendとして知られる地域）には、より小さな部族が暮らしていた。これらの部族はGundrakとして知られる小国を築いたが、南の帝国ほどの規模や繁栄には決して至らなかった。", "." },
  ["68c94213ba386d62"] = { "偉大なCyclonianを召喚する私の呪文に必要なものを、以下に記す。幸運があなたと共にあらんことを。\n\n--Bath'rah the Windwatcher", "." },
  ["68d843de3ca22505"] = { "AjeckとSir Erlgadinは身構え、揺れる木々の根元の逆立った茂みに銃を向けていた。真昼の太陽が我々に重く照りつけていた。Elrgadinが撃鉄を引くと、そのこめかみから汗がゆっくりと一筋流れ落ちた。カチリという音と同時に、濃い茂みが割れ、大きな黒豹——見事な個体だ——が平原へと飛び出してきた。", "." },
  ["68fd21d85a1e1939"] = { "2つの種族のうち、ウォリアーであるオークのほうがLegionの堕落に染まりやすいとKil'jaedenは見て取った。彼は、はるか昔にSargerasがQueen Azsharaを支配下に置いたのとほぼ同じやり方で、オークの長老シャーマンNer'zhulを虜にした。その狡猾なシャーマンを媒介として、悪魔はオークの氏族全体に戦いへの渇望と残虐さを広めていった。", "." },
})
