-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["444bec41df6c4c9e"] = { "オークがAzerothへの新たな侵攻を準備していると確信したKing Terenas of Lordaeronは、最も信頼する副官たちを集めた。彼はGeneral Turalyonと大魔導師Khadgarに、Dark Portalを越える遠征隊を率い、オークの脅威にきっぱりと終止符を打つよう命じた。TuralyonとKhadgarの軍勢はDraenorへ進軍し、荒廃したHellfire Peninsulaで幾度となくNer'zhulの氏族と衝突した。", "." },
  ["445ae284b4ca37e5"] = { "Medivhは倒されたものの、HordeはStormwindの守り手たちを圧倒し続けた。Hordeの勝利が近づくにつれ、オーク最大の族長の一人であるOrgrim Doomhammerは、Draenorにいた頃から氏族全体に広がっていた卑しい堕落に気づき始めた。", "." },
  ["4485e6873ef8fd28"] = { "自らの出自の真実を求めて、Thrallは伝説のFrostwolf氏族を探しに北へ旅立った。Thrallは、Gul'danがFirst Warの初期にFrostwolvesを追放したことを知った。さらに彼は、自分がオークの英雄Durotanの息子であり後継者であることを知った。Durotanこそ、20年近く前に荒野で殺されたFrostwolvesの真の族長だったのである。", "." },
  ["44f4e70ca40a0ade"] = { "いや、ささやきだった。Arugalという名のKirin Torの魔法使いについての。聞いたところでは、その者もまたworgenを呼び出したのかもしれない。気は進まないが、その魔法使いに相談し、何を知っているのか確かめてみるつもりだ。\n\nworgenは危険であり、私はその流れを食い止めたい。明日、Barrensの港へ赴き、New World行きの船の切符を手に入れよう。\n\n我が務めが果たされるまで、Eluneの祝福が我にあらんことを。", "." },
  ["44f66cca0ce080d5"] = { "Twilight Hammerの全構成員に即時通達する。\n\nSilithusの現状を鑑み、True Believerの文書の配布はすべて、武装したTwilight Hammerの人員4名以上の護衛のもとで行うこと。\n\nこの新たな方針に違反した構成員は、即座に罰せられる。\n\n-Twilight Lord D'Sak", "." },
})
