-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["830b48480ab321aa"] = { "<HTML>\n<BODY>\n<H1 align=\"center\">Allianceの下士官・兵の階級</H1><BR/>\n<IMG src=\"Interface\\PvPRankBadges\\PvPRank05\" align=\"left\"/><BR/>\n<P align=\"right\">Sergeant Major</P><BR/><BR/>\n<IMG src=\"Interface\\PvPRankBadges\\PvPRank04\" align=\"left\"/><BR/>\n<P align=\"right\">Master Sergeant</P><BR/><BR/>\n<IMG src=\"Interface\\PvPRankBadges\\PvPRank03\" align=\"left\"/><BR/>\n<P align=\"right\">Sergeant</P><BR/><BR/>\n<IMG src=\"Interface\\PvPRankBadges\\PvPRank02\" align=\"left\"/><BR/>\n<P align=\"right\">伍長</P><BR/><BR/>\n<IMG src=\"Interface\\PvPRankBadges\\PvPRank01\" align=\"left\"/><BR/>\n<P align=\"right\">二等兵</P><BR/><BR/>\n</BODY>\n</HTML>", "." },
  ["83a7f9a6ab8da975"] = { "Kirin TorのArchmage Khadgar\n\nMedivhのかつての弟子。オークの故郷Draenorへ進軍したAlliance Expeditionの最高司令官。死亡したものとみなされる。\n\nこれほど無私に魔法と戦の暗き核心へと身を投じた者はいなかった。勇敢なる放浪者よ、そなたの無事を祈る。そなたがどこにいようとも。\n\n- Dalaranの大魔導師、Antonidas", "." },
})
