-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["ab41af8586cf42ac"] = { "Danath Trollbane\n\nStromgardeの民兵司令官。Alliance Expeditionの総司令官であり、オークの故郷Draenorへ進軍したGeneral Turalyonの戦術顧問。戦死したものと推定される。\n\n甥よ、我らはそなたの記憶と犠牲を称える。我らが栄光ある帝国の建国以来、武勇への道は常に英雄たちの血に染まってきたのだ。\n\n- Stromgardeの主、Thoras Trollbane", "." },
  ["ab5cd0f88a3b92c0"] = { "木箱に書き付けが添えられている。こう書かれている。\n\n「Verner——Redridgeがそんなに困っているとは気の毒に。必要な蹄鉄を送る。都合がつき次第、100シルバー払ってくれ。」\n\n「なんなら、黒いdragon whelpsの腹の鱗で払ってくれてもいい（Redridge MountainsにはDragon Whelpsがたくさんいると聞いている）。俺たちは友達だからな……鱗4枚で十分だ。よろしく——Argus」", "." },
  ["ab5fb0f23308561b"] = { "賢い月は偉大な牡鹿と取引をした――彼が自分を愛し、孤独を終わらせてくれるなら、星々の罠から解き放ってあげよう、と。\n\nMu'shaはApa'roを愛し、彼の子を身ごもった。半神だと言う者もいるその子は、夜の影に包まれた森で生まれた。彼はCenariusと呼ばれ、目覚めた世界と天の王国との間の星の道を歩むことになる。", "." },
  ["abd3cc67cc5ee161"] = { "あなたは愛と善行に満ちた静かな人生を送った。貧しき者に施し、病める者を癒し、死にゆく者を慰めた。永遠の安らぎに満ちた来世が与えられると固く信じ、喜びと確信をもって待っていた。\n\nあなたは裏切られたのだ。\n\n私はあなたに慰めを与えることはできない。だが復讐ならば、十分に私の力の及ぶところだ。Deathknellの古い教会へ来るがいい。あなたが教え込まれたその信仰そのものを通じて、致命的な傷を負わせる術を教えよう。\n\n-プリーストのトレーナー、Dark Cleric Duesten", "." },
  ["abdbe43a8f52fd7b"] = { "GuardianであるAegwynnは年月とともに力を増し、Tirisfalの力を使って自らの寿命を大きく延ばした。Sargerasを永遠に打ち倒したと愚かにも信じた彼女は、900年近くにわたり、悪魔の王の手下から世界を守り続けた。しかし、Council of Tirisfalはついに、彼女の務めは終わりを迎えたと裁定した。", "." },
  ["abdd57e1a735565e"] = { "<HTML>\n<BODY>\n<BR/>\n<BR/>\n<H1 align=\"center\">\nEliza\n</H1>\n<BR/>\n<BR/>\n<BR/>\n<BR/>\n<P align=\"center\">\n愛しき妻よ、大地がそなたの飢えを満たさんことを。\n</P>\n</BODY>\n</HTML>", "." },
})
