-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["5f02fb23df030dc0"] = { "Titanの伝承の守り手にして大魔術師であるNorgannonは、青竜Malygosに自らの広大な力の一部を与えた。それ以来、MalygosはSpell-Weaver、すなわち魔法と秘められた秘術の守護者として知られることになる。", "." },
  ["5f0660d034611ace"] = { "Northrendの上空に、巨大な暗い顔が現れた。悪魔の王にしてBurning Legionの主であるSargerasが、地獄の力を漲らせてAegwynnの前に姿を現した。彼は若いGuardianに、Tirisfalの時代はまもなく終わりを迎え、世界はほどなくLegionの猛攻の前に屈するだろうと告げた。", "." },
  ["5f3f50f31580cfb2"] = { "その巨木はナイトエルフと自然との絆の永遠の象徴となり、その命を与えるエネルギーは、時とともに広がって世界の残りの部分を癒していくことになる。ナイトエルフたちは自分たちのWorld TreeにNordrassilという新たな名を与えた。それは彼らの母語で「天の冠」を意味した。", "." },
  ["5f87a9b8d06ba129"] = { "Lordaeronであった。Morganは伝説のパラディンUther the Lightbringerのもとに召集され、オークやアンデッドと戦うことになった。妻子を安全な我が家に残し、Morganは戦場へと旅立った。\n\n年月が過ぎ、戦争は長引いた。Morganは、Paladins of the Silver Handの解散、Utherの死、疫病の蔓延など、数多くの恐ろしい出来事を目にすることになる。彼を狂気の淵から引き留めていた唯一のものは、", "." },
  ["5fad5f601b51e3b4"] = { "あの腐った舟でZanzilから逃げ出したのは、そのときは賢明に思えた。だが今では、死んだほうがまだましな運命だったのではないかと思い始めている。\n\n祖霊たちの怒りから逃れさせてくれたことで、恵みを授けてくれたのだと思っていた。だが今は、この虜囚の日々を生き延びたとして、自分がどんな知恵を得るのだろうかと考えている。", "." },
})
