-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["948b62aa3a35544f"] = { "さて、この樽から北を向け。カラスが飛ぶようにまっすぐ、海辺の崖にぽつんと立つ風車の横に空の水差しが見えるまで歩き続けるんだ。その水差しの周りを探ってみりゃ、お目当てのものが見つかるかもしれねえぜ。", "." },
  ["94a0a1933aed8c80"] = { "機知に富むがまだ経験の浅いThrallは、Blackmooreの砦から逃げ出し、同族を探しに旅立つことを決めた。旅の途中でThrallは収容所を訪れ、かつて強大だった自らの種族が奇妙なほど怯え、無気力になっているのを目にした。望んでいた誇り高きウォリアーたちを見つけられなかったThrallは、いまだ負けを知らない最後のオークの族長、Grom Hellscreamを探しに出発した。", "." },
})
