-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["d996370d7a0f79bb"] = { "--5日目--\n\n同じ牢のナイトエルフはひどい傷を負っている。猪男どもに何度も鞭打たれたのだ。奇跡でも起きて、救出隊がこの危険な場所に乗り込んでこない限り、彼はじきに死んでしまうだろう。彼は意識を失っては取り戻している。目を覚ますと、わずかに残った水を飲ませてやっている。", "." },
  ["d9b3f92f0299a2b9"] = { "<HTML>\n<BODY>\n<H1>Horde徴兵登録</H1>\n<BR></BR>\n<P>この者はHordeの名において、驚くべき力と技を示した。ただちにCrossroadsでの任務に配属すべきである。</P>\n<BR></BR>\n<BR></BR>\n<P>敬具:\n<BR></BR>- Kargal Battlescar</P>\n<BR></BR>\n<BR></BR>\n<BR></BR>\n<P>問題ないと思う。<BR></BR>\n- Takrin Pathseeker</P>\n</BODY>\n</HTML>", "." },
  ["d9bc4834d8fd5ed7"] = { "こうした悪魔との遭遇のほとんどは単発の出来事であり、統治するMagocratsはそうした出来事を民衆から隠すためにできる限りのことをした。最も強力な魔術師たちが捕らえがたい悪魔を捕えるために送り出されたが、彼らはしばしば、強大なLegionの単独の手先を相手に、まるで歯が立たないことを思い知らされた。", "." },
})
