-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["ece2cd1355238a34"] = { "日記さんへ\n\n前回書いた後、怒りにまかせて隠れ家を飛び出した。いやあ、本当に腹が立った。俺の苦悩がもっとよく表れるように、手下どもの制服をデザインし直すことにした。少し気分は良くなったけど、何かが足りない。すぐ戻る……", "." },
  ["ecff92304a7f3068"] = { "{name}、あなたの鎧を作るのに必要なものは以下のとおりだ：\n\nStonetalon MountainsのWindshear mineにいるWindshear koboldsが持つ、燻した鉄のインゴット。\n\nHillsbradのHillsbrad minersが持つ、粉末のazurite。\n\n鉱夫が持つ鉄の延べ棒。あなたが鉱夫なら、鉄の鉱床から採ってもよい。\n\nRazorfen Kraulにいるquilboar、Roogugが持つphlogistonの小瓶。", "." },
})
