-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["637b6e34e1655e8b"] = { "私はworgenをこれ以上呼び出していないのに、その数は増え続けている。まるでScytheが、呼び出しにもはや私の介在を必要としていないかのようだ。これは憂慮すべきことだ。私は見つけられる限りの群れを集め、Shrine of Mel'Thandrisにとどまるよう命じた。\n\nその間、Darnassusの書庫を調べ、DarkshoreのCircle of Ancientsにも相談した。だが、このworgenについての情報は一片たりとも見つからなかった。私が耳にしたのは、知らせ、", "." },
  ["63994dace7fc197f"] = { "Abyssal Templars\n\n入門者は、定例の儀式のためにAbyssal Templarsと接触することを許されている。wind stoneを用いる際は、我らの防御の魔法を作動させぬよう、必ずふさわしい装束をまとうことを忘れるな。\n\n監督者が不在の時に不測の緊急事態が起きた場合は、Abyssal Templarを召喚することが許される。\n\n召喚の儀式の詳細については、先月のTrue Believerを参照せよ。", "." },
  ["63c0236a8ccd0995"] = { "Bethek Stormbrow\n\nBethekの放浪は、彼をBlackrockの奥深くへと導く。山の秘密が彼を招いているのだ。\n\n彼の魂が決して揺らがぬことを。", "." },
  ["63d13d1cdb2e15b0"] = { "Sargerasは広大なBurning Legionを集め、何も知らぬ世界Azerothへと向かった。Legionは宇宙の果てから引き裂かれてきた百万の叫ぶ悪魔からなり、悪魔たちは征服に飢えていた。Sargerasの副官であるArchimonde the DefilerとMannoroth the Destructorは、地獄の手下どもに攻撃の準備をさせた。", "." },
  ["63e68e74b6cc3551"] = { "時が満ちると、Kil'jaedenはLich Kingを生み出した目的である使命を明かした。Ner'zhulは、人間の文明を永遠に消し去る死と恐怖の疫病をAzeroth全土に広めることになっていた。恐るべき疫病で死んだ者はみなアンデッドとして蘇り、その魂は永遠にNer'zhulの鉄の意志に縛られるのだ。", "." },
})
