-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["4d056416c47dd5e8"] = { "Icecrownにたどり着いてLich Kingに自らの力を捧げようと心に決めていた大魔導師は、荒廃し戦火に引き裂かれたAzjol-Nerubの廃墟を通り抜けた。Kel'Thuzadは、Ner'zhulの力の規模と凄まじさを目の当たりにした。彼は、謎めいたLich Kingと手を結ぶことが賢明であり、大きな実りをもたらしうると気づき始めた。", "." },
  ["4d39143cd2d94375"] = { "Kul Tiras Fleetへの正式命令\n\n我、Admiral Proudmooreが、Kalimdorの岸辺への最初の上陸を率いる。\n\n我が不在の間は、Lieutenant Benedictが副指揮官を務める。Kul Tiras国内の軍事はすべて彼が取り仕切るものとする。12か月以内に我がTiragarde Keepより便りがなければ、Lieutenant Benedictが第二陣を率いてその地を確保すること。", "." },
  ["4d51ea886e95073c"] = { "強大なトロールにとって、疑いなく落ち着かない隣人であった。\n\nここで記しておくべきは、最近の発見によれば、トロールがGreat Seaの彼方の地を探検することにほとんど関心を持っていなかったらしいということである。トロールの種族はAzeroth、Khaz Modan、Lordaeronの全域で見つかっているが、新たに発見されたKalimdorの地やSouth Seasの島々では、彼らの文明の痕跡はほとんど見つかっていない。これが示しているのが、", "." },
  ["4d9d800e9ee0bfcf"] = { "彼は分別に反して、Raven Hillの墓地に立ち寄ることにした。Morganは何時間も墓石の間を歩いた。知っている人々の名前を数多く見つけ、彼はますます取り乱していった。そして、それを見つけた。数多くの墓の中にある、手入れのされていない小さな区画に、3つの小さな墓石が並んでいた。近づくにつれ、恐怖が彼を包み込んだ。Morganは最も目立つ墓石の埃を払い、そこに刻まれた名前をあらわにした。墓に簡素に刻まれた文字が綴っていたのは、", "." },
  ["4ddccc79c2278c39"] = { "第3章 - 4人の司令官\n\nStormpikeという玉ねぎの第三の皮は、4人の司令官からなる。この点において、Vanndarは我らが誇るFrostwolfの防衛をまねたのだ。もちろん奴は違うと言うだろうが……話がそれた。\n\n4人の司令官は、Dun Baldarを激しく守るStormpike Guardsmenの増減を操っている。全員を黙らせれば、Stormpike Guardsmenは倒れる。\n\nそうなれば、むくべき皮はあと一枚だけだ。", "." },
})
