-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["5a1c1a21531411e2"] = { "<HTML>\n<BODY>\n<H1 align=\"center\">ALLIANCEの下士官・兵階級</H1><BR/>\n<IMG src=\"Interface\\PvPRankBadges\\PvPRank05\" align=\"left\"/><BR/>\n<P align=\"right\">Sergeant Major</P><BR/><BR/>\n<IMG src=\"Interface\\PvPRankBadges\\PvPRank04\" align=\"left\"/><BR/>\n<P align=\"right\">Master Sergeant</P><BR/><BR/>\n<IMG src=\"Interface\\PvPRankBadges\\PvPRank03\" align=\"left\"/><BR/>\n<P align=\"right\">Sergeant</P><BR/><BR/>\n<IMG src=\"Interface\\PvPRankBadges\\PvPRank02\" align=\"left\"/><BR/>\n<P align=\"right\">Corporal</P><BR/><BR/>\n<IMG src=\"Interface\\PvPRankBadges\\PvPRank01\" align=\"left\"/><BR/>\n<P align=\"right\">Private</P><BR/><BR/>\n</BODY>\n</HTML>", "." },
  ["5a25de616d8a7488"] = { "悪魔のウォーロックたちは燃え盛るinfernalを呼び降ろし、それらは地獄の流星のようにKalimdorの神殿の優美な尖塔へと激突した。Doomguardとして知られる、燃え盛る血に飢えた殺戮者の一団はKalimdorの野を進軍し、行く手のすべての者を虐殺した。野生の悪魔felhoundの群れは、何者にも阻まれずに田園地帯を蹂躙した。勇敢なKaldoreiのウォリアーたちは古の故郷を守るために駆けつけたが、Legionの猛攻の激しさの前に、じりじりと後退を余儀なくされた。", "." },
  ["5a2b2963061de6ce"] = { "それから数週間、私はRidersを恐れて一か所にとどまることなく、転々と移動した。今は打ち捨てられた町Raven's Hillにいる。いつものように、隠れている。奴らがSvenの妻に使ったあの力に、私は立ち向かえない。そしてその力が今もなおScytheを求めてDuskwoodを探っていることを、私は知っている。Scytheは私の手を離れた。光に感謝する。持ち続けていれば、きっと見つかっていただろうから。今でさえ、いずれ見つかるだろうと心の底では分かっている。\n\nひどく疲れた。", "." },
  ["5a7492ba929a62cc"] = { "PantheonのHighfatherであるAman'Thulは、宇宙の力の一部を巨大な青銅竜Nozdormuに授けた。Highfatherは、時そのものを守り、絶えず巡り続ける運命と宿命の道を見張る力をNozdormuに与えた。禁欲的で高潔なNozdormuは、Timeless Oneとして知られるようになった。", "." },
  ["5a8d47138fa0b87e"] = { "帝国が成長して新たな土地へと広がるにつれ、若い魔術師たちもまた南の地へと散らばっていった。神秘の力を振るう魔術師たちは、その地の野生の生き物から同胞を守り、荒野に新たな都市国家を建設することを可能にした。だが、力が増すにつれ、魔術師たちはますます自惚れ、社会の他の人々から孤立していった。", "." },
  ["5ac1739f61f20601"] = { "ピストンの仕様は以下のとおり：\n\n長さ: 32 WW\n幅: 12 WW\n重さ: 23.5 IBG～25.5 IBG\n伝導率: 70 TC\nせん断強度: 98以上\nCombobule評価: 「超頑丈」以上\n\nノームの単位を忘れた場合のために：\nWW = 「ひげの幅」\nIBG = 「ちびっこグラム」\nTC = 「足の指の丸まり」", "." },
  ["5ada4409122745e9"] = { "Frozen Throneの破壊に失敗したことをKil'jaedenが快く思わないと知るIllidanは、Outlandとして知られる荒涼とした次元へ逃れた。そこはオークのかつての故郷の世界、Draenorの最後の名残である。そこで彼はKil'jaedenの怒りを逃れ、次の一手を練るつもりだった。", "." },
})
