-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["8e0f6e83355f3123"] = { "Master Carevinへ\n\nこの書状の持ち主は、光において高潔であり、Duskwoodの境を脅かすアンデッドや悪魔と戦う力を持ち、光の大義のためにCarevin家に加わる意志があることを、自ら示しました。\n\nつきましては、この光のウォリアーにさらなる任務を与えてはいかがでしょうか——たとえば、光の敵に手を貸している疑いのある町の者たちの調査などを。\n\n敬具\nCalor", "." },
  ["8e85102e46b5c112"] = { "この悪魔の鎧は、我らの民に初めて血の渇きの呪いをかけた者が身に着けていたものだ。一人の勇敢なオークの英雄的な行いによって、奴は倒された。Mannoroth the Destructorはもういない。この鎧が、我らがどれほどの道のりを歩み、名誉を取り戻すためにどれほど激しく戦ってきたかを、常に思い出させてくれるように。\n\n\n\n- Hordeの大族長、Thrall", "." },
})
