-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["9ea14622f5d44d04"] = { "Abyssal High Councilのお一方によって我らの血が流されたことは、祝福なのだ！ 倒れた同志たちを羨むべきだ。彼らの魂は今、この上なく正しき獣の腹の中に宿っているのだから！\n\nOld Godsを讃えよ！ そのしもべたちを讃えよ！ Twilight's Hammerを讃えよ！", "." },
  ["9ea6aaf624da3a3a"] = { "敵のウォリアーたちと対峙したModgudは、その力を使って彼らの心に恐怖を植えつけた。影は彼女の命令で動き、暗きものどもが大地の深みから這い上がって、Wildhammersを彼ら自身の広間で付け狙った。やがてModgudは門を突破し、要塞そのものを包囲した。Wildhammersは必死に戦い、Khardros自らが渦巻く敵の群れをかき分けて進み、魔術師の女王を討ち取った。", "." },
  ["9eb4d3db71a989e7"] = { "Deathwingの突然の裏切りはあまりに破壊的で、5つの竜族は二度と真に立ち直ることはなかった。傷つき衝撃を受けたAlexstraszaとほかの高貴な竜たちは、定命の同盟者たちを見捨てざるを得なかった。いまや絶望的な数の差に置かれたMalfurionと仲間たちは、続く猛攻をかろうじて生き延びた。", "." },
})
