-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["e877e8a3886ca097"] = { "Heralathとその同胞は、この地の堕落の源を突き止めようとしている。Agamagganは清らかな神だと信じられていた、と彼は言った。ならばなぜ、あの醜い生き物どもと邪悪な茨がこの地を蝕んでいるのか、実に謎だ。\n\nさらに聞き出す前に、Heralathはまた浅い眠りに落ちてしまった……", "." },
  ["e89efc3f8d65ab82"] = { "Illidanがnagaとともに旅立つと、Warden Maiev Shadowsongが彼を追い始めた。Maievは10000年にわたってIllidanの看守を務めており、彼を再び捕らえるという見込みに胸を躍らせていた。しかしIllidanはMaievとそのWatchersの裏をかき、彼女たちの妨害にもかかわらずEye of Sargerasを手に入れることに成功した。強力なEyeを手にしたIllidanは、かつての魔術師の都Dalaranへ向かった。", "." },
  ["e8fcc96f6c69cff8"] = { "Uggel Hammerhand\n\nUggelは腕の立つ、寡黙な石工である。闇の鍵を負っていないとき、その手はHall of Craftingで偉大な作品を形づくる。", "." },
})
