-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["b839b931c66277b5"] = { "黒竜は完全な変貌を遂げ、ついにNeltharionはもはや存在しなくなった。彼は悪意と憎しみの生き物、Deathwingとなったのだ。high elvesのような種族の目にはもはやEarth-Warderではなく、titanに与えられた名に代わって、Death AspectそしてXaxasと呼ばれるようになった。Deathwingは混沌と悪の化身であり、常に破壊に飢えている。彼は、Old Godsが追放された後にAzerothに現れた最初の悪であると言っても過言ではない。", "." },
  ["b8798e25cac00f10"] = { "今、私たちは危険の及ばなさそうな、奥まった洞窟に身を隠しています。でも、Raptorsを片付ける部隊が送られてくるまで、ここに閉じ込められているのです。Whelgarは作業を続けようとしていますが、まだかなり怯えているようです。これが私たちの状況です、Tarrel。どうかLongbraidに、すぐに救出部隊を集めるよう促してください。\n\nこの苦しい時にあっても、あなたへの愛は変わりません。\n\n——Merrin", "." },
  ["b8e2fd4cfa03dcc2"] = { "<HTML>\n<BODY>\n<H1 align=\"center\">\nEASTERN PYLON 配置図\n</H1>\n<BR/>\n<IMG src=\"Interface\\Pictures\\11482_crystals_east\"/>\n</BODY>\n</HTML>", "." },
})
