-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["a53e23de8a53096f"] = { "Master Delgrenへ\n\n恐れておられたとおりでした。Tower of Althalaxxについてのあなたの説は正しかったのです。塔にはカルト教団が集まっており、その中には多くのウォーロックが、さらには忌まわしいsatyrまでもがいます。彼らは自らをCult of the Dark Strandと名乗っています。どのような邪悪な目的で彼らが集まっているのか想像もつきませんが、気がかりです。\n\nこの書簡が簡潔すぎることをお許しください。周囲の森には危険が潜んでおり、状況を説明するのにあまり言葉を割けないのです。私は", "." },
})
