-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["465dd7acd43f3a9e"] = { "Legacy Heart\n\n古い文献によれば、Legacy Heartを持つ者は墓を恐れないという。それは本当なのかもしれない。その心臓の持ち主であるトロールのMoghは、Mogh the Undyingとして知られているのだから。Skullsplitter族の呪術医であるMoghは、StranglethornのRuins of Zul'Mamweに住んでいる。", "." },
  ["4686ec06c3c81f75"] = { "我々は西へ向けて出発し、絡み合うジャングルの深い茂みを抜けていった。ゆっくりと慎重な足取りで、獲物を求めて濃い草木の中を進んだ。朝は苛立ちに満ちた沈黙のうちに過ぎた。Valeでは何ひとつ動くものはなく、そよ風さえ吹かなかった。午後になる頃には、一行は落ち着きをなくしていた。Barnilはもはや、獲物を追う捕食者の慎重な足取りで歩いてはいなかった。それどころか、乾いた葉や落ちた枝をしばしば音を立てて踏みながら、道をどたどたと不格好に歩いていた。", "." },
})
