-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["8a2162593f2296f6"] = { "Shael'drynは、Lake Irisの北東にある月の泉を守るdryadだ。彼女は森を離れることも、森を堕落に明け渡すことも拒んでいる。彼女なら杖を修復する力と知識を持っているはずだし、少なくとも私一人で直す方法を教えてくれるだろう。\n\n柄頭\n杖の柄頭は、Dor'danilのドルイドたちに託された。だが、これには大きな問題が1つある。そのドルイドたちは死んでいるのだ。\n\n今では彼らの霊がその地に棲みつき、もはや客を迎え入れてはくれない。", "." },
  ["8a6ae8ec49f5bedc"] = { "Star of Xil'yeh\n\nAlteracのogre、Grel'borg the Miserが、この宝石の最後の持ち主として知られている。持ち主に異界と交信する力を与えるとささやかれる宝石だ。情報によれば、GrelborgはAlterac MountainsのRuins of Alteracをさまよい、瓦礫や残骸の中からさらなる遺物を探しているという。", "." },
  ["8a71b330a85c7681"] = { "Gul'danの堕落が自らの民を滅ぼすとなおも確信していたDurotanは、再びウォーロックたちに異を唱えた。その勇敢なウォリアーは、ウォーロックがオークの魂の純粋さを破壊しており、この無謀な侵攻は彼らの破滅となるであろうと主張した。これほど人望のある英雄を殺す危険を冒せなかったGul'danは、Durotanとその氏族Frostwolf Clanを、この新たな世界の最果てへ追放せざるを得なかった。", "." },
})
