-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["9b56b86c47de9ad8"] = { "Sargerasは、暗さを増していくMedivhの心の中で歓喜していた。世界への二度目の侵攻の計画が完成に近づいており、世界最後のGuardianがそのすべてを実現させるであろうことを知っていたからである。", "." },
  ["9bbefb22b2aaa180"] = { "群れが一つ失われた。worgenを森じゅうに遣わして悪魔に侵された地域を突き止めさせたが、彼らは戻らなかった。私は、指揮を任せた指導者たちのことが心配になり始めている。彼らは単純な心しか持たず、私が与えたこのわずかな権限を、極限まで押し広げている。私は制御を失いつつあるのだろうか？ しばらくは、worgenをこれ以上呼び出すのはやめておくべきかもしれない。\n\n我が務めが果たされるまで、Eluneの祝福が我にあらんことを。", "." },
})
