-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["e32cae2a1fa2b097"] = { "どの車が絶好調で、どの車がそうでないかを我々が操れるなら……それが賭けでどれほど有利になるか、君に説明するまでもないだろう。\n\nそこで、Fizzlebub殿、君にはピットクルーの失敗を引き起こす手段を用意してもらいたい。\n\nStranglethornには、ノームやゴブリンの頭を混乱させるのに使えそうな植物や薬草、あるいは飲み物はないだろうか?\n\n--K. Koalbeard", "." },
  ["e34ceb5e04fc24b1"] = { "かつての名を捨てた。\n\n長年にわたり、TidebearerはGurubashi Empireに仕え、戦では従僕のwater elementalを呼び出し、帝国のためにStranglethorn Valeの水の流れを操った。しかし年月が経つにつれ、Tidebearerは人を避けるようになり、長い間宮廷を離れていることが多くなった。\n\nTidebearerは宮廷の詮索の目から秘密を隠していた。Stone of the Tidesが彼に与えた力には、呪いもまた伴っていたのである。年月が", "." },
  ["e36d0c3c78ae8ab7"] = { "GilneasとAlteracはStromの強力な支持者となり、Khaz Modanの山がちな南の地を探検する強大な軍勢を育てた。人間が古代の種族であるドワーフと初めて出会い、その洞窟の地下都市Ironforgeを訪れたのはこの時期のことである。人間とドワーフは金属加工と工学の多くの秘密を分かち合い、戦いと物語を愛する心が共通していることを知った。", "." },
})
