-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["9820548d32c92fbc"] = { "哀れなHeralathは骨のように青白い。熱は刻一刻とひどくなっている。その間にも、猪男どもは何か大きな軍事行動の準備を進めている。早く脱出を試みなければ、私もエルフの同房者と同じ運命をたどることになるだろう。\n\n猪男どもが次の狩りに出かけたときに抜け出すつもりだ。見張りは怠け者で、よく当番中に眠りこけている。", "." },
  ["9862403dbd9430ed"] = { "Quel'Thalasを統治する権力としてConvocation of Silvermoonが設立されたが、Sunstrider Dynastyもわずかながら政治的な力を保っていた。ハイエルフの最も偉大な領主7人から成るConvocationは、エルフの土地と民の安全を確保するために働いた。防護の障壁に囲まれたハイエルフたちは、Kaldoreiの古い警告に心を動かされることなく、生活のほぼあらゆる面で魔法をあからさまに使い続けた。", "." },
  ["98fd4ea2d87a0493"] = { "Alexstrasza：\n\r古く強大なドラゴンの女王Alexstraszaは、titanによってLife-Binderと名付けられた。彼女は、titanが去った後に世界を守るため、titanによって最初に創られた存在である。Azerothの地に現在のあらゆる種族が誕生するのを見届けたと言われている。誇り高い気質で知られる彼女の赤竜の一族は、かつて他のすべてのドラゴン族を支配していた。", "." },
})
