-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["8fa8906cd745f97b"] = { "第3章 - 4人の司令官\n\nこの手引きの知恵に従ってきたなら、今ごろDrek'Tharの司令官のうち2人は死んでいるはずだ。よくやった、兵士よ！ 奴らの決意はすでに揺らいでいる。今度は残る2人の司令官を倒し、指揮系統の解体を完了させねばならない。\n\n4人の司令官がすべて倒れれば、Frostwolf Keepを守るFrostwolf Legionnairesは指揮を失い、散り散りになる。摘み取りどきだ！", "." },
  ["8fafac80c831a06f"] = { "さまざまな生物の化石を研究した結果、太古の昔、Lake Lordamereの水域を大いなる疫病が襲ったと私は推論した。その原因は何か。それは永遠に分からないかもしれない。だが、湖底一帯に遺骸が密集していることからすると、汚染の広がりは極めて速かったようである。", "." },
  ["8fcd91206fcc9050"] = { "今日、Syndicateがこの地で持つ力はわずかですが、彼らはこの地域をよく知っており、今後の任務に十分な人手を集めております。適切に導けば、まもなくSyndicateが再びAlteracを支配するものと確信しております。\n\n加えて、近隣のArathi HighlandsにあるStromgardeの都を狙うよう、Syndicateに促しました。その都は我らの軍勢、ogre、そしてStromgardeの人間がぶつかり合う戦場となっておりますが、慎重な戦術をもってすれば、このかつての大都市を我らのものにできると考えております。", "." },
  ["8ff210d0e7d358c3"] = { "Councilは、Guardianの力の新たな後継者を選べるよう、AegwynnにDalaranへ戻るよう命じた。だが、常にCouncilを信用していなかったAegwynnは、自分自身で後継者を選ぶことに決めた。", "." },
})
