-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["301c9aadb01c04a5"] = { "L. F.がAllianceの愚か者どもへの攻勢強化を命じた。以下は、Southshoreに対する重要な任務に必要な物資の一覧である。\n\n20人分の1週間の携帯食料\n黒い夜間装束 20着\n新しい靴 20足\n新しい剣 25本\n投げナイフ 30本\n黒い覆面 20枚\n発火油 10瓶\n麻痺毒 50回分\n盗んだSouthshore衛兵の制服 5着(入手できれば)\n銀貨 100枚\n\n--Baron V.\n補給係", "." },
  ["30470b98a4ce981e"] = { "high-borneは研究に没頭し、絶え間なくWellを調べた。やがて彼らは、Wellの宇宙的なエネルギーを操り、制御する力を身につけた。無謀な実験が進むにつれ、high-borneは新たに得た力を使って、思いのままに創造することも破壊することもできると知った。不運なhigh-borneは原始的な魔法に偶然たどり着き、今やその習得に身を捧げると決意していた。", "." },
  ["309272b19e377bcc"] = { "健常なすべての男女へ：\n\nScourgeが戻ってきた。我々は争いを脇に置き、この脅威に立ち向かわねばならない。Argent Dawnは、Scourgeの脅威に武器を取らんとする者を誰一人拒まない。\n\n我らの地を守らんとする者は、Eastern PlaguelandsのLight's Hope Chapelに集結しつつある。共に戦えば、我々は勝利するだろう。\n\n名簿の守り手\nThe Argent Dawn", "." },
})
