-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["dd8d6e4a549b32e3"] = { "月と炎にかけて、\n肉と骨にかけて、\n血にて記し、\n石に刻む。\n\nこの地を去れ\nさもなくば破滅に出会うであろう\n死が見張りに立つ\nEmperor's Tombの上に。", "." },
})
