-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["b99968d49d77a2f2"] = { "その後の年月、StormwindがStonemasons' Guildを裏切ってから、Sir Erlgadinは王国における貴族の役割に苦々しい思いを抱くようになった。彼はもはや、父の血筋によって得たHouse of Noblesでの地位を守りたいとは思わなくなったのである。\n\nだが話がそれた。この物語の目的は、政治論文や伝記となることではない。これは、Stranglethornの緑の丘で大物を狩った私の経験の記録である。", "." },
  ["b9d54b67b1307f71"] = { "新たな土地を手放そうとしない頑固なエルフたちは、Well of Eternityから得た魔法を用いて、獰猛なトロールを寄せつけなかった。Dath'Remarの指導のもと、彼らは自分たちの10倍もの数を擁するAmaniの戦闘部隊を打ち破ることができた。Kaldoreiの古い警告を警戒する一部のエルフたちは、自分たちの魔法の使用が、追放されたBurning Legionの注意を引きかねないと感じていた。", "." },
  ["b9e072ac539de39e"] = { "弱っていたにもかかわらず、Arthasは最終的にIllidanの裏をかき、先にFrozen Throneへたどり着いた。ルーンの剣Frostmourneを使って、ArthasはLich Kingの氷の牢獄を打ち砕き、それによってNer'zhulの魔力を帯びた兜と胸当てを解き放った。", "." },
})
