-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["d0e17264ff198c65"] = { "彼のAtal'aiのプリーストたちでさえ、最終的には首都Zul'Gurubから追われ、北の未開の沼地で生き延びることを余儀なくされた。その薄暗い沼地の中に、彼らは倒れた神のための大いなる神殿――Atal'Hakkar――を築き、主の仕事を続けられるようにした……", "." },
})
