-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["851b816e70055a87"] = { "Valea Twinblades\nScarlet Crusadeのウォリアー\nAlteracの市民\nEastern Plaguelandsの奥深くにて最後に目撃される", "." },
  ["85274ad949a39cf0"] = { "ベータ作戦――Windshear Mine:\n\nゴブリンどもが鉱山の入口の北で、爆薬を積んだ別の荷馬車を使っているのを見た。NG-5 Charge (Red)を仕掛けるには、あそこで十分だと思う。荷馬車の後ろに爆薬を仕掛けたら、距離を取ってボタンを押せ。\n\nゴブリンどもが騒ぎを確かめに駆けつけてこなかったら、それはたぶん山が奴らの頭上に崩れ落ちたからだろう。", "." },
  ["85ecfdc99a00c7a8"] = { "我が主へ\n\n戦争が迫っております。破滅はすぐ戸口まで来ております。\n\nLakeshireの町の治安判事として、陛下の最東端の植民地で起きた最近の軍事行動をご報告するのが私の務めです。\n\nこの書面には、Redridge Mountainsの懐に抱かれたLakeshireの現状についての報告が記されております。", "." },
})
