-- GENERATED by `wfj generate` from data/book/. Do not edit: `wfj validate` regenerates and diffs it.
local _, WFJ = ...
WFJ.Data.add("book", {
  ["a46dfdd3ed0797a7"] = { "日記さんへ\n\n今日、宿敵のNarain Soothfancyが、処刑の場に手下どもを身代わりに送り込んで、俺を騙そうとした。あいつ自身の処刑なのに。信じられるか？\n\nあのいまいましい小屋からあいつをおびき出すために、わざわざこの極悪な計画を練り上げたっていうのに、こんな手を使うとは？ もういい……腹が立ちすぎて書き続けられない。また後で書く。", "." },
  ["a4936a6785d9aa2f"] = { "大変動を無傷で生き延びたHighborneも多くいた。彼らはほかのナイトエルフとともに、新たな大地の岸へとたどり着いた。MalfurionはHighborneの動機を信用していなかったが、Wellのエネルギーがなければ彼らも大した悪さはできまいと納得していた。", "." },
  ["a4acf239ab8fffef"] = { "だが、Arathiとして知られるある部族は、トロールが無視できないほど大きな脅威になりつつあることを見て取った。Arathiはすべての部族を自らの支配下に置き、トロールの戦闘部隊に対して一致団結した戦線を築こうと望んだ。", "." },
  ["a4ad2f52a3ae1e9d"] = { "過ぎるにつれ、Tidebearerは消えつつあった。潮が満ち引きするたびにTidebearerは少しずつ自分を失い、肉体を失っていき、存在と非存在の間を明滅するようになった。そしてついに死期が迫ったとき、彼は初めてStoneを見つけた浜辺へ赴き、海の中へと歩み入り、二度と姿を現さなかった。\n\n幾世代も後、Stone of the TidesはStranglethornの岸に打ち上げられ、そのトロールがStoneを", "." },
  ["a4c374239e9a8530"] = { "Ferren Marcus\n\nScarlet Monasteryの大修道院長\n\nStratholmeの市民\n\nFirst Summertide AssaultにてScarlet Monasteryを守り戦死", "." },
  ["a4d91cae266588ae"] = { "父と息子は、Silithusで高まりゆく昆虫の群れの波を食い止めようと、熱烈に戦った。Ahn'Qirajの砦からは、果てしないとも思えるsilithidの流れが途切れることなく湧き出し、侵攻するQirajiの軍勢の隊列を補強し続けた。Silithus全土が包囲されていた。", "." },
  ["a4dc830696270816"] = { "KhardrosとそのWildhammerのウォリアーたちはDun Algazの防壁の門を抜けて北へと旅し、遠いGrim Batolの峰の中に自分たちの王国を築いた。そこでWildhammersは繁栄し、財宝の蓄えを再建した。ThaurissanとそのDark Ironsはそううまくはいかなかった。敗北に屈辱と怒りを覚えた彼らは、Ironforgeへの復讐を誓った。Thaurissanは民を率いて遥か南へ向かい、美しいRedridge Mountainsの中に都市を築いた(その都市には自らの名を付けた)。", "." },
})
